### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by TadbirPaydar** [ZoneMinder/ZoneMinder#1010]
Hello
I think this good project needs image or video encryption for saving videos or images in storage.
I wanna do this but i want to know which module is responsible for getting and saving images or videos.
any help ?

**Comment by knnniggett** [comment]
Thank you for your willingness to participate in the development of ZoneMinder.  However, this is not the place for general discussion.  Please join us in the ZoneMinder IRC channel for development questions. We are online daily and are most active in the morning (US Timezones). Thank you.
