### ISSUE TITLE
Zoneminder cannot install to ubuntu 15.0x

### ISSUE THREAD

**Issue by dreaddy** [ZoneMinder/ZoneMinder#1022]
Last bit of instructions followed here: http://www.zoneminder.com/wiki/index.php/Ubuntu_Server_15.04_64-bit_with_Zoneminder_1.28.1_the_easy_way

stuck at the following section: 
systemctl enable zoneminder.service

error returned
ug 18 15:52:51 u135 zmpkg.pl[5425]: Can't connect to db at /usr/share/perl5/ZoneMinder/Config.pm line 105.
Aug 18 15:52:51 u135 zmpkg.pl[5425]: BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder/Config.pm line 105.
Aug 18 15:52:51 u135 zmpkg.pl[5425]: Compilation failed in require at /usr/share/perl5/ZoneMinder.pm line 33.
Aug 18 15:52:51 u135 zmpkg.pl[5425]: BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder.pm line 33.
Aug 18 15:52:51 u135 zmpkg.pl[5425]: Compilation failed in require at /usr/bin/zmpkg.pl line 48.
Aug 18 15:52:51 u135 zmpkg.pl[5425]: BEGIN failed--compilation aborted at /usr/bin/zmpkg.pl line 48.
Aug 18 15:52:51 u135 systemd[1]: zoneminder.service: control process exited, code=exited status=255
Aug 18 15:52:51 u135 systemd[1]: Failed to start ZoneMinder CCTV recording and surveillance system.
Aug 18 15:52:51 u135 systemd[1]: Unit zoneminder.service entered failed state.
Aug 18 15:52:51 u135 systemd[1]: zoneminder.service failed.

This is actually correct because the current Installation does not create the database for zoneminder.

How exactly is zoneminder supposed to be installed to ubuntu 15.xx?

**Comment by knnniggett** [comment]
Installation questions belong in the user forum.

Please see our posting criteria:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules

Closing.
