### ISSUE TITLE
filter email and postfix

### ISSUE THREAD

**Issue by cippalippa2014** [ZoneMinder/ZoneMinder#1034]
With zoneminder 1.28.1 I configured postfix and I created a filter to send emails with photos, the filter works but the mails arrive repeated up to 50 for each event, the same event repeated ... Why?

**Comment by knnniggett** [comment]
This issue does not describe a bug and belongs in the user forum.
There have been a few other mail related questions in the user forum recently.  It might be worth your time to read those.  If that does not resolve the issue, then feel free to create a new thread in the user forum that contains:
- your postfix configuration
- the monitor configuration, particularly how you have your zones set up
- your zoneminder fillter configuration
- your zoneminder mail configuration
