### ISSUE TITLE
Optional google recaptcha

### ISSUE THREAD

**Issue by pliablepixels** [ZoneMinder/ZoneMinder#1046]
There was interest in adding a google recaptcha option to ZM which could be disabled/enabled via options. Default state is disabled. 

I'll be submitting a PR on this soon for review.

Note that the user will have to follow recaptcha instructions to configure a site and secret key for their ZM domain and enter those values in the options screen.

**Comment by marcolino7** [comment]
Hi,
I updated my ZM installation from 1.28.102 to 1.28.106, and on login screen I got recaptcha widget with an error. I connot login on my installation.

![image](https://cloud.githubusercontent.com/assets/11460036/10041336/df8681f0-61e3-11e5-8a06-5c0621d18a16.png)

**Comment by marcolino7** [comment]
Hi,
I run database upgrade script, and now work. Sorry for this.
Marco
