### ISSUE TITLE
Undefined object error in actions.php - seems to be related to Server table additions

### ISSUE THREAD

**Issue by pliablepixels** [ZoneMinder/ZoneMinder#1047]
This gets logged into apache error logs:
```
[client 127.0.0.1:60758] PHP Notice:  Undefined index: object in /usr/local/share/zoneminder/www/includes/actions.php on line 707, referer: http://localhost/zm/index.php
```

**Comment by knnniggett** [comment]
This is a known issue.  
This is part of @connortechnology 's multi-server work. see #1040 

It's complaining because a server name has not been set.  Last time I checked the new server tab under Options doesn't yet allow one to add a server, so for now we just have to live with the error message.

**Comment by pliablepixels** [comment]
okay, closing
