### ISSUE TITLE
One computer serving cameras to main server?

### ISSUE THREAD

**Issue by DaAwesomeP** [ZoneMinder/ZoneMinder#1061]
I want to have a specific setup. My main ZoneMinder machine will be Debian it will have a few cameras plugged into it. I also have an Ubuntu machine and a Windows machine with cameras on them. Is it possible to have the Ubuntu and Windows machine serve streams to the main Debian machine? I don't want to have any UI or Web access to the cameras on the Ubuntu and Windows machines. I'm fine running a service other than ZoneMinder on those machines. I effectively need those machines to act as network cameras. Is this possible?

**Comment by knnniggett** [comment]
This issue does not describe a bug, nor is it a feature request.

Please refer to out posting rules and then post this in our user forum:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules

**Comment by DaAwesomeP** [comment]
Ok. Sorry about that. You should create a `CONTRIBUTING.md` file in the root of the repo. GitHub will then show a banner when creating new issues and pull requests. You can just link to the Wiki in it.

Forum post: [One computer serving cameras to main server?](http://www.zoneminder.com/forums/viewtopic.php?f=32&t=23473)

**Comment by knnniggett** [comment]
Our github posting rules are linked under the section Contacting the Development Team in Readme.md, which is prominently displayed on our front page in large front.

I'll look into duplicating that in contributing.md
