### ISSUE TITLE
Core.php.default does not include ZMSESSID cookie code - API auth fails

### ISSUE THREAD

**Issue by pliablepixels** [ZoneMinder/ZoneMinder#1064]
Looks like I modified core.php and not core.php.default with the cookie code that is needed to make API auth work. This results in new package updates overwriting the cookie code with old code. I'll be submitting a PR to make this mod into core.php.default

**Comment by knnniggett** [comment]
Please note that we have an open pull request on core.php

**Comment by knnniggett** [comment]
see #1049

**Comment by pliablepixels** [comment]
Ah, ok. I'm closing mine then. Can someone accept your PR? This breaks the APIs for each update.
