### ISSUE TITLE
Zoneminder montage imege freeze

### ISSUE THREAD

**Issue by cippalippa2014** [ZoneMinder/ZoneMinder#1068]
Zoneminder 1.28.1 on Ubuntu 14.4 server when I open the montage after a few minutes the image was freeze, there is 10 monitor ffmpeg / rtp unicast / source rtsp
Thanks

**Comment by knnniggett** [comment]
No information has been provided that indicates this is a bug. 
Please refer to our posting guidelines:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules

Then post this in the user forum for help. This is almost certainly a configuration or resource issue.
