### ISSUE TITLE
Unable to determine path for arp command, type -p arp returned '127'

### ISSUE THREAD

**Issue by shibdib** [ZoneMinder/ZoneMinder#1076]
Trying to add a camera, put everything in correctly and get http://i.imgur.com/tK4F1eS.png

If I run probe it gives me the error "Unable to determine path for arp command, type -p arp returned '127' "

This is on Ubuntu 14.04

**Comment by knnniggett** [comment]
The arp command has issue already been resolved in master.

Your camera issue does not describe a bug.
To get help, create a post in the user forum that describes your system, your camera config, and relevant log entries.
See our posting requirements:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules
