### ISSUE TITLE
Wiki Migration

### ISSUE THREAD

**Issue by chriswiggins** [ZoneMinder/ZoneMinder#108]
We should start using the GitHub wiki for information. This is going to require a fair amount of work.

Suggested first steps:
 * Migrate FAQ and update ( See #110 )
 * Migrate tutorials and update for latest versions of ZoneMinder and the relative OSes

This issue will be updated as these steps are deemed complete and as more are added. Please open an issue for each "task" required and I'll update this issue.

**Comment by knnniggett** [comment]
This has been completed. Closing.
