### ISSUE TITLE
ZoneMinder Web API

### ISSUE THREAD

**Issue by Lankaw** [ZoneMinder/ZoneMinder#1093]
I want my own home automation system to be updated when any detection captured in zoneminder. 
So, Does Zone Minder has any api call to get camera detections? or anyway to broadcast the detection information. please help..

**Comment by knnniggett** [comment]
This does not describe a bug nor is it a feature request.  

Please refer to our posting rules:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules

Feel free to have this discussion in our user forum or IRC channel.
