### ISSUE TITLE
1.28.2 zmfilter.pl syntax error

### ISSUE THREAD

**Issue by mdetweiler** [ZoneMinder/ZoneMinder#1098]
root@ubuntu-video:~/bin# /usr/bin/zmfilter.pl 
Bareword found where operator expected at /usr/bin/zmfilter.pl line 828, near "Error"
	(Missing semicolon on previous line?)
syntax error at /usr/bin/zmfilter.pl line 828, near "Error"
Execution of /usr/bin/zmfilter.pl aborted due to compilation errors.
root@ubuntu-video:~/bin# vi /usr/bin/zmfilter.pl

root@ubuntu-video:~/bin# /usr/bin/zmfilter.pl 
Name "Net::SFTP::Foreign::debug" used only once: possible typo at /usr/bin/zmfilter.pl line 818.

**Comment by knnniggett** [comment]
I was hoping @connortechnology would respond to this.
Zoneminder 1.28.2 only exists in his Ubuntu ppa. I don't have a copy of that to see what you've got. 
The copy of zmfilter.pl in master is clearly different than the one you are using:
https://github.com/ZoneMinder/ZoneMinder/blob/master/scripts/zmfilter.pl.in

You can ignore the message about Net::SFTP::Foreign::debug. It is just a warning and can be ignored. I don't think the author of Net::SFTP::Foreign wrote a debug module, so we simply need to disable the check for debug when using sftp as opposed to plain ftp. We are aware of it and it will get fixed eventually.

**Comment by connortechnology** [comment]
I think the issue is a missing ; after the eval above that line.  When doing block evals I think you need a semi-colon after the end of the block;

So on line 827 change it to 

}; # end eval

**Comment by mdetweiler** [comment]
Yes...  I had fixed it that way when I saw this issue on my system.

**Comment by knnniggett** [comment]
Can someone with 1.28.2 compare their copy of zmfilter.pl to the copy in master and verify whether or not this problem hasn't already been fixed? 

Line 907 looks suspect:
https://github.com/ZoneMinder/ZoneMinder/blob/master/scripts/zmfilter.pl.in#L907

**Comment by connortechnology** [comment]
The issue does not exist in master.  It exists only in 1.28.2.  Although I am going to look at merging the code into master.  The Net::SFTP stuff uses die and croak, so it can kill zmfilter.pl.  So we need to put it into an eval to prevent the failure of one filter from killing all filters.

**Comment by knnniggett** [comment]
@mdetweiler If you are still around, can you test #1323 ?
It makes the Net::SFTP::Foreign::debug warnign go away, but I want to make sure that the sftp transfers still work correctly.

**Comment by mdetweiler** [comment]
Did you want me to test it on 1.29?

**Comment by knnniggett** [comment]
You should be able to patch any recent version of zoneminder with the proposed change.

**Comment by knnniggett** [comment]
The original syntax error from this issue was fixed previously.
#1323 fixes the warning that was also mentioned in this issue.

**Comment by Mat2Vence** [comment]
I am having the same kind of issue with the 1.29.

**Comment by mdetweiler** [comment]
I just did an install of 1.29 from the Ubuntu 14.04 PPA and did not see this issue.  Are you using Ubuntu or another OS?

**Comment by Mat2Vence** [comment]
I am running on Ubuntu 14.04.4 LTS
