### ISSUE TITLE
M5014 Axix control with ZM 1.28.2 lost

### ISSUE THREAD

**Issue by s80ts0465** [ZoneMinder/ZoneMinder#1109]
Hello,

i cannot get PTZ working on my Axis M5014.
I've just upgrade from 1.25 to 1.28.2. With the old version of ZM everything was working fine.

What i tried so far:

Controllable selected.
Control Type: Axis API v2
Control Device: /axis-cgi/com/ptz.cgi
Control Address: ip address of your camera

If i try to use PTZ a alert pops up after some time:

Control response was status = undefined
message = /usr/bin/zmcontrol.pl --panspeed=2 --panstep=19 --command=moveRelRight --id=3=>

Any tipps how i can get PTZ working?

Regards
Stefano

**Comment by knnniggett** [comment]
Our github forum is being used for bug reporting and serious feature requests only.
Since this issue does not fit into either category, please take this discussion to the user forum.

Please see our posting rules:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules
