### ISSUE TITLE
Console does not abort if timezone unset

### ISSUE THREAD

**Issue by baffo32** [ZoneMinder/ZoneMinder#1110]
A mound of warnings are issued when this should be a fatal error.

Example of why this should be fatal: http://www.zoneminder.com/forums/viewtopic.php?f=32&t=23511

![zm-console](https://cloud.githubusercontent.com/assets/240981/10419890/2bfb7e14-7053-11e5-9d6e-28270eeb8155.png)

**Comment by knnniggett** [comment]
@baffo32 The root cause of this problem is a failure to follow the instructions shown here:
https://wiki.gentoo.org/wiki/ZoneMinder

Spamming us with the same message again will not change that and will result in banning from this forum.
