### ISSUE TITLE
Script zoneminder error 1

### ISSUE THREAD

**Issue by luky7795** [ZoneMinder/ZoneMinder#1114]
Hi, these days I am using zm for an alarm system, but I do not work automatically run a script through the filters (error 1).
The script is this:

#!/bin/bash
mkdir /home/muletto/hellozm/ > hello.txt

Of course the folder is not created, and even txt (has all the script execute permissions)
I made another one in perl, but it did not change.
Thanks in advance and sorry for any errors in translation (google translate)

**Comment by knnniggett** [comment]
ZoneMinder runs under the web account user so, unless you have started your web server using the account name muletto (unlikely), this script is guaranteed to fail. All operations are relative to the web root.  For further help, please take this to the user forum, as described in our posting guidelines:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules
