### ISSUE TITLE
support for ssmtp mail.

### ISSUE THREAD

**Issue by dreaddymck** [ZoneMinder/ZoneMinder#1128]
Often find myself updating /usr/bin/zmfilter.pl after each update.

            ### Send the Message
            # MIME::Lite->send( "smtp", $Config{ZM_EMAIL_HOST}, Timeout=>60 );
            # $mail->send();
            $mail->send('sendmail','/usr/sbin/ssmtp',$Config{ZM_EMAIL_ADDRESS});

Would it be possible to add support for ssmtp?

I may be able to do this. Not really clear on howto contribute. Is there an irc chatroom available that can help?

**Comment by knnniggett** [comment]
Hey, this was merged. Closing....
