### ISSUE TITLE
Source Options "loglevel=debug", where do the FFmpeg log messages go??

### ISSUE THREAD

**Issue by wdeninger** [ZoneMinder/ZoneMinder#1129]
Where do the log mesages go?  I can't seem to find them or a relavant option anywhere.

-W

**Comment by dreaddy** [comment]
Good question. On ubuntu I do my log checking via

    tail -f /var/log/syslog

You may be able to track debug activities for zmvideo.pl which I THINK calls ffmpeg in the admin system log interface.

**Comment by knnniggett** [comment]
Guys, thank you for your support of this project, but please follow our posting guidelines and take this discussion to either our IRC channel or the User forum. We spend time in both daily.

https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules
