### ISSUE TITLE
Unable to generate video, check /usr/share/zoneminder/www/events/.../ffmpeg.log

### ISSUE THREAD

**Issue by dreaddymck** [ZoneMinder/ZoneMinder#1146]
Re-opened previously closed issue #1126 

Fix for the following log ERR experienced using ubuntu 15.10

```
zmvideo[10668]: INF [Creating video file Event-1028-r1-s1.avi for event 1028]
zmvideo[10668]: ERR [Unable to generate video, check /usr/share/zoneminder/www/events/1/15/10/04/22/38/37/ffmpeg.log for details]
```
##

**Comment by connortechnology** [comment]
So... I don't think the \ in front of $command is the right thing to do.  You seem to be complaining that there is an error in your logs... but the error is telling where to look to find out what the error is.  You are going to have to go look in /usr/share/zoneminder/www/events/1/15/10/04/22/38/37/ffmpeg.log to find out.

**Comment by dreaddy** [comment]
The ffmpeg.log wasn't generated either. Adding the escape(\) character was a quick solution.

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
