### ISSUE TITLE
ZoneMinder Console - Stopped - v1.28.1

### ISSUE THREAD

**Issue by Simpler1** [ZoneMinder/ZoneMinder#1150]
I've recently installed ZoneMinder v1.28.1 on a Linux Mint 17.2 box.

I previously had a LAMP server installed on this machine which is still running fine.

When I open the <ip>/zm/index.php URL, it shows the following at the top of the screen:
`ZoneMinder Console - Stopped - v1.28.1`

even though the processes are running:
`user1@box410 ~ $ ps -ef | grep zm`
`www-data 14712     1  0 19:29 pts/0    00:00:00 /usr/bin/perl -wT /usr/bin/zmdc.pl startup`
`www-data 14741 14712 13 19:29 pts/0    00:04:35 /usr/bin/zmc -m 1`
`www-data 14745 14712  0 19:29 pts/0    00:00:00 /usr/bin/perl -wT /usr/bin/zmfilter.pl`
`www-data 14752 14712  0 19:29 pts/0    00:00:00 /usr/bin/perl -wT /usr/bin/zmaudit.pl -c`
`www-data 14769 14712  0 19:29 pts/0    00:00:00 /usr/bin/perl -wT /usr/bin/zmwatch.pl`
`user1    15259 14322  0 20:03 pts/0    00:00:00 grep --colour=auto zm`
`user1@box410 ~ $`

Even after I click "Stopped" and click "Apply" to "Start", the header never changes to "Running".

Also, when I add a new Monitor, the name is not clickable to view the camera.  The text of the name is there, but it's not a hyperlink with an "onclick()".

BTW, I tried the same install of ZoneMinder on a new VM of Linux Mint 17.2 and it works fine.  I can't figure out what's different between the two.  I've looked at the log files.  The log file on the broken machine actually states that it is capturing video, but it's not.

Please help...

**Comment by knnniggett** [comment]
Requests for installation help belong in our user forum. 
When posting, make sure and describe how you installed zoneminder, particularly what set of instructions you followed.
