### ISSUE TITLE
Misplaced comment

### ISSUE THREAD

**Issue by ledvinap** [ZoneMinder/ZoneMinder#1156]
There is misplaced comment in 
https://github.com/ZoneMinder/ZoneMinder/blob/master/scripts/Makefile.am#L60

Line continuation fails, breaking dpkg-buildpackage on debian in quite cryptic way (following lines are taken as command)

**Comment by knnniggett** [comment]
@ledvinap Note that the next release of ZoneMinder will likely be the last version to support autotools.
