### ISSUE TITLE
Migrate www to new host

### ISSUE THREAD

**Issue by kylejohnson** [ZoneMinder/ZoneMinder#1159]
I worked on this tonight, and I believe it is finished.

Please report any issues here!

Biggest thing to look out for are redirects and broken links.

E.g. both of these should redirect from the first to the last URL.

```
http://www.zoneminder.com/forums/viewtopic.php?f=32&t=23073
TO
https://www.zoneminder.com/forums/viewtopic.php?f=32&t=23073
TO
https://forums.zoneminder.com/viewtopic.php?f=32&t=23073

AND

http://www.zoneminder.com/wiki/Index.php/Documentation
TO
https://www.zoneminder.com/wiki/Index.php/Documentation
TO
https://wiki.zoneminder.com/Index.php/Documentation
```
##

**Comment by knnniggett** [comment]
Thanks @kylejohnson I'll keep an eye out.

**Comment by mnoorenberghe** [comment]
Given that this happened over a year ago I guess it can be closed.

(I'm triaging issues looking for ways to help.)
