### ISSUE TITLE
[patch] php54 incompatibility in views/image.php

### ISSUE THREAD

**Issue by abishai** [ZoneMinder/ZoneMinder#1163]
I upgraded to latest zmrepo development version and noticed that imagescale function was intruduced. This one is from php 5.5 and is not available in CentOS7 repo.

As CentOS7 is supported by ZM developers, I think workaround is required. I wrote simple wrapper around imagecopyresampled() and added at the beginning of the image.php after the header();
```
// Compatibility for PHP 5.4 
if (!function_exists('imagescale'))
{
	function imagescale($image, $new_width, $new_height = -1, $mode = 0)
	{
            $mode; // Not supported
      
            $new_height = ($new_height == -1) ? imagesy($image) : $new_height;
            $imageNew = imagecreatetruecolor($new_width, $new_height);
            imagecopyresampled($imageNew, $image, 0, 0, 0, 0, (int)$new_width, (int)$new_height, imagesx($image), imagesy($image));
            return $imageNew;
	}
}
```

**Comment by pliablepixels** [comment]
@abishai  - can you convert this into a Pull Request and reference it from this issue?  I can test it by forcing it on.

**Comment by abishai** [comment]
Never did that before, hope, I did it right
https://github.com/ZoneMinder/ZoneMinder/pull/1164

**Comment by pliablepixels** [comment]
Works well.
