### ISSUE TITLE
ERR [Connection dropped by remote end]

### ISSUE THREAD

**Issue by rajil** [ZoneMinder/ZoneMinder#1175]
I am using 1.28.1 with a remote camera feeding via mjpg-streamer. Sometimes the connection dies down and ZM starts to hammer the hard disk with a continuous stream of messages. iotop peaks to about 80%.

Here is the log produced:

Nov 29 21:33:53 server zmc_m5[9850]: WAR [Select timed out]
Nov 29 21:33:53 server zmc_m5[9850]: ERR [Connection dropped by remote end]
Nov 29 21:33:53 server zmc_m5[9850]: WAR [Unable to capture image, retrying]
Nov 29 21:33:53 server zma_m5[5401]: WAR [Signal: Lost]
Nov 29 21:33:55 server zmc_m5[9850]: WAR [Select timed out]
Nov 29 21:33:55 server zmc_m5[9850]: ERR [Connection dropped by remote end]
Nov 29 21:33:55 server zmc_m5[9850]: WAR [Unable to capture image, retrying]
Nov 29 21:33:58 server zmc_m5[9850]: WAR [Select timed out]
Nov 29 21:33:58 server zmc_m5[9850]: ERR [Connection dropped by remote end]
Nov 29 21:33:58 server zmc_m5[9850]: WAR [Unable to capture image, retrying]
Nov 29 21:34:00 server zmc_m5[9850]: WAR [Select timed out]
Nov 29 21:34:00 server zmc_m5[9850]: ERR [Connection dropped by remote end]
Nov 29 21:34:00 server zmc_m5[9850]: WAR [Unable to capture image, retrying]
Nov 29 21:34:03 server zmc_m5[9850]: WAR [Select timed out]
Nov 29 21:34:03 server zmc_m5[9850]: ERR [Connection dropped by remote end]
Nov 29 21:34:03 server zmc_m5[9850]: WAR [Unable to capture image, retrying]
Nov 29 21:34:06 server zmc_m5[9850]: WAR [Select timed out]
Nov 29 21:34:06 server zmc_m5[9850]: ERR [Connection dropped by remote end]
Nov 29 21:34:06 server zmc_m5[9850]: WAR [Unable to capture image, retrying]
Nov 29 21:34:08 server zmc_m5[9850]: WAR [Select timed out]
Nov 29 21:34:08 server zmc_m5[9850]: ERR [Connection dropped by remote end]
Nov 29 21:34:08 server zmc_m5[9850]: WAR [Unable to capture image, retrying]
Nov 29 21:34:11 server zmc_m5[9850]: WAR [Select timed out]
Nov 29 21:34:11 server zmc_m5[9850]: ERR [Connection dropped by remote end]
Nov 29 21:34:11 server zmc_m5[9850]: WAR [Unable to capture image, retrying]
Nov 29 21:34:13 server zmc_m5[9850]: WAR [Select timed out]
Nov 29 21:34:13 server zmc_m5[9850]: ERR [Connection dropped by remote end]
Nov 29 21:34:14 server zmc_m5[9850]: WAR [Unable to capture image, retrying]
Nov 29 21:34:16 server zmc_m5[9850]: WAR [Select timed out]
Nov 29 21:34:16 server zmc_m5[9850]: ERR [Connection dropped by remote end]
Nov 29 21:34:16 server zmc_m5[9850]: WAR [Unable to capture image, retrying]
Nov 29 21:34:19 server zmc_m5[9850]: WAR [Select timed out]
Nov 29 21:34:19 server zmc_m5[9850]: ERR [Connection dropped by remote end]
Nov 29 21:34:19 server zmc_m5[9850]: WAR [Unable to capture image, retrying]
Nov 29 21:34:21 server zmc_m5[9850]: WAR [Select timed out]
Nov 29 21:34:21 server zmc_m5[9850]: ERR [Connection dropped by remote end]
Nov 29 21:34:21 server zmc_m5[9850]: WAR [Unable to capture image, retrying]
Nov 29 21:34:24 server zmc_m5[9850]: WAR [Select timed out]
Nov 29 21:34:24 server zmc_m5[9850]: ERR [Connection dropped by remote end]
Nov 29 21:34:24 server zmc_m5[9850]: WAR [Unable to capture image, retrying]

The camera is defined as:
Source:remote
Function:modect
Max FPS:10
Alarm Max FPS:10
Remote Protocol:http
Remote Method: Regexp

Is there any way to make zm stop probing the camera when the connection drops?

**Comment by knnniggett** [comment]
There is nothing presented here that indicates this is the kind of problem which can be solved by a change to the source code. Please move this discussion to the user forum.

You don't want zoneminder to stop checking if the camera has come back. That would cause (has caused) a whole load of other complaints, and rightly fully so.

I do see that you've populated the Max & Alarm Max fields, which is guaranteed to cause problems if the incoming stream is >10 fps. Get rid of those values and instead restrict the frame rate on he sending side.

When posting in the user forum, we need a description the sending device and the properties of the stream being sent.  Maybe we can figure out how to keep the device from dropping offline in the first place, or maybe someone can come up with a nifty script to turn off the device in zoneminder if is stops returning a ping.
