### ISSUE TITLE
Debian/Ubuntu package files

### ISSUE THREAD

**Issue by atimonin** [ZoneMinder/ZoneMinder#1177]
When installing from source (v1.28.109) on ubuntu 15.04 found out:
1. in apache.conf /usr/share/zoneminder/www specified instead of /usr/share/zoneminder/
2. in /usr/share/www events and images are not links to /var/cache/zoneminder/.... (maybe temp also?)

**Comment by SteveGilvarry** [comment]
Distro specific issue not a bug, there is about 8 distro folders for debian/ubuntu so some may be out of date. Try this to save you hassles of working out which one works, one does as it is used to build this ppa https://launchpad.net/~iconnor/+archive/ubuntu/zoneminder-master.

https://github.com/ZoneMinder/ZoneMinder#building-from-source-is-discouraged
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules
