### ISSUE TITLE
Implement namespaces

### ISSUE THREAD

**Issue by SteveGilvarry** [ZoneMinder/zoneminder#1198]
As per #1190 we had to implement namespace to keep the Authenticator class from conflicting, this issue is to track the overall need to further implement namespaces to prevent this occurring again between zoneminder code and external libs.
Open for discussion on structure of namespaces, i.e. zm across all classes or split down to specific namespaces for by logical function groups.
##

**Comment by SteveGilvarry** [comment]
Just do it.

**Comment by connortechnology** [comment]
Did it.
