### ISSUE TITLE
Install wizard

### ISSUE THREAD

**Issue by kylejohnson** [ZoneMinder/zoneminder#12]
A wizard which walks you through installation, such as configuring the database, adding users, adding monitors, etc.
##

**Comment by kylejohnson** [comment]
I'm going to get this into 1.30 with the goal of easing install and new-user onboarding.

**Comment by SteveGilvarry** [comment]
Maybe 1.30.1?

**Comment by kylejohnson** [comment]
Unfortunately definitely not ready for 1.30.1
