### ISSUE TITLE
monitorUrl incorrect in non-MultiServer Envinroment

### ISSUE THREAD

**Issue by knnniggett** [ZoneMinder/ZoneMinder#1219]
@connortechnology 
Should be easy to fix.

monitorUrl, as defined in watch.js.php, looks like this when not in a multiserver environment:
 `var monitorUrl = 'https://';`

https://github.com/ZoneMinder/ZoneMinder/blob/master/web/skins/classic/views/js/watch.js.php#L51

That breaks a few of the widgets, like the state and the fps, in the Watch view.

So do we redefined $monitor->Server()->Url() to return empyset instead or just ignore it when it contains that particular value?

**Comment by knnniggett** [comment]
Thinking out loud here. 
Should we redesign things such that, not selecting a server under the monitor config, results in a value of localhost, rather than emptyset or none? Or would that cause other issues?

**Comment by connortechnology** [comment]
I think it needs to return a relative url or something similar... we can't assume that we are accessing localhost.  Easy fix though.

**Comment by connortechnology** [comment]
If no Server is set, it uses ZM_BASE_URL ... which used to be defined... but now is not.  Ok.  Need to use ZM_BASE_PATH instead...
