### ISSUE TITLE
Liveview and events video view isn't working if i enable OPT_USE_AUTH

### ISSUE THREAD

**Issue by rafaelrs** [ZoneMinder/ZoneMinder#1228]
Installed Zoneminder on Fedora 23, added 2 IP cameras. It's working good, liveview end events video showing normally thru web and in mobile ZmView.

But after i enabled OPT_USE_AUTH it stopped working until i disabled it back.

**Comment by knnniggett** [comment]
It's working fine here.
Stating "My widget does not work" without providing any additional technical information does not meet our criteria for a bug report.

You should ask for help in the user forum instead. Don't worry I'll be there to help.
In that post, you should state the exact version of zoneminder you are using, exactly how you installed zoneminder (where did you get it from <- VERY IMPORTANT), and what instructions you followed. You should also inspect your log files and post any info from there.
