### ISSUE TITLE
Privacy issues

### ISSUE THREAD

**Issue by spstrmlv** [ZoneMinder/ZoneMinder#1230]
The new "flat" skin triggers fonts downloads from google.com, at least on Firefox. How about we try to avoid feeding log entries to Google and everyone else that may be listening every time we log in to Zoneminder Console?
##

**Comment by knnniggett** [comment]
Yeah, that sucks.
Preliminary checks don't reveal any appearance issues if we simply delete the line that imports the fonts, but I don't use the flat sin myself. 

Fixed in #1232

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
