### ISSUE TITLE
Ubuntu 14.04 ppa installs wrong version

### ISSUE THREAD

**Issue by mdetweiler** [ZoneMinder/ZoneMinder#1236]
I followed these instructions and ended up with 1.26.5

https://wiki.zoneminder.com/Ubuntu_Server_14.04_64-bit_with_Zoneminder_1.28.1_the_easy_way

This is a freshly installed Ubuntu 14.04 server.  Any ideas?

**Comment by SteveGilvarry** [comment]
This does not describe a bug. 
Please refer to our github posting rules and then create a post in our user forum:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules
