### ISSUE TITLE
Add PTZ for Amcrest ip2m-841b pro hd 1080p

### ISSUE THREAD

**Issue by ExMM** [ZoneMinder/ZoneMinder#1238]
I have been trying to setup PTZ control for the Amcrest ip2m-841b pro hd 1080p camera.

Is that even possible?

I have been trying to use some Foscam profile as I know Amcrest is basically the same company, but without results, I keep getting errors like:

Control response was status = undefined
message = /usr/bin/zmcontrol.pl --tiltspeed=0 --command=moveConUp --id=3=>

Really don't know how to mod then.

**Comment by knnniggett** [comment]
Please read our posting guidelines:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules

Our github forum is reserved for bug reports and serious feature requests only. "How do I configure" questions should be asked either in our user forum or IRC channel.
