### ISSUE TITLE
Unable to open input due to: Success?

### ISSUE THREAD

**Issue by mob41** [ZoneMinder/ZoneMinder#1241]
Recently, I used ZoneMinder for camera recording, monitoring. When I tried to connect a camera to Zoneminder via FFMPEG. The monitor frame stayed blue. I checked out the logs. 

zmc_m3 11155 ERR Unable to open input 192.168.70.89:90/videostream.asf due to: Success

What is the problem behind?

I tried:
1. Restart zoneminder
2. Restart the computer
3. Install FFMPEG
4. Install libvlc-dev
5. Switched to Libvlc mode but it doesn't work.

P.S. The camera doesn't require password for the video stream (The camera is stupid. The video stream is not encrypted.) I also found that the camera is stupid as it returns the request header as "text/plain" when I tried to get the stream!

**Comment by knnniggett** [comment]
Please read our posting rules:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules

Camera configuration issues belong in the user forum.

When posting in the user forum we need to know:
- The version of zoneminder
- exactly how you installed zoneminder
- make/model of camera
- your complete monitor configuration (screenshots are preferred)
