### ISSUE TITLE
XML output works everywhere in the API, except for events.

### ISSUE THREAD

**Issue by salberin** [ZoneMinder/ZoneMinder#1250]
Wanted to use the shiny new API in XML format, which works nicely everywhere, except when trying to request the list of events in XML. For that URL (http://server/zm/api/events.xml) I get the following output:

```
$xml = Xml::fromArray(array('response' => $events));
echo $xml->asXML();
```

Which is obviously not what we expect.
##

**Comment by pliablepixels** [comment]
the xml outputs are untested - especially related to all the change made since mid of last year. I'd recommend you stick to JSON for now

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
