### ISSUE TITLE
Provide an ability to quit zms for a specific connkey

### ISSUE THREAD

**Issue by pliablepixels** [ZoneMinder/ZoneMinder#1253]
ZMS is written to implement a long running TCP connection continuously streaming images. The only way to quit the connection is to "kill the browser window". While this is fine for a desktop browser, it makes it almost impossible to release zms resources in single page mobile apps (like zmNinja or any other app in the future). Any web application that uses ``img src`` to display images does not have control on the stream and cannot terminate the TCP object on its own which makes it exceeding hard to remove 'zms' processes even when nothing is being viewed.

There is an option to send a "Pause" and "Stop" control command today - that pauses the image streaming but the zms process still continues in memory and headers are still exchanged.

Proposal: We introduce a new CMD_QUIT to zm_event.cpp and zm_monitor.cpp
that basically does this:

```
case CMD_QUIT :
        {
            Debug( 1, "User initiated stream termination" );
            exit(-1);

        }
```
 
I haven't tested this - but I'm going to do that in the next day or two. @connortechnology @knnniggett  - do you have any issues with this approach? I'm currently going nuts trying to plug zms leaks and it shouldn't be so hard.

Its currently very hard to try and contain run away zms processes since web-apps don't have the ability to "close" the window

**Comment by knnniggett** [comment]
I'm not sure we should return -1 when we exit, but I don't have a problem with this.

**Comment by connortechnology** [comment]
I'm cool with it.

**Comment by pliablepixels** [comment]
great. Yes, I'm doing exit(0). I'll test some more and PR
