### ISSUE TITLE
not load video stream

### ISSUE THREAD

**Issue by N3KRoN** [ZoneMinder/ZoneMinder#1258]
after update zoneminder to 1.29.0 and mysql db not load videostream on web. And in log i can see error:
"Attempt to fetch string value for ZM_OPT_USE_GOOG_RECAPTCHA, actual type is boolean. Try running 'zmupdate.pl -f' to reload config."

zmupdate.pl -f not help

**Comment by knnniggett** [comment]
This does does not describe a bug. You have to make sure all zoneminder processes are stopped before calling "zmupdate.pl -f" as root so it can get a lock on the dB.

If you still need support, then create a post in the user forum. Make sure to describe your system in detail, including your distro and how you installed zoneminder.
