### ISSUE TITLE
jquery 1.7.2 is too old

### ISSUE THREAD

**Issue by onlyjob** [ZoneMinder/ZoneMinder#1263]
[web/skins/classic/js/jquery-1.7.2.js](../blob/master/web/skins/classic/js/jquery-1.7.2.js) is too old. Please update to 1.11.3 or above.

**Comment by knnniggett** [comment]
Posting the following as a reminder to self that this might not be as easy as replacing the js file with a newer version: https://github.com/ZoneMinder/ZoneMinder/issues/785#issuecomment-95772526

**Comment by onlyjob** [comment]
JQuery upgrade guide https://jquery.com/upgrade-guide/1.9/ may be useful...

**Comment by connortechnology** [comment]
It probably is that easy.  We don't do much with it.

I'll pull it into my home system and see if anything breaks.

**Comment by onlyjob** [comment]
No, @connortechnology, please no minification. How many times we have to go through this?
Minified files are effectively pre-compiled binaries, un-modifiable, unreadable and non-distributable in Debian (i.e. non-free). It is a bad practice to commit pre-built files to Vcs.
Moreover there are even more concerns, including security: https://wiki.debian.org/onlyjob/no-minification

Please always commit uncompressed files. If you believe in minification than you can compress on build time.

**Comment by connortechnology** [comment]
Does debian not already package jquery?  Perhaps debian should use the debian package version as you do mootools?

**Comment by onlyjob** [comment]
Yes we can use "libjs-jquery" (v1.11.3 at the moment) but that's not the point. It is the best to have no pre-minified files committed. Otherwise there will be maintenance overhead, repacking tarball to throw away non-free content etc. Really it is not worth it: there are serious cons and no pros...
Besides mootools-1.5.1 may be not safe to replace with mootools-1.4.5...
