### ISSUE TITLE
incomplete copyright; license violation (removed copyright statement)

### ISSUE THREAD

**Issue by onlyjob** [ZoneMinder/ZoneMinder#1275]
[SPP1802SWPTZ.pm](../blob/master/scripts/ZoneMinder/lib/ZoneMinder/Control/SPP1802SWPTZ.pm) is based upon [FI8918W.pm](../blob/master/scripts/ZoneMinder/lib/ZoneMinder/Control/FI8918W.pm) therefore it is a derivative work. However original copyright statement(s) were removed/replaced with copyright "2015- Bobby Billingsley" which is a license violation. One shall not remove someone else's copyright statements and replace 'em with his own.

You can't do such things, @bofhdk. You should have preserve original copyright statements and add your own.
##

**Comment by SteveGilvarry** [comment]
Fixed in #1819
