### ISSUE TITLE
communication protocol

### ISSUE THREAD

**Issue by Juanicardinali** [ZoneMinder/ZoneMinder#1284]
I can't find the real protocol that ZM uses to do the streaming, i don't know if it is HLS, UDP, RTP RTSP ?

**Comment by knnniggett** [comment]
Please read our posting rules before creating issues:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules

This is not a discussion forum, but a bug reporting forum. Feel free to ask this question in our user forum or irc channel.
