### ISSUE TITLE
ZoneMinder consultants (new Wiki page)

### ISSUE THREAD

**Issue by onlyjob** [ZoneMinder/ZoneMinder#1287]
Hi team,

I want to make a new Wiki page "consultants" listing people and organisations offering commercial ZoneMinder support/services, similar to https://www.debian.org/consultants/ and https://civicrm.org/partners-contributors

I think list of known consultants with recognised skills around ZoneMinder may be of help to those who seek paid assistance and/or support/services as well as for contributors to help them raise some funds and (hopefully) contribute more.

I shall be happy to add my own company and I suppose @connortechnology would be interested to list his business as well.

It is not against GitHub TOS, right?

Please let me know if you have any objections or ideas. Thanks.

**Comment by connortechnology** [comment]
Yes this is needed and is on the todo list.

**Comment by onlyjob** [comment]
So shall I/we do it now?

**Comment by knnniggett** [comment]
Was @kylejohnson planning on putting something like this on our new website?

**Comment by onlyjob** [comment]
I think Wiki page might be better as it will be easier to update (or request changes).
For now we could start with wiki page and see how it goes. It can always be changed later.

**Comment by onlyjob** [comment]
https://github.com/ZoneMinder/ZoneMinder/wiki/Consultants
Done, nothing more to do here.
