### ISSUE TITLE
Build packages wiht onvif support in Ubuntu 12.04LTS (zm release 1.29)

### ISSUE THREAD

**Issue by POKKAHOH** [ZoneMinder/ZoneMinder#1289]
I wrote to @altaroca, he asked me open  issue here...

HOWTO build deb --with-onvif=yes in ubuntu 12.04 LTS you would 

1. apt-get install -y apache2 mysql-server php5 php5-mysql build-essential libmysqlclient-dev libssl-dev libbz2-dev libpcre3-dev libdbi-perl libarchive-zip-perl libdate-manip-perl libdevice-serialport-perl libmime-perl libpcre3 libwww-perl libdbd-mysql-perl libsys-mmap-perl yasm automake autoconf libjpeg8-dev libjpeg8 apache2-mpm-prefork libapache2-mod-php5 php5-cli libphp-serialization-perl libgnutls-dev libjpeg8-dev libavcodec-dev libavformat-dev libswscale-dev libavutil-dev libv4l-dev libtool ffmpeg libnetpbm10-dev libavdevice-dev libmime-lite-perl dh-autoreconf dpatch **quilt**;
2. ln -s distros/ubuntu1204 debian;
3.  dpkg-checkbuilddeps;
4. Edit /distros/ubuntu1204/rules  (_may be exist some autoconfig?_)
CFLAGS="$(CFLAGS)" CXXFLAGS="$(CXXFLAGS)" dh_auto_configure -- --host=$(DEB_HOST_GNU_TYPE) --build=$(DEB_BUILD_GNU_TYPE) --sysconfdir=/etc/zm --prefix=/usr --mandir=\$${prefix}/share/man --infodir=\$${prefix}/share/info --with-mysql=/usr --with-mariadb=/usr --with-webdir=/usr/share/zoneminder --with-ffmpeg=/usr --with-cgidir=/usr/lib/cgi-bin --with-webuser=www-data --with-webgroup=www-data --enable-crashtrace=no --enable-mmap=yes **--enable-onvif=yes**
5. Add strings to ./distros/ubuntu1204/install
usr/share/perl5/ONVIF
usr/share/perl5/WSDiscovery
usr/share/perl5/WSSecurity
6. Install perl packages
apt-get install libdata-dump-perl libclass-std-fast-perl libsoap-wsdl-perl libio-socket-multicast-perl
 (libsoap-lite-perl - install as dependences)
7. In 12.04 LTS repo not exist libdigest-sha1...
wget http://launchpadlibrarian.net/85191944/libdigest-sha1-perl_2.13-2build2_amd64.deb
dpkg -i libdigest-sha1-perl_2.13-2build2_amd64.deb
8. dpkg-buildpackage;
9. One level above you'll now find a deb package matching the architecture of the build host

**Comment by knnniggett** [comment]
Please follow our posting rules:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules
Our github forum is intended for bug reporting and feature requests only.

A few notes:
- Autotools is no longer supported and will be going away soon. Use cmake instead.
- Feel free to post your guide in the user forum if you wish. It simply does not belong in our github forum.
- One can see all the available cmake variables, including ZM_ONVIF, by looking here: https://github.com/ZoneMinder/ZoneMinder/blob/master/CMakeLists.txt
- Once #1273 is merged, it ONVIF support will be automatically included with every build on zoneminder, unless the build author turns it off.
