### ISSUE TITLE
recoded videos are smaller length

### ISSUE THREAD

**Issue by pranjal08** [ZoneMinder/ZoneMinder#1297]
In zoneminder, when I set function to record mode it saves only 2-3 mins videos...I want 10-15 mins..and in record mode it is triggering alarm..Can anyone help me?

**Comment by knnniggett** [comment]
We don't handle tech support requests in this forum, only bug reports, and what you have stated does not describe a bug.  Please read our posting rules and then create a thread in the user forum.
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules
