### ISSUE TITLE
Add input checking / validation when creating a group of monitors. 

### ISSUE THREAD

**Issue by bodegard** [ZoneMinder/ZoneMinder#1322]
Currently, it allows you to attempt to create a group, then press SAVE, but if you do not have any monitors selected it gives an SQL error. I think there should be some kind of validation that alerts the user that no monitors are selected, deactivates the SAVE button, or allow it to create an empty names group to add monitors to later.

`SQL-ERR 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'MonitorIds' cannot be null', statement was 'INSERT INTO Groups SET Name=?, MonitorIds=?'`

**Comment by knnniggett** [comment]
Oddly enough, I just mentioned in #1317 that I seem to recall some place in the web console where the buttons lit up incorrectly. I think this was it.
If memory serves, there should be some existing javascript that controls the state of the buttons on that popup. Guess it isn't working right. Will have to look into it.

**Comment by knnniggett** [comment]
@bodegard Please test #1326

**Comment by bodegard** [comment]
@knnniggett #1326 That fixed the issue. Thanks
