### ISSUE TITLE
Docker build of v1.29 stable tag fails with missing dependency (Ubuntu 15.10)

### ISSUE THREAD

**Issue by trelane** [ZoneMinder/ZoneMinder#1331]
trelane@zoneminder:~$ sudo docker build -t='andrew/release-1.29' github.com/ZoneMinder/ZoneMinder#v1.29.0
Sending build context to Docker daemon 95.12 MB
Step 1 : FROM ubuntu:precise
 ---> e4e69443bc98
Step 2 : MAINTAINER Kyle Johnson kjohnson@gnulnx.net
 ---> Running in 4ab1324286ea
 ---> 5840e3ae35c0
Removing intermediate container 4ab1324286ea
Step 3 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in 54ae44c5b088
 ---> 8ab669ef1dfb
Removing intermediate container 54ae44c5b088
Step 4 : RUN apt-get update && apt-get install -y       libpolkit-gobject-1-dev build-essential libmysqlclient-dev libssl-dev libbz2-dev libpcre3-dev     libdbi-perl libarchive-zip-perl libdate-manip-perl libdevice-serialport-perl libmime-perl libpcre3      libwww-perl libdbd-mysql-perl libsys-mmap-perl yasm automake autoconf libjpeg-turbo8-dev  libjpeg-turbo8 libtheora-dev libvorbis-dev libvpx-dev libx264-dev libmp4v2-dev libav-tools mysql-client   apache2 php5 php5-mysql apache2-mpm-prefork libapache2-mod-php5 php5-cli openssh-server         mysql-server libvlc-dev libvlc5 libvlccore-dev libvlccore5 vlc-data libcurl4-openssl-dev  libavformat-dev libswscale-dev libavutil-dev libavcodec-dev libavfilter-dev     libavresample-dev libavdevice-dev libpostproc-dev libv4l-dev libtool libnetpbm10-dev      libmime-lite-perl dh-autoreconf dpatch
 ---> Running in c0e1e3a73441
Hit http://archive.ubuntu.com precise Release.gpg
Get:1 http://archive.ubuntu.com precise-updates Release.gpg [198 B]
Get:2 http://archive.ubuntu.com precise-security Release.gpg [198 B]
Hit http://archive.ubuntu.com precise Release
Get:3 http://archive.ubuntu.com precise-updates Release [55.4 kB]
Get:4 http://archive.ubuntu.com precise-security Release [55.5 kB]
Get:5 http://archive.ubuntu.com precise/main Sources [1175 kB]
Get:6 http://archive.ubuntu.com precise/restricted Sources [5306 B]
Get:7 http://archive.ubuntu.com precise/universe Sources [6239 kB]
Get:8 http://archive.ubuntu.com precise/main amd64 Packages [1640 kB]
Get:9 http://archive.ubuntu.com precise/restricted amd64 Packages [9098 B]
Get:10 http://archive.ubuntu.com precise/universe amd64 Packages [6167 kB]
Get:11 http://archive.ubuntu.com precise/main i386 Packages [1641 kB]
Get:12 http://archive.ubuntu.com precise/restricted i386 Packages [9108 B]
Get:13 http://archive.ubuntu.com precise/universe i386 Packages [6180 kB]
Get:14 http://archive.ubuntu.com precise-updates/main Sources [607 kB]
Get:15 http://archive.ubuntu.com precise-updates/restricted Sources [8938 B]
Get:16 http://archive.ubuntu.com precise-updates/universe Sources [153 kB]
Get:17 http://archive.ubuntu.com precise-updates/main amd64 Packages [1266 kB]
Get:18 http://archive.ubuntu.com precise-updates/restricted amd64 Packages [24.0 kB]
Get:19 http://archive.ubuntu.com precise-updates/universe amd64 Packages [351 kB]
Get:20 http://archive.ubuntu.com precise-updates/main i386 Packages [1343 kB]
Get:21 http://archive.ubuntu.com precise-updates/restricted i386 Packages [24.0 kB]
Get:22 http://archive.ubuntu.com precise-updates/universe i386 Packages [362 kB]
Get:23 http://archive.ubuntu.com precise-security/main Sources [178 kB]
Get:24 http://archive.ubuntu.com precise-security/restricted Sources [4320 B]
Get:25 http://archive.ubuntu.com precise-security/universe Sources [53.2 kB]
Get:26 http://archive.ubuntu.com precise-security/main amd64 Packages [764 kB]
Get:27 http://archive.ubuntu.com precise-security/restricted amd64 Packages [18.3 kB]
Get:28 http://archive.ubuntu.com precise-security/universe amd64 Packages [166 kB]
Get:29 http://archive.ubuntu.com precise-security/main i386 Packages [840 kB]
Get:30 http://archive.ubuntu.com precise-security/restricted i386 Packages [18.3 kB]
Get:31 http://archive.ubuntu.com precise-security/universe i386 Packages [175 kB]
Fetched 29.5 MB in 15s (1862 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libavresample-dev
The command '/bin/sh -c apt-get update && apt-get install -y    libpolkit-gobject-1-dev build-essential libmysqlclient-dev libssl-dev libbz2-dev libpcre3-dev     libdbi-perl libarchive-zip-perl libdate-manip-perl libdevice-serialport-perl libmime-perl libpcre3      libwww-perl libdbd-mysql-perl libsys-mmap-perl yasm automake autoconf libjpeg-turbo8-dev  libjpeg-turbo8 libtheora-dev libvorbis-dev libvpx-dev libx264-dev libmp4v2-dev libav-tools mysql-client   apache2 php5 php5-mysql apache2-mpm-prefork libapache2-mod-php5 php5-cli openssh-server         mysql-server libvlc-dev libvlc5 libvlccore-dev libvlccore5 vlc-data libcurl4-openssl-dev  libavformat-dev libswscale-dev libavutil-dev libavcodec-dev libavfilter-dev     libavresample-dev libavdevice-dev libpostproc-dev libv4l-dev libtool libnetpbm10-dev      libmime-lite-perl dh-autoreconf dpatch' returned a non-zero code: 100

**Comment by mnoorenberghe** [comment]
The Dockerfile has since switched to `precise` and soon will switch to xenial (#1787) and both don't have this problem so I think this can be closed.
