### ISSUE TITLE
Zoneminder docker shouldn't run SSH, and should be tty enabled.

### ISSUE THREAD

**Issue by trelane** [ZoneMinder/ZoneMinder#1332]
Docker strongly does not recommend using SSH inside a container. https://blog.docker.com/2014/06/why-you-dont-need-to-run-sshd-in-docker/

The docker runfile should be modified (and the scripts therein) such that the container is tty enabled (-t)
you can still use ENV DEBIAN_FRONTEND noninteractive to automate the build.

This would be a significantly more secure replacement for OpenSSH.

**Comment by mnoorenberghe** [comment]
I believe this was fixed by #1774
