### ISSUE TITLE
Telemetry data collection to be disabled by default

### ISSUE THREAD

**Issue by kubaa24** [ZoneMinder/ZoneMinder#1342]
Hi everyone
I just noticed that telemetry data collection is enabled (at least for 1.29.0-vivid-2016030701). Would you please consider to have it disabled by default and perhaps to have a user prompt for opting in if one is happy with it? I trust that most people would like to have it setup that way. 

As a side note I wanted to add that 'Montage Review' is an absolutely incredible feature. Looking forward to seeing h264 storage implemented fully which will make ZM ultimate CCTV recording software...

**Comment by knnniggett** [comment]
Having a prompt for it something we certainly plan to add to the upcoming installation wizard.
However, just like the check-for-updates prompt, it will default to on, not off.
