### ISSUE TITLE
How does multiserver work?

### ISSUE THREAD

**Issue by newburns** [ZoneMinder/ZoneMinder#1343]
I have 5 VM's in a multiserver environment.
My server ids are vm103, vm104, vm105, vm106, vm107.
VM103 is my main connected server. I setup my cameras to record on VM104-VM107.
If I restart VM103, all of my events are still there just fine, but there is no montage view anymore.
I can't view the live feed of any camera, but I can confirm through HTOP that each camera is being recorded on the different servers.
If I go into each camera configuration and click 'Save', my main VM103 will start to have a significantly high load. As if IT is recording each of the cameras. But I can still confirm, the other servers are recording the cameras.

**Comment by knnniggett** [comment]
@newburns We have told you previously that this is not the place to ask "how do I configure" questions. As long as you continue to ignore the rules we have set forth to keep this environment manageable, we will continue to close them out without answering them.

If you want help, start by reading our posting rules:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules

Then feel free to ask this question in our IRC channel or user forum. 

I am not going to debate this with you and am locking this thread.
