### ISSUE TITLE
Pid field is too small

### ISSUE THREAD

**Issue by abishai** [ZoneMinder/ZoneMinder#1351]
Pid field in database schema is smallint, however PIDs at least in FreeBSD are 1 to 99999
https://www.freebsd.org/doc/handbook/basics-processes.html
At least MEDIUMINT (better to use INT for compatibility) is needed for that.

**Comment by knnniggett** [comment]
Yes, this is what I suspected. I just don't know FreeBSD well enough to find documentation which states what the range was. Glad you referenced it.

I'll let @kylejohnson take the lead on writing a PR for this since he just recently made the jump to FreeBSD on one of his production machines. I think we caught this just in time for the nest release.

**Comment by abishai** [comment]
I'm planning to move from CentOS to FreeBSD (I just love FreeBSD). I found that ZoneMinder port http://www.freshports.org/multimedia/zoneminder/ is extremely outdated. I started to work on the new one. At the moment my port compiles and installs ZoneMinder HEAD. Now I'm looking if I can use nginx to power zms instead of apache (I just love nginx). If @kylejohnson already works on the port, I can halt or share it.

**Comment by josh4trunks** [comment]
@abishai
I have some experience with porting stuff to freebsd. *can you host your modified port on github so we can work on it together?* then over we have it ready we can file a bug on bugs.freebsd.org. I think this needs a maintainer as well so maybe we can request to transfer it to you when we're done.

I also am decent at writing nginx configs and did have zoneminder working with nginx several years ago when I still used Ubuntu on my servers.

when I have more time i'd love to dive in and get a working port & freebsd based pbi/docker image & nginx config

**Comment by abishai** [comment]
@josh4trunks 
https://github.com/abishai/Zoneminder-port

**Comment by josh4trunks** [comment]
@abishai thanks when I have some free time I'll take a look
