### ISSUE TITLE
h264 Passthrough Disable for unsupported monitors in GUI

### ISSUE THREAD

**Issue by SteveGilvarry** [ZoneMinder/zoneminder#1373]
Currently h264 passthrough option on the Storage Tab shows up for all monitor types in the GUI, need to have a way to control visibility of this based on monitors that do actually support it, so currently ffmpeg only, but as discussed ffmpeg and remote for initial release.

**Comment by knight-of-ni** [comment]
I am going to close this out because I believe this has been implemented. Feel free to reopn this if this is not the case.

For example, if I arbitrarily pick the Curl source type, h264 passthrough appears dimmed in the storage drop down.
