### ISSUE TITLE
1.29.0 Bt878 Blue Screen

### ISSUE THREAD

**Issue by sikam32** [ZoneMinder/ZoneMinder#1375]
Hello ppl, im new here and im facing a problem with this new version of zoneminder.

i have two pci Brooktree Corporation Bt878 Video Capture (rev 11) 4 channel cards connected to my pc and running Ubuntu 14.04 x86. Until last version of zm (1.28.1) everything was fine but now after a fresh install of Ubuntu 14.04 x86 and Zoneminer 1.29 im seeing only blue screen on each monitor in my zm console and another strange thing is that zm not creating any event.

Can anyone help??

thx in advance

**Comment by knnniggett** [comment]
Hi @sikam32 
Please take a moment to read our posting rules:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules

Someone will be glad to help you configure your capture card in the user forum. Thank you.
