### ISSUE TITLE
Make ZMS stream h264 directly from event video file.

### ISSUE THREAD

**Issue by connortechnology** [ZoneMinder/zoneminder#1380]

**Comment by connortechnology** [comment]
Wwe can't be using a link directly to the video file.  Auth is required, and when storageareas gets put in, it just doesn't work.

So the link to video must be a link to zms.  So zms needs to be able to send the right stuff.

**Comment by isusername** [comment]
https://gist.github.com/isusername/c627a73dab23fc90c6ac4eec6e85374e
I made this from these:
http://www.media-division.com/php-download-script-with-resume-option/
zoneminder/www/skins/classic/views/image-ffmpeg.php from the feature-h264-videostorage branch.

It can be used by replacing
`<?php echo getEventDefaultVideoPath($event) ?>`
with
`?view=video-event&eid=<?php` echo $eid;?>`
in event.php and timeline.php
It works fine with authentication turned on.

**Comment by mastertheknife** [comment]
I think we can do that without zms.
A simple PHP script will do. We can use apache's mod_xsendfile to efficiently send the video file to the browser. Apache will take of everything, including partial transfers, making seeking possible.
I have done this at work but with MP3 files. it works well.

**Comment by connortechnology** [comment]
It needs to authenticate.

**Comment by connortechnology** [comment]
And we are moving away from apache long term.

**Comment by mnoorenberghe** [comment]
Nginx has sendfile support too. I agree a simple PHP script doing auth. plus sendfile would be efficient and easy.

**Comment by connortechnology** [comment]
I implemented this when implementing h265 support.
