### ISSUE TITLE
One RTSP Camera not working

### ISSUE THREAD

**Issue by petegriggs** [ZoneMinder/ZoneMinder#1414]
Hello,

I have three IP Cams and all were working fine until the hard disk in my server died and I had to rebuild. 2 are working fine using the Remote and RTSP config. The third just reports unable to decode frame 0 if I use the same method, however it works if I use the ffmpeg option how the camera feed is then stuttery and awful. Any ideas, its annoying as it was all working and the other 2 cameras as the same model they may just be different firmwares but like I said was working.

Any ideas welcome.

**Comment by knnniggett** [comment]
We only handle bug reports in this forums, and you have provided no information to indicate this is a bug.

Please read our posting rules, then feel free to seek help in our user forum:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules
