### ISSUE TITLE
(FreeBSD) Default timestamp contains no monitor name

### ISSUE THREAD

**Issue by abishai** [ZoneMinder/ZoneMinder#1426]
Default timestamp value is %N - %d/%m/%y %H:%M:%S, it shows in stream as N - timestamp
If I add leading % (%%N - %d/%m/%y %H:%M:%S ) it starts to work properly. Not found where the code is to figure what's the problem.

**Comment by josh4trunks** [comment]
is this set here?
https://github.com/ZoneMinder/ZoneMinder/blob/master/db/zm_create.sql.in#L353

**Comment by josh4trunks** [comment]
looks like it's different than the default so I'm guessing not

**Comment by josh4trunks** [comment]
Can anyone running linux using Zoneminder 1.29.1 comment? I'm wondering if this is a FreeBSD specific issue.

**Comment by SteveGilvarry** [comment]
@josh4trunks FreeBSD only, here I think https://github.com/ZoneMinder/ZoneMinder/blob/master/src/zm_monitor.cpp#L3142
<img width="161" alt="screen shot 2016-05-18 at 6 54 34 pm" src="https://cloud.githubusercontent.com/assets/7613276/15353013/4fce95a4-1d2a-11e6-9772-db1b0779e17b.png">

**Comment by josh4trunks** [comment]
Seems like a difference with BSD then. Like things running through this function need to be double escaped for some reason.

I confirmed '%f' also does not work, and needs the double **%**. Also position doesn't matter, %N / %f don't work properly anywhere in the label.
