### ISSUE TITLE
ZM 1.29 can't get cURL source type to work

### ISSUE THREAD

**Issue by mdetweiler** [ZoneMinder/ZoneMinder#1430]
ZM 1.29 installed on Ubuntu 14.04 using the PPA

I have the exact same config working on 1.28.107 with serveral IP cameras from Samsung and Axis.

I thought there was an issue with using avcons instead of ffmpeg so I installed ffmpeg as below:
sudo add-apt-repository ppa:mc3man/trusty-media
apt-get update
apt-get dist-upgrade
apt-get install ffmpeg

I made sure to enable it in the config and set the path, but still get no image and no usable error mesage in syslog.

Any idea?

Here is a log excerpt as ZM starts:
Apr 20 21:39:17 system-z zmpkg[31065]: INF [Sanity checking States table...]
Apr 20 21:39:17 system-z zmpkg[31065]: INF [Command: start]
Apr 20 21:39:17 system-z zmdc[31076]: INF [Server starting at 16/04/20 21:39:17]
Apr 20 21:39:20 system-z zmpkg[31065]: INF [Starting up services]
Apr 20 21:39:20 system-z zmdc[31076]: INF ['zmc -m 1' starting at 16/04/20 21:39:20, pid = 31100]
Apr 20 21:39:20 system-z zmdc[31100]: INF ['zmc -m 1' started at 16/04/20 21:39:20]
Apr 20 21:39:20 system-z undef[31100]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:20 system-z zmdc[31076]: ERR ['zmc -m 1' exited abnormally, exit status 255]
Apr 20 21:39:20 system-z zmdc[31076]: INF [Starting pending process, zmc -m 1]
Apr 20 21:39:20 system-z zmdc[31105]: INF ['zmc -m 1' started at 16/04/20 21:39:20]
Apr 20 21:39:20 system-z zmdc[31076]: INF ['zmc -m 1' starting at 16/04/20 21:39:20, pid = 31105]
Apr 20 21:39:20 system-z undef[31105]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:20 system-z zmdc[31076]: INF ['zmc -m 2' starting at 16/04/20 21:39:20, pid = 31109]
Apr 20 21:39:20 system-z zmdc[31109]: INF ['zmc -m 2' started at 16/04/20 21:39:20]
Apr 20 21:39:20 system-z undef[31109]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:20 system-z zmdc[31076]: ERR ['zmc -m 2' exited abnormally, exit status 255]
Apr 20 21:39:20 system-z zmc[31105]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:20 system-z zmdc[31076]: INF [Starting pending process, zmc -m 2]
Apr 20 21:39:20 system-z zmc[31105]: FAT [Unable to match Content-Type. Check URL, username and password]
Apr 20 21:39:20 system-z zmdc[31076]: ERR ['zmc -m 1' exited abnormally, exit status 255]
Apr 20 21:39:20 system-z zmdc[31076]: INF ['zmc -m 2' starting at 16/04/20 21:39:20, pid = 31113]
Apr 20 21:39:20 system-z zmdc[31113]: INF ['zmc -m 2' started at 16/04/20 21:39:20]
Apr 20 21:39:20 system-z zmdc[31115]: INF ['zmc -m 3' started at 16/04/20 21:39:20]
Apr 20 21:39:20 system-z zmdc[31076]: INF ['zmc -m 3' starting at 16/04/20 21:39:20, pid = 31115]
Apr 20 21:39:20 system-z undef[31113]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:20 system-z undef[31115]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:20 system-z zmdc[31076]: ERR ['zmc -m 3' exited abnormally, exit status 255]
Apr 20 21:39:20 system-z zmc[31113]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:20 system-z zmdc[31076]: INF [Starting pending process, zmc -m 3]
Apr 20 21:39:20 system-z zmdc[31120]: INF ['zmc -m 3' started at 16/04/20 21:39:20]
Apr 20 21:39:20 system-z zmdc[31076]: INF ['zmc -m 3' starting at 16/04/20 21:39:20, pid = 31120]
Apr 20 21:39:20 system-z undef[31120]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:20 system-z zmdc[31123]: INF ['zmc -m 4' started at 16/04/20 21:39:20]
Apr 20 21:39:20 system-z zmdc[31076]: INF ['zmc -m 4' starting at 16/04/20 21:39:20, pid = 31123]
Apr 20 21:39:21 system-z zmc[31120]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:21 system-z undef[31123]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:21 system-z zmdc[31076]: ERR ['zmc -m 4' exited abnormally, exit status 255]
Apr 20 21:39:21 system-z zmdc[31076]: INF [Starting pending process, zmc -m 4]
Apr 20 21:39:21 system-z zmdc[31076]: INF ['zmc -m 4' starting at 16/04/20 21:39:21, pid = 31130]
Apr 20 21:39:21 system-z zmdc[31130]: INF ['zmc -m 4' started at 16/04/20 21:39:21]
Apr 20 21:39:21 system-z undef[31130]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:21 system-z zmdc[31076]: INF ['zmc -m 5' starting at 16/04/20 21:39:21, pid = 31134]
Apr 20 21:39:21 system-z zmdc[31134]: INF ['zmc -m 5' started at 16/04/20 21:39:21]
Apr 20 21:39:21 system-z zmc[31130]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:21 system-z zmc[31130]: FAT [Unable to match Content-Type. Check URL, username and password]
Apr 20 21:39:21 system-z zmdc[31076]: ERR ['zmc -m 4' exited abnormally, exit status 255]
Apr 20 21:39:21 system-z undef[31134]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:21 system-z zmdc[31076]: ERR ['zmc -m 5' exited abnormally, exit status 255]
Apr 20 21:39:21 system-z zmdc[31076]: INF [Starting pending process, zmc -m 5]
Apr 20 21:39:21 system-z zmdc[31141]: INF ['zmc -m 5' started at 16/04/20 21:39:21]
Apr 20 21:39:21 system-z zmdc[31076]: INF ['zmc -m 5' starting at 16/04/20 21:39:21, pid = 31141]
Apr 20 21:39:21 system-z undef[31141]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:21 system-z zmdc[31076]: INF ['zmc -m 6' starting at 16/04/20 21:39:21, pid = 31144]
Apr 20 21:39:21 system-z zmdc[31144]: INF ['zmc -m 6' started at 16/04/20 21:39:21]
Apr 20 21:39:21 system-z undef[31144]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:21 system-z zmdc[31076]: ERR ['zmc -m 6' exited abnormally, exit status 255]
Apr 20 21:39:21 system-z zmc[31141]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:21 system-z zmdc[31076]: INF [Starting pending process, zmc -m 6]
Apr 20 21:39:21 system-z zmc[31141]: FAT [Unable to match Content-Type. Check URL, username and password]
Apr 20 21:39:21 system-z zmdc[31076]: ERR ['zmc -m 5' exited abnormally, exit status 255]
Apr 20 21:39:21 system-z zmdc[31150]: INF ['zmc -m 6' started at 16/04/20 21:39:21]
Apr 20 21:39:21 system-z zmdc[31076]: INF ['zmc -m 6' starting at 16/04/20 21:39:21, pid = 31150]
Apr 20 21:39:21 system-z zmdc[31153]: INF ['zmc -m 7' started at 16/04/20 21:39:21]
Apr 20 21:39:21 system-z zmdc[31076]: INF ['zmc -m 7' starting at 16/04/20 21:39:21, pid = 31153]
Apr 20 21:39:21 system-z undef[31150]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:21 system-z undef[31153]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:21 system-z zmdc[31076]: ERR ['zmc -m 7' exited abnormally, exit status 255]
Apr 20 21:39:21 system-z zmc[31150]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:21 system-z zmdc[31076]: INF [Starting pending process, zmc -m 7]
Apr 20 21:39:21 system-z zmc[31150]: FAT [Unable to match Content-Type. Check URL, username and password]
Apr 20 21:39:21 system-z zmdc[31076]: ERR ['zmc -m 6' exited abnormally, exit status 255]
Apr 20 21:39:21 system-z zmdc[31159]: INF ['zmc -m 7' started at 16/04/20 21:39:21]
Apr 20 21:39:21 system-z zmdc[31076]: INF ['zmc -m 7' starting at 16/04/20 21:39:21, pid = 31159]
Apr 20 21:39:21 system-z zmdc[31076]: INF ['zmc -m 8' starting at 16/04/20 21:39:21, pid = 31161]
Apr 20 21:39:21 system-z zmdc[31161]: INF ['zmc -m 8' started at 16/04/20 21:39:21]
Apr 20 21:39:21 system-z undef[31159]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:21 system-z undef[31161]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:21 system-z zmdc[31076]: ERR ['zmc -m 8' exited abnormally, exit status 255]
Apr 20 21:39:21 system-z zmdc[31076]: INF [Starting pending process, zmc -m 8]
Apr 20 21:39:21 system-z zmdc[31166]: INF ['zmc -m 8' started at 16/04/20 21:39:21]
Apr 20 21:39:21 system-z zmdc[31076]: INF ['zmc -m 8' starting at 16/04/20 21:39:21, pid = 31166]
Apr 20 21:39:21 system-z zmc[31159]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:21 system-z undef[31166]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:21 system-z zmdc[31076]: INF ['zmc -m 9' starting at 16/04/20 21:39:21, pid = 31170]
Apr 20 21:39:21 system-z zmdc[31170]: INF ['zmc -m 9' started at 16/04/20 21:39:21]
Apr 20 21:39:21 system-z zmc[31166]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:21 system-z undef[31170]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:21 system-z zmdc[31076]: ERR ['zmc -m 9' exited abnormally, exit status 255]
Apr 20 21:39:21 system-z zmdc[31076]: INF [Starting pending process, zmc -m 9]
Apr 20 21:39:21 system-z zmdc[31175]: INF ['zmc -m 9' started at 16/04/20 21:39:21]
Apr 20 21:39:21 system-z zmdc[31076]: INF ['zmc -m 9' starting at 16/04/20 21:39:21, pid = 31175]
Apr 20 21:39:21 system-z undef[31175]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:21 system-z zmdc[31179]: INF ['zmc -m 10' started at 16/04/20 21:39:21]
Apr 20 21:39:21 system-z zmdc[31076]: INF ['zmc -m 10' starting at 16/04/20 21:39:21, pid = 31179]
Apr 20 21:39:21 system-z zmc[31175]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:21 system-z undef[31179]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:21 system-z zmdc[31076]: ERR ['zmc -m 10' exited abnormally, exit status 255]
Apr 20 21:39:21 system-z zmdc[31076]: INF [Starting pending process, zmc -m 10]
Apr 20 21:39:21 system-z zmdc[31076]: INF ['zmc -m 10' starting at 16/04/20 21:39:21, pid = 31185]
Apr 20 21:39:21 system-z zmdc[31185]: INF ['zmc -m 10' started at 16/04/20 21:39:21]
Apr 20 21:39:21 system-z undef[31185]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:21 system-z zmdc[31188]: INF ['zmfilter.pl' started at 16/04/20 21:39:21]
Apr 20 21:39:21 system-z zmdc[31076]: INF ['zmfilter.pl' starting at 16/04/20 21:39:21, pid = 31188]
Apr 20 21:39:21 system-z zmc[31185]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:21 system-z zmdc[31196]: INF ['zmaudit.pl -c' started at 16/04/20 21:39:21]
Apr 20 21:39:21 system-z zmdc[31076]: INF ['zmaudit.pl -c' starting at 16/04/20 21:39:21, pid = 31196]
Apr 20 21:39:21 system-z zmfilter[31188]: INF [Scanning for events]
Apr 20 21:39:21 system-z zmdc[31076]: INF ['zmwatch.pl' starting at 16/04/20 21:39:21, pid = 31204]
Apr 20 21:39:21 system-z zmdc[31204]: INF ['zmwatch.pl' started at 16/04/20 21:39:21]
Apr 20 21:39:22 system-z zmdc[31076]: INF ['zmupdate.pl -c' starting at 16/04/20 21:39:22, pid = 31211]
Apr 20 21:39:22 system-z zmdc[31211]: INF ['zmupdate.pl -c' started at 16/04/20 21:39:22]
Apr 20 21:39:22 system-z zmwatch[31204]: INF [Watchdog starting]
Apr 20 21:39:22 system-z zmwatch[31204]: INF [Watchdog pausing for 30 seconds]
Apr 20 21:39:24 system-z zmc[31159]: WAR [Can't find payload details for audio payload type 98, name MPEG4-GENERIC]
Apr 20 21:39:25 system-z zmdc[31076]: INF [Starting pending process, zmc -m 1]
Apr 20 21:39:25 system-z zmdc[31229]: INF ['zmc -m 1' started at 16/04/20 21:39:25]
Apr 20 21:39:25 system-z zmdc[31076]: INF ['zmc -m 1' starting at 16/04/20 21:39:25, pid = 31229]
Apr 20 21:39:25 system-z undef[31229]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:25 system-z zmc[31229]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:25 system-z zmc[31229]: FAT [Unable to match Content-Type. Check URL, username and password]
Apr 20 21:39:25 system-z zmdc[31076]: ERR ['zmc -m 1' exited abnormally, exit status 255]
Apr 20 21:39:25 system-z zmc[31159]: WAR [Sequence in probation 2, out of sequence]
Apr 20 21:39:25 system-z zmc[31159]: WAR [Discarding frame 0]
Apr 20 21:39:26 system-z zmdc[31076]: INF [Starting pending process, zmc -m 5]
Apr 20 21:39:26 system-z zmdc[31076]: INF ['zmc -m 5' starting at 16/04/20 21:39:26, pid = 31232]
Apr 20 21:39:26 system-z zmdc[31232]: INF ['zmc -m 5' started at 16/04/20 21:39:26]
Apr 20 21:39:26 system-z zmdc[31076]: INF [Starting pending process, zmc -m 4]
Apr 20 21:39:26 system-z zmdc[31076]: INF ['zmc -m 4' starting at 16/04/20 21:39:26, pid = 31233]
Apr 20 21:39:26 system-z zmdc[31233]: INF ['zmc -m 4' started at 16/04/20 21:39:26]
Apr 20 21:39:26 system-z zmdc[31076]: INF [Starting pending process, zmc -m 6]
Apr 20 21:39:26 system-z undef[31232]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:26 system-z zmdc[31239]: INF ['zmc -m 6' started at 16/04/20 21:39:26]
Apr 20 21:39:26 system-z zmdc[31076]: INF ['zmc -m 6' starting at 16/04/20 21:39:26, pid = 31239]
Apr 20 21:39:26 system-z undef[31233]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:26 system-z zmc[31232]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:26 system-z zmc[31233]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:26 system-z zmc[31232]: FAT [Unable to match Content-Type. Check URL, username and password]
Apr 20 21:39:26 system-z undef[31239]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:26 system-z zmdc[31076]: ERR ['zmc -m 5' exited abnormally, exit status 255]
Apr 20 21:39:26 system-z zmc[31233]: FAT [Unable to match Content-Type. Check URL, username and password]
Apr 20 21:39:26 system-z zmdc[31076]: ERR ['zmc -m 4' exited abnormally, exit status 255]
Apr 20 21:39:26 system-z zmc[31239]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:26 system-z zmc[31239]: FAT [Unable to match Content-Type. Check URL, username and password]
Apr 20 21:39:26 system-z zmdc[31076]: ERR ['zmc -m 6' exited abnormally, exit status 255]
Apr 20 21:39:35 system-z zmdc[31076]: INF [Starting pending process, zmc -m 1]
Apr 20 21:39:35 system-z zmdc[31076]: INF ['zmc -m 1' starting at 16/04/20 21:39:35, pid = 31246]
Apr 20 21:39:35 system-z zmdc[31246]: INF ['zmc -m 1' started at 16/04/20 21:39:35]
Apr 20 21:39:35 system-z undef[31246]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:35 system-z zmc[31246]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:35 system-z zmc[31246]: FAT [Unable to match Content-Type. Check URL, username and password]
Apr 20 21:39:35 system-z zmdc[31076]: ERR ['zmc -m 1' exited abnormally, exit status 255]
Apr 20 21:39:36 system-z zmdc[31076]: INF [Starting pending process, zmc -m 5]
Apr 20 21:39:36 system-z zmdc[31249]: INF ['zmc -m 5' started at 16/04/20 21:39:36]
Apr 20 21:39:36 system-z zmdc[31076]: INF ['zmc -m 5' starting at 16/04/20 21:39:36, pid = 31249]
Apr 20 21:39:36 system-z zmdc[31076]: INF [Starting pending process, zmc -m 4]
Apr 20 21:39:36 system-z zmdc[31076]: INF ['zmc -m 4' starting at 16/04/20 21:39:36, pid = 31250]
Apr 20 21:39:36 system-z zmdc[31250]: INF ['zmc -m 4' started at 16/04/20 21:39:36]
Apr 20 21:39:36 system-z undef[31249]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:36 system-z zmdc[31076]: INF [Starting pending process, zmc -m 6]
Apr 20 21:39:36 system-z zmdc[31076]: INF ['zmc -m 6' starting at 16/04/20 21:39:36, pid = 31254]
Apr 20 21:39:36 system-z zmdc[31254]: INF ['zmc -m 6' started at 16/04/20 21:39:36]
Apr 20 21:39:36 system-z undef[31250]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:36 system-z zmc[31249]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:36 system-z zmc[31249]: FAT [Unable to match Content-Type. Check URL, username and password]
Apr 20 21:39:36 system-z zmdc[31076]: ERR ['zmc -m 5' exited abnormally, exit status 255]
Apr 20 21:39:36 system-z undef[31254]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:36 system-z zmc[31250]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:36 system-z zmc[31250]: FAT [Unable to match Content-Type. Check URL, username and password]
Apr 20 21:39:36 system-z zmdc[31076]: ERR ['zmc -m 4' exited abnormally, exit status 255]
Apr 20 21:39:36 system-z zmc[31254]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:36 system-z zmc[31254]: FAT [Unable to match Content-Type. Check URL, username and password]
Apr 20 21:39:36 system-z zmdc[31076]: ERR ['zmc -m 6' exited abnormally, exit status 255]
Apr 20 21:39:55 system-z zmdc[31076]: INF [Starting pending process, zmc -m 1]
Apr 20 21:39:55 system-z zmdc[31258]: INF ['zmc -m 1' started at 16/04/20 21:39:55]
Apr 20 21:39:55 system-z zmdc[31076]: INF ['zmc -m 1' starting at 16/04/20 21:39:55, pid = 31258]
Apr 20 21:39:55 system-z undef[31258]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:55 system-z zmc[31258]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:55 system-z zmc[31258]: FAT [Unable to match Content-Type. Check URL, username and password]
Apr 20 21:39:55 system-z zmdc[31076]: ERR ['zmc -m 1' exited abnormally, exit status 255]
Apr 20 21:39:56 system-z zmdc[31076]: INF [Starting pending process, zmc -m 5]
Apr 20 21:39:56 system-z zmdc[31076]: INF ['zmc -m 5' starting at 16/04/20 21:39:56, pid = 31261]
Apr 20 21:39:56 system-z zmdc[31261]: INF ['zmc -m 5' started at 16/04/20 21:39:56]
Apr 20 21:39:56 system-z zmdc[31076]: INF [Starting pending process, zmc -m 4]
Apr 20 21:39:56 system-z zmdc[31076]: INF ['zmc -m 4' starting at 16/04/20 21:39:56, pid = 31263]
Apr 20 21:39:56 system-z zmdc[31263]: INF ['zmc -m 4' started at 16/04/20 21:39:56]
Apr 20 21:39:56 system-z zmdc[31076]: INF [Starting pending process, zmc -m 6]
Apr 20 21:39:56 system-z undef[31261]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:56 system-z zmdc[31076]: INF ['zmc -m 6' starting at 16/04/20 21:39:56, pid = 31265]
Apr 20 21:39:56 system-z zmdc[31265]: INF ['zmc -m 6' started at 16/04/20 21:39:56]
Apr 20 21:39:56 system-z undef[31263]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:56 system-z zmc[31261]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:56 system-z zmc[31261]: FAT [Unable to match Content-Type. Check URL, username and password]
Apr 20 21:39:56 system-z zmdc[31076]: ERR ['zmc -m 5' exited abnormally, exit status 255]
Apr 20 21:39:56 system-z undef[31265]: INF [No Server ID or Name specified in config.  Not using Multi-Server Mode.]
Apr 20 21:39:56 system-z zmc[31263]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:56 system-z zmc[31263]: FAT [Unable to match Content-Type. Check URL, username and password]
Apr 20 21:39:56 system-z zmdc[31076]: ERR ['zmc -m 4' exited abnormally, exit status 255]
Apr 20 21:39:56 system-z zmc[31265]: INF [Starting Capture version 1.29.0]
Apr 20 21:39:56 system-z zmc[31265]: FAT [Unable to match Content-Type. Check URL, username and password]
Apr 20 21:39:56 system-z zmdc[31076]: ERR ['zmc -m 6' exited abnormally, exit status 255]

The monitors that work fine are, but are not using source type cURL:
2,3,7,8,9,10

The monitors that are having trouble and using source type cURL:
1,4,5,6

**Comment by mdetweiler** [comment]
Had some brief hope that I found the issue when I noticed that my working older install has the package below and some old threads about geting cURL to work say you need the -dev package.

apt-get install libcurl4-gnutls-dev

No luck still.

**Comment by knnniggett** [comment]
We have previously asked you to follow our posting rules:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules

The issue you have created in our github forum is not a bug report but is a request for help configuring your cameras. 

We will be glad to help you configure cameras in the user forum, in the thread you already created there: https://forums.zoneminder.com/viewtopic.php?f=34&t=24599
