### ISSUE TITLE
Default PATH_ZMS seems wrong (at least on Ubuntu)

### ISSUE THREAD

**Issue by daveselinger** [ZoneMinder/ZoneMinder#1432]
At first I thought the install may have failed, because cameras weren't visible. This is my first install, so hopefully this is helpful--and not user error.

Then I checked the HTML, found the image src was "/cgi-bin/nph-zms"
Simply changed this to "/zm/cgi-bin/nph-zms" and voila, it worked.

**Comment by knnniggett** [comment]
The best way to avoid this issue is to follow the installation instructions, which would have pointed this out and told you how to fix it. For the case of Ubuntu that would be the "easy way" instructions at wiki.zoneminder.com.
