### ISSUE TITLE
New monitor function: viewonly

### ISSUE THREAD

**Issue by caduellery** [ZoneMinder/ZoneMinder#1448]
Hello! Is there any way to achieve a "view only" function for monitors? Let's say I need to define 300 monitors, but just to have an "index of cameras" and access them just to visualize the live streams, individually. There is no need to record or analyze anything. The "monitor" function is not convenient, because the server would be receiving 300 streams simultaneously, wasting hardware and network resources.

The "viewonly" function would make ZoneMinder connect to the camera only when the user wants to view the live stream. Is this possible to be achieved? Thanks!

**Comment by knnniggett** [comment]
There are a number of ways to do this, but this is not the place to have this discussion. 
Feel free to discuss this in the user forum.

Here is thread where this topic was recently discussed:
https://forums.zoneminder.com/viewtopic.php?f=32&t=24579
