### ISSUE TITLE
OpenBSD cmake condition to skip librt

### ISSUE THREAD

**Issue by czettnersandor** [ZoneMinder/ZoneMinder#1477]
Because in OpenBSD, clock_gettime is provided by libc and librt does not exist, I came up with this updated line in CMakeLists.txt

if (UNIX AND NOT ${CMAKE_SYSTEM_NAME} MATCHES "OpenBSD")

Is this the proper solution? I'm not familiar with cmake, but it's a solution on OpenBSD, cmake is making further progress after the change. I'll check if this is the case in FreeBSD and other BSD like systems and add it to the condition.

**Comment by josh4trunks** [comment]
The updated FreeBSD port is being worked on here.
https://github.com/abishai/Zoneminder-port/tree/master/files

There are some patched to CMakeLists.txt so assuming OpenBSD uses a similar ports system you can probably do a similar thing.

**Comment by czettnersandor** [comment]
Great thanks, at least I will not work twice. Interesting He didn't disable librt, probably it's only a problem in OpenBSD.
