### ISSUE TITLE
API - Add Monitor returns Undefined index: Device

### ISSUE THREAD

**Issue by Glyphs** [ZoneMinder/ZoneMinder#1493]
Hello,

Whenever I try adding a new monitor through the API, the monitor is added without any information filled in. 
![image](https://cloud.githubusercontent.com/assets/10164439/15388735/b10e8cb4-1db3-11e6-8d89-46d8aafdd74e.png)

The webserver responds with a 200 (or 204? I accept both in my wrapper) but when I pull the actual response message out I see the following information:

`Notice (8): Undefined index: Device [APP/Controller/MonitorsController.php, line 243]
Code Context
MonitorsController::daemonControl() - APP/Controller/MonitorsController.php, line 243
MonitorsController::add() - APP/Controller/MonitorsController.php, line 106
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - CORE/Cake/Controller/Controller.php, line 490
AppController::invokeAction() - APP/Plugin/Crud/Lib/CrudControllerTrait.php, line 31
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 191
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 165
[main] - APP/webroot/index.php, line 108`

The data I am POST-ing to monitors.json is as follows:

`Monitor[Name]=Demo-Unit&Monitor[Function]=Modect&Monitor[Protocol]=http&Monitor[Method]=simple&Monitor[Host]=usr:pass@192.168.11.20&Monitor[Port]=80&Monitor[Path]=/mjpg/video.mjpg&Monitor[Width]=704&Monitor[Height]=480&Monitor[Colours]=4`

**EDIT:** Changed the post data to better represent the documented example.

As you can see, this does not include the Device option. Am I doing something wrong, or does this option in the API not work?

**Comment by pliablepixels** [comment]
I'm not sure what the exact command is, but there are two issues:

a) This works:
```
curl -k -b cookies.txt https://myserver:myport/zm/api/monitors.json -d"Monitor[Name]=test1-hyphen&Monitor[Function]=Modect&Monitor[Type]=Remote&Monitor[Protocol]=http&Monitor[Method]=simple&Monitor[Host]=a:b@1.1.1.1"
```

Produces:
![screen shot 2016-05-19 at 2 48 54 pm](https://cloud.githubusercontent.com/assets/4116654/15405692/ef806f40-1dd0-11e6-939e-d642025d7122.png)


b) However, the start to daemonControl is wrong, which is why after adding the monitor, it throws an error. To fix that, edit MonitorController.php, around line 106, remove the ``$this->request->data`` 

``
//$this->daemonControl($this->Monitor->id, 'start', $this->request->data);
$this->daemonControl($this->Monitor->id, 'start');
``

**Comment by Glyphs** [comment]
I'll have to try that later, not currently at a location where I have access to a ZM installation.

Anyhow, I'm not using a command from the linux box itself, so no curl involved. I've basically took what the documentation stated, and converted this to a C# method. A simple webrequest which POSTs data to the system with the data as its content. I'll have a fidget with that some more after I fix up MonitorController.php.

**Comment by Glyphs** [comment]
Just confirming that this did indeed fix the issue.
