### ISSUE TITLE
mocord doesn't always generate the correct movie timeframe

### ISSUE THREAD

**Issue by aviadoffer** [ZoneMinder/ZoneMinder#1502]
If the system is busy, zmvideo.pl generates a video file which does not match the actual event time.
Suggestion to zmvideo.pl

Add -start_number $first_alarm_frame 
my $first_alarm_frame = int($event->{Frames})-25-int($event->{AlarmFrames})-25;

   my $command = $Config{ZM_PATH_FFMPEG}
                 ." -y -r $frame_rate "
                 .$Config{ZM_FFMPEG_INPUT_OPTIONS}
                 ." -i %0"
                 .$Config{ZM_EVENT_IMAGE_DIGITS}
                 ."d-capture.jpg -s $video_size "
                 ."-start_number $first_alarm_frame "
                 .$Config{ZM_FFMPEG_OUTPUT_OPTIONS}
                 ." '$video_file' > ffmpeg.log 2>&1"
    ;

I choose 25 frames before and after but clearly it needs to be done better and dynamic based on the config. I just didn't know where it is.
Thanks,

**Comment by aviadoffer** [comment]
Think I got it wrong, here it is

    {
        my $sql = "SELECT * FROM Frames
                   WHERE EventId = ? AND Type = 'Alarm'
                   ORDER BY FrameId"
        ;
        my $sth = $dbh->prepare_cached( $sql )
            or Fatal( "Can't prepare '$sql': ".$dbh->errstr() );
        my $res = $sth->execute( $event->{Id} )
            or Fatal( "Can't execute '$sql': ".$sth->errstr() );
        while( my $frame = $sth->fetchrow_hashref() )
        {
            if ( !$first_alarm_frame )
            {
                $first_alarm_frame = $frame->{FrameId};
            }
        }
        $sth->finish();
    }
Also the -start_number needs to be before the -i (which is silly)

my $command = $Config{ZM_PATH_FFMPEG}
." -y -r $frame_rate "
.$Config{ZM_FFMPEG_INPUT_OPTIONS}
." -i %0"
.$Config{ZM_EVENT_IMAGE_DIGITS}
."-start_number $first_alarm_frame "
."d-capture.jpg -s $video_size "
.$Config{ZM_FFMPEG_OUTPUT_OPTIONS}
." '$video_file' > ffmpeg.log 2>&1"
;

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
