### ISSUE TITLE
Ongoing Modetect recordings get cancelled on camera disconnect

### ISSUE THREAD

**Issue by SharkWipf** [ZoneMinder/ZoneMinder#1512]
If you configure Zoneminder to record on motion, and it loses connection to the camera while triggered to record, it'll stop recording and not save the recorded event.

This means that a malicious person could effectively just unplug/otherwise disable the camera without raising alarms, even while it is already recording them.
Kinda makes the concept of a "security camera" a lot less secure.

Tested with:  
Source Type: Remote
Remote Protocol: HTTP
Remote Method: Simple
Remote Host Path: /video1.mjpg

**Comment by SharkWipf** [comment]
After I unplugged my camera yesterday, I left it unplugged. 
After 24 hours and 10 minutes, I got an email from Zoneminder saying it detected motion, linking to a recording of me unplugging the camera.
Sounds to me like it does record the video, crashes on disconnect and later picks up the pieces again.
However, some earlier disconnect recordings did not go through, even after 48+ hours.

**Comment by 0xABAB** [comment]
ZoneMinder appears to be developed by people without credentials and in general they don't seem to know what they are doing. Expecting ZoneMinder to work is a mistake.

**Comment by SharkWipf** [comment]
#salty

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
