### ISSUE TITLE
do_debian.sh version name for package

### ISSUE THREAD

**Issue by pliablepixels** [ZoneMinder/ZoneMinder#1517]
This is only applicable to folks to want to build packages from source and in the case of non-stable builds.

``do_debian.sh`` uses ``zoneminder_release/version`` to determine package name version. Given our recent discussion about not bumping up version in rc builds, this leads to a confusing representation where the package that is built is called 1.29 but is actually 1.30 (in the case where 1.30 is not stable) when installed.

Given that @connortechnology uses this file for local version changes, does it make sense to add an option to do_debian - ``gitversion`` or something that replaces [VERSION](https://github.com/ZoneMinder/ZoneMinder/blob/master/utils/do_debian_package.sh#L40) with the value of ``git describe --tags $(git rev-list --tags --max-count=1)`` ? That way for others building a package from source, the output is always consistent. Thoughts?

**Comment by knnniggett** [comment]
This is the same conversation that is discussed in #1515 
See that issue for the proposed solution which will solve this.

**Comment by pliablepixels** [comment]
One of the reasons I made this a separate issue was it is not clear to me if those discussions resolve this particular issue. If it is, I'll close this.

My understanding so far is you will not be changing the release version in the version file for pre-releases  (irrespective of whether the version file is in a wiki page or not). Is that correct? If so, this issue will continue?

**Comment by knnniggett** [comment]
Yes, this is exactly the problem @connortechnology described in #1485. This is why even he can't build a package right now. The solution is shown in #1515 . 

Let's not unnecessarily spawn more issues surrounding the same topic. You can always ask the question within the existing issue if it applies or not.

**Comment by pliablepixels** [comment]
Happy to close this, but you haven't answered my core question - will you be updating the version text for pre-releases as well (like 1.30 right now) ? If so, that PR will solve it. If not, then this is a different issue, not related to the PR you pointed me to.
