### ISSUE TITLE
Zoneminder just stops randomly

### ISSUE THREAD

**Issue by locutus13** [ZoneMinder/ZoneMinder#1523]
I have a strange issue with the Zoneminder installation on my Raspberry Pi 3:

At random times - usually when there is a lot of motion detection going on - the zoneminder service just stops - without a valid explanation.

Here are some details on my specs:
Raspberry Pi 3
used this installation guide: https://wiki.zoneminder.com/Raspbian

5 Cameras with 640x480 resolution @ 2 FPS 
No wifi used

I put a txt file with 2 minutes before the latest shutdown in the attachment. There are some buffer overruns - not sure how to fix those yet - but there is no message explaining the "zmpgk.pl - Command: stop"

I also checked the Apache log and the system log: Noone was logged in or accessing the server during that time.

Anybody got an idea?
Thank you for your assistance
[zm-log-part.txt](https://github.com/ZoneMinder/ZoneMinder/files/303145/zm-log-part.txt)

PS: I will add a log with debug switched on the next time I catch it "just stopping" - but the last time I checked with debug on all additional info I got was about tracking motion.

**Comment by knnniggett** [comment]
Your post does not describe a bug and this is not a technical support forum.

Please read our posting rules and then create a post in the user forum:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules
