### ISSUE TITLE
(TRIVIAL) 1.30 is not compiling under FreeBSD11-ALPHA3

### ISSUE THREAD

**Issue by abishai** [ZoneMinder/ZoneMinder#1530]
FreeBSD11 is not yet released. however packages are built against it as well. 
We need a hint what abs() to use. Can we assume that *psrc is long ?

/wrkdirs/usr/ports/multimedia/zoneminder/work/ZoneMinder-1.30.0-rc1/src/zm_image.cpp:1624:24: error: call to 'abs' is ambiguous
        if ( (unsigned)abs((*psrc)-RGB_VAL(ref_colour,c)) >= RGB_VAL(threshold,c) )
                       ^~~
/usr/include/stdlib.h:83:6: note: candidate function
int      abs(int) __pure2;
         ^
/usr/include/c++/v1/stdlib.h:115:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
                                           ^
/usr/include/c++/v1/stdlib.h:117:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT {return llabs(__x);}
                                           ^
/usr/include/c++/v1/math.h:646:1: note: candidate function
abs(float __lcpp_x) _NOEXCEPT {return fabsf(__lcpp_x);}
^
/usr/include/c++/v1/math.h:650:1: note: candidate function
abs(double __lcpp_x) _NOEXCEPT {return fabs(__lcpp_x);}
^
/usr/include/c++/v1/math.h:654:1: note: candidate function
abs(long double __lcpp_x) _NOEXCEPT {return fabsl(__lcpp_x);}

**Comment by abishai** [comment]
Or use fabs(), it's less overloaded.

**Comment by abishai** [comment]
Or labs() :)
I don't know what solution is better.

**Comment by abishai** [comment]
As we already has workaround for SOLARIS here, maybe remove abs entirely if it's so confuse compiler?
        unsigned int diff = ((*psrc)-RGB_VAL(ref_colour,c)) > 0 ? (*psrc)-RGB_VAL(ref_colour,c) : RGB_VAL(ref_colour,c) - (*psrc);
        if (diff >= RGB_VAL(threshold,c))
        {
          count++;
        }

If you don't have better ideas, I can make a PR.

**Comment by connortechnology** [comment]
I'm not sure why it is confused, but we don't need the float version of abs.  The values being compared at uint8_t...

**Comment by abishai** [comment]
Yeh, I looked into the code lately and rewrited it to dump compare instead of abs() at all.

**Comment by abishai** [comment]
Also, the error is gone of I convert *psrc to long.

**Comment by kylejohnson** [comment]
@abishai  Did you ever get this resolved?

**Comment by abishai** [comment]
I'm patching sources before build.
See https://svnweb.freebsd.org/ports/head/multimedia/zoneminder/files/patch-src_zm__image.cpp?revision=417142&view=markup

However, I'd like it to be upstreamed if you find solution suitable.
