### ISSUE TITLE
zmvideo.pl should return filename

### ISSUE THREAD

**Issue by abishai** [ZoneMinder/ZoneMinder#1542]
Looks like it's expected that zmvideo.pl returns something, however it's not, so we'll get Video Generation Failed
https://github.com/ZoneMinder/ZoneMinder/blob/master/web/includes/functions.php#L1075
https://github.com/ZoneMinder/ZoneMinder/blob/fe46785e94081d86b6dfb565c423198b52855c77/web/ajax/event.php#L23

**Comment by knnniggett** [comment]
You need to tell us exactly what you are trying to do. Did you configure ffmpeg properly under options? That is the most common cause to failed video generation.

**Comment by abishai** [comment]
Video generated, however ZM tolds me Video Generation Failed. createVideo() expects that zmvideo.pl will write something in console on success, however it's not (see disabled prints in the end)

**Comment by 0xABAB** [comment]
`Video generation failed` message also happens with the lowest speed and lowest quality settings when creating an AVI file with correctly configured ffmpeg with 1.29. It does work for a higher quality setting with more frames per second.  

This feels extremely flakey to me. It's like if you look at ZoneMinder wrong, it breaks. Is the original author to blame for this? Is it the ffmpeg people?  

The reported error is way too vague to be useful. While there might be logs, it would be *much* better to just show that in the UI too (e.g. a "details" link).

**Comment by abishai** [comment]
ZM uses https://github.com/ZoneMinder/ZoneMinder/blob/master/web/includes/functions.php#L1074 exec() to ezecute external script. It returns the last row from the external script output if execution success. The problem is that zmvideo.pl is not always return output. Actually, in most cases it won't return output to console, so at the end, the file will be created, but Generation Failed error printed.

**Comment by abishai** [comment]
@0xABAB you can easily trace the root of the problem by inserting the debug code https://github.com/ZoneMinder/ZoneMinder/blob/master/web/includes/functions.php#L1074 here to grab $command . After that, call the command from the console. It would be interesting to see what it's writing with different settings.

**Comment by knnniggett** [comment]
Fixed. See #1557
