### ISSUE TITLE
(1.30.3 storage areas) Unable to view stream when OPT_USE_AUTH enabled

### ISSUE THREAD

**Issue by moeiscool** [ZoneMinder/ZoneMinder#1543]
Ubuntu 16.04

when i try to view the stream the log shows 
```
2016-06-18 11:07:36.914646	zms		3712	ERR	Unable to authenticate user	zms.cpp	225
2016-06-18 11:07:36.672888	zms		3711	ERR	Unable to authenticate user	zms.cpp	225
2016-06-18 11:07:36.494288	zms		3710	ERR	Unable to authenticate user	zms.cpp	225
2016-06-18 11:07:36.319226	zms		3709	ERR	Unable to authenticate user	zms.cpp	225
2016-06-18 11:07:36.087327	web_php		3531	WAR	Unknown function call Monitor->CanMoveCon	/usr/share/zoneminder/www/includes/Monitor.php	57
2016-06-18 11:07:36.085793	web_php		3531	WAR	Unknown function call Monitor->CanMoveRel	/usr/share/zoneminder/www/includes/Monitor.php	57
2016-06-18 11:07:36.082661	web_php		3531	WAR	Unknown function call Monitor->CanMoveMap	/usr/share/zoneminder/www/includes/Monitor.php	57
```

but when i turn off auth and view it works fine. I could not find zms.cpp in the /usr/bin folder... is it somewhere else?

oddly enough this only occurs on my production server. I cannot reproduce the error on my local instance.

I also did copy of the DB from the local instance onto the production, instead of doing zm_create as that still threw an error... but even with the error it seemed to write a bunch of the tables... will get the error message and post it shortly.

zm_create says error is this line
`insert into Filters values ('PurgeWhenFull','{"sort_field":"Id","terms":[{"val":0,"attr":"Archived","op":"="},{"cnj":"and","val":95,"attr":"DiskPercent","op":">="}],"limit":100,"sort_asc":1}',0,0,0,0,0,0,'',1,1,0);`

after i edit the line from the sql file it runs properly.

`insert into Filters values (1,'PurgeWhenFull','{"sort_field":"Id","terms":[{"val":0,"attr":"Archived","op":"="},{"cnj":"and","val":95,"attr":"DiskPercent","op":">="}],"limit":100,"sort_asc":1}',0,0,0,0,0,0,'',1,1,0);`

i just added the Id Number at the beginning of the insert and it added.

**Comment by moeiscool** [comment]
so ive found that if open up the console on the stream
then add the user and pass fields to the url it works.. 
`/zm/cgi-bin/nph-zms?mode=jpeg&scale=100&maxfps=5&buffer=1000&monitor=2&auth=c4bdc1c108f0213469fc97521c1d2110&connkey=515277&rand=1466280768**&user=admin&pass=admin**`

**Comment by connortechnology** [comment]
interesting.  I was recently messing around with that code, so I might have broken something.  

Thanks for the report.  I will get to the bottom of it, but likely not till Monday.

**Comment by connortechnology** [comment]
zms is located in /usr/lib/zoneminder/cgi-bin

The CanMoveCon etc warnings should be gone in the latest build. 

I can't imagine why auth is not working for you.  It works great for me of course. Did it work for you in master branch?

**Comment by SteveGilvarry** [comment]
Same as #1552 going to close this out in favour of the one occurring in master multi-server, but does appear that @connortechnology not seeing this in his installations.
