### ISSUE TITLE
(FreeBSD) Storage areas compilation failure

### ISSUE THREAD

**Issue by abishai** [ZoneMinder/ZoneMinder#1545]
```
/wrkdirs/usr/ports/multimedia/zoneminder/work/ZoneMinder-1.30.0-rc1/src/zm_remote_camera_http.cpp:111:13: error: invalid application of 'sizeof' to an
      incomplete type 'struct in6_addr'
                        char buf[sizeof(struct in6_addr)];

```
You need to add `netinet/in.h ` in scope of usage of that struct http://www.leidinger.net/FreeBSD/dox/netinet6/html/d4/d7d/structin6__addr.html
I found int6_addr only in zm_remote_camera_http.cpp, so adding this in the beginning of the file solves the issue.
```
#ifdef __FreeBSD__
#include <netinet/in.h>
#endif
```

**Comment by connortechnology** [comment]
You are correct of course. merged.
