### ISSUE TITLE
Is there a CentOS installation video tutorial

### ISSUE THREAD

**Issue by pedoro** [ZoneMinder/ZoneMinder#1572]
Is where defined the buildzm.sh?

page:http://zoneminder.readthedocs.io/en/latest/installationguide/redhat.html
this line:buildzm.sh zmrepo-el7-x86_64 ~/rpmbuild/SRPMS/zoneminder-1.28.1-2.el7.centos.src.rpm

**Comment by SteveGilvarry** [comment]
General support is not provided through github issues, please use our forums at zoneminder.com.
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules
