### ISSUE TITLE
ZM v1.30.0 - "Preserve Aspect Ratio" setting isn't saved

### ISSUE THREAD

**Issue by morphey1** [ZoneMinder/ZoneMinder#1574]
Hello,

I found out that in the ZM v1.30.0 Monitor (source settings), the "Preserve Aspect Ratio" option is not saved. Also browsing database in the "Monitors" I do not see any options for it.

Thank you

**Comment by SteveGilvarry** [comment]
It is javascript function. Tick the box and change the width and height will change with it.
https://github.com/ZoneMinder/ZoneMinder/blob/master/web/skins/classic/views/js/monitor.js#L1
