### ISSUE TITLE
ZM v1.30.0 - RTSP double image

### ISSUE THREAD

**Issue by morphey1** [ZoneMinder/ZoneMinder#1575]
Hi,

I have a problem with a RTSP camera (onvif).
Any imposed resolution parameters, the live image is double (mirror) and cut in half as screenshots.
Has anyone had the same problem?

Thank you.

![schermata del 2016-08-01 10-06-54](https://cloud.githubusercontent.com/assets/16464184/17287399/b422b8e8-57cf-11e6-8397-847c0b2752a2.png)

**Comment by knnniggett** [comment]
Hi, 
We do not accept issues in our github forum, which are not clear indications of a bug in the software.
Please post camera configuration issues to the user forum. Thank you.
