### ISSUE TITLE
Live View Socket Error

### ISSUE THREAD

**Issue by twitchy1373** [ZoneMinder/ZoneMinder#1596]
Hello all,

I have been digging around on the forums for a couple days now trying to resolve my issue.  I cannot get live stream to work, as it is giving me a socket error.  Some general information:

I am running lubuntu 140.04 LTS

This is a brand new install with no previous upgrades.

This is a short copy of my log showcasing the error, but also showing what I believe to be my back end working.

[zm-log.txt](https://github.com/ZoneMinder/ZoneMinder/files/423128/zm-log.txt)

Any feedback is greatly appreciated and thank you in advanced!

**Comment by knnniggett** [comment]
This is not a bug, but a common configuration error which is frequently discussed in the user forum.
