### ISSUE TITLE
zmrepo install fails on RHEL 7.2 Server

### ISSUE THREAD

**Issue by jmearrle** [ZoneMinder/ZoneMinder#1598]
Hayloo,

I am trying to install zmrepo on RHEL7 but get the errors below:

Followed the instructions on zmrepo site to try to install but ...
The URL for 7Server should be 7 but I haven't been able to fix the script.

Because zmrepo is meant to install on rhel 7 out of the box, I don't want to play with it because I need to be able to package it up late.

My repos are purely redhat so I believe the system is 'clean,' 
and it does not exhibit any problems when running yum update.
The error message points to the missing file but the message leads to repo gets that don't work because rhel is setup to use Classic and RHSM subscriptions. But my system is only using subscription-manager and is not setup to use the classic subscription.

I searched the forums and web but nottathing I could find to resolve this.

     Are there scripts for installing zmrepo on RHEL 7.2 Server? 
     Or please help me fix this error.

Thanks
Jazzzzzzz

=================================
[zm]$ sudo yum install zoneminder
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-
              : manager
http://zmrepo.connortechnology.com/el/7Server/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article 

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.

http://67.53.78.182/el/7Server/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
zmrepo                                                   |  13 kB     00:00     
http://zmrepo.mehvc.com/el/7Server/x86_64/repodata/repomd.xml: [Errno -1] Error importing repomd.xml for zmrepo: Damaged repomd.xml file
Trying other mirror.

 One of the configured repositories failed (Zoneminder and its dependencies for Enterprise Linux 7Server - x86_64),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable zmrepo

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=zmrepo.skip_if_unavailable=true

failure: repodata/repomd.xml from zmrepo: [Errno 256] No more mirrors to try.
http://zmrepo.connortechnology.com/el/7Server/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
http://67.53.78.182/el/7Server/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
http://zmrepo.mehvc.com/el/7Server/x86_64/repodata/repomd.xml: [Errno -1] Error importing repomd.xml for zmrepo: Damaged repomd.xml file
[zm]$

**Comment by SteveGilvarry** [comment]
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules
Please raise in forums where general support is managed.
