### ISSUE TITLE
stopping zmc when setting monitor function to None trough APIs

### ISSUE THREAD

**Issue by sctt** [ZoneMinder/ZoneMinder#1606]
Hello,

my problem is explained here :
https://forums.zoneminder.com/viewtopic.php?f=34&t=25205

in short, if i set my monitor function to None trought ZM web interface, zmc process is stopped and i can't see live stream (expected behavior).
but if i set it to None trough APIs, zmc process is stopped but then restarted, so i can see live stream perfectly (unexpected behavior).

to work around this i modified the edit method of MonitorsController class in this way:
```
[...]
                $this->set(array(
                        'message' => $message,
                        '_serialize' => array('message')
                ));

                $func = $this->Monitor->find('first', array(
                        'fields' => array('Function'),
                        'conditions' => array('Id' => $id)
                ))['Monitor']['Function'];

                if ($func == 'None') {
                    $cmd = 'stop';
                }
                else {
                    $cmd = 'restart';
                }

                // - restart this monitor after change
                $this->daemonControl($this->Monitor->id, $cmd);
        }

[...]
```

i did a lot of tests and that actually solved my problem, but i'd like to know your opinion about this.
in particular:

- is this problem known? someone else experimented it?
- is it right to stop zmc if monitor function is None? why using APIs it is currently restarted?

thank you.

**Comment by kylejohnson** [comment]
@sctt I think stopping `zmc` is appropriate when function is set to `None`.  The fact that the APIs restart the monitor instead of stopping it was an oversight.
