### ISSUE TITLE
Issues with image rotation in montage review view

### ISSUE THREAD

**Issue by tommycw1** [ZoneMinder/ZoneMinder#1611]
This is related to "Issues with image rotation #1431".  When a camera is rotated 90 deg in the source, the montage review view shows the image shows rotated, but uses a non-rotated resolution.  So a 1920x1080 camera that is rotated 90deg should show as a 1080x1920 image, but instead it is showing as a squashed rotated image at 1920x1080.

Issue 1431 fixed this in all other views.

**Comment by schlosserbd** [comment]
I'm getting the same bug still in version v1.30.4. Any chance someone could extend [https://github.com/ZoneMinder/ZoneMinder/pull/1442](url) to fix the montage review as well?
