### ISSUE TITLE
same old onvif ptz cam issues

### ISSUE THREAD

**Issue by craigstill** [ZoneMinder/ZoneMinder#1616]
trying to get panning up down left and right no sure about settings for control , cam workers fine connects and recorded but no ptz control Control Device and Control Address fields are empty
im running 1.29 zone minder on unraid server cam as lil easy web page for mobile to control it 
"
<html>
<head>
<title>Video Mobile</title>
<meta content="text/html; charset=utf-8" http-equiv="content-type">
<script type="text/javascript" src="js/language.js"></script>
<script language="javascript">

</script>
</head>
<body onLoad="load()">
<form name="form1" method="get" target="test">
</form>
<p><input type="button" value="&#8593;" name="B3" onClick="ptzUpSubmit()"> 
<input type="button" value="&#8595;" name="B2" onClick="ptzDownSubmit()"> 
<input type="button" value="&#8592;" name="B1" onClick="ptzLeftSubmit()"> 
<input type="button" value="&#8594;" name="B0" onClick="ptzRightSubmit()"> 
<button type="button" name="B4" onClick="location.reload()"><script type="text/javascript">document.write(str_refresh);</script></button>
</p>
<p><img id="img1" border="0" src="tmpfs/auto.jpg"></p>
<iframe name="test" style="none" width="0" height="0"></iframe>
</body>
</html>"

and works in ispy to connect and control 

any help pleaseeeee

**Comment by knnniggett** [comment]
Please read our posting rules:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules

This belongs in the user forum.
We don't troubleshoot camera configuration problems in our github forum.
