### ISSUE TITLE
feature-h264-videostorage cannot add or edit zones

### ISSUE THREAD

**Issue by hableel** [ZoneMinder/ZoneMinder#1630]
In the branch feature-h264-videostorage, zoneminder version 1.30

Cannot add or edit zones. Instead blank page shown even when enabling "Save JPEGs" option in camera settings.

http://puu.sh/rgk8S/a6bbba4506.png

**Comment by connortechnology** [comment]
I just updated the feature-h264-videostorage branch with some fixes from master.

Zone editing works for me.  Can you update and let us know if it is fixed?

**Comment by SteveGilvarry** [comment]
Closing as no feedback
