### ISSUE TITLE
Camera Foscam FI9821 V2

### ISSUE THREAD

**Issue by yvin** [ZoneMinder/ZoneMinder#1631]
Hi,
I have 2 cameras Foscam FI9821 V2
I have no problem to configure one camera but it's impossible to configure the second one.
I have no picture for the second one.
I have tested a lot of things, I have put the configuration of the first camera to the second one.
But I still have no picture do you have an idea to solve this problem
BR

**Comment by SteveGilvarry** [comment]
Please review posting guidelines we do not accept usage issues in GitHub issues. Instead please post to forums.zoneminder.com. Include details of both cameras, distro, ram and disk usage.
