### ISSUE TITLE
PATH_ZMS wrong in PPA

### ISSUE THREAD

**Issue by sagitt** [ZoneMinder/ZoneMinder#1636]
PATH_ZMS is wrong after installation:

/cgi-bin/nph-zms - won't work
/zm/cgi-bin/nph-zms - works

without this i can't see streaming images of cameras

i'm using this ppa: add-apt-repository ppa:iconnor/zoneminder 
on ubuntu server 14.04.5 LTS

**Comment by knnniggett** [comment]
You ran into this issue because you did not follow the installation documentation, which tells you what PATH_ZMS should be set to for your distro.
