### ISSUE TITLE
Log Web UI needs date/time filters

### ISSUE THREAD

**Issue by connortechnology** [ZoneMinder/zoneminder#1647]

**Comment by vajonam** [comment]
what were you thinking for this? i.e like last hour? last 6 hours? or a to-from range? to-from is bit cumbersome, but more powerful for large scale deployments.

**Comment by connortechnology** [comment]
to from.  In most of the cases where I've wanted to look at the logs, it has been... what happened between 3 and 4 last night?  Or last week...
