### ISSUE TITLE
Failed login needs more text/explanation of what happened instead of just staying on the login screen

### ISSUE THREAD

**Issue by connortechnology** [ZoneMinder/ZoneMinder#1648]

**Comment by kylejohnson** [comment]
Not sure what you were thinking, but the most the login screen should say is 'invalid username or password', or something along those lines.  Saying which one is incorrect gives away information which would help in a brute force login attempt.

**Comment by connortechnology** [comment]
Yeah... right now it says nothing.  If you aren't watching you might not even notice the page refresh.

**Comment by kylejohnson** [comment]
I was looking for some low hanging fruit and threw together a fix for this in #1680
