### ISSUE TITLE
Ubuntu 16.04: systemctl stop zoneminder takes too long to kill all the processes

### ISSUE THREAD

**Issue by ghulands** [ZoneMinder/ZoneMinder#1662]
When stopping or reloading zoneminder with just one camera in the system is causing systemd's stopping process to timeout.

Oct 26 20:24:32 zm systemd[1]: Stopping ZoneMinder CCTV recording and surveillance system...
Oct 26 20:24:32 zm zmpkg[7921]: INF [Sanity checking States table...]
Oct 26 20:24:32 zm zmpkg[7921]: INF [Command: stop]
Oct 26 20:24:53 zm zmc_m2[7287]: INF [Monitor-2: 69000 - Capturing at 25.00 fps]
Oct 26 20:25:35 zm zmc_m2[7287]: INF [Monitor-2: 70000 - Capturing at 25.00 fps]
Oct 26 20:26:02 zm systemd[1]: zoneminder.service: Stopping timed out. Terminating.

**Comment by knnniggett** [comment]
This is not a bug in the zoneminder source code and should be taken to the user forum.
