### ISSUE TITLE
ZM1.3 Onvif Detection of Doorbird Intercom

### ISSUE THREAD

**Issue by Transalpler** [ZoneMinder/ZoneMinder#1664]
When trying to connect the Intecom to Zm via Onvif detection the Camera will be detected as "IntercomDoorBirdOne@192.168.27.80" - after hitting "next" I get: "Unable to probe network cameras, status is '255'"

This is what I get when Probing via Command Line:

`wolfgang@Zoneminder:~$ sudo zmonvif-probe.pl probe
[sudo] Passwort für wolfgang:
http://192.168.27.80/onvif/device_service, 1.1, (Profile='Streaming', hardware='IntercomDoorBirdOne', name='DoorBird', location/country='Germany', location/city='Berlin', location/building='Joachimsthaler_Str_12')
`

`wolfgang@Zoneminder:~$ sudo zmonvif-probe.pl -v probe
Probing for SOAP 1.1
Received message:
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:dn="http://www.onvif.org/ver10/network/wsdl"><SOAP-ENV:Header><wsa:MessageID>uuid:ee66ecc4-00f2-49cf-babd-1ccae377e2c3</wsa:MessageID><wsa:RelatesTo>uuid:</wsa:RelatesTo><wsa:To SOAP-ENV:mustUnderstand="true">http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</wsa:To><wsa:Action SOAP-ENV:mustUnderstand="true">http://schemas.xmlsoap.org/ws/2005/04/discovery/ProbeMatches</wsa:Action><d:AppSequence SOAP-ENV:mustUnderstand="true" MessageNumber="16" InstanceId="100157161"></d:AppSequence></SOAP-ENV:Header><SOAP-ENV:Body><d:ProbeMatches><d:ProbeMatch><wsa:EndpointReference><wsa:Address>urn:uuid:cfab3893-688f-4a60-961c-ed8a6324b4ac</wsa:Address></wsa:EndpointReference><d:Types>dn:NetworkVideoTransmitter</d:Types><d:Scopes>onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/hardware/IntercomDoorBirdOne onvif://www.onvif.org/name/DoorBird D101 onvif://www.onvif.org/location/country/Germany onvif://www.onvif.org/location/city/Berlin onvif://www.onvif.org/location/building/Joachimsthaler_Str_12 </d:Scopes><d:XAddrs>http://192.168.27.80/onvif/device_service</d:XAddrs><d:MetadataVersion>1</d:MetadataVersion></d:ProbeMatch></d:ProbeMatches></SOAP-ENV:Body></SOAP-ENV:Envelope>
l_xaddr = http://192.168.27.80/onvif/device_service
http://192.168.27.80/onvif/device_service, 1.1, (Profile='Streaming', hardware='IntercomDoorBirdOne', name='DoorBird', location/country='Germany', location/city='Berlin', location/building='Joachimsthaler_Str_12')
Probing for SOAP 1.2
Received message:
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:dn="http://www.onvif.org/ver10/network/wsdl"><SOAP-ENV:Header><wsa:MessageID>uuid:ee66ecc4-00f2-49cf-babd-1ccae377e2c3</wsa:MessageID><wsa:RelatesTo>uuid:</wsa:RelatesTo><wsa:To SOAP-ENV:mustUnderstand="true">http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</wsa:To><wsa:Action SOAP-ENV:mustUnderstand="true">http://schemas.xmlsoap.org/ws/2005/04/discovery/ProbeMatches</wsa:Action><d:AppSequence SOAP-ENV:mustUnderstand="true" MessageNumber="17" InstanceId="100157161"></d:AppSequence></SOAP-ENV:Header><SOAP-ENV:Body><d:ProbeMatches><d:ProbeMatch><wsa:EndpointReference><wsa:Address>urn:uuid:cfab3893-688f-4a60-961c-ed8a6324b4ac</wsa:Address></wsa:EndpointReference><d:Types>dn:NetworkVideoTransmitter</d:Types><d:Scopes>onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/hardware/IntercomDoorBirdOne onvif://www.onvif.org/name/DoorBird D101 onvif://www.onvif.org/location/country/Germany onvif://www.onvif.org/location/city/Berlin onvif://www.onvif.org/location/building/Joachimsthaler_Str_12 </d:Scopes><d:XAddrs>http://192.168.27.80/onvif/device_service</d:XAddrs><d:MetadataVersion>1</d:MetadataVersion></d:ProbeMatch></d:ProbeMatches></SOAP-ENV:Body></SOAP-ENV:Envelope>
l_xaddr = http://192.168.27.80/onvif/device_service
`

`wolfgang@Zoneminder:~$ sudo zmonvif-probe.pl -v profiles "http://192.168.27.80/onvif/device_services" 1.2 myuser mypassword

<Fault xmlns="http://schemas.xmlsoap.org/soap/envelope/"><faultcode>SOAP-ENV:Server</faultcode><faultstring>Error deserializing message: Bad top node html at /usr/share/perl5/ONVIF/Deserializer/MessageParser.pm line 89.
 at line 4 at /usr/share/perl5/SOAP/WSDL/Expat/Base.pm line 82.
.
Message was:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot;
         &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;en&quot; lang=&quot;en&quot;&gt;
 &lt;head&gt;
  &lt;title&gt;404 - Not Found&lt;/title&gt;
 &lt;/head&gt;
 &lt;body&gt;
  &lt;h1&gt;404 - Not Found&lt;/h1&gt;
 &lt;/body&gt;
&lt;/html&gt;
</faultstring><faultactor>urn:localhost</faultactor></Fault>`

**Comment by tony5** [comment]
you have the URL wrong it is sudo zmonvif-probe.pl -v profiles "http://192.168.27.80/onvif/device_service" 1.2 myuser mypassword

but then I get the error Can't call method "GetProfiles" on an undefined value at /usr/bin/zmonvif-probe.pl line 238.

**Comment by knnniggett** [comment]
We have since made improvements to the zoneminder onvif probe, if you still have an issue after you try again w/o the trailing "s" as @tony5 indicated, then please try again after rebuilding zoneminder from the master the branch. Otherwise, just wait until the next release.

**Comment by Transalpler** [comment]
wolfgang@Zoneminder:~$  sudo zmonvif-probe.pl -v profiles "http://192.168.27.80/onvif/device_service" 1.2 myuser mypassword
[sudo] Passwort für wolfgang:
<Fault xmlns="http://schemas.xmlsoap.org/soap/envelope/"><faultcode>SOAP-ENV:Server</faultcode><faultstring>Error deserializing message: Bad top node html at /usr/share/perl5/ONVIF/Deserializer/MessageParser.pm line 89.
 at line 4 at /usr/share/perl5/SOAP/WSDL/Expat/Base.pm line 82.
.
Message was:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot;
         &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;en&quot; lang=&quot;en&quot;&gt;
 &lt;head&gt;
  &lt;title&gt;404 - Not Found&lt;/title&gt;
 &lt;/head&gt;
 &lt;body&gt;
  &lt;h1&gt;404 - Not Found&lt;/h1&gt;
 &lt;/body&gt;
&lt;/html&gt;
</faultstring><faultactor>urn:localhost</faultactor></Fault>wolfgang@Zoneminder:~$

**Comment by knnniggett** [comment]
Closing all the Onvif issues out since the latest release contains improvements to the Onvif probe. Please create a new issue if problems persist.
