### ISSUE TITLE
Deleting event from watch view doesn't work

### ISSUE THREAD

**Issue by kylejohnson** [ZoneMinder/ZoneMinder#1671]
If you click on one of the `X` buttons in the `eventList` of the `watch` view, the request that is sent to the server has the `id` set to `undefined` and as such doesn't actually do anything.  Submitting a PR for this.

**Comment by connortechnology** [comment]
I don't see how this code could work. event is defined at the time we are generating the button using the dom, but will not be defined when the button is clicked.  This works for the other buttons because it is passing the current value of event.Id, not the event object.  delete event needs to be changed to not take event as a parameter.

**Comment by connortechnology** [comment]
yeah we should be passing e instead of event.

**Comment by kylejohnson** [comment]
Passing `e` instead of `event` isn't the issue, though it is causing the `event.stop` error.

The issue is that for this button, the var `event` was being overwritten within `function( event )` and as such when we passed `event.Id` to `deleteEvent`, `event.Id` was not defined.  You can see that the other buttons don't have a `function( event )`.

> yeah we should be passing e instead of event.

My PR does fix the immediate issue, but then causes the `event.stop` error.  SO we should probably pass `e` as the first argument.

**Comment by connortechnology** [comment]
yeah that's what I'm saying.  This shouldn't have been merged because it was just incomplete.   passing e will complete the fix.

**Comment by kylejohnson** [comment]
Ah, fair enough.
BTW, originally I couldn't find where `event.stop` was defined.  Looks like it comes right from mootools: http://mootools.net/core/docs/1.6.0/Types/DOMEvent#DOMEvent:stop

**Comment by knnniggett** [comment]
My bad. I thought I understood what was happening here and merged it. Clearly, I should have tested this before merging.
