### ISSUE TITLE
zoneminder v1.25 make error.

### ISSUE THREAD

**Issue by danguantianxia** [ZoneMinder/ZoneMinder#1679]
when i use 'make' command in zoneminder (v1.25),there will be following errors:

[root@switch ZoneMinder-1.25]# make
make  all-recursive
make[1]: Entering directory `/src/new/zone1.25/ZoneMinder-1.25'
Making all in src
make[2]: Entering directory `/src/new/zone1.25/ZoneMinder-1.25/src'
g++ -DHAVE_CONFIG_H -I. -I..  -I/usr/include -I/usr/include/ffmpeg//include -Walzmc.Tpo -c -o zmc.o zmc.cpp
In file included from zm_stream.h:27,
                       from zm_event.h:39,
                       from zm_zone.h:27,
                       from zm_monitor.h:26,
                       from zmc.cpp:28:
zm_mpeg.h:44: 错误：使用枚举‘PixelFormat’前没有给出声明
zm_mpeg.h:46: 错误：ISO C++ 不允许声明无类型的‘AVOutputFormat’
zm_mpeg.h:46: 错误：expected ‘;’ before ‘*’ token
zm_mpeg.h:47: 错误：ISO C++ 不允许声明无类型的‘AVFormatContext’
zm_mpeg.h:47: 错误：expected ‘;’ before ‘*’ token
zm_mpeg.h:48: 错误：ISO C++ 不允许声明无类型的‘AVStream’
zm_mpeg.h:48: 错误：expected ‘;’ before ‘*’ token
zm_mpeg.h:49: 错误：ISO C++ 不允许声明无类型的‘AVFrame’
zm_mpeg.h:49: 错误：expected ‘;’ before ‘*’ token
zm_mpeg.h:50: 错误：ISO C++ 不允许声明无类型的‘AVFrame’
zm_mpeg.h:50: 错误：expected ‘;’ before ‘*’ token
make[2]: *** [zmc.o] 错误 1
make[2]: Leaving directory `/src/new/zone1.25/ZoneMinder-1.25/src'
make[1]: *** [all-recursive] 错误 1
make[1]: Leaving directory `/src/new/zone1.25/ZoneMinder-1.25'
make: *** [all] 错误 2
[root@switch ZoneMinder-1.25]#

please help me ,thank you very much...Forgive my poor english.

**Comment by knnniggett** [comment]
Hi @danguantianxia 
You are attempting to use a very old version of ZoneMinder which has reached end of life. The latest version is 1.30.0, and the best way to install it is by package. There are too many pitpalls when attempting to build from-source.

In any case, our user forum is the place to ask this question: https://forums.zoneminder.com/
Installation instructions for the most popular distros can be found in the wiki: https://wiki.zoneminder.com/Supported_distributions

Our github forum is reserved strictly for bug reporting.
