### ISSUE TITLE
H.264 branch - mp4 video length does not match event length 

### ISSUE THREAD

**Issue by pliablepixels** [ZoneMinder/zoneminder#1695]
the length of the event (as stored in the DB) does not match the actual mp4 video length. This creates issues when trying to insert cue points in the video player for where alarmed frames are.

@connortechnology is aware of this issue but the cause of the problem is yet unknown. I'm putting this up here so I can refer to it from zmNinja as a dependent issue.

**Comment by liucougar** [comment]
i think at least one of the problems is caused by keyframes: missing keyframe at the beginning/end could cause the video to be off by several seconds (depends on the key frame settings)

**Comment by SteveGilvarry** [comment]
Not an unknown issue zm begins events at arbitrary points in decoded
stream, videostream has to on keyframes. Needs to be coded to get the key
frame before events start, and offset the event to match the video.

**Comment by pliablepixels** [comment]
I don't believe it is. I'm using video storage for a while now, and in general, the cue points seem to align.

**Comment by connortechnology** [comment]
I think we can close.
