### ISSUE TITLE
Onvif motion detection

### ISSUE THREAD

**Issue by mutley** [ZoneMinder/ZoneMinder#1699]
I am very interested in off loading motion detection to the cameras to free up my cpu. Is this possible?

**Comment by mutley** [comment]
I would also be able to put a bounty on this if there is a developer willing to tackle it.

**Comment by knnniggett** [comment]
When you created this issue, you were asked to review our guidelines for contributing, which pointed to our github posting rules. 

Please read them: 
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules
