### ISSUE TITLE
zmaudit.pl can not remove files with spaces

### ISSUE THREAD

**Issue by onlyjob** [ZoneMinder/ZoneMinder#1703]
As reported in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=837527
`zmaudit.pl` seems to be unable to remove files with spaces:

> Create a camera with a name containing a space, and, get this at cleaning time:
/usr/bin/zmaudit.pl

~~~~
Filesystem monitor link 'NVT cam-01-mycam' does not point to valid monitor directory, deleting
rm: cannot remove 'NVT': No such file or directory
rm: cannot remove 'cam-01-mycam': No such file or directory
~~~~

**Comment by knnniggett** [comment]
fixed by 8009bce3d92c757bc65a9994ff4060b5b6ff35d0
