### ISSUE TITLE
Text mistake documentation screenshot

### ISSUE THREAD

**Issue by mealstrom** [ZoneMinder/ZoneMinder#1716]
http://zoneminder.readthedocs.io/en/latest/userguide/components.html#system-overview
Screenshot text mistake: "Cature Video" --> Should be "Capture video, convert to frames"
![ed-zm-system-overview](https://cloud.githubusercontent.com/assets/761686/21451846/115e6226-c90b-11e6-9700-dacc0875d22c.jpg)

**Comment by knnniggett** [comment]
@pliablepixels I forget how to edit these files. Would you mind fixing this small spelling error?

**Comment by pliablepixels** [comment]
done
