### ISSUE TITLE
rpi camera as ffmpeg rtsp stream

### ISSUE THREAD

**Issue by thorus90** [ZoneMinder/ZoneMinder#1722]
Hi,

I want to configure a monitor which gets its content from an ffmpeg rtsp stream.

I have an raspberry pi with an Noir V2.1 attached to it. I already tried to use solutions like mjpeg streamer or motion, but these only make pictures no videos (best I got so far was 9 fps). So this seams like not the best solution as the camera is able to achieve up to 40fps (honestly 24fps is enough for me, but with 9 fps it just looks horrible).

So I tried to make an rtsp stream, the best solution I found so far is with ffmpeg:

`raspivid -w 1640 -h 922 -fps 30 -t 0 -b 1024000 -o - | ffmpeg -re -f h264 -r 30 -i - -threads 1 -c:v copy -loglevel info -f rtsp -rtsp_transport tcp -stimeout 10000000 rtsp://zoneminder.intranet.jr0.de:8888/video.h264`

This sends an rtsp stream to an server listening on port 8888 @ zoneminder.intranet.jr0.de. I can receive this stream on zoneminder via:

`ffmpeg -f rtsp -rtsp_flags listen -rtsp_transport tcp -i rtsp://zoneminder.intranet.jr0.de:8888/video.h264 video.h264`

This creates an file video.h264 with the content of the stream, which is pretty good video file. So far timestamp is missing for seeking, and the delay is still about 5 secs, but the best I got so far.

Now I don't understand how to get this ffmpeg stream into zm. I tried to configure the monitor with:

Server: None
Source Type: Ffmpeg
Function: Monitor
Enabled: yes
Maximum FPS:

Source Path: rtsp://zoneminder.intranet.jr0.de:8888/video.h264
Remote Method: RTP/RTSP
Options: -f rtsp,-rtsp_flags listen,-rtsp_transport tcp
Target colorspace: 32 bit color
Capture Width: 1640
Capture Height: 922

In the logs I only get:

`Dec 29 12:19:44 zoneminder zmc[16507]: ERR [Unable to open input rtsp://192.168.100.244:8888/video.h264 due to: Operation now in progress]
Dec 29 12:19:45 zoneminder zmc[16507]: INF [pi-huehner: 928000 - Capturing at 1000.00 fps]`

So I get it tries to connect to 192.168.100.244:8888 (which is the zoneminder server), but it should listen there instead of trying to connect there (specified by -rtsp_flags listen). Is Zoneminder capable of listening on a port to receive a rtsp stream with that?

Is there a way to see what ffmpeg it build together? Or is my approach wrong? (As clearifaction, motion and mjpeg_stream did not look well because of not delievering a real video stream, just putting as many jpeg after another as possible, resulting in max 9fps)

Thanks for help!

**Comment by knnniggett** [comment]
Hi @thorus90 
Please refer to our github posting rules: 
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules

Our github forum is reserved for bug reports only. Please use our user forum for support requests. 

See this thread thread here to see how I stream from a rasppi to zoneminder: https://forums.zoneminder.com/viewtopic.php?f=9&t=25392

Others have used motioneyeos. Please create a thread in the user forum for further quetions.
