### ISSUE TITLE
Adding SCC/HK P2P_IPC Camera Protocol Support

### ISSUE THREAD

**Issue by jameshilliard** [ZoneMinder/ZoneMinder#1723]
We picked up a bunch of cheap and small WiFi security cameras from china that just have "Plug2Cam" on the label. They appear to implement a customized control protocol that is common to a lot of cheap Chinese network security cameras. This protocol appears to be used by a large number of different camera brands that manufacture in china.

There are clients available for most platforms [here](http://www.scc21.com/) however they all use a library that implements the custom UDP based control and transmission protocol that is not supported by ZoneMinder yet. The [protocol](http://www.uipcam.hk/ShowProducts/?21-1.html) has a NAT bypass capability or can just use the LAN. I've tracked down quite a few SDK's from Chinese websites and Github which should have enough information to implement minimal control protocol and capture capability. I also found that someone [implemented](http://jheyman.github.io/blog/pages/VideoSurveillance/) what appears to be a [python client](https://github.com/jheyman/videosurveillance/blob/master/surveillance.py) that can pull captures from the cameras.

When the device connects to a network it broadcasts UDP packets(authentication data removed) on port 5000 with these contents.

```
MainCmd=LocalData;bootproto=static;dns0=192.168.1.1;dns1=;netmask=255.255.255.0;netwet=192.168.1.1;userType=312;status=2;ver=833;index=0;lanport=0;wannetable=0;errorcod=200;EnableSD=0;MoveRec=0;OutMoveRec=0;AutoRec=0;LoopWrite=0;Splite=0;AllSize=0;HaveUse=0;LeftSize=0;sdAudioMux=0;SDRecQC=0;devid=;Psw=;DEVNAME=smart;allAttribute=d6:isopen1:19:bootproto6:static10:wifistatus1:12:Ip12:10.29.32.2317:netmask13:255.255.255.06:netwet11:192.168.1.14:dns011:192.168.1.14:dns10:7:wifisid7:12:wifipassword14:
```

These values correspond to those in [this header](https://github.com/jameshilliard/pcSCCSDK140920/blob/5d5372ca210303dd929277b1c27e7ddd56dbac63/pc_SDK/include/utils/HKCmdDefine.h)/[this header](https://github.com/jameshilliard/pcSCCSDK140920/blob/5d5372ca210303dd929277b1c27e7ddd56dbac63/pc_SDK/include/utils/HKMonCmdDefine.h) and are normally configured using the phone app or computer app.

I haven't been able to find full source code to the client networking libraries which are usually called libcaptetown1, libchinalink, libSCCodec and/or libsystem in the SDK's(although there is a lot of information in header/other files). However I did find what appears to be the multiple variants of complete [source code](https://github.com/ivysboy/wuyuanswork/tree/6c7bc2d77c9e8887a2ea12c15912438c50f1fe88/sample/hkipc_3518E-zqj) for [different](https://github.com/Qgeorge/Hisi3518/tree/Hisi3518) cameras. I've uploaded all the SDK's and software I could find so far related to these cameras [here](https://mega.nz/#F!DZdxSBpD!V3FycpkZPr976K4I82EInQ).

**Comment by knnniggett** [comment]
Hi @jameshilliard 
Please check our posting rules:
https://github.com/ZoneMinder/ZoneMinder/wiki/Github-Posting-Rules

This is not the place to have this discussion. Feel free to discuss your ideas in the user forum or our irc channel.
