### ISSUE TITLE
Add monitor preset for Qihan cameras

### ISSUE THREAD

**Issue by StefanLindblom** [ZoneMinder/ZoneMinder#1726]
Hi!
Creating this issue to track my upcoming pull request for supporting Qihan IP cameras.
For example, the model QH-NV470SO-P via RTSP.
Slightly related to #17

**Comment by StefanLindblom** [comment]
PR done:
https://github.com/ZoneMinder/ZoneMinder/pull/1727

**Comment by knnniggett** [comment]
pr has been merged. closing.
