### ISSUE TITLE
comparison between pointer and zero

### ISSUE THREAD

**Issue by abishai** [ZoneMinder/zoneminder#1760]
ZoneMinder can't be compiled with CLANG 4.0 It bumped severity of such comparison to error. 
src/zm_monitor.cpp contains comparison between (unsigned char*) mem_ptr and 0 in several places.
```
src/zm_monitor.cpp:197:18: error: ordered comparison between pointer and zero
('unsigned char *' and 'int')
    if ( mem_ptr > 0 )
	 ~~~~~~~ ^ ~
```

**Comment by connortechnology** [comment]
The line should probably like this:
if ( mem_ptr > (void *)0 ) {

**Comment by abishai** [comment]
Maybe, !=0 is OK too.

**Comment by connortechnology** [comment]
No because failure to mmap results in -1.

**Comment by abishai** [comment]
I added fix to my FreeBSD PR. Compiles on my test system with your fix.

**Comment by mastertheknife** [comment]
What about comparing it to NULL?
NULL is typically defined as (void*)0, so mem_ptr > NULL should work.

**Comment by arvidn** [comment]
for the record, ``mmap()`` returns ``MAP_FAILED`` on error (which may or may not be the same value as ``(void*)-1``). [posix spec.](http://pubs.opengroup.org/onlinepubs/009695399/functions/mmap.html#tag_03_379_04)

**Comment by connortechnology** [comment]
It seems like we should follow posix.. defined constants are both readable... and defined.. hence... good.. Mmkay?

**Comment by ali-babaei** [comment]
> The line should probably like this:
> if ( mem_ptr > (void *)0 ) {

on:
Telegram Android Client

I had following error:

jni/./gifvideo.cpp:151:28: error: ordered comparison between pointer and zero ('AVStream *' and 'int')
    if (info->video_stream <= 0) {
        ~~~~~~~~~~~~~~~~~~ ^  ~

Thanks @connortechnology, your solution worked for me too.

Just commented here for everybody facing this issue later!
