### ISSUE TITLE
show USE_DEEP_STORAGE in zm 1.30

### ISSUE THREAD

**Issue by fpultera** [ZoneMinder/ZoneMinder#1766]
Good morning dear

Currently in production I have a server with zoneminder version 1.28. (Centos 6.8 )
To update, install on another server the version of zoneminder 1.30. (Centos 6.8 )

Reading the zoneminder github link: https://github.com/ZoneMinder/ZoneMinder/releases

In one section it says the following:

"The option USE_DEEP_STORAGE has been hidden." This option has been enabled for many years, and this option was turned off in the near immediate deletion of events from the disk. No longer be modified from Options.In the unlikely event that you have a working system not already using deep storage, please contact us so we can get that enabled without your data.

Is there any possibility of disabling the USE_DEEP_STORAGE option?

Greetings and thank you very much.

**Comment by knnniggett** [comment]
Hi @fpultera 
I'm not sure why you thought it was necessary to double post. Please don't do that.
Please keep this conversation in the user forum.

https://forums.zoneminder.com/viewtopic.php?f=36&p=98818&sid=e7cf65c32d42240175e306893a1d6c99#p98818
