### ISSUE TITLE
Dockerfile Ubuntu 16.04 Xenial support

### ISSUE THREAD

**Issue by MarkosVakondios** [ZoneMinder/zoneminder#1786]
As requested by SteveGilvarry in #1774

**Comment by mharrend** [comment]
Hi, I have a Zoneminder Docker setup using Xenial which can be found here:
https://github.com/mharrend/docker-zoneminder

Maybe you can check it out.

**Comment by knnniggett** [comment]
We've moved our dockerfiles here:
https://github.com/ZoneMinder/zmdockerfiles

We will continue to troubleshoot docker related issue there.

@MarkosVakondios We would be willing to give you direct commit access to the new zmdockerfiles repo if you are interested in maintaining it. Let me know.

**Comment by MarkosVakondios** [comment]
@knnniggett: Sure, I will be glad to. Please be aware that it's the first time I will be maintaining a github repo. Any pointers apart from general Googling would be appreciated to avoid elementary mistakes.

**Comment by viktorsmari** [comment]
Why don't we have a single Dockerfile and a `docker-compose.yml` in the main repo, like most open source projects do?
Even though it is flaky or a bit broken, we can note in the readme that things are 'experimental'.
