### ISSUE TITLE
Logging should be scrubbed of passwords

### ISSUE THREAD

**Issue by ghulands** [ZoneMinder/ZoneMinder#1799]
When zoneminder has an issue opening the stream, it logs something like this

Feb 28 15:24:34 zoneminder zmc_m2[1401]: ERR [Unable to open input rtsp://user:secret@cam01/cam/realmonitor?channel=1&subtype=0 due to: Operation now in pro

It would be good if you scrub the logs of usernames and passwords

**Comment by knnniggett** [comment]
duplicate of #767
