### ISSUE TITLE
Main page event counter mistakes

### ISSUE THREAD

**Issue by flexiti** [ZoneMinder/zoneminder#1802]
Event counters live their own lives.
Should something reset?

![counter](https://cloud.githubusercontent.com/assets/11538048/23704320/9030b5fc-0404-11e7-84b2-9540934b0232.JPG)

**Comment by connortechnology** [comment]
I'm not sure what you are trying to show us.  You are pointing out an event that happened at 10:29am ... and the current time is 1:31pm.

So?

**Comment by flexiti** [comment]
if the last 24 hours is ok, this explains 11 events , thanks  
btw. which in this case means month and how much is it?  30 days? 31 days? :)

however,   

I think (my opinion) **day** is more associated with the current day than the last 24 hours.
I'm thinking that it would be more convenient: 
- just how much of this hour 
- how much on this day, 
- how much this month etc.
