### ISSUE TITLE
Bootstrap tooltip and jQueryUI tooltip collision error

### ISSUE THREAD

**Issue by WDKevin** [ZoneMinder/zoneminder#181]
The following error is on every page in the console:

Uncaught TypeError: Cannot call method 'createDocumentFragment' of null 

This is caused by Bootstrap's tooltip and jQueryUI's tooltip colliding. The tooltip functionality needs to be removed from one or the other and the error will go away. I was going to do this myself, but I'm not sure how either package was built.

StackOverflow thread for reference: http://stackoverflow.com/questions/15790568/jquery-1-9-1-unable-to-get-property-createdocumentfragment-of-undefined-or-nul
##

**Comment by knnniggett** [comment]
Is this issue still relevant?

**Comment by nop1984** [comment]
same problem
