### ISSUE TITLE
Add config option for date/time format [$5]

### ISSUE THREAD

**Issue by WDKevin** [ZoneMinder/zoneminder#183]
We should add a config option to allow users to set a date and time format to be displayed throughout the system.

Additionally, we may want to consider storing these values as UNIX time stamps in the database rather than strings. I'm currently just fetching them with the MySQL UNIX_TIMESTAMP, but storing them that way in the first place would be more efficient.
##

**Comment by SteveGilvarry** [comment]
Convert to UTC and have user and monitor timezones

**Comment by connortechnology** [comment]
Bountysource is going to take the money in this bounty on July 1st unless the funds are redirected. Alternatively I can close this out, collect the bounty and ZoneMinder will hold the funds until it is properly closed.

**Comment by connortechnology** [comment]
Fixed with the release of 1.36.20.
