### ISSUE TITLE
Timestamp Label Format (%N, %f, %Q) / behaviour of strftime() on FreeBSD

### ISSUE THREAD

**Issue by schrorg** [ZoneMinder/ZoneMinder#1865]
When using ZoneMinder on FreeBSD (at least on FreeBSD 11.0), all my cameras are named "N" in the image timestamps. This is because strftime() on FreeBSD removes the `%` sign of unknown conversion specifications instead of not touching it.
On Linux, where strftime() does not touch the unknown `%N`, `%f`, and `%Q` in the LabelFormat string, camera names are printed correctly into the images.
As a workaround, putting `%%N` in the LabelFormat string of a camera makes the substitiutions work on both Linux and FreeBSD for my cameras, because strftime() than simply substitutes `%%` with `%` and so leaves `%N` in the string.

I would like to fix this but are not sure what solution is the "best". There are several possible solutions:

- add a second `%` sign to the default LabelFormat string for the camera name (make it `%%N - %d/%m/%y %H:%M:%S`) or
- use a different character for substitutions that are manually done after strftime() (i.e. `!N - %d/%m/%y %H:%M:%S`) or
- change the logic in `src/zm_monitor.cpp` to first replace ZoneMinder substitutions and than use strftime() on the LabelFormat string (this would be in `Monitor::TimestampImage()` beginning around line 3151 and could be dangerous because of user input).

Unfortunately the behaviour of strftime() in situations where it finds unknown conversion specifications is undefined, so I would prefer to change the default LabelFormat string to double the `%`. So every existing installation would work as before and new cameras on updated or new installations would have the new default LabelFormat string. Also, the documentation should be updated then.

What do you think?

Thanks for reading this longish text...
Robin

**Comment by knnniggett** [comment]
My brain is telling me this was discovered, and possibly addressed previously, but right now I'm only at 1/2 out of 2 cups of coffee so that's all I got right now.

@abishai Did you recall running into this? Is this one in the list the FreeBSD patches you plan to give us?

**Comment by abishai** [comment]
@knnniggett  Yes, actually I opened an issue here, however I can't find it now. I found the same as @schrorg, it was rather confusing. %%N is not the perfect solution as extra % comes to API/zmNinja for monitor name.

**Comment by knnniggett** [comment]
Doesn't solve the problem, but provides some background:
https://bugs.python.org/issue9811

I keep thinking about this from time to time, trying to imagine what the best solution should be moving forward.  At the moment I'm inclined to make the substitution character configurable under Options. The default should remain "%" since that works for the majority, but we could easily tie this into cmake, so that one could change this at build time.
