### ISSUE TITLE
ZM_AUTH_HASH_SECRET needs mysql escaping

### ISSUE THREAD

**Issue by ryannathans** [ZoneMinder/ZoneMinder#187]
When configuring "AUTH_HASH_SECRET" using some symbols the server spits an error that suggests there's no escaping taking place
```
 "SQL-ERR 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?123./.3#?!#2/3.13$'124''4145;51' where Name = 'ZM_AUTH_HASH_SECRET'' at line 1', statement was 'update Config set Value = 'R1'?123./.3#?!#2/3.13$'124''4145;51' where Name = 'ZM_AUTH_HASH_SECRET''" 
```

**Comment by knnniggett** [comment]
I am able to successfully define an AUTH_HASH_SECRET using characters that typically must be escaped so I am going assume this is fixed.

If the issue still persists for the OP, then feel free to reopen this issue and provide sample symbols you are using so we can attempt to reproduce the problem.
