### ISSUE TITLE
I want a test monitor added to ZM during every build to test that daemons do not crash

### ISSUE THREAD

**Issue by kylejohnson** [ZoneMinder/ZoneMinder#189]
This can be accomplished in Travis.  See the db/test.monitor.sql file, which is the current hang up.

Once the file is inserted and the daemons started (zmpkg.pl), we can check log files or the process table for the zm\* daemon status.
##

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
