### ISSUE TITLE
[mysql] Base table or view not found: zm.Storage

### ISSUE THREAD

**Issue by dylon** [ZoneMinder/ZoneMinder#1892]
I've recently install ZoneMinder 1.30.4 on Arch Linux (AUR package zoneminder-git), and am getting many of the following error in journalctl:

May 23 10:34:47 arch-workstation web_php[37476]: FAT [SQL-ERR 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'zm.Storage' doesn't exist', statement was 'SELECT * FROM           Storage ORDER BY Name']

There are references to the Storage table in the PHP sources of the application, but not in the db schemata.  I'm not sure what the schema of the table should be, otherwise I'd create it manually.  Please update the db scripts to create/update the Storage table.

**Comment by SteveGilvarry** [comment]
I think that package is building master, (which will show as 1.30.4 until next release, but will have more commits in git describe --long) not 1.30.4, it points to git but never specifies a branch or tag. And master is likely to have breaking changes at the moment.
 
Probably needs something like below to be a release package, but I believe by it's name zoneminder-git this is supposed to be bleeding edge package.

https://julienrenaux.fr/2013/10/04/how-to-automatically-checkout-the-latest-tag-of-a-git-repository/
Get new tags from the remote
$ git fetch --tags
# Get the latest tag name
$ latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
# Checkout the latest tag
$ git checkout $latestTag
