### ISSUE TITLE
How to configuration access rtsp monitor ？

### ISSUE THREAD

**Issue by silence-liu** [ZoneMinder/ZoneMinder#1907]
I want use zoneminder-1.30.4 to management some rtsp camera, but I get a error from log, please give me some suggestion to resolve this problem。 thank you!

**this is my log:**
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
06/06/17 13:56:28.386220 zmc_m2[25071].DB1-zm_logger.cpp/234 [LogOpts: level=DB1/DB1, screen=OFF, database=INF, logfile=DB1->/tmp/zm/tm/zm1.log.25071, syslog=INF]
06/06/17 13:56:28.386361 zmc_m2[25071].DB1-zm_utils.cpp/266 [Detected a x86\x86-64 processor with SSSE3]
06/06/17 13:56:28.386500 zmc_m2[25071].DB1-zm_monitor.cpp/2735 [Got 1 for v4l_captures_per_frame]
06/06/17 13:56:28.387116 zmc_m2[25071].DB1-zm_thread.cpp/241 [Creating thread]
06/06/17 13:56:28.387125 zmc_m2[25071].DB1-zm_thread.cpp/280 [Starting thread]
06/06/17 13:56:28.387166 zmc_m2[25071].DB1-zm_thread.cpp/301 [Started thread 25076]
06/06/17 13:56:28.387176 zmc_m2[25076].DB1-zm_comms.cpp/562 [connect(): Trying '10.10.10.6', family '2', proto '6']
06/06/17 13:56:28.387184 zmc_m2[25071].DB1-zm_monitor.cpp/390 [monitor purpose=1]
06/06/17 13:56:28.387187 zmc_m2[25071].DB1-zm_monitor.cpp/398 [mem.size=11521760]
06/06/17 13:56:28.387212 zmc_m2[25071].DB1-zm_monitor.cpp/543 [Unable to map file /dev/shm/zm.mmap.2 (11521760 bytes) to locked memory, trying unlocked]
06/06/17 13:56:28.387216 zmc_m2[25071].DB1-zm_monitor.cpp/546 [Mapped file /dev/shm/zm.mmap.2 (11521760 bytes) to locked memory, unlocked]
06/06/17 13:56:28.390026 zmc_m2[25071].DB1-zm_monitor.cpp/449 [Monitor TH000006 has no zones, adding one.]
06/06/17 13:56:28.390034 zmc_m2[25071].DB1-zm_zone.cpp/51 [Initialised zone 0/All - 1 - 320x240 - Rgb:0000ff, CM:3, MnAT:15, MxAT:0, MnAP:50, MxAP:75000, FB:3x3, MnFP:50, MxFP:50000, MnBS:10, MxBS:0, MnB:0, MxB:0, OF: 0, AF: 0]
06/06/17 13:56:28.390283 zmc_m2[25071].DB1-zm_monitor.cpp/459 [Monitor TH000006 has function 2]
06/06/17 13:56:28.390285 zmc_m2[25071].DB1-zm_monitor.cpp/460 [Monitor TH000006 LBF = '%N - %d/%m/%y %H:%M:%S', LBX = 0, LBY = 0, LBS = 1]
06/06/17 13:56:28.390287 zmc_m2[25071].DB1-zm_monitor.cpp/461 [Monitor TH000006 IBC = 50, WUC = 25, pEC = 25, PEC = 25, EAF = 1, FRI = 1000, RBP = 6, ARBP = 6, FM = 0]
06/06/17 13:56:28.390426 zmc_m2[25071].DB1-zm_zone.cpp/957 [Got 1 zones for monitor TH000006]
06/06/17 13:56:28.390453 zmc_m2[25071].DB1-zm_zone.cpp/51 [Initialised zone 2/All - 1 - 320x240 - Rgb:c00000ff, CM:3, MnAT:25, MxAT:0, MnAP:2304, MxAP:57600, FB:3x3, MnFP:2304, MxFP:57600, MnBS:1536, MxBS:0, MnB:1, MxB:0, OF: 0, AF: 0]
06/06/17 13:56:28.390723 zmc_m2[25071].DB1-zm_monitor.cpp/2998 [Loaded monitor 2(TH000006), 1 zones]
06/06/17 13:56:28.390727 zmc_m2[25071].INF-zmc.cpp/247 [Starting Capture version 1.30.4]
06/06/17 13:56:29.993852 zmc_m2[25076].DB1-zm_rtsp.cpp/389 [Processing DESCRIBE response header 'RTSP/1.0 200 OK
CSeq: 2
Content-Base: rtsp://10.10.10.6:554/video
Content-Length: 393
Content-Type: application/sdp']
06/06/17 13:56:29.993899 zmc_m2[25076].INF-zm_rtsp.cpp/398 [Received new Content-Base in DESCRIBE response header. Updated device Url to: 'rtsp://10.10.10.6:554/video']
06/06/17 13:56:30.027501 zmc_m2[25076].DB1-zm_rtsp.cpp/407 [Processing SDP 'v=0
o=- 1001 1 IN IP4 10.10.10.6
s=VCP IPC Realtime stream
m=video 0 RTP/AVP 108
c=IN IP4 10.10.10.6
a=control:rtsp://10.10.10.6/media/video1/video
a=rtpmap:108 H265/90000
a=fmtp:108 
a=recvonly
m=application 0 RTP/AVP 107
c=IN IP4 10.10.10.6
a=control:rtsp://10.10.10.6/media/video1/metadata
a=rtpmap:107 vnd.onvif.metadata/90000
a=fmtp:107 DecoderTag=h3c-v3 RTCP=0
a=recvonly
']
06/06/17 13:56:30.028001 zmc_m2[25076].ERR-zm_signal.cpp/50 [Got signal 6 (Aborted), crashing]
06/06/17 13:56:30.060894 zmc_m2[25076].DB1-zm_signal.cpp/61 [Signal information: number 6 code -6 errno 0 pid 25071 uid 33 status 0]
06/06/17 13:56:30.060912 zmc_m2[25076].ERR-zm_signal.cpp/81 [Signal address is 0x21000061ef, from 0x7fa59521ec37]
06/06/17 13:56:30.095315 zmc_m2[25076].ERR-zm_signal.cpp/102 [Backtrace 0: /usr/bin/zmc(_Z14zm_die_handleriP9siginfo_tPv+0x72) [0x7fa598dde662]]
06/06/17 13:56:30.127750 zmc_m2[25076].ERR-zm_signal.cpp/102 [Backtrace 1: /lib/x86_64-linux-gnu/libpthread.so.0(+0x10330) [0x7fa597c52330]]
06/06/17 13:56:30.161183 zmc_m2[25076].ERR-zm_signal.cpp/102 [Backtrace 2: /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37) [0x7fa59521ec37]]
06/06/17 13:56:30.194610 zmc_m2[25076].ERR-zm_signal.cpp/102 [Backtrace 3: /lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x7fa595222028]]
06/06/17 13:56:30.228025 zmc_m2[25076].ERR-zm_signal.cpp/102 [Backtrace 4: /usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x155) [0x7fa595b29535]]
06/06/17 13:56:30.261450 zmc_m2[25076].ERR-zm_signal.cpp/102 [Backtrace 5: /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5e6d6) [0x7fa595b276d6]]
06/06/17 13:56:30.294854 zmc_m2[25076].ERR-zm_signal.cpp/102 [Backtrace 6: /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5e703) [0x7fa595b27703]]
06/06/17 13:56:30.328249 zmc_m2[25076].ERR-zm_signal.cpp/102 [Backtrace 7: /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5e922) [0x7fa595b27922]]
06/06/17 13:56:30.361646 zmc_m2[25076].ERR-zm_signal.cpp/102 [Backtrace 8: /usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZSt20__throw_out_of_rangePKc+0x67) [0x7fa595b79447]]
06/06/17 13:56:30.395093 zmc_m2[25076].ERR-zm_signal.cpp/102 [Backtrace 9: /usr/bin/zmc(_Z5splitRKSsSsi+0x355) [0x7fa598df8aa5]]
06/06/17 13:56:30.428447 zmc_m2[25076].ERR-zm_signal.cpp/102 [Backtrace 10: /usr/bin/zmc(_ZN17SessionDescriptorC2ERKSsS1_+0x160b) [0x7fa598dda49b]]
06/06/17 13:56:30.461969 zmc_m2[25076].ERR-zm_signal.cpp/102 [Backtrace 11: /usr/bin/zmc(_ZN10RtspThread3runEv+0x17e0) [0x7fa598dc45a0]]
06/06/17 13:56:30.495341 zmc_m2[25076].ERR-zm_signal.cpp/102 [Backtrace 12: /usr/bin/zmc(_ZN6Thread11mThreadFuncEPv+0xa6) [0x7fa598de9d16]]
06/06/17 13:56:30.528755 zmc_m2[25076].ERR-zm_signal.cpp/102 [Backtrace 13: /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7fa597c4a184]]
06/06/17 13:56:30.562151 zmc_m2[25076].ERR-zm_signal.cpp/102 [Backtrace 14: /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fa5952e237d]]
06/06/17 13:56:30.595593 zmc_m2[25076].INF-zm_signal.cpp/109 [Backtrace complete, please execute the following command for more information]
06/06/17 13:56:30.629022 zmc_m2[25076].INF-zm_signal.cpp/110 [addr2line -e /usr/bin/zmc 0x7fa598dde662 0x7fa597c52330 0x7fa59521ec37 0x7fa595222028 0x7fa595b29535 0x7fa595b276d6 0x7fa595b27703 0x7fa595b27922 0x7fa595b79447 0x7fa598df8aa5 0x7fa598dda49b 0x7fa598dc45a0 0x7fa598de9d16 0x7fa597c4a184 0x7fa5952e237d]

**zm config :**
![1](https://cloud.githubusercontent.com/assets/20079928/26816408/f9b6cfa6-4ac3-11e7-9a61-8a9f5cf85d4a.jpg)
![2](https://cloud.githubusercontent.com/assets/20079928/26817185/27fdd7e8-4ac8-11e7-9203-d62d4df648e0.jpg)

the image of hidden part is username and password. The format is: username:password

**Comment by knnniggett** [comment]
Please do not double post.
The best place to get support is in the thread you created in the user forum:
https://forums.zoneminder.com/viewtopic.php?f=36&t=26227
