### ISSUE TITLE
Add support for Maginon Supra IPC cameras

### ISSUE THREAD

**Issue by MartinGoodwell** [ZoneMinder/ZoneMinder#1946]
I created a script for that cam and I'd love to contribute it.

**Comment by connortechnology** [comment]
Ok.  You can either send it to me at isaac@zoneminder.com, or fork our repo, add your script, and make a pull request....
If you aren't familiar with github development, just sending it to me might be the easiest.

**Comment by MartinGoodwell** [comment]
Awesome. Created a pull request

**Comment by connortechnology** [comment]
Welcome to ZoneMinder development!  Thanks for your contribution!

**Comment by MartinGoodwell** [comment]
Thanks a lot!
