### ISSUE TITLE
Montage review history should complain when php-gd is missing

### ISSUE THREAD

**Issue by doublehp** [ZoneMinder/ZoneMinder#1957]
https://forums.zoneminder.com/viewtopic.php?p=101599#p101599

Montage review history requires php-gd. When that part is missing, the ZM interface should produce an explicit warning about it.

Genrally speaking, the ZM interface should provide a sanity checker routine, that checks after all deps, and produce comprehensive log on screen (independent from the classic runtime log).

**Comment by knnniggett** [comment]
Good, you reported this to the Debian bug tracking system:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=870140

That's the place where this should be fixed. 

The build scripts under our distros folder (and under our control) already have this dependency. If you wanted to roll your own deb, you could, and it would not have this issue. Or you can wait to see what kind of feedback you get on the debian site. It is up to you.

In any case, the type of general checking you are referring to, is the type of thing that should go into an install wizard, which we all agree would be helpful. See #12. All it takes is for someone to volunteer their time to write one.
