### ISSUE TITLE
Replay: Gapless Events - doesn't it work

### ISSUE THREAD

**Issue by peruchi** [ZoneMinder/zoneminder#1961]
Hi,
The mode "Replay: Gapless Events" doesn't it work.

Zm: v1.31.1
Mode: Storage Video Writer
S.O: Ubuntu 16.04
PPA: ppa:iconnor/zoneminder-master

**Comment by knnniggett** [comment]
Our build system just cranked out a new set of packages with several fixes related to event viewing. Please update to 1.31.1~20170814175712-xenial or newer and let us know if the issue was resolved.

**Comment by peruchi** [comment]
Still it does not work.

**Comment by sonicspeedway** [comment]
Same problem here, same setup, also neither the next or previous buttons work in the event window, nothing happens.
Zm: v1.31.1
Storage Video Writer
Ubuntu 16.10
PPA: ppa:iconnor/zoneminder-master
