### ISSUE TITLE
API-support has broken in the current docker image

### ISSUE THREAD

**Issue by MiGoller** [ZoneMinder/zoneminder#1962]
Hi all,

looks like the API-support has broken in the current docker image. 

Starting with PHP 7.0, APCu removed the option for full backwards compatibility with APC that existed with APCu in PHP 5.5 and 5.6. We will need to add the APCu Backwards Compatiblity Module on top of apcu to make it work (https://pecl.php.net/package/apcu_bc) .

I managed to get it up and running with some modifications of the Dockefile:
```
#	Install PHP opcache und APCu support.
RUN set -x \
	&& apt-get update \
	&& apt-get install -y php7.0-opcache php-apcu 

#	Add software-properties-common to enable adding additional repositories.
RUN set -x \
	&& apt-get install -y software-properties-common

#	Must add DEBIAN repository to be able to install backward compatibility for APCu.
RUN set -x \
	&& add-apt-repository -y "deb http://ftp.de.debian.org/debian sid main" \
	&& apt-get update \
	&& apt-get install -y --allow-unauthenticated php-apcu-bc
```
Using an docker image built with those modifications now I am able to access the API at http://server/zm/api/ (http://zoneminder.readthedocs.io/en/stable/api.html) .

Regards.

**Comment by knnniggett** [comment]
fixed in commit https://github.com/ZoneMinder/zmdockerfiles/commit/9fd281f4f2f129e1f34da10290daf5b589d5f659

Will test tomorrow.

Note the dockerfile has been moved to its own repo: https://github.com/ZoneMinder/zmdockerfiles
