### ISSUE TITLE
Zoneminder & Fedora - Path ZMS

### ISSUE THREAD

**Issue by dylanduffy** [ZoneMinder/ZoneMinder#1967]
Hi,

There is some sort of issue with Zoneminder 1.30.4 and Fedora.

The ZMS/CGI locations don't seem to work no matter what you enter.

`getStreamCmdResponse stream error: Socket /var/lib/zoneminder/sock/zms-624179s.sock does not exist. This file is created by zms, and since it does not exist, either zms did not run, or zms exited early. Please check your zms logs and ensure that CGI is enabled in apache and check that the PATH_ZMS is set correctly. Make sure that ZM is actually recording. If you are trying to view a live stream and the capture process (zmc) is not running then zms will exit. Please go to http://zoneminder.readthedocs.io/en/latest/faq.html#why-can-t-i-see-streamed-images-when-i-can-see-stills-in-the-zone-window-etc for more information. - checkStreamForErrors()` 

I hope someone can try work out what is happening.

**Comment by kingofkya** [comment]
this seam like more of a forum question....

but like it says go look at your logs something is setup wrong or your cgi /apaache install has some other issue.

**Comment by dylanduffy** [comment]
Hi,

This is not an isolated issue while using Fedora, I know of a few users with the same issue on a fresh install.

**Comment by kingofkya** [comment]
Also witch fedora your running

**Comment by dylanduffy** [comment]
We are all on Fedora release 25 (Twenty Five)

**Comment by kingofkya** [comment]
I will see if i can replicate, version of package/repo its from. 

Also in the mean time if it a non production machine try  SElinux / putting it in permisive mode.

**Comment by dylanduffy** [comment]
Running default v1.30.4 FYI - I will try that and get back to you

**Comment by knnniggett** [comment]
This is not a software bug.
To get help, create a thread in the user forum stating the version of Fedora 25, where you got zoneminder from, the value of PATH_ZMS and the contents of your ZoneMinder apache config file.

As always make sure you follow the contents of the README.
