### ISSUE TITLE
zmfilter crashes in docker container after switching on sftp upload - missing sftp module in Dockerfile

### ISSUE THREAD

**Issue by britisch** [ZoneMinder/zoneminder#2004]
Dear all,

after getting zone minder running in a docker container, zmfilter continuously crashed after switching on the upload via sftp. Adding the package libnet-sftp-foreign-perl to the Dockerfile ubuntu setup solved the problem.

Solved thanks to this:
https://bugs.launchpad.net/ubuntu/+source/zoneminder/+bug/1006890

Maybe you can add to one of the next releases.

**Comment by knnniggett** [comment]
Fixed as part of the initial upload to the new home for our dockerfiles:
https://github.com/ZoneMinder/zmdockerfiles
