### ISSUE TITLE
Fail in the line 244.

### ISSUE THREAD

**Issue by juanmoura** [ZoneMinder/ZoneMinder#2008]
https://github.com/ZoneMinder/ZoneMinder/blob/ded6b1864a8abc06c400e97532c839007d23e4df/utils/do_debian_package.sh#L244

My instalation stops in the line 244, Debuild: command not found.

**Comment by connortechnology** [comment]
You need to install the devscripts package.

sudo apt-get install devscripts.

I have added a test to do_debian_package to test and report on this.
