### ISSUE TITLE
error in the installation with hard way (master)

### ISSUE THREAD

**Issue by juanmoura** [ZoneMinder/ZoneMinder#2009]
gpg: ignorade "root <root@zmteste.local>": no secret key
gpg: /tmp/debsign.YZECYPm2/zoneminder_1.31.1-artful.dsc: clearsign failed: no secret key
debsign: gpg error occurred! Aborting....
debuild: fatal error at line 1053:
running debsign failed
Error status code is: 0
Build Failed

**Comment by digital-gnome** [comment]
Make sure -t='local' is in the command line somewhere.  That's trying to sign with the release key.
