### ISSUE TITLE
ZM options save button not working in v1.31.16

### ISSUE THREAD

**Issue by silins1188** [ZoneMinder/ZoneMinder#2023]
Hello! I just upgraded from 1.30.4 to 1.31.16 with storageareas and everything completed successfully but now i cant save changes in Options->Config, System, Web & Images. 
Maybe theres is problem with save command, or some permissions?

P.S i can add users & configure storage locations

**Comment by connortechnology** [comment]
Please try the latest version, it should fix this problem.

**Comment by silins1188** [comment]
Thank you for fix! In monitors view "Back" button isn't working

**Comment by connortechnology** [comment]
@digital-gnome Back button works for me, but doesn't if I open the monitor view in a new tab.

**Comment by silins1188** [comment]
this was safari specific bug, everytjing works in chrome
