### ISSUE TITLE
Database saving frames

### ISSUE THREAD

**Issue by juanmoura** [ZoneMinder/zoneminder#2042]
I was checking that even using Storage Areas, and scoring for H264 Passthroug the system keeps event frames within the database.
Is there any way to delete these frames since I have the recordings?

I see, in the events directory are the videos only, but inside the database are the frames in the resolution that I enter in Zoneminder.

Catching on a huge database. I would like to see a way to delete and stop recording those unnecessary images on the bench.

**Comment by knnniggett** [comment]
This is not the place to ask questions. Either wait for a response in your thread in the user forum, or you can ask in our irc channel.
