### ISSUE TITLE
Installation Conflict

### ISSUE THREAD

**Issue by sillytenant** [ZoneMinder/zoneminder#2045]
Version of ZoneMinder (attempted at) being installed is: 1.30.4 (from 'yum info zoneminder')
OS Version: CentOS Linux release 7.4.1708 (Core) (from /etc/centos-release)
Kernel installed: 3.10.0-693.17.1.el7.x86_64 (from (uname -a')

When I attempt to install ZoneMinder, there are many conflicts that appear in RPMs, including:
 - php vs. php72w
 - vlc
 - Perl

I was able to manually install:
 - VLC components: vlc vlc-core vlc-extras vlc-plugin-jack

 - FFMpeg components: ffmpeg-libs gstreamer-ffmpeg ffmpeg ffmpegthumbnailer

 - PERL components: perl perl-AppConfig perl-Archive-Tar perl-Archive-Zip perl-Astro-SunTime perl-CGI perl-Class-Inspector perl-Class-Load perl-Class-Std perl-Class-Std-Fast perl-Convert-BinHex perl-Data-Dump perl-Data-OptList perl-Data-UUID perl-Date-Manip perl-Device-SerialPort perl-Digest-SHA perl-Email-Date-Format perl-FCGI perl-Image-Base perl-Image-Info perl-Image-Xbm perl-Image-Xpm perl-IO-Interface perl-IO-SessionData perl-IO-Socket-Multicast perl-IO-Zlib perl-List-MoreUtil perl-Locale-Maketext perl-Locale-Maketext-Simple perl-LWP-Protocol-https perl-MailTools perl-MIME-Lite perl-MIME-tools perl-MIME-Types perl-Module-CoreList perl-Module-Implementation perl-Module-Load perl-Module-Load-Conditional perl-Module-Metadata perl-Module-Runtime perl-Mozilla-CA perl-Net-SMTP-SSL perl-Package-Constants perl-Package-DeprecationManager perl-Package-Stash perl-Package-Stash-XS perl-Params-Check perl-Params-Util perl-Pod-POM perl-SOAP-Lite perl-SOAP-WSDL perl-Sub-Install perl-Sys-CPU perl-Sys-MemInfo perl-Sys-Mmap perl-Sys-Syslog perl-Template-Toolkit perl-Time-ParseDate perl-Try-Tiny perl-URI-Encode perl-version perl-X10 perl-XML-LibXML perl-XML-NamespaceSupport perl-XML-SAX perl-XML-SAX-Base perl-XML-Simple

 - PHP72W Components: php72w php72w-cli php72w-common php72w-gd php72w-mysql php72w-pdo php72w-gd php72w-mysqli php72w-pear php72w-pecl-apcu php72w-posix php72w-process php72w-xml

     I then attempt to install zoneminder: 'yum install zoneminder'
 However, there are apparently dependencies in zoneminder for php (no suffix version) which conflict with the php72w packages, specifically (see full output at bottom):
 - php72w-common conflict with php-common
 - php72w-pecl-apcu conflict with php-pecl-apcu

     I searched the issues page and the forums, but was unable to find any sort of resolution.  I am generally disinclined to utilize the skip broken feature as installing both php-common and phpXXw-common tends to end poorly.  Can the dependencies in the ZoneMinder RPM be updated so that it has consistent dependencies?

Stu

```
# yum install zoneminder
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.mirror.lstn.net
 * epel: mirror.us.leaseweb.net
 * extras: linux.cc.lehigh.edu
 * rpmfusion-free-updates: mirror.math.princeton.edu
 * rpmfusion-nonfree-updates: mirror.math.princeton.edu
 * updates: mirror.trouble-free.net
 * webtatic: us-east.repo.webtatic.com
Resolving Dependencies
--> Running transaction check
---> Package zoneminder.x86_64 0:1.30.4-3.el7 will be installed
--> Processing Dependency: php-pecl-apcu for package: zoneminder-1.30.4-3.el7.x86_64
--> Processing Dependency: cambozola for package: zoneminder-1.30.4-3.el7.x86_64
--> Running transaction check
---> Package cambozola.noarch 0:0.936-3.el7 will be installed
---> Package php-pecl-apcu.x86_64 0:4.0.11-1.el7 will be installed
--> Processing Dependency: php(api) = 20100412-64 for package: php-pecl-apcu-4.0.11-1.el7.x86_64
--> Processing Dependency: php(zend-abi) = 20100525-64 for package: php-pecl-apcu-4.0.11-1.el7.x86_64
--> Running transaction check
---> Package php-common.x86_64 0:5.4.16-43.el7_4 will be installed
--> Processing Conflict: php72w-common-7.2.2-1.w7.x86_64 conflicts php-common < 7.2
--> Finished Dependency Resolution
Error: php72w-common conflicts with php-common-5.4.16-43.el7_4.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
# 
```

**Comment by knnniggett** [comment]
This issue has occurred because you have chosen to upgrade the version of php that ships with CentOS. IYou should this to avoid common problems such as this:
http://zoneminder.readthedocs.io/en/latest/installationguide/redhat.html#how-to-avoid-known-installation-problems

You didn't say where you got the zoneminder package from, but also note you should use rpm fusion for the latest zoneminder release.
