### ISSUE TITLE
"New Events" being created with zero length images, never creating a real Event.

### ISSUE THREAD

**Issue by joseph85750** [ZoneMinder/zoneminder#2054]
Issue where a zero length image shows up in the Events page, with no index value.
Does not appear to be a permissions issue, since I made all directories owned by proper use, as well as chmod 777 to verify.

 chown -R www-data:www-data /usr/share/zoneminder/

Seems to be tied to Debian releases, since I didn't experience this on CentOS.

See for screenshots, more info, and some dialogue:
  https://forums.zoneminder.com/viewtopic.php?f=36&t=27049

**Comment by knnniggett** [comment]
@joseph85750 Please do not double post. Rest assured your message in the user forum has been read. It will be dealt as time allows.
