### ISSUE TITLE
Feature Request: Add ONVIF support [$60]

### ISSUE THREAD

**Issue by digdilem** [ZoneMinder/ZoneMinder#208]
http://www.onvif.org/

"ONVIF Profiles for Streaming, Storage and Recording, and Access Control, are designed to enable security solution designers and integrators, to more easily identify features supported by a product, without the challenge of determining the compatibility between versions of the ONVIF specification. "

Phill looked at this in 2012 - see https://www.facebook.com/zoneminder/posts/509918749033943 

Random google turned up: http://www.cctvforum.com/viewtopic.php?f=19&t=24469&start=15  

"Zoneminder could triple their compatibility by integrating ONVIF."

**Comment by knnniggett** [comment]
ONVIF support was officially merged in #479 as an optional feature.

If I understand Bountysource correctly, I need to close the issue in order for the bounty to be claimed.
@altaroca feel free to claim the bounty.
