### ISSUE TITLE
Montage Review is not working under Debian - $path not filled in view.php

### ISSUE THREAD

**Issue by fsardone** [ZoneMinder/zoneminder#2094]
Hello everybody.
I have ZM 1.30.4 installed on a Debian Stretch which runs in a fully PV machine under a xen hypervisor.
The install (of ZM) has been performed as per directions at
https://wiki.zoneminder.com/Debian_9_64-bit_with_Zoneminder_1.30.4_the_Easy_Way#Debian_9_with_Zoneminder_1.30.4

The system performs correctly and it is currently running 4 cameras.
All cameras records and store multiple jpegs which are replayed in the individual camera event window.

The trouble is the Montage review which, as soon as I go out of live mode into event mode, displays no data even if the time cursor is on events.
I do get errors (invalid image path - see below) when supposedly it should be playing video in some of the frames.
I did modify the message and appended the $path to see the content and appears to be empty.
I cannot reverse engineer the montage review, but if you point me out on the mechanics and where the variable should be set, I can try to locate the reason why this variable is empty and try to fix it myself.

Any help is appreciated. 

Thanks

Fabio

**ZoneMinder Version (`zmaudit.pl -v`):**
1.30.4
**Are you using a development snapshot / git checkout?  If so, what is the latest commit? (`git rev-parse HEAD`):**
no
**Linux Distribution and Version (`cat /etc/os-release` or `cat /etc/redhat-release`):**
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
**If the issue concerns a camera, provide the make, model, frame rate, resolution and ZoneMinder Source Type:**
n/a
**Relevant log lines:**
```
Please NOTE:
I changed the error text from Invalid to Xnvalid to validate my insertion point and appended the $path variable. to ensure I was in the right place in code.
log lines here
```
2018-04-27 16:38:17.555639	zmc_m2		3804	INF	CancelloSu: 1698000 - Capturing at 10.00 fps	zm_monitor.cpp	3125
2018-04-27 16:38:08.960837	zma_m3		930	INF	Backyard: 1923000 - Analysing at 10.00 fps	zm_monitor.cpp	1296
2018-04-27 16:38:07.327630	web_php		16368	ERR	Xnvalid image path	/usr/share/zoneminder/www/views/image.php	132
2018-04-27 16:38:07.095368	web_php		16368	ERR	Xnvalid image path	/usr/share/zoneminder/www/views/image.php	132
2018-04-27 16:37:41.309877	zmc_m5		3778	INF	Citofono: 2556000 - Capturing at 14.93 fps	zm_monitor.cpp	3125
2018-04-27 16:37:31.832120	zma_m4		932	INF	GarageGate: 1915000 - Analysing at 10.00 fps	zm_monitor.cpp	1296

**Comment by knnniggett** [comment]
Here is the block of code returning the error you mention:
https://github.com/ZoneMinder/zoneminder/blob/release-1.30.4/web/views/image.php#L82

The first thing it does is call realpath. What that does is expand symbolic links and resolve indirect references e.g. ../../ 

If the resulting path is not the same as the original path passed to it, then it fails with "Invalid image path". This is by design to prevent a hacker from reading arbitrary files anywhere on your filesystem.

That also means there are some restrictions on how you can set up your event folder, at least with the version of zoneminder you are using. So what we need to know is the value of DIR_EVENTS under Options -> Paths. Please also describe how you set up the zoneminder events folder, how you mounted it if the volume is external, and the results of the following: `ls -lhd /var/cache/zoneminder/www/events`.

**Comment by fsardone** [comment]
Hello and thanks for your reply.
`ls -lhd /var/cache/zoneminder/www/events`
returned 
`ls: cannot access '/var/cache/zoneminder/www/events': No such file or directory`

My install 'appears' to stores the events under (more about this below):

`/var/cache/zoneminder/events`

I did try creating a symbolic link (guess it was too easy ..) but it obviously fails due to the safe implementation you mentioned above ...now 
`ls -lhd /var/cache/zoneminder/www/events`
returns
`lrwxrwxrwx 1 root root 28 May  3 06:24 /var/cache/zoneminder/www/events -> /var/cache/zoneminder/events`

But I still have:
`2018-05-03 08:25:31.490096 | web_php |   | 30244 | ERR | Xnvalid image pathend path | /usr/share/zoneminder/www/views/image.php | 132
-- | -- | -- | -- | -- | -- | -- | --
2018-05-03 08:25:31.488488 | web_php |   | 30280 | ERR | Xnvalid image pathend path | /usr/share/zoneminder/www/views/image.php | 132`

I did change the reporting line as follows to assess content and location:
`$errorText = "Xnvalid image path" . $path . "end path";`

Also the actual install of zoneminder appears to live in 

fabio@zoneminder:~$ cd /usr/share/zoneminder/
fabio@zoneminder:/usr/share/zoneminder$ ls -la
total 16
drwxr-xr-x  4 www-data www-data 4096 Jan 27 15:11 .
drwxr-xr-x 97 root     root     4096 Jan 28 08:22 ..
drwxr-xr-x  2 www-data www-data 4096 Jan 27 15:11 db
drwxr-xr-x 13 www-data www-data 4096 Apr 27 14:37 www
fabio@zoneminder:/usr/share/zoneminder$ cd www
fabio@zoneminder:/usr/share/zoneminder/www$ ls -la
total 68
drwxr-xr-x 13 www-data www-data 4096 Apr 27 14:37 .
drwxr-xr-x  4 www-data www-data 4096 Jan 27 15:11 ..
drwxr-xr-x  2 www-data www-data 4096 Jan 27 15:11 ajax
drwxr-xr-x  4 www-data www-data 4096 Jan 27 15:11 api
drwxr-xr-x  2 www-data www-data 4096 Jan 27 15:11 css
lrwxrwxrwx  1 www-data www-data   28 Jul 10  2017 events -> /var/cache/zoneminder/events
drwxr-xr-x  2 www-data www-data 4096 Jan 27 15:11 fonts
drwxr-xr-x  2 www-data www-data 4096 Jan 27 15:11 graphics
lrwxrwxrwx  1 www-data www-data   28 Jul 10  2017 images -> /var/cache/zoneminder/images
drwxr-xr-x  3 www-data www-data 4096 Jan 27 15:11 includes
-rw-r--r--  1 www-data www-data 7394 Apr 27 14:37 index.php
drwxr-xr-x  2 www-data www-data 4096 Jan 27 15:11 js
drwxr-xr-x  2 www-data www-data 4096 Jan 27 15:11 lang
-rw-r--r--  1 root     root     7394 Apr 27 14:09 original_index.php
drwxr-xr-x  3 www-data www-data 4096 Jan 27 15:11 skins
lrwxrwxrwx  1 www-data www-data   26 Jul 10  2017 temp -> /var/cache/zoneminder/temp
drwxr-xr-x  3 www-data www-data 4096 Jan 27 15:11 tools
drwxr-xr-x  2 www-data www-data 4096 Apr 27 14:37 views
fabio@zoneminder:/usr/share/zoneminder/www$

and checking the event directory:

`fabio@zoneminder:/usr/share/zoneminder/www$ ls -lhd /usr/share/zoneminder/www/events
lrwxrwxrwx 1 www-data www-data 28 Jul 10  2017 /usr/share/zoneminder/www/events -> /var/cache/zoneminder/events`

The events are actually in /var/cache/zoneminder/events which is symlinked in the zoneminder install directory.

So my impression is that the packaging relocation to /usr/share/zoneminder rather than /var/cache/zoneminder might have broken the safeguards against unauthorized access.

The system was a fresh install from a new Virtual Machine .... just created for the purpose.

Cheers

Fabio

**Comment by fsardone** [comment]
knnniggett,

thanks for your support.
Digging down to variable content, I found out that the problem was a path difference on the hour position. This clearly pointed out to a timezone issue.
The PHP date was correct but the system TZ was set to GMT this was causing the checks on $path to fail. The issue is unrelated to zoneminder but to the setup of the server.
This has been rectified, closing issue.

Kind regards
Fabio

**Comment by knnniggett** [comment]
Nice catch. Even though I didn't respond immediately, I was thinking about this and as I was driving into work this morning the thought occurred to add Info statements to reveal the contents of key variables to aid in troubleshooting.  It's relatively easy to do, so if you find yourself scratching your head over a new problem, you can do the following in just about any place in zoneminder's php code:
```php
Info("The path received was: $path");
```
Or in your case, modify the error message itself to show the path:

```php
$errorText = "Invalid image path: $path";
```

That would have shown the path it was looking for, which ideally would speed up the troubleshooting experience.

**Comment by vvaldelamar** [comment]
fsardone You right 
Add the following line of code to top of your php.ini file
date.timezone = "America/Mexico_City"
with this FIX I can see "Thumbnail and  Montage Review"  :)
