### ISSUE TITLE
Important bad link on https://wiki.zoneminder.com/Beginner_hardware

### ISSUE THREAD

**Issue by TopView** [ZoneMinder/zoneminder#2102]
The link for "BSIT" is broken, i.e. "BSIT are really cheap but also not the greatest quality. "

Sorry guys, for reporting this here, but this web page has a broken link, and I can't find any other way there to report it.  I can't login to the MediaWiki, and there is no option for me to register.  Hopefully you can pass it forwards to the right person.  

----------------

You should only file an issue if you found a bug.  Feature and enhancement requests, general discussions and support questions should occur in one of the following areas:

- The ZoneMinder IRC channel - irc.freenode.net #zoneminder
- The [ZoneMinder Forum](https://forums.zoneminder.com/)

**Do not post feature or enhancement requests, general discussions or support questions here.**

Docker related issues should be posted here: https://github.com/ZoneMinder/zmdockerfiles

Make sure you are running the latest version of ZoneMinder before reporting an issue.

**ZoneMinder Version (`zmaudit.pl -v`):**

**Are you using a development snapshot / git checkout?  If so, what is the latest commit? (`git rev-parse HEAD`):**

**Linux Distribution and Version (`cat /etc/os-release` or `cat /etc/redhat-release`):**

**If the issue concerns a camera, provide the make, model, frame rate, resolution and ZoneMinder Source Type:**

**Relevant log lines:**
```
log lines here
```

**Comment by knnniggett** [comment]
For future reference, the place to report issues with our website, including the wiki, is here:
https://forums.zoneminder.com/viewforum.php?f=13

Going through the wiki history, that link was added in 2010. I'm not sure what BSIT is or was, so I just deleted it. That whole page could use an update. Axis is no longer the only game in town for good ip cameras. I've made a moderate change to that page, but it certainly could use some additional love.

Note, if you tell us what your user forum name is, we can add you to the list of users who can edit the wiki.  Sorry for having to go through this, but we had some serious spam problems when anyone could edit the wiki w/o having to first contact a human moderator.
