### ISSUE TITLE
Broken tab links in monitor view 

### ISSUE THREAD

**Issue by epruesse** [ZoneMinder/zoneminder#2119]
**ZoneMinder Version (`zmaudit.pl -v`):**

1.31.44 (1.31.44~20180606205548-bionic from **iconnor ppa**)

**Are you using a development snapshot / git checkout?  If so, what is the latest commit? (`git rev-parse HEAD`):**

No

**Linux Distribution and Version (`cat /etc/os-release` or `cat /etc/redhat-release`):**

Ubuntu 18.04

**If the issue concerns a camera, provide the make, model, frame rate, resolution and ZoneMinder Source Type:**

NA
**Relevant log lines:**
```
```

---
After upgrading from 1.31.0 to 1.31.44 I noticed a lot of changes to the UI (looks neat overall), with some breakage:

- Minor: Changing skin or theme does not seem to have any effect 
- Minor: The layouts don't seem to work fully, e.g. the content in the options view is rendered below and to the right of the tab menu, while I assume it's supposed to be just to the right of the tab menu.
- **Major: The "tab" links in the monitor view are broken,**  making it impossible for "end users" to edit the monitor settings on any but the first tab.

URI: `http://localhost/zm/index.php?view=monitor&mid=3#`
From the page HTML:
```
    <li class="active">General</li>
      <li><a href="#" onclick="submitTab( 'source' ); return( false );">Source</a></li>
      <li><a href="#" onclick="submitTab( 'storage' ); return( false );">Storage</a></li>
      <li><a href="#" onclick="submitTab( 'timestamp' ); return( false );">Timestamp</a></li>
      <li><a href="#" onclick="submitTab( 'buffers' ); return( false );">Buffers</a></li>
      <li><a href="#" onclick="submitTab( 'misc' ); return( false );">Misc</a></li>
```
though `submitTab` does not seem to be defined at all. 

Manually adding `&tab=source` to the URL works for now.

**Comment by connortechnology** [comment]
There are required updates to your apache config. See
https://gist.github.com/connortechnology/9ca83f812d94b2777b93ad54ee45067e

for an example.
