### ISSUE TITLE
Allow to limit user to monitor groups rather than to individual monitors

### ISSUE THREAD

**Issue by Harvie** [ZoneMinder/zoneminder#212]
Zoneminder implements some "monitor groups", but when it comes to restricting users it can only restrict users to individual monitor. Can you please fix this?

My use case:
i have two separate monitor groups: A & B.
first 5 people should see both A & B
another 10 people should see only A
and 15 more people should see only B

when i add 1 monitor to group B, i have to edit 20 users. after this fix i'll have to just edit 1 group...
##

**Comment by Harvie** [comment]
Any ideas on this?

**Comment by Harvie** [comment]
Is zoneminder still under active development?

**Comment by Harvie** [comment]
I wonder if shinobi has this feature
https://shinobi.video/
https://github.com/moeiscool/Shinobi

**Comment by SteveGilvarry** [comment]
Tomas I am working on this feature, but only in my free time. Please bear with me as may take me a while as I need to learn some stuff while I work on it. Ok got to run as late for work.
And feel free to try any solutions you like, I do this for fun not profit, so competitive tension has no bearing.

**Comment by Harvie** [comment]
@SteveGilvarry Sorry for teasing you :-) Just wanted to know if there is still somebody reading these issues, because for 6 years i only got replies from robot trying to close the topic...

Thanks for your work anyway. Just checked the commit history and i've found the project is suprisingly active :-)

**Comment by moorsey** [comment]
Honestly thought ZM already had this feature, stumbled across this issue while searching around, subscribed and keeping fingers crossed!

**Comment by connortechnology** [comment]
1.37.27 now has this.
