### ISSUE TITLE
Autorefresh in login page prevents from login to zoneminder UI

### ISSUE THREAD

**Issue by dwrobel** [ZoneMinder/zoneminder#2123]
**ZoneMinder Version (`zmaudit.pl -v`):**
`$ rpm -qv zoneminder`
`zoneminder-1.31.44-1.215.20180608gitgf5f464988.fc28.x86_64`

When I open in firefox _(v60.0.1)_ zoneminder main login page _(https://host-name-where-zm-is-installed/zm)_ there seems to be autorefresh. As a result, if you're not fast enough to complete filling both `Username` and `Password` fields then you are forced to repeat that process until you become faster than autorefresh (~5secs).

Steps to reproduce:
1. Open zoneminder login page,
2. In `Username' field type `test`,
3. Press `TAB` key _(which should transfer focus to the `Password` field)_,
4. Wait 10 or more secs.

**Result**: `test` disappear from the `Username` field and focus is transferred automatically to the `Username` field.
**Expected result**: Focus should stay in the `Password` field and `test` shouldn't disappear from the `Username` field.

**Comment by MalakymR** [comment]
We're seeing the same problem too.

No need to tab into the password field.
