### ISSUE TITLE
H264 passthoug removed in the 1.31.44.

### ISSUE THREAD

**Issue by juanmoura** [ZoneMinder/zoneminder#2126]
After update for the most recent version from the master repo the option H264 Passthoug is missing. If i put the H264 encode i will need to change de resolution in the monitor config, if i choose H264 Passthoug i will be use use less memory because i will put in the resolution low config. But the system will record the high resolution configurated inside the camera.

**Comment by juanmoura** [comment]
UPDATE: I see in the commits. Only with ffmpeg will be enable to choose the passthoug. In my case i'm using with ffmpeg but the passthoug still missing.

**Comment by connortechnology** [comment]
I have corrected it.  Building new packages now.
