### ISSUE TITLE
Change order in webui

### ISSUE THREAD

**Issue by juanmoura** [ZoneMinder/zoneminder#2128]
The button for up or down monitors in the webui don't work in any version like a 1.31.xx. Work only in the 1.30.4.
For reorder the monitor we need to use the link http://IP/zm/?view=console&action=sequence&mid=2&smid=1

**Comment by megasaturnv** [comment]
Have you tried clicking and dragging?

**Comment by knight-of-ni** [comment]
The behavior has changed 1.31.xx. To change the order of a monitor, click on the up/down arrow on the right of the monitor then drag it to where you want it.
