### ISSUE TITLE
ship only one version of jQuery

### ISSUE THREAD

**Issue by onlyjob** [ZoneMinder/zoneminder#2149]
Let's ship only one version of jQuery please.

Currently there are two:

  * 1.11.3: `web/skins/classic/js/jquery-1.11.3.js`
  * 1.12.4: `web/skins/classic/js/jquery-ui-1.12.1/external/jquery/jquery.js`

**Comment by onlyjob** [comment]
I've just found aother one in `web/skins/classic/js/chosen`, version 1.8.2:

https://github.com/ZoneMinder/zoneminder/blob/master/web/skins/classic/js/chosen/chosen.jquery.js
https://github.com/ZoneMinder/zoneminder/blob/master/web/skins/classic/js/chosen/chosen.jquery.min.js

**Comment by onlyjob** [comment]
Could someone re-open this bug please before we all forget? Thanks.

**Comment by connortechnology** [comment]
Um, that is not jquery, that is chosen, using the jquery api.  We can get rid of chosen.proto.* though.

**Comment by onlyjob** [comment]
Ah, right, my mistake... All good then. Thanks.
