### ISSUE TITLE
ZMC Glibc error

### ISSUE THREAD

**Issue by nokia001** [ZoneMinder/zoneminder#2170]
Hi,

traps: zmc[6333] general protection ip:7f2ba9361680 sp:7ffc47ecb090 error:0 in libc-2.26.so[7f2ba9326000+1bb000]

What happen here?
Gentoo ebuild 1.30.4

I need help.
thx

**Comment by Magic919** [comment]
I expect it's not a ZM problem as it used to build and work.

If you can build it with debug, there are some troubleshooting steps using addr2line.  I tried strace and couldn't see anything that helped.  https://zoneminder.readthedocs.io/en/stable/faq.html#i-am-getting-messages-about-a-backtrace-in-my-logs-what-do-i-do

**Comment by connortechnology** [comment]
I'm actually aware of several potential crashes in 1.30.4.  I fixed them all in creating 1.31.*.
