### ISSUE TITLE
Can't filter for some log events in the log viewer

### ISSUE THREAD

**Issue by Warudo** [ZoneMinder/zoneminder#2180]
**ZoneMinder Version (`zmaudit.pl -v`):** 1.31.45
**Are you using a development snapshot / git checkout?  If so, what is the latest commit? (`git rev-parse HEAD`):** Yes, 3dc424282b60ae10ea9f0bde1d36579a1e27e977
**Linux Distribution and Version (`cat /etc/os-release` or `cat /etc/redhat-release`):** Arch Linux
**Browser:** Firefox 61.0.2

When using the Log viewer on the web interface, I can't filter for certain things. For example in the attached screenshot, I can't filter for line 50 to see logins. I can't filter for component web_php, PID 4949 or file auth.php file either. This happens to some other components too, for example I can't filter for line 40, or any other properties of the zms_mX lines either.
This is a regression, it used to work in 1.30.4.

When setting LOG_LEVEL_FILE to INFO, no log file web_php gets created either, although all the zm*.log files show up.
![screenshot](https://user-images.githubusercontent.com/1916368/44107952-45742520-9ff9-11e8-8e8e-3bcf1eacfea2.png)

**Comment by Warudo** [comment]
The LOG_LEVEL_FILE problem is solved. I just had to log in again after enabling it, I though that ZM also writes existing log entries from the DB to the files.

The filtering problem ist not solved however is not solved. The browser console shows no errors.

**Comment by connortechnology** [comment]
I think I have this issue fixed or at least improved.

**Comment by Warudo** [comment]
Fix confirmed for me.
