### ISSUE TITLE
Excessive logging resulting from what looks like a debug line left in

### ISSUE THREAD

**Issue by rjclark** [ZoneMinder/zoneminder#2183]
This line in a recent commit:

https://github.com/ZoneMinder/zoneminder/blob/871e3807e644f11b8e0e8454461e062cbab4b0b7/web/ajax/log.php#L98

is generating about 1200 log messages a minute for me and looks like it was left by accident as part of the last merge.

The log messages look like this

    2018-08-19 12:48:37 | web_php |   | 979 | WAR | TimeKey: 1534697314.763473Intval:1534697314 DateTime:2018-08-19 12:48:34

**Comment by connortechnology** [comment]
Thanks for reporting it.  Definitely my fault. Fixed.
