### ISSUE TITLE
Database Upgrade 1.31.43 Over-Qualifies Table Name

### ISSUE THREAD

**Issue by N3X15** [ZoneMinder/zoneminder#2190]
https://github.com/ZoneMinder/zoneminder/blob/c271948f3d8f139b1b0ad418e22e0192b18e6cbd/db/zm_update-1.31.43.sql#L8

When building from source and using a non-standard database, the `` `zm`. `` specifies that the table to be `ALTER`ed is in the `zm` schema, which doesn't exist on my system.

Fix was to remove `` `zm`. ``.

**Comment by connortechnology** [comment]
Thanks!  I have committed the fix.
