### ISSUE TITLE
startpackpack.sh typo

### ISSUE THREAD

**Issue by mtfurlan** [ZoneMinder/zoneminder#2204]
I just used startpackpack.sh with the [instructions to build a package ](https://zoneminder.readthedocs.io/en/stable/installationguide/packpack.html) to build 1.32.0 for debian stretch.

There is a typo in moving the unpacked cakePHP enum behavior at line [157](https://github.com/ZoneMinder/zoneminder/blob/2f7c9a406a428f79c67844dd0938ae134bae3ef5/utils/packpack/startpackpack.sh#L157)
```
-        mv -f crud-${CEBVER} web/api/app/Plugin/CakePHP-Enum-Behavior                                                                        │·····································
+        mv -f CakePHP-Enum-Behavior-${CEBVER} web/api/app/Plugin/CakePHP-Enum-Behavior 
```

It looks like everything else ran fine, but I haven't got a test system together quite yet to test it.

**Comment by knight-of-ni** [comment]
Nice catch. Fixed in commit 7ef9cf4
