### ISSUE TITLE
LoginController could not be found

### ISSUE THREAD

**Issue by NigelTicknor** [ZoneMinder/zoneminder#2206]
**ZoneMinder Version:** 1.32.0

**Linux Distribution and Version:** 
Ubuntu 16.04.5 LTS

/zm/api/login.json produces the following error:
{
    "code": 404,
    "name": "Controller class LoginController could not be found.",
    "message": "Controller class LoginController could not be found.",
    "url": "\/zm\/api\/login.json"
}

**Comment by knight-of-ni** [comment]
Try: `/zm/api/host/login.json`

Appears to be a typo in our documentation.

**Comment by NigelTicknor** [comment]
/zm/api/host/login.json worked for me.
Thanks
