### ISSUE TITLE
Job for zoneminder.service failed because the control process exited with error code

### ISSUE THREAD

**Issue by fontes31** [ZoneMinder/zoneminder#2210]
Hi,

After installing zoneminder 1.30.4 on ubuntu server 16.04 and starting the service i have the error: 

"Job for zoneminder.service failed because the control process exited with error code" See "systemctl status zoneminder.service" and "journalctl -xe" for details

I run journalctl -xe, but iam completely lost:

-- Unit zoneminder.service has begun starting up.
Sep 16 08:43:10 Media zmpkg.pl[8766]: DBI connect('database=zm;host=localhost','
Sep 16 08:43:10 Media zmpkg.pl[8766]: Can't connect to db at /usr/share/perl5/Zo
Sep 16 08:43:10 Media zmpkg.pl[8766]: BEGIN failed--compilation aborted at /usr/
Sep 16 08:43:10 Media zmpkg.pl[8766]: Compilation failed in require at /usr/shar
Sep 16 08:43:10 Media zmpkg.pl[8766]: BEGIN failed--compilation aborted at /usr/
Sep 16 08:43:10 Media zmpkg.pl[8766]: Compilation failed in require at /usr/bin/
Sep 16 08:43:10 Media zmpkg.pl[8766]: BEGIN failed--compilation aborted at /usr/
Sep 16 08:43:10 Media systemd[1]: zoneminder.service: Control process exited, co
Sep 16 08:43:10 Media systemd[1]: Failed to start ZoneMinder CCTV recording and 
-- Subject: Unit zoneminder.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit zoneminder.service has failed.
-- 
-- The result is failed.
Sep 16 08:43:10 Media systemd[1]: zoneminder.service: Unit entered failed state.
Sep 16 08:43:10 Media systemd[1]: zoneminder.service: Failed with result 'exit-c

**Comment by knight-of-ni** [comment]
Failed to connect to database is a configuration error. This is not a bug. 

Feel free to ask this question in the user forum. The following information will be required:
- how you installed zoneminder: built it yourself, ppa, etc
- what documentation you followed
- is there some reason why you are not attempting to install the latest version of zoneminder?
- have you verified the sql login credentials given to zoneminder are correct?
