### ISSUE TITLE
Live View does not work, pollutes file system

### ISSUE THREAD

**Issue by zmeggyesi** [ZoneMinder/zoneminder#2211]
**ZoneMinder Version (`zmaudit.pl -v`):** 1.32.0

**Are you using a development snapshot / git checkout?  If so, what is the latest commit? (`git rev-parse HEAD`):** 7f98277571529b322c379817449c8ac3a0c3ba84

**Linux Distribution and Version (`cat /etc/os-release` or `cat /etc/redhat-release`):** Raspbian GNU/Linux 9

When trying to view Live View for any camera, I get a continuous stream of JS errors in the console, with no live view. The error message is `getStreamCmdResponse stream error: Socket /var/run/zm/${filename}.sock does not exist` - obviously, it's not a variable, but a continuously changing file name.
However, running `watch ls -lah` in parallel shows that the file pops into existence for a moment before being deleted. It does, however, leave behind its corresponding `.lock` file, which is not garbage-collected and pollutes the run directory.

**Comment by knight-of-ni** [comment]
What you have described is exactly the behavior of an improperly configured system. The problem could be an incorrect PATH_ZMS, insufficient space in /dev/shm, an improperly configured camera, or something else. Recommend you search the user forum for posts with symptoms just like yours. 

Feel free to create a new post in the user forum, but we need the following:
- how you installed zoneminder
- what documentation you followed
- output `df -lh |grep| shm`
- average system load
- quantity, resolution, framerate of all cameras
- A full page of the zoneminder log from the moment it is started up until just after errors begin to show
