### ISSUE TITLE
h264 camera passthrough causes events to be unviewable

### ISSUE THREAD

**Issue by howlett** [ZoneMinder/zoneminder#2212]
When selecting storage->h264 camera passthrough, alarms occur but the events are not viewable.

version 1.32.0

No error is logged, the video screen shows the alarm bar (red/not) but cannot load the video.

**Comment by connortechnology** [comment]
Are you sure?  With .mp4 the current event will not be viewable (because it is still writing the file) but older events will be.  

What happens if you click Download MP4? Is that file viewable in vlc?

**Comment by howlett** [comment]
No, I'm wrong.  For some reason none of the recordings worked for when I had set this up but when I just tested with setting off the alarm, it worked fine.

**Comment by howlett** [comment]
I've posted a request for support that may be related to this issue.  No events over 2 days old have any video files yet the events remain.

**Comment by howlett** [comment]
This looks to be a configuration issue causing zma to exit with status 255
