### ISSUE TITLE
1.32.0: Camera stopped working (Image size is not multiples of 12 and 64)

### ISSUE THREAD

**Issue by onlyjob** [ZoneMinder/zoneminder#2220]
Some cameras stopped working with error `Image size is not multiples of 12 and 64` after upgrade to 1.32.0.

Here is one example: http://www.weathercamnetwork.com.au/new_farm/982x737.jpg - easy to configure as HTTP/simple.

That was working fine with 1.30.4 and earlier versions.

**Comment by onlyjob** [comment]
Any progress here? 1.32.1 didn't fix it and it would be really nice to restore feed from not perfectly sized cameras... Thanks.

**Comment by onlyjob** [comment]
There was a similar issue here before: #979

**Comment by connortechnology** [comment]
I did some work on this... just got side tracked..

**Comment by onlyjob** [comment]
Thanks, @connortechnology. I've just upgraded to 1.32.3 but this problem is still present...

**Comment by onlyjob** [comment]
Thanks! :)

**Comment by strusty** [comment]
You may want to look at the video itself in a browser, copy the picture, paste it into gimp, and see the size that gimp reports.  It may be different than the 982x737 or other odd size that is reported at that link.  This is the case when using Android application IP Camera.   Inspecting the size at browser will give a wrong size.  If you use the size gimp reports, it will work and be a multiple of 64.
