### ISSUE TITLE
1.32.0 - Can't re-use deleted filter ID

### ISSUE THREAD

**Issue by sagitt** [ZoneMinder/zoneminder#2235]
If I delete a filter i can't re-use the ID. So now my filters starts from ID 5. maybe can add a way to manually associate filter ID

**Comment by knight-of-ni** [comment]
The same behavior is true for monitor ID's. What you are referring to is the auto-increment primary key in the dB table. As the name implies, it will auto-increment anytime a new record is added. The index does not auto-decrement, even if an existing record is deleted. This is normal database behavior and does not affect the operation of the system. 

If you have written some third party application to read Filter by ID, then try using the name of the filter instead.
