### ISSUE TITLE
1.32.0 - Zoneminder server from IP Cam Viewer

### ISSUE THREAD

**Issue by sagitt** [ZoneMinder/zoneminder#2236]
The App "IP Cam Viewer Pro" for iOS and Android that supports "ZoneMinder Server" as source are now broken in the new 1.32.0

works with 1.30.4

https://play.google.com/store/apps/details?id=com.rcreations.WebCamViewerPaid&hl=it

**Comment by knight-of-ni** [comment]
The popularity of ZoneMinder is a great thing. There are many third parties out there who have written various software to interface with it. However, that in no way means we, the developers of this project, are obligated to spend time fixing said third party product. 

I suggest you follow the advice @asker gave you in the user forum:
https://forums.zoneminder.com/viewtopic.php?f=33&t=27609

Simply re-asking the same question here in our github forum isn't going to change the answer.
