### ISSUE TITLE
No image in Monitor 

### ISSUE THREAD

**Issue by 72crew** [ZoneMinder/zoneminder#2249]
Not getting any answers on the other channels so I'm posting here.

I can see zms streaming in VLC and in chrome browser, but in Zoneminder I just have a broken image icon, no streaming.

I get no errors in the log it is quite happy and says it is capturing.

Can I get some help on how to find out how to debug this issue please.

1.32.1

NAME="Antergos Linux"
VERSION="16.10-ISO-Rolling"
ID="antergos"
ID_LIKE="arch"

```
log lines here

2018-10-11 15:53:03 | zmc_m1 |   | 22135 | INF | Monitor-1: images:459390 - Capturing at 10.00 fps, capturing bandwidth 941355bytes/sec | zm_monitor.cpp | 2473
-- | -- | -- | -- | -- | -- | -- | --



```

**Comment by knight-of-ni** [comment]
Not sure what you mean by channels as it does not appear you have posted in our user forum or slack channel. 

When the backend says you are capturing but the frontend displays no video, that almost certainly means your path_zms is set wrong. Some users have also had missing php modules which have caused this.

In any case, this is a bug reporting forum, and, for our sanity, we are requiring all support requests be made in our user forum or slack channel. We will be glad to help you there.
