### ISSUE TITLE
Update cakephp for php 7.2 compatibility

### ISSUE THREAD

**Issue by dlandon** [ZoneMinder/zoneminder#2260]
Cakephp 2.10.8 is not php 7.2 compatible.  Zoneminder Ubuntu package from iconnor ppa requests php 7.2 modules (common and mysql), but cakephp is not php 7.2 compatible.  Why request packages for php 7.2 that can't be used because of cakephp?

Please update to the latest cakephp stable.

**Comment by connortechnology** [comment]
We did.  ZM 1.32.* work fine with php 7.2.
