### ISSUE TITLE
PPA not uptodate

### ISSUE THREAD

**Issue by sgofferj** [ZoneMinder/zoneminder#2262]
ppa:iconnor/zoneminder is still at 1.30.4 from 2017-05-09. The PPA is mentioned as the download source for Ubuntu on zoneminder.com, so assuming that it's the "official" PPA, might I suggest it being updated?

**Comment by connortechnology** [comment]
You have to add the zoneminder-1.32 ppa.

**Comment by connortechnology** [comment]
Sadly I have little power over the zoneminder.com website.  We will get it updated eventually though.  Thanks for the heads up.
