### ISSUE TITLE
Remove recurring privacy agreement 

### ISSUE THREAD

**Issue by jzielke-nli** [ZoneMinder/zoneminder#2267]
After updating zoneminder I'm asked to accept the privacy agreement every time, which is annoying when I just want to use the app after updating. The agreement should only be required to be accepted once.

**Comment by zhuykovkb** [comment]
I am think also.

**Comment by knight-of-ni** [comment]
This is not a discussion forum. We have a user forum and slack channel in which you can state your opinion.
