### ISSUE TITLE
Have a monitoring daemon (or an existing such as zmaudit.pl) check periodically for camera(s) availability

### ISSUE THREAD

**Issue by nzbtuxnews** [ZoneMinder/zoneminder#227]
As pointed out in thread 
http://www.zoneminder.com/forums/viewtopic.php?f=30&t=21568&p=81985#p81985

There are currently no reliable means of notifying a sysadmin that a camera has gone offline, this feature should be added in future ZM releases as this would enhance the overall reliability of the package.

Currently, it was suggested to use a ping (if an IP camera) but as pointed out, ping is not meaningful as it only tells if the camera still is powered and has a valid IP.

There is however the existing functionality that ZM knows if a camera goes offline by putting the monitor status in RED in the main webpage.  Considering this, I believe modifying an existing daemon or adding a new one (not the preferred option IMO) may be easily done.
##

**Comment by SharkWipf** [comment]
This sounds like it could be a simple filter like the "disk percent" filters, something like "Monitor State -> equal to -> Error".  
Without this feature, Zoneminder is imitating security software from movies, where taking down cameras one by one doesn't raise any alarms.

**Comment by mastertheknife** [comment]
This is something that i personally need for a long time.
Also, when using linked monitors, with a Nodect camera linking to a Modect\Mocord camera, when the Modetect\Mocord camera loses signal or stops functioning for whatever reason, it also affects the Nodect camera. I had the idea of detecting such signal losses, sending an email and also changing the Nodect camera to "Mocord" or "Modect" until the bad camera returns working again.

**Comment by BjornR1989** [comment]
I've used _incron_ to call a script that evaluates each line added to the _/var/log/messages_ file and updates a db table to reflect the status of the camera's according to ZM, then it gets displayed in a table on a webpage.
It works but it's unreliable as incron often stops monitoring the file until _incrontab -e_ and saving its config again and ZM doesn't log everything. Furthermore it's inefficient because it's spawning a new process each time the log changes.

**Comment by connortechnology** [comment]
I use monit to ping the cameras.
I use logcheck to monitor the logs.

**Comment by SharkWipf** [comment]
These sound like terribly complex solutions for something that you'd expect to be a built-in feature

**Comment by nitrag** [comment]
Somehow ZM is still using CPU even if there is no feed. Whoops, bunch of electricity wasted there. This feature is needed!

**Comment by asantaga** [comment]
I have the same problem and I was wondering if we could simply add the capturing data to the Monitor info REST API?

Ive looked at it and I cant see it in there, but this would allow us to detect when a monitor stops sending images..
