### ISSUE TITLE
Event Upload fails with error in log files (Can't use string ("gadgetan") as a subroutine ref while "strict refs" in use at ./zmfilter.pl line 582.)

### ISSUE THREAD

**Issue by asantaga** [ZoneMinder/zoneminder#2275]
**ZoneMinder Version (`zmaudit.pl -v`):**
1.32.2
**Are you using a development snapshot / git checkout?  If so, what is the latest commit? (`git rev-parse HEAD`):**
No, installed via apt-get

**Linux Distribution and Version (`cat /etc/os-release` or `cat /etc/redhat-release`):**
Ubuntu 18.04

**If the issue concerns a camera, provide the make, model, frame rate, resolution and ZoneMinder Source Type:**
N/A
**Relevant log lines:**
```
Error when running filter using zmfilter.pl
root@e447d94d6d07:/usr/bin# ./zmfilter.pl 3
10/25/18 14:28:05.680172 zmfilter[2858].INF [main:181] [Scanning for events using all filters]
10/25/18 14:28:10.736147 zmfilter[2858].INF [main:286] [Checking filter emailAlarms upload, email returned 100 events ]
10/25/18 14:28:10.782737 zmfilter[2858].INF [main:504] [Creating upload file '/tmp/zonemindertmp/KitchenCam-1806.zip', 3 files]
10/25/18 14:28:10.880396 zmfilter[2858].INF [main:577] [Uploading to xxxx.com:22 using SFTP]
Can't use string ("gadgetan") as a subroutine ref while "strict refs" in use at ./zmfilter.pl line 582.
```

The filter is a basic, select all events with score of > 10 with the upload button set. I use the same filter for emailing the events and this works fine.

Discussed on thread @ https://forums.zoneminder.com/viewtopic.php?f=38&t=27684&p=107867#p107867

@connortechnology identified that zmfilter.pl line579 should have a comma at the end

```
         host=>$Config{ZM_UPLOAD_HOST}, user=>$Config{ZM_UPLOAD_USER}
          ($Config{ZM_UPLOAD_PASS} ? (password=>$Config{ZM_UPLOAD_PASS}) : ()),
         
```
should be 
```
host=>$Config{ZM_UPLOAD_HOST}, user=>$Config{ZM_UPLOAD_USER},
          ($Config{ZM_UPLOAD_PASS} ? (password=>$Config{ZM_UPLOAD_PASS}) : ()),
```      

Confirmed working on my environment

**Comment by connortechnology** [comment]
Fix was already committed.
