### ISSUE TITLE
Feature request: Modect event auto-split

### ISSUE THREAD

**Issue by ASerbinski** [ZoneMinder/zoneminder#2276]
This request is similar to closed issue https://github.com/ZoneMinder/zoneminder/issues/2139 -- however, I will be more concrete with respect to rationale for the feature.

I use Modect mode 24/7 with several *nightvision* cameras mounted on my home. For the most part, there are minimal events, the odd squirrel or somebody turning around in my driveway, however, there are occasional very LONG events which simply cannot be filtered out with zone configurations, resulting in extremely long events, which are painful to review.

A specific example of such an event, is a SNOW STORM. The IR lights up the snowflakes like hundreds of comets. If I set the thresholds to filter out the snowflakes falling 12 inches past the camera lens, it would completely miss a van full of ninjas pulling into my driveway.

**Comment by knight-of-ni** [comment]
We are not accepting feature requests from those who are not willing to do the work.

This is simply an issue of time. This decision is not based on the merit of your idea. Many people have good ideas... and that is the problem. There are too many ideas but not nearly enough people spending time on them. 

If you want, feel free to discuss your idea in the user forum or our slack channel. Maybe you can convince someone there to work on the idea.

**Comment by ASerbinski** [comment]
On what grounds do you assume that I wouldn't be willing to do some or all of the work?

But now that you mention it, I am now finding this project to be quite close minded, which seriously reduces my incentive to participate in it.

**Comment by knight-of-ni** [comment]
When you opened this issue you were presented with a set of criteria telling you this forum is for bug reports only and where to direct feature requests. Then, when I pointed you to where these kind of discussions should go, you replied back questioning my motive. 

So yeah, we are absolutely closed minded, when it comes to anyone dumping whatever they want to say into this forum. We have a set of rules in this forum to keep the list to only bug reports. You can discuss ideas all you want in the user form and our slack channel. Feel free to not like it. You aren't the one managing the forum.
