### ISSUE TITLE
Feature request: compressed domain motion detection

### ISSUE THREAD

**Issue by ASerbinski** [ZoneMinder/zoneminder#2284]
Given that most cameras now provide h264/h265 video streams, which as part of their design directly include description of motion of blocks, it would seem to make a lot of sense to use that existing data to perform motion detection in the compressed domain rather than decompressing the video and working in the pixel domain.

There is work being done to implement this feature for light servers (in particular, ARM hardware) here; https://github.com/cmisip/ZoneMinder -- however, he is specifically focused on raspberry pi hardware rather than developing this feature for general use. Nevertheless, it looks like a lot of what he has implemented may be reusable.

**Comment by knight-of-ni** [comment]
Camera base motion detection is already on our dashboard for the next major release:
https://github.com/ZoneMinder/zoneminder/projects/2

**Comment by ASerbinski** [comment]
That's not even remotely the same as compressed domain motion detection.

**Comment by SteveGilvarry** [comment]
Adam,
I looked at this a while ago, at the time the motion vectors access through
ffmpeg had been removed. Happy to look at it with you, if you have the
coding skills to help. Chat in slack, but I am in Australia so not online
at the same time as others that much. Also chat with icon in Slack as he is
looking for people to help him.
Don’t feel unwelcome, just frustration with so many channels to manage with
so few people.
I have been looking more at Edge motion detection with the camera as first
level of analysis to also offload detection workload.
Steve

**Comment by ASerbinski** [comment]
Ok, fair enough on all accounts.
I do tend to find user forums a lot more challenging to deal with due to the abundance of.. I guess users, but I'll see what I can do using that and slack.

@SteveGilvarry : I am currently researching the requirements for this feature, and will be in touch as soon as I have a reasonable picture of what is involved. A Korean running a Chinese restaurant once asked me if I was Australian, but I'm about as far as you can get while still on the same planet.
