### ISSUE TITLE
Montage layout creation bug

### ISSUE THREAD

**Issue by klausseufzger** [ZoneMinder/zoneminder#2295]
I think i found a bug in the montage view layout selection.

I can't 100% reproduce the problem, but it happened to me, when i opened the montage window, didn't change anything, hit the "edit layout" button, entered the name "layout" for the layout and hit enter.
The layout with the name "layout" was created but then the "edit layout" button was not working anymore and i was not able to select any different layout. 

Looking in the mysql database i found the problem in the "MontageLayout" table.

There was the following entry:
```
*************************** 6. row ***************************
       Id: 6
     Name: layout
Positions:
```

After I manually deleted this row everything worked find and when i changed the layout I was able to save and modify and select a different one.

This is how a working layout looks like:
```
*************************** 6. row ***************************
       Id: 8
     Name: testlayout2
Positions: {"mId2":{"width":"320px","height":"240px","top":"0px","bottom":"0px","left":"0px","right":"0px","position":"relative","float":"left"},"mId4":{"width":"320px","height":"180px","top":"256px","bottom":"0px","left":"-320px","right":"0px","position":"relative","float":"left"},"mId5":{"width":"240px","height":"320px","top":"10px","bottom":"0px","left":"-291px","right":"0px","position":"relative","float":"left"},"mId6":{"width":"320px","height":"240px","top":"14px","bottom":"0px","left":"-262px","right":"0px","position":"relative","float":"left"}}
```

I think because of the empty "positons" section zoneminder got a problem.

As I said, i was able to reproduce it a few times, but I didn't find a way to always do so.

Additionally I think there should be a way to remove layouts.

My zoneminder version is 1.32.2 and this is my system:
root@zoneminder:/home/klaus# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by tedrudie** [comment]
Similar issue. Not able to edit montage layout. Saving it breaks layout function until manually removing the new entry from the table MontageLayout.

Cenos 7.6.1810
Zoneminder 1.32.3
