### ISSUE TITLE
No cgi-bin folder in /usr/share/zoneminder/www/ causes 404 on images requests

### ISSUE THREAD

**Issue by AnnoyingTechnology** [ZoneMinder/zoneminder#2306]
Minder Version (`zmaudit.pl -v`):**
1.30.4

**Are you using a development snapshot / git checkout?  If so, what is the latest commit? (`git rev-parse HEAD`):**
official package from debian repo

**Linux Distribution and Version (`cat /etc/os-release` or `cat /etc/redhat-release`):**
Debian 9.6

Hello, 

I'm using lighttpd, have configured `.php` to point to the fpm socket and `.pl` and `.cgi` to point to the perl interpretter. 
Issue is that I'm getting 404 errors on images because zoneminder is trying to access `/cgi-bin/nph-zms?mode=jpeg&scale=100&maxfps=30...` 
but the installer didn't create any cgi-bin folder in `/usr/share/zoneminder/www/` 

![screenshot from 2018-11-12 20-37-32](https://user-images.githubusercontent.com/5336824/48370973-f3990f00-e6ba-11e8-8ed4-946d9a45889a.png)

**Comment by knight-of-ni** [comment]
The installer doesn't create a cgi-bin folder, nor should a symlink exist under the webroot that points to the cgi-bin folder. Instead you need to create an alias in your lighttpd that points to the folder zms was installed to. I believe that location on Debian is the global cgi-bin folder, but I could be wrong.

In any case, this question is really a support question. It's not a bug in the sense that we can fix it by merging a change in our forum. Feel free to ask this question in our user forum or our slack channel. You are more likely to find someone there, rather then here, who might have gone down a similar path.
