### ISSUE TITLE
Customize home page OR get ZoneMinder stream link

### ISSUE THREAD

**Issue by sanaihoussem** [ZoneMinder/zoneminder#2311]
Hi everyone
Thanks for this amazing work all of you are doing :+1:  

So, I have installed zoneminder and well configured my camera so now I'm receiving the stream from it. That's awesome I'm happy :+1:  But that's not what I really need. 
I'm trying to find a way ow just to show the stream in the web page: how can I remove all other html components from the page ? he navbar, the links, etc .. I already downloaded the source code and I found the web folder. I know it is done with cakePHP but from reading the code, I think it is so difficult to do what I want to do easily :( So that's why I'm asking for our help 

Maybe you will suggest  for me to read the doc and notice that there is already a link that you can put in <img> like this one  : https://yourserver/zm/cgi-bin/nph-zms?scale=50&width=640p&height=480px&mode=jpeg&maxfps=5&buffer=1000&&monitor=1&auth=b54a589e09f330498f4ae2203&connkey=36139 but I already tried and it doesn't really work for me.

Ps: I'm working in local network: my device which provides RTSP stream and my laptop are connected with local network 

SO, what I'm I asking for is :
1. Either cleaning the code so I can remove all things that I don't need and let just transforming RTSP to http view ( monitor display ) 
2. OR making the link provided in the [doc](https://zoneminder.readthedocs.io/en/latest/api.html) working :( 

Thank you all in advance 
Please help

**Comment by knight-of-ni** [comment]
This is not a bug report but a request for support.
Please use our user forum or slack channel. They are set up exactly for this kind of request.
