### ISSUE TITLE
GPU processing for ffmpeg and jpeg manipulations

### ISSUE THREAD

**Issue by dinskuns** [ZoneMinder/zoneminder#2312]
This is a repeated issue, copy above

This is really more a feature request/enhancement than a bug or issue:

eventually, Zoneminder should allow compilation with certain flags to permit utilization of GPU's to perform ffmpeg or jpeg transformations hence providing a much better performance than CPU while freing this one for other CPU related tasks (perl & php scripts, SQL database, etc)

I am not sure if this should be done at the component level (ffmpeg, libjpeg-turbo, etc) or at the top level (zm daemons)

**Comment by knight-of-ni** [comment]
You should only file an issue if you found a bug.  Feature and enhancement requests, general discussions and support questions should occur in one of the following areas:

- The [ZoneMinder-Chat Slack channel](https://zoneminder-chat.herokuapp.com/)
- The [ZoneMinder Forum](https://forums.zoneminder.com/)

**Do not post feature or enhancement requests, general discussions or support questions here.**
