### ISSUE TITLE
events are out of order.

### ISSUE THREAD

**Issue by aaronsta1** [ZoneMinder/zoneminder#2317]
my events are happening out of order and sometimes shown on different cameras.

say i have event 105 on camera one, if i do a gapless events playback and view the alarm, it will switch to camera two on  event 102 after 105 has completed playing. if i keep going it might go to 103 on camera 2 104 on camera one BEFORE the alarm happened, then back to 106.. 

i never had this before in previous versions.

**Comment by connortechnology** [comment]
We need to know how you are getting to the events list.  When you view a list of events, it basically makes a filter and passes that around in the URL.  It sounds like your list is losing the monitor specification.  

So we need to know where you are clicking to get to the initial event view.  Then perhaps the contents of the url bar which will give us the filter that it is using.

**Comment by aaronsta1** [comment]
just click on the monitor feed then click on past events.. then when you play back on gapless events it doesnt always choose the next event from that camera when it gets to the end.
