### ISSUE TITLE
Only one monitor with h264 Decoder on Raspberry PI

### ISSUE THREAD

**Issue by Mario-F** [ZoneMinder/zoneminder#2318]
Have an issue using 1.32.2 on RPi with 2 ffmpeg/RTSP h264 Streams attached.
From what i found out is ffmpeg on RPi using h264_mmal hardware decoder by default, but this seems (from my understanding) limited to only one decode at a time.
So zm trying to start capture with ffmpeg using h264_mmal on the second monitor and terminates.

I didnt find out how to tell ZM using h264 (software) decoder on the second Monitor.
Manually capturing with ffmpeg on commandline works fine with h264 decoder on input.

Possible Solution: Fallback to software decoding if hardware decoding fails.

**Comment by connortechnology** [comment]
I have had mine doing 4, so I don't think there is a hard coded single stream limit.
If opening the codec fails, it SHOULD fallback to software.  I will have to review the code again.  
One thing that is required for this is when you go into rasp-config and set the ram split, the gpu needs all the ram it can get.
