### ISSUE TITLE
purgewhenfull not working.

### ISSUE THREAD

**Issue by aaronsta1** [ZoneMinder/zoneminder#2320]
i have it set to 95% but my drive just hit 98% and when i run the filter manually it shows zero events.
i have the fast delete unchecked.

it doesnt seem to be working.. 

could it be because i have 2 drives??

![2](https://user-images.githubusercontent.com/10490149/48922758-cc320700-ee5d-11e8-9d18-ded583107fd9.png)

**Comment by connortechnology** [comment]
Yes.  How it is supposed to know which drive you are concerned with?  

Duplicate the filter, and add a Storage Area line to each filter for each storage area.

**Comment by aaronsta1** [comment]
ok thanks, i figured PWF was a global thing and just ran for all listed storage drives..
