### ISSUE TITLE
1.32 upgrade high CPU usage

### ISSUE THREAD

**Issue by mfauvain** [ZoneMinder/zoneminder#2332]
Hi, after upgrade to 1.32.2 CPU usage jumps (was around 1 now around 3). To reduce CPU I've set all monitors in B&W instead of 24b Color and CPU usage is better but still much higher than 1.30. Anyone with same problem?

EDIT : changing stream to (lower res) sub stream helped CPU (back to around 1). My mistake. Thank you for the massively useful zoneminder.

**Comment by connortechnology** [comment]
Turn off zmaudit.  It is more intensive and also more not required.

**Comment by connortechnology** [comment]
Also 24bit colour will make your cpu not use SSE instructions, which is slower.  It will use more ram, but less cpu.  Use 32bit.

**Comment by mfauvain** [comment]
Thank you very much, moving to 32bit lowered CPU usage I am now below 1 with 12 cams.. Excelent work. thx
