### ISSUE TITLE
Event delete API seems broken

### ISSUE THREAD

**Issue by pliablepixels** [ZoneMinder/zoneminder#2340]
**Describe Your Environment**
- Version of ZoneMinder: 1.32.3
- How you installed ZoneMinder: Doesn't matter
- Full name and version of OS: Ubuntu 18

**Describe the bug**

The API for Event Delete seems to have the following issues:

~~1. Doing a delete results in a ` web_php[15282]: FAT [Event 302794 Not found]` for any event that we try and delete using the API~~ (unrelated to this issue and was specific to how my app refreshes)

2. If `OPT_FAST_DELETE` is disabled (which I think is the default now), the actual event files never get deleted.

**To Reproduce**

`curl -XDELETE http://server/zm/api/events/<event>.json` 

**Debug Logs**

```
none
```

**Comment by connortechnology** [comment]
It's true, the api does not implement file deletion.

I wonder if we could get away with:
require_once(/includes/Event.php);
new Event($event)->delete();
