### ISSUE TITLE
how are zones order processed?

### ISSUE THREAD

**Issue by aaronsta1** [ZoneMinder/zoneminder#2344]
what order are the zones processed? are they by name? or size? or internal number when created? 

i have an active zone with a preclusive zone ontop of it.
the active zone has a threshold of 25 and the preclusive 150.
each one has a 3/3/2 area.. basically the default preset.

i live on a corner and this camera looks out to the street, this is to keep car headlights from causing an alarm, but still be able to detect people.. 

the issue is, as soon as the car goes around the corner i get a 1 frame alarm, then the preclusive kicks in and it stops the alarm for the next few frames.

how do i make the preclusive go first?

also ive tried to use the min/max threshold in active to do the same thing, but it didnt work at all.. even tho it says the overload is blocking frames in the log, the alarm still goes off when its done.

**Comment by knight-of-ni** [comment]
When you opened this issue, you were presented with a template that explained this forum is for gub reports only and where to go for support requests. Please follow those instructions....

**THIS FORUM IS FOR BUG REPORTS ONLY**

Do not post feature or enhancement requests, general discussions or support questions here.

Feature and enhancement requests, general discussions, and support questions should occur in one of the following areas:

- The [ZoneMinder-Chat Slack channel](https://zoneminder-chat.herokuapp.com/)
- The [ZoneMinder Forum](https://forums.zoneminder.com/)
