### ISSUE TITLE
Zone area does not update when entering coordinates manually

### ISSUE THREAD

**Issue by wdizzle** [ZoneMinder/zoneminder#2352]
In order to submit a bug report, please populate the fields below. This is required.

**Describe Your Environment**
- Version of ZoneMinder: 1.32.3
- How you installed ZoneMinder: PPA
- Full name and version of OS: Unbuntu server 18.04LTS

**Describe the bug**
I noticed this issue while upgrading from ZM 1.30 to 1.32.3 today. To make things easier to transfer, I decided to keep both installations going for a bit while I transfer my zones from the old to the new installation. I figured it would be easiest to re-create the zones by simply adding the number of coordinates first and then typing in their values in manually. After entering in the coordinates the zone resizes on screen as it should but if you look at the zone area field it will still show 100. If you drag any one of the points with the mouse, it will instantly change to the correct value. 

**To Reproduce**
1. Go to Zones for any of your cameras
2. Click Add New Zone
3. Select your preset first, if you don't do this, it will show a crazy value like 1474560
![zmbug1](https://user-images.githubusercontent.com/45977386/50175588-255d5100-02cb-11e9-88c3-c64c0d8fa40b.JPG)
4. After selecting your preset, verify that zone area now shows 100
6. Begin entering in your coordinates by changing the values manually. You will see the red zone area update on screen as you edit each point.
7. Witness the Zone area stay at 100
![zmbug2](https://user-images.githubusercontent.com/45977386/50175597-2e4e2280-02cb-11e9-9b5e-278631b3b98c.JPG)
8. Once you have all your points added, take your mouse and move any one of the points slightly.
9. You will see the value change to some crazy number again!
10. To work around this bug, you'll have to Save and then click the zone area to edit again.
![zmbug3](https://user-images.githubusercontent.com/45977386/50176138-994c2900-02cc-11e9-88ba-a50fc2c14282.JPG)
11. Back in the zone editor, drag any of your points again slightly, and Zoneminder will FINALLY enter in the correct zone area value.

**Expected behavior**
I should be able to enter in my zone coordinates manually. The zone area field should update automatically whenever anything on this screen is changed.  Any value larger than 100 should not be allowed and trigger some type of error or warning. 

This bug is not a show stopper as it can be worked around but its awfully annoying to work around. If you do not fix the values for zone area the zones will not trigger any alarm events until you correct it. 

**Debug Logs**
```

<insert debug logs here, please make sure they are within the ``` quotes so they are formatted properly>

```

**Comment by knight-of-ni** [comment]
Closing, since this was fixed in #2372
