### ISSUE TITLE
Invalid UE golomb code

### ISSUE THREAD

**Issue by zhuykovkb** [ZoneMinder/zoneminder#2358]
I broke my production with one of the latest update.

Version https://github.com/ZoneMinder/zoneminder/commit/c4bf67b06371a2510d083c8b7e1bc81b9df4b7b1 worked perfectly. But i decided to upgrade my zoneminder to the latest commit 6eb7892fc758a098f6ecd0b62ae505b9744691e2 and all cameras goes down (see attachment). In the LOG i see many WARN like as "Invalid UE golomb code"(see attachment).
Help me, please =)

I build zm with that  [Dockerfile](https://github.com/ZoneMinder/zmdockerfiles/blob/master/development/ubuntu/xenial/Dockerfile).
![war](https://user-images.githubusercontent.com/8007038/50335739-50d77a00-051d-11e9-8524-741b4beb43dc.png)
![cam](https://user-images.githubusercontent.com/8007038/50335740-51701080-051d-11e9-9cb8-f311c393fc4a.png)

**Comment by zhuykovkb** [comment]
i'm afraid the problem lies elsewhere. I've opened brower console and see, that all links on the page points to http proto instead of https (see attachment).
![http](https://user-images.githubusercontent.com/8007038/50336982-ba0cbc80-0520-11e9-9582-7d3f1b787262.png)

tell me, please, how zm understand which protocol use a client? i'am using nginx before apache zoneminder, maybe i forgot to set header in proxy request?
![nginx](https://user-images.githubusercontent.com/8007038/50337069-153eaf00-0521-11e9-8276-841132428e32.png)

**Comment by connortechnology** [comment]
When figuring out whether to use http or https, we look first for if we are using https, then in the HTTP_X_FORWARDED_PROTO header.

Alternatively, you can enter a Server in options->Servers and assign it to your monitors and it will use whatever you enter in there.

**Comment by knight-of-ni** [comment]
As a side note, see #2341 if you don't want to see those golomb code messages in your logs.

**Comment by zhuykovkb** [comment]
hmm..okey, i set ZM_LOG_FFMPEG to 0 and no more lines in log. ok. but i have the trouble with using ssl. why all links on the page points to http proto instead of https and port 80, instead of 443?
![httplinks1](https://user-images.githubusercontent.com/8007038/50402823-9bb9f180-07aa-11e9-88b5-91202b133af2.png)

**Comment by zhuykovkb** [comment]
> When figuring out whether to use http or https, we look first for if we are using https, then in the HTTP_X_FORWARDED_PROTO header.
> 
> Alternatively, you can enter a Server in options->Servers and assign it to your monitors and it will use whatever you enter in there.

okey. can you explain why links, look at previous my post, in the firebug (browser dev tool) points to http://zm.beget.ru:80 instead of httpS://zm.beget.ru?

**Comment by connortechnology** [comment]
I believe I already did. You aren't setting a header correctly.  You can work around it by explicitly setting it in a server entry.

**Comment by zhuykovkb** [comment]
> I believe I already did. You aren't setting a header correctly. You can work around it by explicitly setting it in a server entry.

i'm sorry, but i don't think i'm setting a header correctly. I made the screenshot in debug mode
![debug](https://user-images.githubusercontent.com/8007038/50493539-3d517500-0a2f-11e9-8bbe-b44793b182a4.png)

can u tell me what i'm doing wrong?

**Comment by zhuykovkb** [comment]
i solved my problem.
```
proxy_set_header X-Forwarded-Port 443;
```
