### ISSUE TITLE
Misspelling in Option help for ZM_Rand_Stream

### ISSUE THREAD

**Issue by jimender2** [ZoneMinder/zoneminder#2369]
**THIS FORUM IS FOR BUG REPORTS ONLY**

Do not post feature or enhancement requests, general discussions or support questions here.

Feature and enhancement requests, general discussions, and support questions should occur in one of the following areas:

- The [ZoneMinder-Chat Slack channel](https://zoneminder-chat.herokuapp.com/)
- The [ZoneMinder Forum](https://forums.zoneminder.com/)

Docker related issues should be posted here: https://github.com/ZoneMinder/zmdockerfiles

In order to submit a bug report, please populate the fields below. This is required.

**Describe Your Environment**
- Version of ZoneMinder [release version, development version, or commit]
- How you installed ZoneMinder [e.g. PPA, RPMFusion, from-source, etc]
- Full name and version of OS

**If the issue concerns a camera**
- Make and Model
- frame rate
- resolution
- ZoneMinder Source Type:

**Describe the bug**
The Help page says "Some browsers can cache the streams used by ZoneMinder. In order to prevent his a harmless random string can be appended to the url to make each invocation of the stream appear unique." but it should say "Some browsers can cache the streams used by ZoneMinder. In order to prevent this a harmless random string can be appended to the url to make each invocation of the stream appear unique."

**To Reproduce**
1. Go to Images options
2. Click on the help button
3. See error

**Expected behavior**

**Debug Logs**
```

<insert debug logs here, please make sure they are within the ``` quotes so they are formatted properly>

```

**Comment by knight-of-ni** [comment]
Feel free to send us a PR fixing the spelling mistake.

**Comment by knight-of-ni** [comment]
Nice work. You are well on your way to contributing back to projects that interest you.
