### ISSUE TITLE
New Web UI functionality regressed from 1.30

### ISSUE THREAD

**Issue by madscientist159** [ZoneMinder/zoneminder#2386]
The new Web UI introduced in 1.32 has several regressions in terms of usability versus the old 1.30 UI.

Just from a quick glance:
 * Font size is at least double / triple of what it was.  This means I now have to start scrolling on some fairly large monitors where scrolling was never needed before.
 * The new left-tabbed interface assumes widescreen (tablet?) devices.  It is inefficient to use with a mouse and keyboard or with 4:3 monitors (yes, these are still found and preferred in professional setups)
 * Monitors no longer pop up in their own new windows.  This makes firing up mutiple monitors on different screens slower than before (right click, open in new window, select new window, drag vs. click once and drag the popup).

Is there an alternate skin that more closely mimics the features and functionality of the old 1.30 interface?  So far I am less than impressed with this new one, it seems designed for a tablet more than a PC and not exactly a professional level product.

**Comment by knight-of-ni** [comment]
A bug report is something that describes a flaw in the software that was not intended. What you have written does not describe a bug nor a regression. Let's call it what it is. It's your opinion of the new look. That's not a bad thing in and of itself.

We certainly understand that not everyone is going to like change, and we also are willing to make improvements along the way. However, this is not the place to discuss the popularity of certain features of the software. 

Feel free to discuss this with us and the user base in our Slack channel or our user forum. That is where a discussion like this needs to occur. If anything specific comes out of it, then we can add it to our punchlist.
