### ISSUE TITLE
WSOD when clicking '8 hour' in montage review

### ISSUE THREAD

**Issue by joshuacox** [ZoneMinder/zoneminder#2400]
**Describe Your Environment**
- Version of ZoneMinder [release version, development version, or commit]

v1.32

- How you installed ZoneMinder [e.g. PPA, RPMFusion, from-source, etc]

https://github.com/QuantumObject/docker-zoneminder

- Full name and version of OS

docker image is based on ubuntu 16.04

**If the issue concerns a camera**
- Make and Model
Dlink DCS-934L
- frame rate
30
- resolution
640x480
- ZoneMinder Source Type:
remote
**Describe the bug**

If I click on the '8 hour' button in montage review I get a white screen of death  URL looks like this:

https://zm.example.com/zm/index.php?view=montagereview&fit=1&minTime=2019-01-08T01:25:26&maxTime=2019-01-08T09:25:25&current=2019-01-08%2008:55:18&displayinterval=1000&live=0&scale=1&speed=1

**To Reproduce**
1. Go to 'montage review'
2. Click on '8 hour'
3. WSOD

**Expected behavior**

to be able to scrub through the past 8 hours like I can when I click on 1 hour

**Debug Logs**
```
Starting pre-service scritps in /etc/my_init.d
*** Running: /etc/my_init.d/startup.sh
already configured.
starting rc.local scritps
Booting runit daemon...
Process runsvdir running with PID 153
```

zm.log is zero bytes in /var/log/zm:

```
root@7e5c56c02cf9:/var/log/zm# ls -alh
total 12K
drwxr-xr-x 1 www-data root   4.0K Jan  7 11:31 .
drwxrwxr-x 1 root     syslog 4.0K Nov 20 20:53 ..
-rw-r--r-- 1 root     root      0 Jan  7 11:31 zm.log
```

**Comment by connortechnology** [comment]
A white screen typically means that php crashed. Check your apache logs.  It could be running out of memory.  Default php config typically limits ram use to 128MB.  You may have to increase this.

**Comment by joshuacox** [comment]
increasing php memory limit, closing for now
