### ISSUE TITLE
Local camera problem (tw68)

### ISSUE THREAD

**Issue by nickmcgill** [ZoneMinder/zoneminder#2405]
I am unable to access tw68 local cameras.

I think it's a logical error on line 955 of zm_local_camera.cpp

currently reads
    if ( (input.std != V4L2_STD_UNKNOWN) && vidioctl( vid_fd, VIDIOC_S_STD, &stdId ) < 0 )   {
and (I think) should read
    if ( (input.std != V4L2_STD_UNKNOWN) && (vidioctl( vid_fd, VIDIOC_S_STD, &stdId ) < 0) )   {

Unfortunately I am unable to compile the sources from the zip file

Zoneminder ver 1.32, Ubuntu 18.10

Thanks

Nick

**Comment by connortechnology** [comment]
I agree with your assessment that there should be more parenthesis there.  I have applied the fix.  You will have to upgrade to master release and let us know if it works.
