### ISSUE TITLE
Wrong path to filters.php

### ISSUE THREAD

**Issue by VeselaHouba** [ZoneMinder/zoneminder#2409]
**Describe Your Environment**
- Version of ZoneMinder [1.33.1]
- How you installed ZoneMinder [docker image from QuantumObject]
- Full name and version of OS [ubuntu bionic]

**Describe the bug**
Following message appears in logs whenever I try to save new filter. Filter is not saved.
```
web_php |   | 195 | WAR | No includes/actions/filter.php for action Save | /usr/share/zoneminder/www/index.php
```
**Workardound**
Symlinked 
```
ln -s /usr/share/zoneminder/www/includes/actions/{filters.php,filter.php}
```

**To Reproduce**
1. Open filters
1. Fill any name
1. Hit save

**Expected behavior**
Filter is saved

**Comment by connortechnology** [comment]
Fix committed.
