### ISSUE TITLE
Timestamp during event playback does not advance

### ISSUE THREAD

**Issue by merkur2k** [ZoneMinder/zoneminder#2426]
**Describe Your Environment**
- Version of ZoneMinder [release version, development version, or commit]
Git master from Jan 12 2019 (I do not have the exact commit). This issue is potentially several months old.
- How you installed ZoneMinder [e.g. PPA, RPMFusion, from-source, etc]
From source.
- Full name and version of OS
Ubuntu 16.04.3 LTS, Docker 17.12.0-ce

**Describe the bug**
The timestamp displayed at the bottom of the video when playing back an event does not change to reflect the current position in playback. Additionally, "extra" timestamps can be induced to overlay the video.

**To Reproduce**
1. Play back any event. The timestamp does not advance.
Additional steps to reproduce the "extra" timestamps:
1. Play back an event and let it reach the end (make sure the replay option is set to "none").
2. Move the progress bar back to somewhere prior to the end of the video (50% is good).
3. Observe a vertical "stack" of timestamps fill up the video window
![timestamps](https://user-images.githubusercontent.com/3111724/51431823-4fb07000-1be3-11e9-94ef-bfd11e2e4d85.PNG)

**Expected behavior**
The timestamp should change to match the current position that is being viewed in the event.
Additional timestamps should not be displayed when seeking via the progress bar.

**Debug Logs**
(nothing related is logged)

I am available on IRC for further discussion.

**Comment by SteveGilvarry** [comment]
Thanks for the report, I was already aware of the timestamp issue from another user. Appears to have been broken around Aug last year, but is a bit of a hack anyway. Looking at options in videojs to address it better.
