### ISSUE TITLE
ZM_FILTER_EXECUTE_INTERVAL help text and placement

### ISSUE THREAD

**Issue by rnveach** [ZoneMinder/zoneminder#244]
The help text says "saved filters" will be executed, but it doesn't mention anywhere that those filters have to have "run in background" checked when you save the filter.
This should be made more explicit in the help text, the mini-version and the more detailed version. To new people who don't know ZM's inner working, this missing explanation will cause confusion as to why the filter isn't being run automatically.

Also, slightly related, I think the "run in background" checkbox should be moved from the "save filter" section to the actual view of what the filter is (IE: "/index.php?view=filter"). It seems to me the option should always be visible when your viewing the filters and so its not accidentally overlooked during the save.
##

**Comment by SteveGilvarry** [comment]
I will check this and just do it, if it makes sense.

**Comment by rnveach** [comment]
Has this been implemented?
So issue will be closed even if it makes to implement it?

**Comment by connortechnology** [comment]
Filters have changed a lot since this.  Much of this has been addressed.
