### ISSUE TITLE
Camera memory display

### ISSUE THREAD

**Issue by rnveach** [ZoneMinder/ZoneMinder#245]
To help people understand the memory implications of adding a camera, the add/edit camera dialog should also display the amount of (shared) memory required for the camera to function properly, if enough information is there to calculate it correctly.
This will make people more aware of how the settings affect ZM's memory usage and if they need to modify their shared memory for ZM to function properly.
I don't think ZM should directly control the shared memory size, but people should be made aware it is needed when they add more, higher resolution cameras.

ZM memory formula: http://www.zoneminder.com/wiki/index.php/FAQ#What_does_a_.27Can.27t_shmget:_Invalid_argument.27_error_in_my_logs_mean.3F_and_my_cameras_won.27t_display_video_at_higher_resolutions.
"The size it requests is based on the following formula, ring buffer size x image width x image height x 3 (for 24 bit images) + a bit of overhead."

Another page that lists the total memory required for all cameras added, and that are running, would also be another benefit.
##

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
