### ISSUE TITLE
Weak Cross-site Resource Forgery(CSRF) Protection 

### ISSUE THREAD

**Issue by Loginsoft-Research** [ZoneMinder/zoneminder#2469]
**Describe Your Environment**
- ZoneMinder v1.33.1
- Installed from - ppa:iconnor/zoneminder-master 

**Describe the bug**
 `Try again` button in callback function - Whenever a CSRF check fails,a callback function is called displaying a fail message. Unfortunately there also exists an "Try again" button on the page, which allows to resend the failed request, making the attack successful.

**To Reproduce**
  
<img width="619" alt="csrf" src="https://user-images.githubusercontent.com/47003572/51709967-dc2cb980-204d-11e9-8f08-d139d7d2c95f.png">

**Expected behavior**
This allows an attacker to easily carry out the CSRF attack.
Normally users are not too technical to understand what CSRF failure message is & would generally click on "Try Again", themselves making the attack successful.

**Debug Logs**
```

None

```

**Comment by zentery** [comment]
What is it mean?
