### ISSUE TITLE
Open Redirection - export.php

### ISSUE THREAD

**Issue by Loginsoft-Research** [ZoneMinder/zoneminder#2474]
**Describe Your Environment**
- ZoneMinder v1.33.1
- Installed from - ppa:iconnor/zoneminder-master 

**Describe the bug**
The view `export`, while exporting an event file, redirects to the `Exportfile` parameter value without any check, leaving vulnerable to open redirection.

**To Reproduce**
  Affected URL :
http://localhost/zm/index.php?view=export&eid=&exportFile=http://bing.com&generated=1

   Payload used - `http://bing.com`

- Navigate to the Affected URL.
- Click on Download, it would redirect to the injected URL.

<img width="653" alt="redirect 1" src="https://user-images.githubusercontent.com/47003572/51711830-1cdb0180-2053-11e9-86fa-f8d3168fb87b.png">

<img width="647" alt="bing" src="https://user-images.githubusercontent.com/47003572/51711525-5cedb480-2052-11e9-801f-292218cc9bc4.png">

**Expected behavior**
- Sanitize input by creating a list of trusted URL's (lists of hosts or a regex).
- Force all redirects to first go through a page notifying users that they are going off of your site, and have them click a link to confirm

**Debug Logs**
```

None

```

**Comment by mnoorenberghe** [comment]
This was fixed by 02f09aad7f4ff50f1dd113c964f10d8e675da916
