### ISSUE TITLE
Montage Review GET /zm/null

### ISSUE THREAD

**Issue by armonica17** [ZoneMinder/zoneminder#2492]
**Describe Your Environment**
zoneminder-1.33.1-1.115.20190126gitg9956eae70.fc29.x86_64
RPMFusion
Fedora 29 server. Patched to latest.

Montage review fails to produce the stored video.

To reproduce:
Fire up a new VM. Two nics - one for local network, one for the camera network. Link to the appropriate network hardware. Load Fedora 29 server software. I'm using 8 gig of memory, 6 CPU, as a VM on my Threadripper mobo.
Follow instructions to load RPMFusion, set the signature key. Load vlc.
Continue on with the normal instructions found here - zoneminder.readthedocs.io/en/latest/installationguide/redhat.html
Fire up apache server.
Load the mysql database zm database with stored configuration data.
run zmupdate.pl to update the database. It will complain otherwise.
Allow zoneminder to capture data.
Hit montage review, 1 hour. Move the time selector over events. In the log file you'll see the index.php page being pulled up then:
192.168.122.1 - - [31/Jan/2019:21:05:37 -0500] "GET /zm/null?view=image&eid=669&fid=158&width=744&height=419 HTTP/1.1" 404 205
192.168.122.1 - - [31/Jan/2019:21:05:37 -0500] "GET /zm/null?view=image&eid=671&fid=43&width=744&height=419 HTTP/1.1" 404 205
192.168.122.1 - - [31/Jan/2019:21:05:37 -0500] "GET /zm/null?view=image&eid=670&fid=157&width=744&height=419 HTTP/1.1" 404 205
192.168.122.1 - - [31/Jan/2019:21:05:37 -0500] "GET /zm/null?view=image&eid=669&fid=186&width=744&height=419 HTTP/1.1" 404 205
192.168.122.1 - - [31/Jan/2019:21:05:37 -0500] "GET /zm/null?view=image&eid=671&fid=56&width=744&height=419 HTTP/1.1" 404 205

As soon as I saw /zm/null, I knew something was wrong. Ok, I screwed up the loading. Blew VM away, started all over again, same results.

Please let me know. I'll be happy to blow it all away and start all over again.

Thanks,
Rob

**Comment by SteveGilvarry** [comment]
Rob,
Close app is super picky about removing stuff from the template, it wants each section answered. Go figure but can imagine it would be frustrating you :-)

1.33 is the development stream so if you are installing in Production use 1.32.3. I think from zmrepo for RPM packages.
If you want to be on development that is fine, but stuff could be broke. The devs tend to be on Slack if you want to confirm someone else sees the issue and have a chat, or you could log in 1.33 area of the forum also.
