### ISSUE TITLE
Bandwidth change not working

### ISSUE THREAD

**Issue by zd59** [ZoneMinder/zoneminder#2493]
**Describe Your Environment**
-ZoneMinder version
GIT: https://github.com/ZoneMinder/ZoneMinder.git from 31.1.2019 13.46 GMT+1 with commit Isaac Connor "fix state changing/etc"
-ZoneMinder installation source
ZoneMinder installed from a GIT source, compiled & packed with adapted zoneminder.SlackBuild form slackbuilds.org WEB page

- Full name and version of OS
Slackware64-current, updated 31.1.2019, kernel 4.19.16 

**Describe the bug**
GUI click on "Bandwidth" button it happens one of below, by pure chance:
open a new window, & select other than current one closes the window, but there is no change
or  the complete current window is replaced with selecting a bandwidth, when selecting & click on "save", the window wipes and become white without a single character on it.
Than you have to restart GUI - open a startup page again

**To Reproduce**
1. Go to 'bandwidth'
2. Click on 'current bandwidth'
3. Scroll down to 'other than current'
4. Click on "save" button

**Expected behavior**
"save" button changes active bandwidth.

**Debug Logs**
```

 zm_debug.log.29074
```
02/01/19 12:07:14.833059 web_php[29074].DBG [View: options Request:  Action: ] at /var/www/htdocs/zm/index.php line 197
02/01/19 12:07:30.191570 web_php[29074].DBG [View: request Request: status Action: ] at /var/www/htdocs/zm/index.php line 197
02/01/19 12:07:32.903269 web_php[29074].DBG [View: bandwidth Request:  Action: ] at /var/www/htdocs/zm/index.php line 197
02/01/19 12:07:42.387154 web_php[29074].DBG [View: none Request:  Action: bandwidth] at /var/www/htdocs/zm/index.php line 197
02/01/19 12:07:42.387200 web_php[29074].WAR [No includes/actions/none.php for action bandwidth] at /var/www/htdocs/zm/index.php line 218

**Comment by mnoorenberghe** [comment]
I can reproduce this bug… it's probably due to the inline event handler changes.

**Comment by mnoorenberghe** [comment]
Now I'm thinking it was from dbe9817bc823225e3d00ea880fa0001c925b3d15.

**Comment by zd59** [comment]
Confirmed working.
Congratulate, fastest response and a solution.
