### ISSUE TITLE
Update Brazilian Portuguese translation

### ISSUE THREAD

**Issue by mgsantana** [ZoneMinder/zoneminder#2495]
**Describe Your Environment**
- ZoneMinder 1.32.3
- Installed from Debian repository.
- Debian GNU/Linux 9.7

**Describe the bug**
- The Brazilian Portuguese translation is out-dated.

**Expected behavior**
- To update the Brazilian Portuguese translation of ZoneMinder.

**Comment by SteveGilvarry** [comment]
Are you able to assist? All the translations are community supplied, so if you able to update it would help yourself and others.
You can edit it directly in GitHub
https://github.com/ZoneMinder/zoneminder/blob/master/web/lang/pt_br.php

**Comment by mgsantana** [comment]
Hello Steve,
    I'm already working on it! ;-)
    Regards,
    -- 
Marcelo Santana (aka msantana) <marcelo@msantana.eng.br>
4096R/89C55467: 88FB 5D63 ED02 3B5D 90D6  3A3E 8698 1CC9 89C5 5467

    On 2/2/19 2:09 AM, Steve Gilvarry
      wrote:
    
    
      
      Are you able to assist? All the translations are community
        supplied, so if you able to update it would help yourself and
        others.
        You can edit it directly in GitHub
        https://github.com/ZoneMinder/zoneminder/blob/master/web/lang/pt_br.php
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ZoneMinder/zoneminder","title":"ZoneMinder/zoneminder","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ZoneMinder/zoneminder"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SteveGilvarry in #2495: Are you able to assist? All the translations are community supplied, so if you able to update it would help yourself and others.\r\nYou can edit it directly in GitHub\r\nhttps://github.com/ZoneMinder/zoneminder/blob/master/web/lang/pt_br.php"}],"action":{"name":"View Issue","url":"https://github.com/ZoneMinder/zoneminder/issues/2495#issuecomment-459936326"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ZoneMinder/zoneminder/issues/2495#issuecomment-459936326",
"url": "https://github.com/ZoneMinder/zoneminder/issues/2495#issuecomment-459936326",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by mnoorenberghe** [comment]
Looking forward to the pull request but I'll close this for now since I don't think we need to track this as an issue.
