### ISSUE TITLE
Enable CSRF protection by default

### ISSUE THREAD

**Issue by mnoorenberghe** [ZoneMinder/zoneminder#2507]
I've been running with it on for years and never have problems, even using the API from HASS and zmNinja. We really should have it enabled by default to go with our other security fixes. I would suggest enabling it for everyone by default new installs and upgrades, but I would also be fine with just enabling it for new installs as a starting point to not potentially break compatibility. I think it's possible that the other security fixes will already break some compatibility so personally I'd rather do it at the same time and call this stuff out in release notes.

@SteveGilvarry, you were looking for things to help with. Maybe you're familiar with DB migrations / changing defaults?

**Comment by SteveGilvarry** [comment]
Yep can do a PR and we can discuss.
