### ISSUE TITLE
Add support for control of Amcrest cameras

### ISSUE THREAD

**Issue by cnighswonger** [ZoneMinder/zoneminder#2525]
**Describe Your Environment**
- Version of ZoneMinder: master branch

**If the issue concerns a camera**
- Make: Amcrest

**Describe the bug**
There has been [a control module for Amcrest cameras](https://forums.zoneminder.com/download/file.php?id=1878) floating around in the forums. I propose to bring it into line with the current version of Amcrest's HTTP API and at least ZM ver 1.30.x. This report is just to get the ball rolling and obtain an issue number assigned. Pull request will follow in the next few days.

**To Reproduce**
N/A

**Expected behavior**
PTZ, etc. control of Amcrest devices

**Debug Logs**
N/A

**Comment by knight-of-ni** [comment]
Closed via #2536
