### ISSUE TITLE
Extra events showing up with bogus data and no content

### ISSUE THREAD

**Issue by a-bali** [ZoneMinder/zoneminder#2539]
**Describe Your Environment**
- Latest version pulled from github
- from source in docker
- ubuntu xenial docker image

**Describe the bug**
I am getting extra events in the event list without no real data and with a negative timespan. See attached screenshot. Besides this, I am getting normal events perfectly too. This happens for all of my cameras.

**To Reproduce**
1. Go to Event list from anywhere
2. See extra events in event list
![image](https://user-images.githubusercontent.com/6281927/53120367-f759ee80-3551-11e9-912c-6072cd23f6f2.png)

**Expected behavior**
These events do not make any sense, they don't exist on disk and should not appear.

**Debug Logs**
There is nothing relevant in the logs (apart from zmfilter failing to process these actually non-existent events).

**Comment by connortechnology** [comment]
The (r) tells use that it has been re-created by zmaudit.  We would need debug logs from zmaudit.

Please note that you really don't need to run zmaudit. It is putting a lot of load on your server.

**Comment by a-bali** [comment]
This still happens on a fresh install. What does the * represent?

**Comment by connortechnology** [comment]
The * means archived. The r means that it was recovered by zmaudit.

Please note that I have just added support to the web ui to support cleaning logs by line count so if you run master, you will not need zmaudit anymore.

**Comment by connortechnology** [comment]
I should further note that for performance reasons, deleting from logs by line count is not efficient.  First we have to count how many lines there are, and that will hit every row in the db.  So be sure to keep the line count low.
