### ISSUE TITLE
Integrate camera testing into the TravisCI framework

### ISSUE THREAD

**Issue by kylejohnson** [ZoneMinder/ZoneMinder#254]
For each build, I want travis, after successfully building ZoneMinder, to do the following:
1. Insert test cameras of various formats (RTSP, HTTP and FFMPEG) into the monitors table along with default zones
2. Turn on ZM and run the cameras in modetect mode
3. Parse logs for errors.
4. Only pass the build if no errors are detected.

The goal here is to catch code which breaks camera compatibility early and not allow it in production.
##

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
