### ISSUE TITLE
File and curl camera sources simply do not work

### ISSUE THREAD

**Issue by rpdrewes** [ZoneMinder/zoneminder#2544]
**Describe Your Environment**
Zoneminder 1.32.3, 1.32.2, 1.33.x, and other versions affected
Installed via PPA and also tested with source installation
All OS versions believed affected (I tested on Ubuntu 16.04.5)

**If the issue concerns a camera**
File and curl sources affected. Not specific to camera model

**Describe the bug**
The file and curl camera sources incorrectly return 0 from Capture(). The other camera sources which work correctly (http, vlc, ffmpeg, etc.) return 1 from Capture() upon successfully getting a frame. By returning 0, the file and curl camera sources do not advance beyond the first buffer and zms never sees any data and never updates the web interface. After a little while of non-capturing the zmwatch kills the zmc and restarts it, and then it fails again in the same way after another while.

**To Reproduce**
Create a curl or file source camera. Try to monitor it. It will not work.

**Expected behavior**
You should see the image from the file or curl source. You will not see it.

**Debug Logs**
No logs. The file and curl sources just don't work and (I believe) have not worked for a very long time.

**Comment by knight-of-ni** [comment]
fixed via #2545
