### ISSUE TITLE
zmcontrol.pl processes left running after stop/restart of zoneminder

### ISSUE THREAD

**Issue by cnighswonger** [ZoneMinder/zoneminder#2555]
**Describe Your Environment**
- Version of ZoneMinder: 1.30.4
- How you installed ZoneMinder: PPA
- Full name and version of OS: Linux xyz 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

**If the issue concerns a camera**
Control module: Dahua.pm

**Describe the bug**
Restarting ZoneMinder does not result in termination of zmcontrol processes.

**To Reproduce**
1. Exercise any camera control function.
2. List zmcontrol.pl processes, note the PIDs
3. Stop/restart ZoneMinder
4. List zmcontrol.pl processes and compare PIDs with the list from step two.

**Expected behavior**
All processes spawned by ZoneMinder should terminate upon a stop or restart.

**Debug Logs**
```
root@dvr# ps -ef | grep zmcontrol
www-data  5396     1  4 13:11 ?        00:00:00 /usr/bin/zmcontrol.pl --id 2
root      5398 15318  0 13:11 pts/1    00:00:00 grep zmcontrol
root@dvr# service zoneminder restart
root@dvr# ps -ef | grep zmcontrol
www-data  5396     1  0 13:11 ?        00:00:00 /usr/bin/zmcontrol.pl --id 2
root      5594 15318  0 13:12 pts/1    00:00:00 grep zmcontrol
```

**Comment by connortechnology** [comment]
This shouldn't be too difficult to fix, just need to use zmdc.pl to startup zmcontrol.pl

**Comment by cnighswonger** [comment]
Thanks for the tip. I'll dig around and see about fixing it.
