### ISSUE TITLE
Deleting event deletes last event and not one clicked

### ISSUE THREAD

**Issue by kdhosting** [ZoneMinder/zoneminder#2579]
**Describe Your Environment**
- Version of ZoneMinder: 1.32.3
- How you installed ZoneMinder: PPA
- Full name and version of OS: Ubuntu 18.04
- Browser name and version (if this is an issue with the web interface):
Chrome

**Describe the bug**
When deleting events in the Feed page, only the top (last) event gets deleted regardless of which event is clicked. 

**To Reproduce**
1. Go to 'Console'
2. Click on any camera
3. Scroll down to list of events
4. Click 'X'
5. Observer error

**Expected behavior**
That only the event that is intended to be delete, gets deleted.

**Comment by connortechnology** [comment]
This has already been fixed in master.

**Comment by gaaf** [comment]
I could not find the fix in the master branch, so I created a fix myself for use in 1.32.3. It applies to master too. See PR #2660
