### ISSUE TITLE
H264 playback speed changes during gapless replay

### ISSUE THREAD

**Issue by j-marz** [ZoneMinder/zoneminder#2607]
**Describe Your Environment**
- v1.32.3
- iconnor PPA http://ppa.launchpad.net/iconnor/zoneminder-1.32/ubuntu
- Ubuntu 16.04.6 LTS 4.4.0-146-generic
- Firefox 66.0.3 (64-bit)

**Describe the bug**
The playback speed is not preserved during gapless events playback of H264 events. The new event always plays at 1x speed. Sometimes the next event doesn't auto play at all.

**To Reproduce**
1. Configure monitor to use FFMPEG with H264 camera passthrough for video writer
2. Create 2 or more saved events by forcing an alarm through motion or the forced alarm option
3. Playback the oldest event and set the replay option to `Gapless Events`
4. Increase the playback speed during video playback
5. The next video goes back to default playback speed

**Expected behavior**
The playback speed should be preserved during the playback of consecutive H264 events (gapless) to provide the same functionality of jpeg based event playback.

**Comment by ijarraki** [comment]
Fixed in 1.33/master. Go try.
