### ISSUE TITLE
It is not possible to set the orientation of a camera to 'Flipped Horizontally'

### ISSUE THREAD

**Issue by neillbell** [ZoneMinder/zoneminder#2609]
**Describe Your Environment**
- Version of ZoneMinder: 1.33.8~20190512121416-bionic
- How you installed ZoneMinder: ppa:iconnor/zoneminder-master
- Full name and version of OS: Ubuntu 18.04.02
- Browser name and version: Firefox 66.0.5, Chromium 73.0.3683.86

**Describe the bug**
It is not possible to set the orientation of a camera to 'Flipped Horizontally'. When this is attempted, the orientation automatically returns to 'Normal'.

**To Reproduce**
1. Click on camera configuration
2. Select the 'Source' tab
3. Select 'Flipped Horizontally' for the 'Orientation' control
4. Click 'Save'

**Expected behavior**
The camera should have its orientation flipped horizontally. It does not. If you visit the 'Source' tab on the camera configuration the 'Orientation' will have turned to 'Normal'.

**Debug Logs**
```
==> /var/log/zm/web_php.log <==
05/15/19 11:44:06.940497 web_php[12797].ERR [SQL-ERR 'SQLSTATE[01000]: Warning: 1265 Data truncated for column 'Orientation' at row 1', statement was 'UPDATE Monitors SET `LinkedMonitors` = NULL, `ServerId` = NULL, `AnalysisFPSLimit` = NULL, `MaxFPS` = NULL, `AlarmMaxFPS` = NULL, `V4LMultiBuffer` = NULL, `Protocol` = NULL, `Host` = NULL, `ControlId` = NULL, `ControlDevice` = NULL, `ControlAddress` = NULL, `AutoStopTimeout` = NULL, `TrackDelay` = NULL, `ReturnDelay` = NULL, `Options` = NULL, `Orientation` = 'horz', Triggers = '' WHERE Id=?' params:9] at /usr/share/zoneminder/www/includes/database.php line 158
```

**Apparent Cause**
The web interface uses the value 'horz' instead of 'hori' to indicate that a camera orientation should be flipped horizontally.

This can be seen here:
https://github.com/ZoneMinder/zoneminder/blob/74d9f4f1aaae736132296083effedcb734996309/web/skins/classic/views/monitor.php#L392

**Comment by connortechnology** [comment]
Good find!
