### ISSUE TITLE
Unable to Clear Logs

### ISSUE THREAD

**Issue by RXM307** [ZoneMinder/zoneminder#2620]
**Describe Your Environment**
- Version of ZoneMinder 1.33.9 20190524141652-xenial
- How you installed ZoneMinder PPA
- Full name and version of OS ubuntu 16.04 Xenial
- Browser name and version (Chrome Latest but affects others also)

**Describe the bug**
Unable to Clear Logs from the Log Option

**To Reproduce**
1. Go to Logs
2. Click on Clear
3. Click Refresh
4. Logs all still there and the below error message is Logged

**Expected behavior**
Purge existing Log files

**Debug Logs**
```
2019-05-26 21:23:42 | web_js |   | 9619 | ERR |   | Uncaught TypeError: Cannot read property 'isDisplayed' of undefined |   | zm/tools/mootools/mootools-more.js | 1
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
```

**Comment by jepide** [comment]
Same problem
