### ISSUE TITLE
Streaming through reverse proxy is not working correctly when using internal name resolution

### ISSUE THREAD

**Issue by jet-leeroy** [ZoneMinder/zoneminder#2626]
**Describe Your Environment**
- Version of ZoneMinder - 1.32.3
- How you installed ZoneMinder - not relevant
- Full name and version of OS - Debian stretch
- Browser name and version - All browsers

**Describe the bug**
When using a reverse proxy, the stream name is incorrectly named according to the server config.

Monitor.php function getStreamSrc 
$streamSrc = $this->Server() ...

If you are forwarding from an external domain, the internal server name may be different than the external internet URL name...so the function Server() must adhere to the HTTP forwarded rules to correctly determine the stream URL.

**To Reproduce**
Set up machine as proxy called proxy.home configured to proxy to zoneminder1.home and set the server name as if in multi server environment to zoneminder1.home in the config.

The console will behave correctly, but clicking on a feed will result in a broken link. If you inspect the element for the broken link, you will see it has referenced http://zoneminder1.home and applied a port 80 override (even if the proxy server is forwarding via https)

**Expected behavior**
The Server() method should respect the forwarding machine, and replace the Server URI with the correct forwarders name. In the example this should result in the feed getting the address https://proxy.home over the correct protocol

**Comment by tolland** [comment]
can you provide some example configs to demonstrate this...

**Comment by jet-leeroy** [comment]
Sorry

I cant find my credentials to re log on to this site...

I have literally given the line of code that needs to be changed, I'm 
not sure I can be more descriptive than that ?

If the URL is always going to default the current server name as part of 
the response ... then it will NEVER work from behind a proxy.. unless 
the proxy has overwrite or rewrite rules, which is a hack. When using 
the server name variable .. it MUST always be proxy aware, as this is 
the machine that is forwarding the traffic.

I've gone as far as to identify the bug, if you choose to ignore it or 
let it go stale .. that's on you guys .. I cant explain it any more 
clearly than that .. if that explanation needs more clarity ... then I 
give up..

**Comment by connortechnology** [comment]
This may or may not be address with a recent commit of mine.

**Comment by cedric-dufour** [comment]
I was affected by this issue too and can confirm it's fixed by https://github.com/ZoneMinder/zoneminder/commit/60cf4586da11c3922ae141817e0b3c4f11805e5f.
Thanks!
