### ISSUE TITLE
Create One Long Video

### ISSUE THREAD

**Issue by newburns** [ZoneMinder/ZoneMinder#263]
Using the filters to create a Video just creates multiple videos for each event.
Even if "All Events" or "Gapless Events" is selected.

Question is, how do you create a 20 minute video using 5 minute events?

**Comment by clipo1979** [comment]
You will have to manually specify the event Id for that script to work. If you only want a few events in one file then it would be easier to do it manually. This script was to perform a full dump of the day for of site archiving and also use a higher compression format.

**Comment by clipo1979** [comment]
You will have to manually specify the event Id for that script to work. If you only want a few events in one file then it would be easier to do it manually. This script was to perform a full dump of the day for of site archiving and also use a higher compression format.

**Comment by knnniggett** [comment]
This does not describe a bug, nor is it a feature request.

I do agree that this is one of many aspects of zoneminder that I would consider to be "rough", and could use some love.  However, we currently do not have the resources to spend time on this.  If anyone wishes to improve zoneminder in this area, a pull request would be welcome.
