### ISSUE TITLE
Storage not working properly on size limited tmpfs (1 folder = 2 storage pools)

### ISSUE THREAD

**Issue by BlueMax** [ZoneMinder/zoneminder#2636]
Zoneminder v1.32.3
Alpine Linux edge x86_64 (rolling release)

I've created a 128MB tmpfs storage for testing purpose. Its intended to use a larger tmpfs folder later.
`mount -t tmpfs -o nosuid,nodev,size=128M tmpfs /tmp/zonestorage`

The storage diskspace shown on the webui topbar lists two storages though.
- the 128MB limited folder
- and the underlying root partition (58%)

The purge filters won't kick-in and the storage runs full. 
It looks like it needs some additional sanity checks.

![zmstorage](https://user-images.githubusercontent.com/1403092/59151212-7c004800-8a2f-11e9-9bc2-214bb3c5b208.png)

**Comment by connortechnology** [comment]
You have to tell the purge filter which storage area to work on.

**Comment by connortechnology** [comment]
This is a valid complaint, which needs to be fixed...

**Comment by BlueMax** [comment]
That 2nd `default` storage pool (having the same name) seems not related to the tmpfs storage pool though. The tmpfs storage was created by editing the existing `default` entry.
I've removed `ZM_DIR_EVENTS=` and `ZM_DIR_IMAGES=` from `zm.conf`, re-setup the database from scratch and cleared all `storage` entries in webui but this one `default` storage (that seems to point to /var/lib/zoneminder/events here) seems always shown in topbar. Not sure though if that's an Alpine Linux specific issue.

**Comment by connortechnology** [comment]
ZM will n longer auto-add an entry for the default storage area in the header.
