### ISSUE TITLE
Stored Cross Site Scripting - Filters

### ISSUE THREAD

**Issue by joeylane** [ZoneMinder/zoneminder#2642]
- ZoneMinder version 1.32.3
- Installed from PPA (Ubuntu Xenial)
- Ubuntu 16.04 Xenial

The 'Filters' page in ZoneMinder 1.32.3 is vulnerable to stored cross site scripting due to improper input sanitation in the 'Name' field.  This is the latest version available in the Ubuntu 16.04 PPA.  Please see attached screenshots.

<img width="1423" alt="1" src="https://user-images.githubusercontent.com/7573003/59644743-e30ab480-9133-11e9-950c-93eab20fd308.png">
<img width="1434" alt="2" src="https://user-images.githubusercontent.com/7573003/59644744-e30ab480-9133-11e9-8d5f-bd3a68c01b59.png">

1. Go to the "Filters" page.
2. In the "Name" field paste in a javascript payload such as "<script>alert('Vulnerable')</script>"
3. Refresh the page to verify that the payload executes and remains stored through browser sessions.

Expected behavior:
The user input fields should be sanitized.  Special characters should be limited or escaped to prevent injection of malicious code.

**Comment by connortechnology** [comment]
This has already been fixed in master.

**Comment by rakeshsv** [comment]
> This has already been fixed in master

Please can you give commit #

**Comment by galaktipus** [comment]
> This has already been fixed in master.

Can we get a commit please?

**Comment by SteveGilvarry** [comment]
Do you one better the original issue and closing commit. https://github.com/ZoneMinder/zoneminder/issues/2455
