### ISSUE TITLE
image fetch is broken

### ISSUE THREAD

**Issue by cjk32** [ZoneMinder/zoneminder#2654]
**Describe Your Environment**
- zone minder 1.32.3
- installed via FreeBSD ports system
- FreeBSD 11.2-RELEASE-p11 (GENERIC)

**Describe the bug**
Web requests that fetch an image, e.g,
http://${host}/index.php?view=image&fid=1&eid=11&show=analyse
fail.  The returned data starts with a PHP warning:

Notice: ob_end_clean(): failed to delete buffer. No buffer to delete in /usr/local/www/zoneminder/views/image.php on line 251

Warning: Cannot modify header information - headers already sent by (output started at /usr/local/www/zoneminder/views/image.php:251) in /usr/local/www/zoneminder/views/image.php on line 252

Warning: Cannot modify header information - headers already sent by (output started at /usr/local/www/zoneminder/views/image.php:251) in /usr/local/www/zoneminder/views/image.php on line 257

**To Reproduce**
1. Find a URL that should fetch a captured image, e.g.,
http://${host}/index.php?view=image&fid=1&eid=11&show=analyse
2. Fetch the URL,
3. Observe PHP warnings followed by the image data

The issue goes away with,
```
--- /usr/local/www/zoneminder/views/image.php.orig`      2019-07-06 21:52:38.864686000 +0100
+++ /usr/local/www/zoneminder/views/image.php   2019-07-06 21:52:53.981086000 +0100
@@ -247,8 +247,6 @@
 if ( $errorText ) {
   Error($errorText);
 } else {
-  # Clears the output buffer. Not sure what is there, but have had troubles.
-  ob_end_clean();
   header('Content-type: image/jpeg');
   if ( ( $scale==0 || $scale==100 ) && ($width==0) && ($height==0) ) {
     # This is so that Save Image As give a useful filename
```

**Comment by knight-of-ni** [comment]
This was already fixed in commit 5098329d945b25e5a31cfc02f3862e3545ac40f5
