### ISSUE TITLE
"Notice: Undefined index: query in /usr/local/www/zoneminder/skins/classic/views/report_event_audit.php on line 222

### ISSUE THREAD

**Issue by cjk32** [ZoneMinder/zoneminder#2656]
Describe Your Environment

zone minder 1.32.3
installed via FreeBSD ports system
FreeBSD 11.2-RELEASE-p11 (GENERIC)

Describe the bug
The Audit Events Report page produces many warnings of the form,

Notice: Undefined index: query in /usr/local/www/zoneminder/skins/classic/views/report_event_audit.php on line 222

To Reproduce
(I think) with the events database to referencing files that do not exist, use the Audit Events Report page and set the date range to encompass everything.

The issue goes away with,
```
--- /usr/local/www/zoneminder/skins/classic/views/report_event_audit.php.orig   2019-07-07 21:28:44.542599000 +0100
+++ /usr/local/www/zoneminder/skins/classic/views/report_event_audit.php        2019-07-07 21:35:01.617783000 +0100
@@ -192,6 +192,7 @@
             )
           )
         );
+    parseFilter($ZeroSize_filter);
   }


```

**Comment by connortechnology** [comment]
good find, thanks
