### ISSUE TITLE
MySQL 8 does not support password() anymore

### ISSUE THREAD

**Issue by EdwinGH** [ZoneMinder/zoneminder#2658]
I'm using Fedora 29 with MySQL Community 8.0 and Zoneminder 1.33.11 from https://zmrepo.zoneminder.com/f/29/x86_64/ 

I upgraded to Fedora 29 and then MySQL upgraded from 5.7 to 8.0 and Zoneminder stopped working. I got many SQL errors, and at least one trace leads me to the password function not supported by MySQL 8 anymore.
To fix the problem I tried to start clean (drop zm; run zm_create.mysql), but then the zm_create.sql script stops at the line with password('admin'):
ERROR 1064 (42000) at line 748: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('admin'),'',1,'View','Edit','Edit','Edit','Edit','Edit','Edit','','',0,1)' at line 1
I do see that my zm_create.sql script is created by MySQL 5.6 ("first line MySQL dump 10.13 Distrib 5.6.13, for Linux (i686)"), but I also see the password function in the current master branch...

I think I saw references here on GitHub about stronger password support, but clearly it is not working for me. What am I doing wrong?

**Comment by connortechnology** [comment]
Fixed by 5b896b5e5ca57fe9780e852d570a31c7a5b2ecfb
