### ISSUE TITLE
"NO DATA" Montage Review

### ISSUE THREAD

**Issue by opensprinklershop** [ZoneMinder/zoneminder#2690]
**Describe Your Environment**
- Version of ZoneMinder: release version 1.32.3
- How you installed ZoneMinder: zypper/rpm
- Full name and version of OS: SuSE Tumbleweed 2019-08-30
- MySql: Ver 15.1 Distrib 10.2.24-MariaDB, for Linux (x86_64) using readline 5.1
- PHP 7.3.8 (cli) ( NTS )
- php7 -m|grep mysql
mysqli
mysqlnd
pdo_mysql

**Describe the bug**
Montage Review showing "No Data" but zmNinja shows correct frames
https://forums.zoneminder.com/viewtopic.php?t=27953

I think this is the described mysqlnd problem
The problem is, that with SuSE Tumbleweed you can't swap mysqlnd to mysql

**To Reproduce**
see here https://forums.zoneminder.com/viewtopic.php?t=27953
or install SuSE Tubleweed with ZoneMinder

**Expected behavior**
Showing correct frames and not "No Data"

**Comment by connortechnology** [comment]
I recently fixed this in master.  Try running master.
