### ISSUE TITLE
Compiling zoneminder on FreeBSD on Raspberry Pi 3

### ISSUE THREAD

**Issue by BrianDScott** [ZoneMinder/zoneminder#2694]
**Describe Your Environment**
- Version of ZoneMinder [release version, development version, or commit]
zoneminder-1.32.3_2
- How you installed ZoneMinder [e.g. PPA, RPMFusion, from-source, etc]
FreeBSD port
- Full name and version of OS
FreeBSD-12.0 Release, arm64 (aarch64)
- Browser name and version (if this is an issue with the web interface)
N/A

**Describe the bug**
The Clang c++ compiler does some aggressive optimisation even when told not to inline code. This causes the code to not compile.

**To Reproduce**
Steps to reproduce the behaviour:
Attempt to build zoneminder port on FreeBSD on arm64.

**Expected behavior**
Compiled code.

I have submitted these patches to the FreeBSD zoneminder port maintainer but they suggested that the upstream project might also be interested in them.

[patch-src_zm_mem_utils.h.txt](https://github.com/ZoneMinder/zoneminder/files/3567916/patch-src_zm_mem_utils.h.txt)
[patch-src_zm_image.cpp.txt](https://github.com/ZoneMinder/zoneminder/files/3567918/patch-src_zm_image.cpp.txt)

Sorry but I'm not proficient at git to produce a pull request.

**Comment by connortechnology** [comment]
Thanks for the patch.  

We are definitely interested in making ZM work on as many systems as possible.
