### ISSUE TITLE
Error in deleting through event list

### ISSUE THREAD

**Issue by krejler** [ZoneMinder/zoneminder#2700]
**Describe Your Environment**
- Version of ZoneMinder: zoneminder_1.33.14~20190905114845
- How you installed ZoneMinder: apt-update from zoneminder 1.32.3-bionic
- Full name and version of OS: Ubuntu 18.04.3 LTS Container on proxmox
- Browser name and version: Both Internet explorer and google chrome

**Describe the bug**
When I try to delete events from the events list i'll get an "HTTP ERROR 500" ending up on: http://ip-address/zm/index.php?view=events&page=1&filter%5BQuery%5D%5Bterms%5D%5B0%5D%5Battr%5D=MonitorId&filter%5BQuery%5D%5Bterms%5D%5B0%5D%5Bop%5D=%3D&filter%5BQuery%5D%5Bterms%5D%5B0%5D%5Bval%5D=1

**To Reproduce**
1. Go to mainpage of zoneminder
2. Click on the number under events
3. Mark the events you want to delete
4. Hit delete and confirn you want to delete.
5. Ending up on "HTTP ERROR 500"

**Expected behavior**
I should delete the events i've marked and it worked before an update.

**Debug Logs**
Fatal error: Uncaught PDOException: There is already an active transaction in /usr/share/zoneminder/www/includes/Event.php:135 Stack trace: #0 /usr/share/zoneminder/www/includes/Event.php(135): PDO->beginTransaction() #1 /usr/share/zoneminder/www/includes/functions.php(442): ZM\Event->delete() #2 /usr/share/zoneminder/www/includes/actions/events.php(49): deleteEvent(Object(ZM\Event)) #3 /usr/share/zoneminder/www/index.php(216): require_once('/usr/share/zone...') #4 {main} thrown in /usr/share/zoneminder/www/includes/Event.php on line 135

**Comment by connortechnology** [comment]
This is already fixed.
