### ISSUE TITLE
Recent commit appears to have broken multi-port (waiting for available socket)

### ISSUE THREAD

**Issue by wjwoods** [ZoneMinder/zoneminder#2710]
Describe Your Environment
ZM v1.33.14 on Ubuntu 16.04 Server.  Installed from PPA. (zoneminder_1.33.14~20190919145844-xenial_amd64.deb)
Single server with no reverse proxy.

Describe the bug
commit 60cf4586da11c3922ae141817e0b3c4f11805e5f - Don't return a hostname when not in multi-server. Should prevent problems with reverse proxies

This commit appears to have broken multi-port in my installation.

Prior to this commit multiple http streams worked as expected -  {server IP}: {30000+Monitor ID}
After this commit, sessions are {server IP}:80  and receiving "waiting for available socket" on browser.

**Comment by connortechnology** [comment]
commit has been reverted
