### ISSUE TITLE
Hebrew translation not work OK but I fix it!

### ISSUE THREAD

**Issue by or-katz** [ZoneMinder/zoneminder#2712]
Hello,

the Hebrew translation in version that I install on Ubuntu 18.04.3 from here:
https://wiki.zoneminder.com/Ubuntu_Server_18.04_64-bit_with_Zoneminder_1.32.x_the_easy_way
not work. the encoding is not supported by modern browser. I attach new lang file for Hebrew that works, i convert it from the original file and change the encoding to UTF-8 that is now standard. the old encoding was iso-8859-8-i that not work properly on Chrome.
please use that file.

Thanks a lot!

Or

[he_il.zip](https://github.com/ZoneMinder/zoneminder/files/3639385/he_il.zip)

**Comment by connortechnology** [comment]
Thanks, I've merged it.
