### ISSUE TITLE
Unable to batch edit monitors' function 1.32.3

### ISSUE THREAD

**Issue by theonemcdonald** [ZoneMinder/zoneminder#2716]
**Describe Your Environment**
- Version of ZoneMinder: RELEASE
- How you installed ZoneMinder: PPA
- Full name and version of OS: Ubuntu 18.04

**Describe the bug**
When editing multiple monitors simultaneously, I am unable to batch edit these monitors' function. 

**To Reproduce**
1. Select multiple monitors.
2. Click edit.
3. Change function.
4. Click save.

**Expected behavior**
When clicking save, all cameras that were selected should have the new function applied.

**Debug Logs**
```

<insert debug logs here, please make sure they are within the ``` quotes so they are formatted properly>

```

**Comment by connortechnology** [comment]
I cannot reproduce this on current master.  Please update and confirm.
To update to latest master do:
sudo add-apt-repository ppa:iconnor/zoneminder-master
sudo apt-get update
sudo apt-get install zoneminder

**Comment by theonemcdonald** [comment]
Same, master branch seems to work. Closing.
