### ISSUE TITLE
CakePHP installation out of date (version 2.10.8)

### ISSUE THREAD

**Issue by dsl** [ZoneMinder/zoneminder#2733]
Development version, built from source.

The API is currently running using CakePHP version 2.10.8 (24th Feb 2018).

Issue #2685 mentions that enums are not properly handled.
This may be fixed by CakePHP version 2.10.14:
https://bakery.cakephp.org/2018/12/19/cakephp_21014_released.html

It's probably worth in the first instance upgrading CakePHP to the latest 2.10.x release (2.10.19), then following that up with an upgrade to the latest 3.x release, as that will require more refactoring.

**Comment by connortechnology** [comment]
I think for 1.34 we should update to 2.10.19 or whatever is current.  I do not expect it to address the enums issue.

**Comment by dsl** [comment]
Cool. I'll do that then, if you're happy with that plan?

**Comment by connortechnology** [comment]
Go for it.

**Comment by connortechnology** [comment]
Ping.  I am trying to finish up a few last things are release over the christmas holidays.  I don't require this for release, but if you want to get it done, now is the time.
