### ISSUE TITLE
Clicking group name in web UI does not show only that group

### ISSUE THREAD

**Issue by saliyaw** [ZoneMinder/zoneminder#2735]
**Environment**
- ZoneMinder release v1.32.3
- RPMFusion repo enabled, installed with 'yum install zoneminder'
- OS: CentOS Linux release 7.6.1810 (Core)
- Browser: Firefox 68.0.1 (64-bit), Google Chrome Version 77.0.3865.120 (64-bit)

**Describe the bug**
When clicking a group name shown in /zm/index.php and going to the montage view I am shown all cameras to which I have access rather than the group.

**To Reproduce**
1. Go to '/zm/index.php'
2. Click on the group name (displayed below the monitor name)
3. See all monitors not just those within the group clicked on

**Expected behavior**
I expect to only see monitors which belong to the group clicked on.

**Debug Logs**
```
no debug logs attached
```

**Comment by connortechnology** [comment]
Current master does not have this issue.
