### ISSUE TITLE
Cannot write to content dirs('events','images'). Check that these exist and are owned by the web account user

### ISSUE THREAD

**Issue by Malathi15** [ZoneMinder/zoneminder#2741]
I'm using Ubuntu 16.04 , I followed the steps from Easy Way: Debian Jessie. After completing all the steps when I open `http://ip/zm ` 
I got this message
 `Cannot write to content dirs('events','images'). Check that these exist and are owned by the web account user`
events and images directors are exist. Help me to solve this.

Thanks in Advance

**Comment by connortechnology** [comment]
sudo chown www-data:www-data -R /var/cache/zoneminder/
