### ISSUE TITLE
purgewhenfull or web delete does not work

### ISSUE THREAD

**Issue by gobris** [ZoneMinder/zoneminder#2742]
**Describe Your Environment**
- zoneminder 1.33.14
- Installed from PPA
- Ubuntu 14.04

**Describe the bug**
I have an extra disk for camera events storage called /kayit2
storage mounted as 
/kayit2/images /var/cache/zoneminder/images none defaults,bind  0 2
/kayit2/events /var/cache/zoneminder/events none defaults,bind 0 2

so /var/cache/zoneminder/events directory uses /kayit2/events folder by default.

Permissions on folder are www-data:www-data
Recording and playing functions works as it suppose to be.

Deleting a video (both from webgui or via purge script) does not work.(record deleted from db but not from dsik)
No errors thrown.

Here is output of manual purge command.

22-10-2019 11:37:38.408940 zmfilter_1[29018].INF [ZoneMinder::Event:373] [Deleting event 4752942 from Monitor 4 StartTime:2019-10-16 09:37:46 from /kayit2/events//4/2019-10-16/4752942]
22-10-2019 11:37:38.512931 zmfilter_1[29018].INF [ZoneMinder::Event:373] [Deleting event 4752943 from Monitor 23 StartTime:2019-10-16 09:37:49 from /kayit2/events//23/2019-10-16/4752943]
22-10-2019 11:37:38.574604 zmfilter_1[29018].INF [ZoneMinder::Event:373] [Deleting event 4752944 from Monitor 17 StartTime:2019-10-16 09:37:54 from /kayit2/events//17/2019-10-16/4752944]

**To Reproduce**
Running PurgeWhenFUll script or manually deleting a video stream from webgui creates this problem.

Additional info: Same configuration working fine with 1.29 version.
Updated the running version with ppa repository step by step.
Only error had so far is this delete issue.

**Comment by connortechnology** [comment]
Sounds like you have Options -> System -> OPT_FAST_DELETE checked.  Uncheck it.
