### ISSUE TITLE
Remote access - no recordings

### ISSUE THREAD

**Issue by joselito11** [ZoneMinder/zoneminder#2758]
zoneminder latest in docker.

I set up https via nginx proxy manager, but now I can not see recordings when I acces via domain. If I acces via IP I see recordings, but I want to see recordings remote

**Comment by connortechnology** [comment]
There is no information in this for us to help you.  It is not a bug in ZM, it is an error in your setup.
If you want help, then provide us some info.  Post your config, etc.
