### ISSUE TITLE
multiserver and ZM_CSP_REPORT_URI

### ISSUE THREAD

**Issue by Cramac** [ZoneMinder/zoneminder#2761]
Hello.
ubuntu 18.04.03 lts
zm 1.33.14

while working alone, everything was fine. Added another server and now online video shows only from one server. error in the log:

Attempt to fetch boolean value for ZM_CSP_REPORT_URI, actual type is string. Try running 'zmupdate.pl -f' to reload config.
--

having executed on the second server **zmupdate.pl -f**
begins to show online, but disappears from another.

**Comment by connortechnology** [comment]
You are running different versions of ZM. update them both.
