### ISSUE TITLE
PHP Parse error: syntax error, unexpected ')' in /usr/share/zoneminder/www/includes/functions.php on line 2594

### ISSUE THREAD

**Issue by Brunes** [ZoneMinder/zoneminder#2773]
Hi, after updating zoneminder I have error on my apache2 server

`PHP Parse error: syntax error, unexpected ')' in /usr/share/zoneminder/www/includes/functions.php on line 2594`

Can u look at this? 
Thanks.

**Comment by Brunes** [comment]
newest version (1.33.15~20191204.45-buster)

**Comment by connortechnology** [comment]
For now you can delete the entire html_radio function as it is only used in export functionality.  

I havn't been able to reproduce the problem here even using the same package as you.

**Comment by connortechnology** [comment]
I think we have a fix. Please update and let us know.

**Comment by Brunes** [comment]
Yeah, now it work correctly. Thanks!
