### ISSUE TITLE
online play h265

### ISSUE THREAD

**Issue by Cramac** [ZoneMinder/zoneminder#2781]
Hello.
how to watch online video in h265 ?

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '88221.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    title           : Zoneminder Security Recording
    encoder         : Lavf57.83.100
  Duration: 01:00:00.56, start: 0.000000, bitrate: 651 kb/s
    Stream #0:0(und): Video: hevc (Main) (hev1 / 0x31766568), yuvj420p(pc), 1920x1080, 650 kb/s, 10.83 fps, 20.42 tbr, 90k tbn, 90k tbc (default)
    Metadata:
      handler_name    : VideoHandler
At least one output file must be specified
```
![IMG_8062](https://user-images.githubusercontent.com/9798924/71013485-d296bf00-2101-11ea-8bff-2fb75129fe8b.png)

**Comment by connortechnology** [comment]
Most browsers can't play it. In zm switch codec to mjpeg. You can also set this in the monitor to be default

**Comment by Cramac** [comment]
if you put mjpeg in the codec, then there is nothing at all
![1](https://user-images.githubusercontent.com/9798924/71023181-3d9cc180-2113-11ea-98b6-f3147d40584d.png)
![2](https://user-images.githubusercontent.com/9798924/71023182-3e355800-2113-11ea-918a-d149ad420a9c.png)

**Comment by joelsdc** [comment]
Per your screenshot, you have selected *MP4*. You have to select *MJPEG*. 

You can see the codec selector on the top right corner of the GUI.

**Comment by Cramac** [comment]
...
> if you put mjpeg in the codec, then there is nothing at all
> ![2](https://user-images.githubusercontent.com/9798924/71023182-3e355800-2113-11ea-918a-d149ad420a9c.png)

**Comment by connortechnology** [comment]
You may actually have to consult your logs. We are not psychic.

**Comment by Cramac** [comment]
![Без названия](https://user-images.githubusercontent.com/9798924/71192078-aa8d9400-2298-11ea-96d1-31f16a858c2e.png)

**Comment by connortechnology** [comment]
You need to update.  I recently fixed a bug in zms that caused the mjpeg streaming to fail.

**Comment by Cramac** [comment]
updated, mjpeg shows, mp4 never seems

**Comment by joelsdc** [comment]
AFAIK the current way to stream H264 is MP4 and H265 is MJPEG
