### ISSUE TITLE
Intel graphic hwaccel

### ISSUE THREAD

**Issue by piotr-sikora-v** [ZoneMinder/zoneminder#2793]
My setup: Zoneminder v1.33.14 Ubuntu 18.04

I have working ffmpeg from my command line with hwaccel for transcoding
To working I need run ffmpeg with this arguments:
```ffmpeg  -hwaccel vaapi -hwaccel_device /dev/dri/renderD128  -hwaccel_output_format vaapi   -i udp://some.camera.ip:port/  -c:v h264_vaapi -f mpegts udp://127.0.0.1:10002/```
Everything works nice on my core i3-6100 (cpu only take 10% when stream is from hevc  2592x1944 vs more than 100% cpu without this flags)

How can I add this parameters to ZoneMinder?

**Comment by connortechnology** [comment]
Monitor -> Source -> DecoderHWAccelName = vaapi
restart the monitor.
You will need to add www-data to the video usergroup.
