### ISSUE TITLE
Monitor config option "Default Scale" does not work with "Scale to fit"

### ISSUE THREAD

**Issue by darktim** [ZoneMinder/zoneminder#2808]
- Version of ZoneMinder: v1.32.3, installed from http://ppa.launchpad.net/iconnor/zoneminder-1.32/ubuntu on Ubuntu/Disco

**Describe the bug**
I want to use the option "Scale to fit" when configuring a monitor in the misc-panel
Choosing "Scale to fit" does not change anything. If previous value was "3/4" it stays like that. (Same for other choices)

**To Reproduce**
1. Go to the config options for a monitor
2. Click on 'Misc"
3. Change "Default Scale" to 'Scale to fit'
4. Save
5. Reload to see that the value did not change

**Expected behavior**
I expect to have "Scale to fit" saved.

**Possible fix:
`alter table Monitors MODIFY DefaultScale VARCHAR(5) NOT NULL DEFAULT 100;`

After that the database can store "auto" as value which corresponds to "Scale to fit"

**Comment by connortechnology** [comment]
Already fixed in master.
