### ISSUE TITLE
Version 1.34.2 Release shows Version 1.34.1, triggering update popup - annoying

### ISSUE THREAD

**Issue by rossbcan** [ZoneMinder/zoneminder#2824]
Need to update zm_create.sql or zm_update-1.34.2.sql for correct version

**Comment by connortechnology** [comment]
Um, release 1.34.2 has the version file correct, and a zm-update.1.34.2.sql.  zm_create.sql doesn't reference any version #s.   SO not sure what the issue is here.

**Comment by rossbcan** [comment]
Well, zm_create.sql  has ZM_DYN_CURR_VERSION at 1.34.1 (should be 1.34.2?) and with a fresh git bulld from 1.34.2, the update zm window keep popping up til disabled. In addition, the GUI displays V1.34.1

I would expect, at latest release, no update window to popup and correct version to display in GUI 

I can work around this, up to you if issue and fix or not.

Regards;
Bill

**Comment by connortechnology** [comment]
zm_create.sql is a generated file.  You havn't updated it.  it is generated from zm_create.sql.in

**Comment by rossbcan** [comment]
have since updated my build to replace zm_create.sql (after config) with new zm_create.sql with some dir changes. My issue, not yours, sorry for trouble...
