### ISSUE TITLE
zmeventnotification don't start

### ISSUE THREAD

**Issue by stevaedrum** [ZoneMinder/zoneminder#2826]
ZoneMinder release version 1.34.1
installed ZoneMinder via RPMFusion
Zoneminder installed on Fedora server 30
Version of zmeventnotification is v5.4.1

I select in the option, OPT_USE_EVENTNOTIFICATION but zmeventnotification.pl don't start.
If I start with zmdc.pl start zmeventnotification.pl, zonemider crash (core-dump).

If I start zmeventnotification.pl by cmd it's working no crash of zoneminder.

**Comment by pliablepixels** [comment]
You should post this in the [zmeventnotification](https://github.com/pliablepixels/zmeventnotification) repo **with debug logs**
