### ISSUE TITLE
Add button doesn't work

### ISSUE THREAD

**Issue by cowanmax** [ZoneMinder/zoneminder#2827]
Hi guys!
Version of ZoneMinder 1.43.2, Ubuntu 18.04 LTS. I can't add cams. 
I see just _add_circle_ Add button and there is no reaction? What I need to do??

**Comment by connortechnology** [comment]
You havn't adjusted your apache config.  This must be an upgrade (you didn't say).  You might just have to restart apache, or you will have to modify it's config to match the one that would have come with zoneminder.

Here is an example of mine, pay attention to line 17.
.https://gist.github.com/connortechnology/9ca83f812d94b2777b93ad54ee45067e
.

**Comment by cowanmax** [comment]
Thanks for your reply but I use nginx with mariadb. The same?

**Comment by cowanmax** [comment]
I have deleted nginx, php, mysql and install LAMP. So now is works :) Many thanks!
