### ISSUE TITLE
ERR ['zmtelemetry.pl' exited abnormally, exit status 9]

### ISSUE THREAD

**Issue by andreafrati1969** [ZoneMinder/zoneminder#2868]
**Describe Your Environment**
- Version of ZoneMinder [release version, development version, or commit]
   ZoneMinder 1.35.0~20200302135155-eoan
- How you installed ZoneMinder [e.g. PPA, RPMFusion, from-source, etc]
   http://ppa.launchpad.net/iconnor/zoneminder-master/ubuntu eoan main
- Full name and version of OS
  Ubuntu 19.10 5.3.0-41-generic #33-Ubuntu SMP Fri Feb 14 17:26:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux  

**Describe the bug**
MySQL query require "'" delimiter for "function" column

**To Reproduce**
1. start zmtelemetry.pl
2. See error "DBD::mysql::st execute failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Function,Width,Height,Colours,MaxFPS,AlarmMaxFPS FROM Monitors' at line 1 at /usr/bin/zmtelemetry.pl line 252.
Can't execute: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Function,Width,Height,Colours,MaxFPS,AlarmMaxFPS FROM Monitors' at line 1 at /usr/bin/zmtelemetry.pl line 252"

**Expected behavior**
No error

**Debug Logs**
```

<insert debug logs here, please make sure they are within the ``` quotes so they are formatted properly>

```

**Comment by connortechnology** [comment]
Fixed by 7c066822f338fc80f9e5f20ce6390b5f712aad6f.  Will be in 1.34.6
