### ISSUE TITLE
Request: Retry ZM when DB goes down

### ISSUE THREAD

**Issue by rnveach** [ZoneMinder/ZoneMinder#287]
A few times now, when I either am trying to fix up my mysql database for another application or mysql gets upgraded through apt-get, ZM goes goes into stop mode when the DB is gone. I usually dont realize this and make the connection until I try to access ZM later.
Instead of ZM stopping completely, it should keep retrying to re-access the DB like every half an hour or so, or atleast have an option we can set for this.

**Comment by knnniggett** [comment]
If Service A depends on Service B, then Service A should stop, and remain stopped, if Service B stops. If service B starts back up, I do not agree that service A should automatically start back up on its own.  Ever.

That would require making an assumption that, in every single case, it is safe to ZoneMinder back up merely on the status of the mysql daemon.  But what if it isn't safe?  For example, what if I am in the middle of troubleshooting severe breakage? I get the mysqld started back up but I still don't yet have my event storage volume back online.  If zoneminder was started at this point, all the events would get deleted.

If you really want zoneminder to auto-start back up every time, then I recommend you write a cron job that does this.  It would be fairly easy to do. 

Another alternative would be to use health monitoring software to send you e-mail alerts, which would remind you to go start ZoneMinder back up (this is what I currently do).
