### ISSUE TITLE
Error loading user language files

### ISSUE THREAD

**Issue by KTownKnerd** [ZoneMinder/zoneminder#2876]
**Describe Your Environment**

- Version of ZoneMinder [release version, development version, or commit]
 1.35.0~20200304.140-buster

- How you installed ZoneMinder [e.g. PPA, RPMFusion, from-source, etc]
From the Zoneminder Repo (deb https://zmrepo.zoneminder.com/debian/master buster/)
- Full name and version of OS
Debian 10 Buster

**Describe the bug**
Upon updating to the current version of Zoneminder, I am now receiving multiple warnings of WAR	User language file lang/.php does not exist.	/usr/share/zoneminder/www/includes/lang.php	42
The errors began appearing after upgrading Zoneminder from 1.35.0~20200229.97-buster to 1.35.0~20200302.116-buster.
hard coding to $userLangFile=$prefix.'lang/en_gb.php' will stop the warning messages
Under Options LANG_DEFAULT it is set to en_gb

**Debug Logs**
```

<insert debug logs here, please make sure they are within the ``` quotes so they are formatted properly>

```

**Comment by connortechnology** [comment]
This was fixed by f0791c81184bc4cc558fe84205cec9b196c9f1ac
