### ISSUE TITLE
HAVE_DECL_MD5 set when build requires GnuTLS

### ISSUE THREAD

**Issue by rmackinnon** [ZoneMinder/zoneminder#2892]
**Describe Your Environment**
- Version of ZoneMinder [release version, development version, or commit]
tag:release-1.34

- How you installed ZoneMinder [e.g. PPA, RPMFusion, from-source, etc]
source

- Full name and version of OS
Gentoo, x86_64
gnutls-3.6.7-r1
libjwt-1.12.0[--without-openssl]
libmp4v2-2.0.0-r1

- Browser name and version (if this is an issue with the web interface)
N/A

**Describe the bug**
Building zm_rtsp_auth.cpp fails due to missing declarion of type ```MD5```, on line 145 inside the compiler flag if-elif-else check for ```HAVE_DECL_MD5```. Appears ```cmake/config.h``` is defining ```HAVE_DECL_MD5 1``` and haven't dug into why that is. Related to issue #1235 ?

**To Reproduce**
```
cd cmake
cmake ../
make all
```

**Expected behavior**
Completion of build

**Debug Logs**
```
localhost /usr/src/zoneminder/cmake # make clean
localhost /usr/src/zoneminder/cmake # make
Scanning dependencies of target zm
[  1%] Building CXX object src/CMakeFiles/zm.dir/zm_box.cpp.o
[  2%] Building CXX object src/CMakeFiles/zm.dir/zm_buffer.cpp.o
[  4%] Building CXX object src/CMakeFiles/zm.dir/zm_camera.cpp.o
[  5%] Building CXX object src/CMakeFiles/zm.dir/zm_comms.cpp.o
[  6%] Building CXX object src/CMakeFiles/zm.dir/zm_config.cpp.o
[  8%] Building CXX object src/CMakeFiles/zm.dir/zm_coord.cpp.o
[  9%] Building CXX object src/CMakeFiles/zm.dir/zm_curl_camera.cpp.o
[ 10%] Building CXX object src/CMakeFiles/zm.dir/zm.cpp.o
[ 12%] Building CXX object src/CMakeFiles/zm.dir/zm_db.cpp.o
[ 13%] Building CXX object src/CMakeFiles/zm.dir/zm_logger.cpp.o
...
<insert warnings about truncation and deprecations here>
[ 54%] Building CXX object src/CMakeFiles/zm.dir/zm_rtsp_auth.cpp.o
/usr/src/zoneminder/src/zm_rtsp_auth.cpp: In member function ‘std::__cxx11::string zm::Authenticator::computeDigestResponse(std::__cxx11::string&, std::__cxx11::string&)’:
/usr/src/zoneminder/src/zm_rtsp_auth.cpp:145:3: error: ‘MD5’ was not declared in this scope
   MD5((unsigned char*)ha1Data.c_str(), ha1Data.length(), md5buf);
   ^~~
make[2]: *** [src/CMakeFiles/zm.dir/build.make:570: src/CMakeFiles/zm.dir/zm_rtsp_auth.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:493: src/CMakeFiles/zm.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
localhost  /usr/src/zoneminder/cmake #
```

**Fix**
```
cd cmake
mv config.h config.h.orig
sed -e "s/HAVE_DECL_MD5 1/HAVE_DECL_MD5 0/" config.h.orig > config.h
```
After adjusting the flag, things build cleanly.

**Comment by hax0kartik** [comment]
I think this error is being caused due to these [lines](https://github.com/ZoneMinder/zoneminder/blob/master/CMakeLists.txt#L742-L749). You have gnutls-openssl wrapper installed which sets `HAVE_DECL_MD5` to true but gnutls-wrapper itself is not used anywhere in zoneminder project. This should be a simple fix, we just need to remove the highlighted lines.
