### ISSUE TITLE
Buttons in watch and event view are all gray when using dark CSS

### ISSUE THREAD

**Issue by jjakob** [ZoneMinder/zoneminder#2897]
**Describe Your Environment**
- Zoneminder v1.34.6
- ppa:iconnor/zoneminder-1.34
- Ubuntu 16.04
- Firefox 74.0

**Describe the bug**
The buttons in the watch and event view are all gray when using dark CSS.

**To Reproduce**
- Go to Options, set CSS_DEFAULT to "dark", save
- logout, close the tab and reopen it, relogin
- click on a camera, all the buttons are gray, even though they can be clicked

**Expected behavior**
The buttons should be different colors as they are with the base css.

**Comment by alabamatoy** [comment]
related to https://github.com/ZoneMinder/zoneminder/issues/2849  I thought this was fixed?

**Comment by jjakob** [comment]
That was for the default css with thite background (which is fine), this is for the dark css. Here the buttons are all gray and never become blue.

**Comment by jjakob** [comment]
This is still an issue in 1.34.15

**Comment by connortechnology** [comment]
Fixed by cd9f10695dea88f2505096f516d5eabcd365ee0a
