### ISSUE TITLE
[TypeError: ctx is undefined] in  /web/skins/classic/views/js/montagereview.js

### ISSUE THREAD

**Issue by jjakob** [ZoneMinder/zoneminder#2899]
**Describe Your Environment**
- Zoneminder v1.34.6
- ppa:iconnor/zoneminder-1.34
- Ubuntu 16.04
- Firefox 74.0

**Describe the bug**
The following error occurs in web_js:
```
web_js[22379].ERR [x.x.x.x] [TypeError: ctx is undefined] at cache/skins_classic_views_js_montagereview-dark-1583788292.js line 334
```

This is at line 334 in that file:
https://github.com/ZoneMinder/zoneminder/blob/bf9ba39aa25b511e8de04f35520593a665141013/web/skins/classic/views/js/montagereview.js#L334

**To Reproduce**
None that I am aware of. This error was logged once after restarting apache, probably after logging into the web ui.

**Expected behavior**
No error?

**Debug Logs**
None

**Comment by connortechnology** [comment]
I am unable to reproduce this.  Looking at the code, We may be able to make it go away just by cleaning it up a bit.  Expect a commit to master soon.
