### ISSUE TITLE
Live view issues with resolution

### ISSUE THREAD

**Issue by thisabstractmind** [ZoneMinder/zoneminder#2912]
Version: 1.34.9
Install method: iconnor ppa
OS: Ubuntu Server 18.04.4 LTS
Kernel: GNU/Linux 4.15.0-96-generic x86_64
Browser: Chrome  80.0.3987.163 (Official Build) (64-bit)

**Description:**
Fresh install of zoneminder on server using installation instructions with a2enmod zonminder used.
All configuration files per the installation instructions. Live view will not show in browser, all logs show proper capture and analysis. 

**Fix:**
Standard install puts AUTH_RELAY to hashed. When this is set to none the problem is resolved and the live view can be seen.

**Comment by connortechnology** [comment]
This is not a bug, it is a configuration issue that we have seen lots.  Usually it is due to timezone not being set correctly.  AUTH_RELAY=none is not secure.
