### ISSUE TITLE
DCS5020L.pm not running

### ISSUE THREAD

**Issue by stevaedrum** [ZoneMinder/zoneminder#2931]
-  ZoneMinder 1.34.11
- installed with RPMFusion
- Fedora Core 31
- Chrome & Firefox

- D-Link DCS5020L

PTZ not running and exit error on zmcontrol

I have detected in the DCS5020L.pm un bug in the version and master.
This sub is missing "sub printMsg", present in 1.34.9 version.

I have add this and working normaly.

sub printMsg
{
    my $self = shift;
    my $msg = shift;
    my $msg_len = length($msg);

    Debug( $msg."[".$msg_len."]" );
}

**Comment by connortechnology** [comment]
The better thing to do is 
Line 72 of /usr/share/perl5/ZoneMinder/Control/DCS5020L.pm should be:
$self->printMsg($cmd, 'Tx');

**Comment by stevaedrum** [comment]
Thanks for your feedback, I have made your proposal, it's working.
But don't correct issue #2932

**Comment by stevaedrum** [comment]
Hi all,

I permit to share a problem in branch
Concerning this issue, I have detected that in master branch it's correct but not in branch 1.34.15, 1.34.14, 1.34.13....

 $self->printMsg($cmd, 'Tx');

Thnaks in advance for your support.

**Comment by connortechnology** [comment]
fixed in 1.34.16
