### ISSUE TITLE
PTZ arrow in monitor not working

### ISSUE THREAD

**Issue by stevaedrum** [ZoneMinder/zoneminder#2932]
ZoneMinder 1.34.11
installed with RPMFusion
Fedora Core 31
Chrome & Firefox

D-Link DCS5020L

"PantiltButtons" on the page of monitor not running with Chrome or Firefox, I click on arrow button no move.
PresetButton, Wake, Sleep, Reset and PresetHome working correctly.

I don't have error message.

It's running with ZmNija, with API.

**Comment by connortechnology** [comment]
There is a known issue with DCS5020L in 1.34.11.  Line 72 of /usr/share/perl5/ZoneMinder/Control/DCS5020L.pm should be:
$self->printMsg($cmd, 'Tx');
Can you change that line and report if it fixes your problem?

**Comment by stevaedrum** [comment]
This issue is not corrected,
"PantiltButtons" on the page of monitor not running

**Comment by connortechnology** [comment]
I will release 1.34.13 with this fix in a few days.
