### ISSUE TITLE
Preclusive percent is not integer number after saving

### ISSUE THREAD

**Issue by sagitt** [ZoneMinder/zoneminder#2938]
**Describe Your Environment**
-  1.34.14
- PPA
- UBUNTU SERVER 18.04.4 LTS
- Chrome las release
- Fresh install, every install do same thing.

**If the issue concerns a camera**
All cameras

**Describe the bug**
If i set "10" on the picture example, after saving and re-edit it i can see "9,XX". this happen on every my cam in preclusive zones

**To Reproduce**
see up

**Expected behavior**
n/a

**Debug Logs**
n/a

![Schermata 2020-05-15 alle 21 03 05](https://user-images.githubusercontent.com/169086/82087100-bb2f2280-96ef-11ea-94b5-b9166ab5890d.png)

**Comment by connortechnology** [comment]
The area can be a decimal when the units are percent.  Calculations can go a bit wrong when you only use integer percentages, so we limit to two decimal digits of precision.
