### ISSUE TITLE
Console view is broken on small devices

### ISSUE THREAD

**Issue by roddone** [ZoneMinder/zoneminder#2941]
**Describe Your Environment**
- Version of ZoneMinder : 1.34.12
- installed from PPA iconnor
- Ubuntu Server 20.04
- Chrome 83.0.4103.61 (64 bits) & Firefox 76.0.1 (64 bits) & Microsoft Edge 83.0.478.37

**Describe the bug**
On small devices (like mobile phones), the console view's responsive display is broken because the grid that contains the list of monitors is larger than the screen. It makes it possible to scroll right/left the entire page .
I principaly use ZM on my mobile phone and this glitch is really annoying 

**To Reproduce**
1. Go to the console view with a mobile phone (or simulate one with your browser's dev tool)
2. Add a monitor if you don't already have one
3. Scroll left/right
![image](https://user-images.githubusercontent.com/34140141/82914713-25598a00-9f70-11ea-9159-362ca674fdfa.png)

**Expected behavior**
In a perfect world, the whole interface should be done "mobile first", but we could also simply wrap the table in a div with class "table-responsive" (see https://getbootstrap.com/docs/3.3/css/#tables-responsive )
This would make the table scroll instead of the whole page.

**Comment by roddone** [comment]
There are also a lot of other "glitches" or possible visual improvements when using ZM on tablet / mobile.
Would it be relevant to describe each one in a separate issue or group them in a single one ?

**Comment by connortechnology** [comment]
I think technically each should have it's own issue, although if some are similar feel free to group them a bit.

Are you intending to solve these issues yourself?

**Comment by roddone** [comment]
Of course I will try to fix these issues but i only use a small bench of ZM's views like console and watch views, so I won't be able to review all the views.

I will open issues when I identify problems ;)
