### ISSUE TITLE
zmtrigger.pl crashes, which keeps Monitors in alarm state.

### ISSUE THREAD

**Issue by Maescool** [ZoneMinder/zoneminder#295]
When using the zmtrigger system for my IP camera's to trigger alarms, it functioned perfect until version 1.24 after that I noticed my diskspace was maxing out.
What I saw was events that had over 3000 seconds.
When looking in the syslog  I noticed this:

```
Jan  3 14:39:37 zoneminder zmdc[32433]: INF [Starting pending process, zmtrigger.pl]
Jan  3 14:39:37 zoneminder zmdc[32433]: INF ['zmtrigger.pl' starting at 14/01/03 14:39:37, pid = 30130]
Jan  3 14:39:37 zoneminder zmdc[30130]: INF ['zmtrigger.pl' started at 14/01/03 14:39:37]
Jan  3 14:39:37 zoneminder zmtrigger[30130]: INF [Trigger daemon starting]
Jan  3 14:39:37 zoneminder zmtrigger[30130]: INF [Opening connection 'Chan1']
Jan  3 14:43:12 zoneminder zmtrigger[30130]: INF [Trigger 'on' 'Motion']
Jan  3 14:43:25 zoneminder zmtrigger[30130]: INF [Trigger 'on' 'Motion']
Jan  3 14:43:46 zoneminder zmtrigger[30130]: INF [Trigger 'on' 'Motion']
Jan  3 14:43:49 zoneminder zmtrigger[30130]: INF [Trigger 'on' 'Motion']
Jan  3 14:44:13 zoneminder zmtrigger[30130]: INF [Found actions expiring at 1388756652]
Jan  3 14:44:13 zoneminder zmtrigger[30130]: INF [Found action '1|cancel']
Jan  3 14:44:13 zoneminder zmtrigger[30130]: INF [Cancelled event]
Jan  3 14:44:26 zoneminder zmtrigger[30130]: INF [Found actions expiring at 1388756665]
Jan  3 14:44:26 zoneminder zmtrigger[30130]: INF [Found action '3|cancel']
Jan  3 14:44:26 zoneminder zmtrigger[30130]: INF [Cancelled event]
Jan  3 14:44:39 zoneminder zmdc[32433]: ERR ['zmtrigger.pl ' exited abnormally, exit status 9]

```

After the zmtrigger dies for an unknown reason, (according to google it has something to do with shared memory?)
The alert state is not reset of the Monitors and they keep recording, even after zmtrigger restarts, untill a new alarm event is generated and cancelled.

How can I debug this exit status? and is there a fix? (Yes the shmmax is upped)

**Comment by mholst** [comment]
I know this is an old question, but do you know if this fix is in the Trusty server version?

I just upgraded my server to Trusty, and I am having an issue similar to this one. However the fix is not available through the PPA for Trusty.

When i look at the alarmed pixel outline, they stay the same, and the events are really long.

Hope you can help. I am truly a fan of ZoneMinder.

Best regards
Morten Attermann Holst

**Comment by connortechnology** [comment]
ok... how about: Why is zmtrigger crashing? have you tried running it manually to see if there is any useful output?

**Comment by mholst** [comment]
Can you guide me in doing that?

**Comment by connortechnology** [comment]
open a command prompt and do the following:
sudo /usr/bin/zmtrigger.pl

**Comment by mholst** [comment]
Hmm... Nothing seems to happen.
It must be my settings for the camera that are off, using "best, high sensitivity". However, they worked like a charm in version 1.25.

**Comment by connortechnology** [comment]
zmtrigger runs and waits for signals.  Eventually it will crash.

**Comment by mholst** [comment]
Allright, i will give it a longer test.
Could it cause the same alarm outline(the red indication) for hours? Thats what I experience. My silouette keeps "hanging" there. Even if the alarm where that was true is long gone.

Venlig hilsen
Morten Attermann Holst

**Comment by connortechnology** [comment]
I suspect that the problem is not in zmtrigger.pl.  I would suggest looking at your zmc and zma logs.

**Comment by Go00oglin** [comment]
Hi,
I have the same problem with the latest zoneminder package under Ubuntu 14.
The zmtrigger.pl, running as "sudo zmtrigger.pl" is waiting for commands, but from zoneminder service it does not work. zmdc.log contains: "exited abnormally, exit status 9"
:(

**Comment by mdetweiler** [comment]
I'm seeing this on a new install on top of Ubuntu 14.04 with 1 monitor set to "Monitor".

**Comment by Go00oglin** [comment]
in may case there is 1 monitor with function Nodect
