### ISSUE TITLE
ZoneMinder user doesn't have permission to access /dev/video0 for local USB camera

### ISSUE THREAD

**Issue by joseph85750** [ZoneMinder/zoneminder#2953]
**Describe Your Environment**
- Version of ZoneMinder [v1.34.15]
- Installed via instructions here:  https://zoneminder.readthedocs.io/en/stable/installationguide/ubuntu.html
- OS:  Ubuntu 18.04.4 LTS

**If the issue concerns a camera**
- USB
- ZoneMinder Source Type: local

**Describe the bug**
When attaching a local USB camera, ZoneMinder doesn't have permission to access.
The camera shows up as /dev/video0, with the following permissions:
`crw-rw---- 1 root video 81, 0 Jun 3 17:23 /dev/video0`

**Log Message**
Jun 3 17:22:40 zoneminder zmc_dvideo0[2801]: FAT [zmc_dvideo0] [Failed to open video device /dev/video0: Permission denied]

**To Fix**
Update /etc/group by adding 'www-data' to the 'video' group as follows:
`video:x:44:www-data`

Rebooted. Problem solved.

```

**Comment by connortechnology** [comment]
This is not a bug, and is well documented.
