### ISSUE TITLE
Coordinates are covering motion settings in zone configuration

### ISSUE THREAD

**Issue by jeroenst** [ZoneMinder/zoneminder#2961]
**Describe Your Environment**
- Version of ZoneMinder [1.34.16]
- How you installed ZoneMinder [PPA]
- Full name and version of OS [Linux mint 19.3]
- Browser name and version [Chrome Version 83.0.4103.61 (Official Build) (64-bit)]

**Describe the bug**
When I open a zone, the coordinates of the zones covers the settings of the motion detection

**To Reproduce**
1. Go to zone
2. Open Zone
3. Scroll down
4. See fault

**Expected behavior**
The coordinates shouldn't cover the motion settings.

**Comment by jeroenst** [comment]
file:///home/jeroen/Pictures/Screenshot%20from%202020-06-12%2014-03-06.png

**Comment by jeroenst** [comment]
![Screenshot from 2020-06-12 14-03-06](https://user-images.githubusercontent.com/2833940/84501256-7da1c300-acb6-11ea-861e-ab7c72726bd9.png)

**Comment by connortechnology** [comment]
Can you right click inspect and tell us the width of the settsPanel div and the zonePoints div?
They should each be 600px.
The layout here is pretty simple... 600px wide, floated left.  They should not overlap. If there were going to, the zonePoints should drop down below.

**Comment by jeroenst** [comment]
![Screenshot from 2020-06-23 16-11-38](https://user-images.githubusercontent.com/2833940/85414391-55df1480-b56c-11ea-84c1-c6a4ee8a5ac4.png)
![Screenshot from 2020-06-23 16-11-54](https://user-images.githubusercontent.com/2833940/85414399-58da0500-b56c-11ea-9385-0c38f8c71f7d.png)

**Comment by jeroenst** [comment]
The issue occurs in Chrome, there is no problem in Firefox.

**Comment by connortechnology** [comment]
I now understand what is going on here.  A quick fix is in master, will be merged to 1.34.19.

**Comment by jeroenst** [comment]
Thanx!

**Comment by jeroenst** [comment]
I can confirm this bug is solved in v 1.34.20.

Thanx!
