### ISSUE TITLE
CUDA/OpenCL multi-device accelleration

### ISSUE THREAD

**Issue by localthink** [ZoneMinder/zoneminder#2966]
This has existed a while .. I upped the ante .. now at $1300.
https://www.bountysource.com/issues/999779-gpu-processing-for-ffmpeg-and-jpeg-manipulations

My ask? .. that the cheap ex-AWS Tesla M units (about $400 and ~3k cores) be able to handle all the heavy lifting. I can do this in OpenCV already, ideally I'd like to see PCI lanes become the limit. I'll work WITH you on as to "where do I get 500mb worth of h264 streams?". I'll pay for it in AWS for practice. Code needs to be totally open license (minus nvidia screwiniess)

**Comment by connortechnology** [comment]
We already have decode support.  Encode support will be in 1.36.  Object detection can already use whatever GPU you have. So I'm closing this to keep things tidy as it already exists in other issues like the one with the bounty.
