### ISSUE TITLE
crash with res at 1080x1920

### ISSUE THREAD

**Issue by connortechnology** [ZoneMinder/zoneminder#2968]
See forums for original reporter. 
https://forums.zoneminder.com/viewtopic.php?f=40&t=29613
1088x1920 and 1072x1920 do not crash.  

Isaac does not have any cameras that will do actual rotation in camera.

**Comment by neillbell** [comment]
I have a HikVision DS-2CD2442FWD-IW that does allow in-camera rotation. I just configured it for 1080x1920 in the camera and also in ZoneMinder and it worked fine. Is this configuration what is expected to crash?

**Comment by connortechnology** [comment]
I believe there is a further requirement that you need to be converting to 24bit RGB instead of 32bit RGBA.  

In any event, the fix is already in master, just undergoing some testing while I finish everything else that is going in 1.34.17

**Comment by mastertheknife** [comment]
Hi, i doubt its the limitation, because 1920*1080 = 2073600 and its dividable by 12, 16 and also 64.

**Comment by connortechnology** [comment]
@mastertheknife nice to see you.

I believe I already have the problem fixed in master.

The issue is that the WIDTH needs to be aligned to use sws_scale.  Not width*height.  sws_scale acts line by line.

**Comment by connortechnology** [comment]
Ugh.  I have come to believe that my fix just won't work.  Going to have to do a memory copy instead.

**Comment by connortechnology** [comment]
Okay, current status which I think I can port to 1.34.17 is that we will now leave the shared images as a contiguous block of ram and do a memcpy in zm_ffmpeg_camera if required.

**Comment by tqk2811** [comment]
how caculate the width? my sws_cale crash too
