### ISSUE TITLE
Alarm via API returns wrong value

### ISSUE THREAD

**Issue by tranzmatt** [ZoneMinder/zoneminder#2978]
**Describe Your Environment**
- Version of ZoneMinder 1.34.16
- How you installed ZoneMinder  PPA APT install
- Full name and version of OS  NVidia Jetpack 32.3.1 (running Bionic 18.04)

**Describe the bug**

Call made via pyzm:

make_request called with url=http://192.168.1.247/zm/api/monitors/alarm/id:3/command:on.json payload={} type=get query={}

Where mid=3. I get a return json of something like

ARM: {'status': 'Alarmed event id: 2'}

But in the web-ui, ID #3 seems to have been created instead.

**Expected behavior**
Shouldn't "3" be returned in the json string?

**Comment by pliablepixels** [comment]
To be specific, this is not an API issue. `zmu` returns the wrong alarm eid when used to trigger an alarm (which then filters up via the API layer too)

**Comment by tranzmatt** [comment]
Ok.  Should I close this and open something different or has it already been reported?

**Comment by pliablepixels** [comment]
No that’s fine. Let’s keep it as is.
