### ISSUE TITLE
Monitors do not display correctly when some scalings and scaling sequences are selected.

### ISSUE THREAD

**Issue by neillbell** [ZoneMinder/zoneminder#2979]
**Describe Your Environment**
- Version of ZoneMinder: 1.35.5
- How you installed ZoneMinder: master PPA/1.35.5~20200714143209-focal
- Full name and version of OS: Ubuntu 20.04 LTS

**Describe the bug**
Monitors do not display correctly when some scalings and scaling sequences are selected.

**To Reproduce**
1. Do a fresh install from the zoneminder master PPA of 1.35.5~20200714143209-focal
2. Add a new FFMPEG monitor
3. Click on the monitor name, the monitor displays at 'actual' scale correctly.
4. Switch the scale to 'scale to fit', the monitor displays correctly.
5. Switch the scale to '1/3', the monitor displays correctly.
6. Click on the 'Console' link to return to the main display
7. Click the monitor name again.
8. The monitor displays with vertical lines as shown here:

![Screenshot from 2020-07-15 12-54-59](https://user-images.githubusercontent.com/19613739/87579875-40a56380-c69c-11ea-89fc-1b544a9fdd30.png)
9. Select any value for scale. The monitor continues to display incorrectly.
10. Click on the 'Console' link to return to the main display.
11. Click on the 'Montage' link, the monitor displays correctly at 'actual' scale.
12. Switch the scale to '1/3', the monitor again displays with vertical lines:

![Screenshot from 2020-07-15 12-56-55](https://user-images.githubusercontent.com/19613739/87579891-48fd9e80-c69c-11ea-9341-ce04edd333a8.png)

**Expected behavior**
The system should be able to correctly display the monitor at all scales in any sequence.

**Comment by connortechnology** [comment]
This issue actually involved any scaling at all.  Changing the scale in the dropdown doesn't actually alter the stream, just adjust the css styles on the image element.  When you reload the page the img stream includes the new scale parameter, so is now scaling.  
A recent fix for widths that are not a multiple of 32 was the culprit.
