### ISSUE TITLE
Monitor does not display correctly when "Rotate Right" is selected for "Orientation" in ZoneMinder

### ISSUE THREAD

**Issue by neillbell** [ZoneMinder/zoneminder#2985]
**Describe Your Environment**
- Version of ZoneMinder: 1.35.5
- How you installed ZoneMinder: master PPA/1.35.5~20200721160555-focal
- Full name and version of OS: Ubuntu 20.04 LTS

**Describe the bug**
Monitor does not display correctly when "Rotate Right" is selected for "Orientation" in ZoneMinder.

**To Reproduce**
1. Add a new FFMPEG monitor with normal orientation
2. Click on the monitor name, the monitor displays correctly.
3. Click on "Console" to return to the main console.
4. Click on the camera address to bring up the monitor configuration screen.
5. Select the "Source" tab and set the monitor orientation to "Rotate Right"
6. Click the "Save" button.
7. When the monitor is up, click on its name.
8. The monitor displays incorrectly at any scale as shown below. The bottom half of the video frequently shows flashes of the non-rotated display.

![Screenshot from 2020-07-21 17-25-36](https://user-images.githubusercontent.com/19613739/88113680-e151c280-cb77-11ea-9b8f-97305a626565.png)

**Comment by connortechnology** [comment]
I think I fixed this.  Please confirm.

**Comment by neillbell** [comment]
You did. I'm sorry that I didn't close this.
