### ISSUE TITLE
Bootstrap 4.5 New UI Punchlist

### ISSUE THREAD

**Issue by knight-of-ni** [ZoneMinder/zoneminder#2991]
This issue has been created to track issues related to Frontend UI changes.

**When reporting problems, we need more than just a statement that "feature X is not working as intended". We need screenshots, console log, and zm log messages which can objectively describe the problem.**

**These changes have a global scope**
- [x] Upgrade to Bootstrap 4.5
- [x] Add new collapsed navigation bar
- [x] upgrade to Jquery 3.5.1, use [JQuery-migrate](https://github.com/jquery/jquery-migrate) to smooth the transition during development
- [x] eliminate mootools
- [x] replace all javascript `alert("you have no permissions")` messages with ENoPerm modal
added in c4c4551
- [x] Eliminate popup links. Instead, make all links navigate to a new view with ZM navbar at the top
IN PROGRESS
- [x] Subset of the previous. Replace all optionhelp "?" popup links with optionhelp modal
- [x] Button styling overrides are not applying
- [x] Color states of the widgets on the navigation bar are not applying (logs, /dev/shm, storage areas, etc)
- [x] The dark skin has not been tested - PLEASE TEST
- [x] verify font sizes
- [x] Review the need for WEB_EVENTS_PER_PAGE and/or server side pagination
UPDATE: Deploy server side pagination for events, frames, and possible watch views
- [x] The buildSelect php function has an option that embeds inline javascript, which is no longer adviseable. Remove this option from the function and rewrite any calls to this function that try to use it in that way.
- [x] Add locale support to bootstrap-table extension
- [x] Set the table-responsive class on all bootstrap tables
- [x] Set a delay timer on the thumbnail zoom animation so accidental touches don't trigger it

**Events view**
- [x] Table changes are not being remembered - cookie extension not working
UPDATE: Cookie size it too big. See https://github.com/wenzhixin/bootstrap-table/issues/5259
UPDATE: Fixed in commit 9bc1b6a
- [x] Thumbnail animation appears to time out after leaving the view sit unattended 
Fixed in commit bf63500
- [x] Thumbnail magnify effect extends too far to the right
- [x] Table responsiveness does not want to turn off - creates a horizontal scroll bar on the bottom of the table (ugly)
maybe fixed in afc3d2c548e718b988a8f28c2b60300b0ff50d96
- [x] Archive buttons not working properly 
fixed in commit f27f6e6
- [x] Implement export report to csv, txt, excel, sql, etc via [export extension](https://live.bootstrap-table.com/example/welcome.html)
Added in commit 9357017a398c273f46e8ab5b41290c0ddbf9e2ae NEEDS TESTING
- [x] To prevent race condition, add a success callback to the Delete ajax call, which then reloads the page
- [x] Deploy server side pagination

**Frames View**
- [x] Apply zoom animation to the thumbnails.
Added in commit 8f70ae1
- [x] Deploy server side pagination

**New Console view Punchlist items:**
- [x] Deploy animated thumbnails
Added in commit 73a01855f8cf6874ca24938990ffaaf41c9750ad
- [x] Evaluate the ability to enable/disable console thumbnails
- [x] Evaluate placement of the thumbnail: under monitor name, in its own column, etc.

**Monitor view**
- [x] Un-popup the view
- [x] Convert horizontal tabs to vertical pills
- [x] Fix back button triggers form resubmission alerts
- [x] Fix the other form resubmission alerts
- [x] Convert links in top-right corner to buttons
- [x] Fix the probe & preset views the new buttons point to

**Server popup**
- [x] Unpopup the view
- [x] convert to modal

**Storage popup**
- [x] Unpopup the view
- [x] convert to modal

**Log view**
- [x] Unpopup the views
- [x] add navbar to the header
- [x] rework the buttons, apply more consistent theme, need to discuss
- [x] evaluate using bootstrap-table for the events list

**Watch view**
- [x] upgrade event list to bootstrap-table
- [x] Unpopup the views
- [x] add navbar to the header
- [x] rework the buttons, apply more consistent theme, need to discuss
- [x] Deploy server side pagination
- [x] Add thumbnails to the event list in this view

**Event view**
- [x] Unpopup the buttons
- [x] add navbar to the header
- [x] rework the buttons, apply more consistent theme, need to discuss
- [x] Handle the case where the event playback window is too wide to show the event stats on the left

If you notice something that looks different than it did before, please post it to this issue.

**Comment by knight-of-ni** [comment]
Hey, hey, look at that... it thinks this is my first issue.

**Comment by jonrub** [comment]
I guess I get below errors because of this?

[https://imgur.com/a/Qa29rEk](url)

**Comment by knight-of-ni** [comment]
You need the latest build of master to fix that

**Comment by jonrub** [comment]
Thank you!

**Comment by knight-of-ni** [comment]
Navbar Widget colorization has been fixed in commit 6486f59
Please test!

**Comment by bkjaya2020** [comment]
In Zoneminder 1.35.5~20200725145046-focal , the filters can't be saved.

**Comment by knight-of-ni** [comment]
> In Zoneminder 1.35.5~20200725145046-focal , the filters can't be saved.

Working fine here. You didn't include any error message or screenshot, so what lead you to believe this is related to the recent bootstrap upgrade?

**Comment by bkjaya2020** [comment]
> > In Zoneminder 1.35.5~20200725145046-focal , the filters can't be saved.
> 
> Working fine here. You didn't include any error message or screenshot. What lead you to believe this is related to the recent bootstrap upgrade?

In the filter , the following  conditional statements are not saved. 
https://drive.google.com/file/d/1i86XWjHSINIZq0YQnCNT59DGW9apa2Xc/view?usp=sharing

The error log is attached.

https://drive.google.com/file/d/1pZXYt_LtLeEGkTeToRqjfvteNBuDAVNa/view?usp=sharing

**Comment by knight-of-ni** [comment]
I don't have permission to view those links.

**Comment by bkjaya2020** [comment]
> I don't have permission to view those links.

Sorry for the mistake
[https://www.dropbox.com/s/jhq1vdy8osx9b5p/conditionalstatement?dl=0](url)

[https://www.dropbox.com/s/jhq1vdy8osx9b5p/conditionalstatement?dl=0](url)

**Comment by knight-of-ni** [comment]
Those download links redirect back to github, strangely. After reading your post in the forums, I was able understand and duplicate the problem. The problem was caused by yesterday's changes to Object.php.
I've let Isaac know. Since this issue is not related to the Bootstrap upgrade, please keep further discussion here:
https://forums.zoneminder.com/viewtopic.php?f=42&p=116674#p116674

**Comment by bkjaya2020** [comment]
Thank you Sir

**Comment by UtechtDustin** [comment]
> Table changes are not being remembered - cookie extension not working
> UPDATE: Cookie size it too big. See wenzhixin/bootstrap-table#5259

Will be fixed in the next bootstrap-table version (see https://github.com/wenzhixin/bootstrap-table/pull/5260 and https://github.com/wenzhixin/bootstrap-table/issues/5259)

**Comment by knight-of-ni** [comment]
Fix black table text

![z1](https://user-images.githubusercontent.com/5150042/90793979-dc487600-e2d1-11ea-97e4-16db5eebb00d.jpg)

**Comment by knight-of-ni** [comment]
Sample screenshot showing frames with with > 25 frames
![image](https://user-images.githubusercontent.com/5150042/93388190-ef4a5980-f82f-11ea-8516-5533e8137ead.png)

**Comment by knight-of-ni** [comment]
@mnoorenberghe 

Server side pagination for the Events view has just been pushed to master. This fixes the issue with the total number of records limited to WEB_EVENTS_PER_PAGE, for that view. PLEASE TEST. 

Server side pagination for the Frames view is the roadmap as well, but we need to test the pagination in the Events view further before proceeding.

**Comment by knight-of-ni** [comment]
tasks are complete. closing...
