### ISSUE TITLE
Notice: Undefined variable: fid (Minor/Lowest priority)

### ISSUE THREAD

**Issue by scottgrobinson** [ZoneMinder/zoneminder#2994]
**Describe Your Environment**
- Version of ZoneMinder [release version, development version, or commit] = v1.34.16
- How you installed ZoneMinder [e.g. PPA, RPMFusion, from-source, etc] = From source
- Full name and version of OS = Ubuntu 20.04
- Browser name and version (if this is an issue with the web interface) = Chrome 84

**Describe the bug**
When clicking 'Max Score' next to an event, the popup displays x2 PHP notices
```
Notice: Undefined variable: fid in /usr/share/zoneminder/www/skins/classic/views/frame.php on line 47
Notice: Undefined variable: fid in /usr/share/zoneminder/www/skins/classic/views/frame.php on line 48
```

Example URL = http://192.168.2.203:1080/zm/?view=frame&eid=22840&fid=0&popup=1
Looks like none of my cameras/events have an FID (whatever that is...)

**Expected behavior**
No PHP notice is displayed

**Comment by connortechnology** [comment]
Fix in master, will be released in 1.34.17
