### ISSUE TITLE
Filter: Unable to select or populate Monitor Name

### ISSUE THREAD

**Issue by PrplHaz4** [ZoneMinder/zoneminder#2995]
**Describe Your Environment**
- Version of ZoneMinder 1.34.16
- How you installed ZoneMinder: Docker (dlandon/zoneminder)
- Browser name and version: Firefox 78.0.2

**Describe the bug**
When attempting to create a filter on Monitor Name, the dropdown for selecting the filtered value contains only blank items.

Note: my monitor names have hyphens in them (`-`) if that matters...
![image](https://user-images.githubusercontent.com/841414/88824212-0bb50880-d194-11ea-8dfd-729a9bc13557.png)

**To Reproduce**
1. Go to Filters
2. Click on 'Alarm Frames' (or any attribute name)
3. Select 'Monitor Name'
4. See Dropdown to choose the value to filter on (the name of the monitor) contains 10 empty items

**Expected behavior**
Ability to select a monitor name, or provide a text value for the filter to apply to.

**Debug Logs**
```html
<select name="filter[Query][terms][7][val]" id="filter[Query][terms][7][val]">
<option value="undefined"></option>
<option value="undefined"></option>
<option value="undefined"></option>
<option value="undefined"></option>
<option value="undefined"></option>
<option value="undefined"></option>
<option value="undefined"></option>
<option value="undefined"></option>
<option value="undefined"></option>
<option value="undefined"></option>
</select>
```

Possibly Related:
https://github.com/ZoneMinder/zoneminder/issues/2817

**Comment by connortechnology** [comment]
Fixed in 1.34.17
