### ISSUE TITLE
Log: Downgrade to INFO "Unable to send raw frame 1: Broken Pipe"

### ISSUE THREAD

**Issue by PrplHaz4** [ZoneMinder/zoneminder#2996]
**Describe Your Environment**
- Version of ZoneMinder 1.34.16
- How you installed ZoneMinder Docker
- Browser name and version: Firefox 78.0.2

**Describe the bug**
Currently these messages are logged as ERRors.

This forum thread indicates they can be safely ignored:
https://forums.zoneminder.com/viewtopic.php?t=26109

As does this article:
https://mattionline.de/zoneminder-error-meanings/

**To Reproduce**
1. Open a live stream from the web console
2. Close the window containing the live stream
3. See the error in the log

**Expected behavior**
INFO message is logged instead of ERROR

**Debug Logs**
```
2020-07-29 11:42:09 | zms_e122678 |   | 30645 | ERR | Unable to send raw frame 1: Broken pipe | zm_eventstream.cpp | 816
```

**Comment by connortechnology** [comment]
Agreed.  Fix is queued for 1.34.17.

**Comment by hdlineage** [comment]
I'm still getting this issue on v1.34.22 ( The stable official docker image)
Can you please confirm if this fix is reflected on the docker version?

**Comment by Hawk84r** [comment]
I'm on on v1.34.22 not docker and can confirm it is still on ERRor level.

**Comment by connortechnology** [comment]
You are correct, I missed getting it into 1.34.  I have now pushed it to the release-1.34 branch which means it will be in 1.34.27 when it gets released.
