### ISSUE TITLE
Its not possible to remove a selected monitor

### ISSUE THREAD

**Issue by connectnet** [ZoneMinder/zoneminder#2998]
Hi there!
There is a small bug in Vers. 1.35.5 because its not possible to remove a selected monitor. E.ex. here Monitor-1.
Proof: Screenshot says more than 1000 Words. ;-)

![Cant-remove-selected-monitor](https://user-images.githubusercontent.com/8360383/88905622-c279bd00-d256-11ea-8e6a-edec9bfb381c.png)

Thanks for fixing in advance! :-)

**Comment by connortechnology** [comment]
What do you mean remove?  What are you trying to do?

**Comment by knight-of-ni** [comment]
It's working fine for me. Just added, then removed a monitor from the web console. Running a build from today.

**Comment by connectnet** [comment]
You can add one or more monitors to decrease the results but you can't remove selected monitors from list.
Version: 1.35.5

**Comment by connectnet** [comment]
Fixed by update. Thank you!

**Comment by jeroenst** [comment]
Same problem with v1.36.4

I get these errors:

`
Date/Time,Component,Server,PID,Level,Message,File,Line
"2022-07-12 13:16:04",web_php,,11901,ERR,"Unable to load ZM\Event record for Id=402275",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,2462,ERR,"Unable to load ZM\Event record for Id=408494",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,918,ERR,"Unable to load ZM\Event record for Id=401913",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,448,ERR,"Unable to load ZM\Event record for Id=407466",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,938,ERR,"Unable to load ZM\Event record for Id=408348",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,681,ERR,"Unable to load ZM\Event record for Id=402033",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,680,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,931,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,2475,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,7682,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,447,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,6310,ERR,"Unable to load ZM\Event record for Id=402087",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,2475,ERR,"Unable to load ZM\Event record for Id=407845",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,447,ERR,"Unable to load ZM\Event record for Id=402513",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,931,ERR,"Unable to load ZM\Event record for Id=402525",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,680,ERR,"Unable to load ZM\Event record for Id=402020",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,7682,ERR,"Unable to load ZM\Event record for Id=401956",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,681,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,11901,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,918,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,448,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,938,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,2462,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,6310,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,918,ERR,"Unable to load ZM\Event record for Id=401911",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,681,ERR,"Unable to load ZM\Event record for Id=402029",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,2462,ERR,"Unable to load ZM\Event record for Id=408490",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,11901,ERR,"Unable to load ZM\Event record for Id=402273",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,448,ERR,"Unable to load ZM\Event record for Id=407461",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,938,ERR,"Unable to load ZM\Event record for Id=408344",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,447,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,6310,ERR,"Unable to load ZM\Event record for Id=402081",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,931,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,7682,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,2475,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,680,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,2475,ERR,"Unable to load ZM\Event record for Id=407836",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,931,ERR,"Unable to load ZM\Event record for Id=402521",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,447,ERR,"Unable to load ZM\Event record for Id=402510",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,680,ERR,"Unable to load ZM\Event record for Id=402018",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,7682,ERR,"Unable to load ZM\Event record for Id=401950",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:04",web_php,,6310,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,938,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,681,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,2462,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,448,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,11901,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:04",web_php,,918,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,7682,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,6310,ERR,"Unable to load ZM\Event record for Id=402079",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,681,ERR,"Unable to load ZM\Event record for Id=402024",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,918,ERR,"Unable to load ZM\Event record for Id=401907",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,11901,ERR,"Unable to load ZM\Event record for Id=402270",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,2462,ERR,"Unable to load ZM\Event record for Id=408487",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,448,ERR,"Unable to load ZM\Event record for Id=407460",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,938,ERR,"Unable to load ZM\Event record for Id=408341",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,447,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,680,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,931,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,2475,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,7682,ERR,"Unable to load ZM\Event record for Id=401941",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,680,ERR,"Unable to load ZM\Event record for Id=402011",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,11901,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,447,ERR,"Unable to load ZM\Event record for Id=402508",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,2475,ERR,"Unable to load ZM\Event record for Id=407832",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,681,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,6310,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,2462,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,918,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,931,ERR,"Unable to load ZM\Event record for Id=402517",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,938,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,448,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,7682,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,448,ERR,"Unable to load ZM\Event record for Id=407456",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,2462,ERR,"Unable to load ZM\Event record for Id=408484",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,6310,ERR,"Unable to load ZM\Event record for Id=402076",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,11901,ERR,"Unable to load ZM\Event record for Id=402267",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,681,ERR,"Unable to load ZM\Event record for Id=402022",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,918,ERR,"Unable to load ZM\Event record for Id=401903",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,938,ERR,"Unable to load ZM\Event record for Id=408338",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,7682,ERR,"Unable to load ZM\Event record for Id=401937",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,680,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,2475,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,447,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,931,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",zmc_m2,,8995,WAR,"Tuin: 3024 - event 410739, has exceeded desired section length. 1657624563 - 1657623963 = 600 >= 600",zm_monitor.cpp,2221
"2022-07-12 13:16:03",web_php,,680,ERR,"Unable to load ZM\Event record for Id=402010",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,931,ERR,"Unable to load ZM\Event record for Id=402514",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,2475,ERR,"Unable to load ZM\Event record for Id=407829",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,447,ERR,"Unable to load ZM\Event record for Id=402503",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:03",web_php,,7682,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,11901,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,2462,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,6310,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,448,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,681,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,938,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:03",web_php,,918,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,681,ERR,"Unable to load ZM\Event record for Id=402020",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,448,ERR,"Unable to load ZM\Event record for Id=407455",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,938,ERR,"Unable to load ZM\Event record for Id=408336",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,11901,ERR,"Unable to load ZM\Event record for Id=402263",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,2462,ERR,"Unable to load ZM\Event record for Id=408482",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,918,ERR,"Unable to load ZM\Event record for Id=401899",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,7682,ERR,"Unable to load ZM\Event record for Id=401934",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,2475,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,680,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,6310,ERR,"Unable to load ZM\Event record for Id=402072",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,447,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,931,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,681,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,680,ERR,"Unable to load ZM\Event record for Id=402008",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,448,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,2475,ERR,"Unable to load ZM\Event record for Id=407817",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,7682,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,11901,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,918,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,2462,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,938,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,447,ERR,"Unable to load ZM\Event record for Id=402499",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,681,ERR,"Unable to load ZM\Event record for Id=402018",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,931,ERR,"Unable to load ZM\Event record for Id=402513",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,6310,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,448,ERR,"Unable to load ZM\Event record for Id=407453",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,918,ERR,"Unable to load ZM\Event record for Id=401896",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,2462,ERR,"Unable to load ZM\Event record for Id=408478",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,7682,ERR,"Unable to load ZM\Event record for Id=401928",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,938,ERR,"Unable to load ZM\Event record for Id=408335",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,11901,ERR,"Unable to load ZM\Event record for Id=402260",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,2475,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,680,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,6310,ERR,"Unable to load ZM\Event record for Id=402068",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,681,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,931,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,447,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,2475,ERR,"Unable to load ZM\Event record for Id=407814",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,680,ERR,"Unable to load ZM\Event record for Id=402004",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,2462,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,11901,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,7682,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,918,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,448,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,938,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,681,ERR,"Unable to load ZM\Event record for Id=402011",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,931,ERR,"Unable to load ZM\Event record for Id=402510",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,447,ERR,"Unable to load ZM\Event record for Id=402496",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:02",web_php,,6310,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:02",web_php,,938,ERR,"Unable to load ZM\Event record for Id=408332",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:01",web_php,,448,ERR,"Unable to load ZM\Event record for Id=407448",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:01",web_php,,7682,ERR,"Unable to load ZM\Event record for Id=401924",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:01",web_php,,2462,ERR,"Unable to load ZM\Event record for Id=408477",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:01",web_php,,11901,ERR,"Unable to load ZM\Event record for Id=402257",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:01",web_php,,918,ERR,"Unable to load ZM\Event record for Id=401892",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:01",web_php,,6310,ERR,"Unable to load ZM\Event record for Id=402060",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:01",web_php,,680,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:01",web_php,,681,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:01",web_php,,447,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:01",web_php,,931,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:01",web_php,,2475,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:01",web_php,,938,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:01",web_php,,2475,ERR,"Unable to load ZM\Event record for Id=407810",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:01",web_php,,680,ERR,"Unable to load ZM\Event record for Id=402001",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:01",web_php,,447,ERR,"Unable to load ZM\Event record for Id=402494",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:01",web_php,,681,ERR,"Unable to load ZM\Event record for Id=402010",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:01",web_php,,931,ERR,"Unable to load ZM\Event record for Id=402508",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:01",web_php,,7682,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:01",web_php,,448,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:01",web_php,,2462,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:01",web_php,,918,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:01",web_php,,6310,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:01",web_php,,11901,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:01",web_php,,938,ERR,"Unable to load ZM\Event record for Id=408330",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:01",web_php,,7682,ERR,"Unable to load ZM\Event record for Id=401918",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:01",web_php,,6310,ERR,"Unable to load ZM\Event record for Id=402050",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:01",web_php,,2462,ERR,"Unable to load ZM\Event record for Id=408469",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:01",web_php,,448,ERR,"Unable to load ZM\Event record for Id=407446",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:01",web_php,,918,ERR,"Unable to load ZM\Event record for Id=401888",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:01",web_php,,11901,ERR,"Unable to load ZM\Event record for Id=402255",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:16:00",web_php,,938,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:00",web_php,,681,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:00",web_php,,447,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:00",web_php,,2475,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:00",web_php,,931,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:00",web_php,,680,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:16:00",web_php,,11901,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:15:59",web_php,,7682,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:15:59",web_php,,918,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:15:59",web_php,,2462,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:15:59",web_php,,448,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:15:59",web_php,,2475,ERR,"Unable to load ZM\Event record for Id=407806",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:15:59",web_php,,11901,ERR,"Unable to load ZM\Event record for Id=402254",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:15:59",web_php,,938,ERR,"Unable to load ZM\Event record for Id=408324",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:15:59",web_php,,931,ERR,"Unable to load ZM\Event record for Id=402503",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:15:59",web_php,,680,ERR,"Unable to load ZM\Event record for Id=401996",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:15:59",web_php,,681,ERR,"Unable to load ZM\Event record for Id=402008",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:15:59",web_php,,447,ERR,"Unable to load ZM\Event record for Id=402493",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:15:59",web_php,,6310,ERR,"Event delete on event with empty Id",/usr/share/zoneminder/www/includes/Event.php,135
"2022-07-12 13:15:59",web_php,,2462,ERR,"Unable to load ZM\Event record for Id=408468",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:15:59",web_php,,918,ERR,"Unable to load ZM\Event record for Id=401883",/usr/share/zoneminder/www/includes/Object.php,20
"2022-07-12 13:15:59",web_php,,7682,ERR,"Unable to load ZM\Event record for Id=401913",/usr/share/zoneminder/www/includes/Object.php,20
`
