### ISSUE TITLE
local camera source dialog broken

### ISSUE THREAD

**Issue by osteffen** [ZoneMinder/zoneminder#3015]
**Describe Your Environment**
- zm version 1.34.19-focal1
- installed from ppa
- Ubuntu 20.04
- Firefox 79.0 (64-bit)

**Describe the bug**
Unable to add local USB camera, none of the provided options for "Device Type" and "Capture Palette" are valid. These are also just weird numbers.

**How To Reproduce:**
On the "console" page, click "Add".
In the popup dialog, "General Tab", select source type "local".
Then in the "source" tab:
Device -> set to some local video device,

**Problem:**
The "Device Type" and "Capture Palette" offer only weird numbers.
No selection of those seems to be accepted when clicking "Save"

**Expected behavior**
The fields should contain human-readable entries that are valid.

**Workaround:**
Open Debug Interface of the browser, edit the dropbown box and swap the value parameter with the text of the possible selection items. Then select one in the page.
Repeat for the other dropdown.

![image](https://user-images.githubusercontent.com/4103215/90547912-77373800-e18c-11ea-80b2-9fa0161cb083.png)
![Screenshot from 2020-08-18 09-37-31](https://user-images.githubusercontent.com/4103215/90547933-7dc5af80-e18c-11ea-84cc-613b2b33e38d.png)

**Comment by connortechnology** [comment]
Fix was included in 1.34.20.
