### ISSUE TITLE
Frames page for an event only ever lists the first 25 frames

### ISSUE THREAD

**Issue by mnoorenberghe** [ZoneMinder/zoneminder#3045]
**Describe Your Environment**
- Version of ZoneMinder: 2020-09-16
- How you installed ZoneMinder: PPA
- Full name and version of OS: Ubuntu 20.04
- Browser name and version (if this is an issue with the web interface): Firefox 82.0a1

**Describe the bug**
Click "Frames" when viewing an event. Only 25 frames are listed even if the event has more than 25 frames. The dropdown only offers 10 or 25 frames per page too. No pagination is offered.

**To Reproduce**
1. Go to an event with more than 25 frames
2. Click on Frames
3. See only 25 frames

**Expected behavior**
All frames shown (with pagination)

**Debug Logs**
No relevant errors in the web console

CC @knight-of-ni

**Comment by knight-of-ni** [comment]
I can view more than 25 frames at once. 

Since this is a UI problem, discuss this here:
https://github.com/ZoneMinder/zoneminder/issues/2991
