### ISSUE TITLE
Audit events report on firefox

### ISSUE THREAD

**Issue by jacobhallgren** [ZoneMinder/zoneminder#3055]
**Describe Your Environment** Ubuntu 20
- Version of ZoneMinder: 1.34.21

**Describe the bug**

When using Audit Events report on firefox jumping over motion highlighted event is off like 2 min. This only happens in firefox, not when using google chrome.

**Comment by connortechnology** [comment]
I'm not sure what you are actually reporting here.
Unfortunately the Audit Events Report was hastily constructed to satisfy a need of a major client who then killed the project before it could be properly finished.  It needs a lot of work.
