### ISSUE TITLE
Cause column needs to wrap the Event[Notes] field

### ISSUE THREAD

**Issue by vajonam** [ZoneMinder/zoneminder#3064]
**Describe Your Environment**
- Version of ZoneMinder - master snapshot
- How you installed ZoneMinder - PPA
- Full name and version of OS - Ubuntu 18.04 LTS (Docker Container) 
- Browser name and version (if this is an issue with the web interface) (Chrome 86+) 

**Describe the bug**
The notes field inside the cause column needs to wrap otherwise it doesn't layout correctly pushing the event id field out of view and not clicable. I store notes about the person/detection in the notes field for each event for historical purposes as I fine tune my system. 

![image](https://user-images.githubusercontent.com/152501/97218266-d9b93f80-179e-11eb-98b0-608521ba0810.png)

In the notes field I use `\n` and `\t` to create bit of formatting to its easy to see 

![image](https://user-images.githubusercontent.com/152501/97218426-0f5e2880-179f-11eb-9d25-bf2b7b0c4261.png)

**Expected Behavior** 

The notes field is rendered similar to the popup in the list view, or at the very least wrapped.

**Comment by vajonam** [comment]
@connortechnology I just added this locally to by build It didn't affect the events in the list view which was what the ticket was for, does it need to be compiled in? if so I can wait for snapshot build to include this

**Comment by connortechnology** [comment]
Hmm I just worked on the \n's and didn't notice about \t.  I suppose we could replace those with some &nbsp's.

**Comment by vajonam** [comment]
Can we not use the code that formats the code in the popup in the list
view? That is what I was thinking of doing.

**Comment by connortechnology** [comment]
There isn't any code in the popup, it's just a textarea.  Doing what textareas do.

perhaps the next best thing would be to stick it in a blockquote or something.

**Comment by vajonam** [comment]
Looks like there is a space in the `<br />` , look in the popup. 

![Screenshot from 2020-11-05 11-17-36](https://user-images.githubusercontent.com/152501/98266738-a625a480-1f58-11eb-8be6-52fd7185b91d.png)
