### ISSUE TITLE
Crud 3.2.0 vs custom commit?

### ISSUE THREAD

**Issue by BlueMax** [ZoneMinder/zoneminder#3075]
Hallo,
i've used Crud 3.2.0 (https://github.com/FriendsOfCake/crud/releases/tag/v3.2.0) for several months (custom setup) without issues (instead of using the custom commit set in git sub-module) with php7. I did not test it all too thoroughly though but everything i've tested worked so far including API. Regarding [the note](https://github.com/ZoneMinder/crud/commit/0bd63fb464957080ead342db58ca9e01532cf1ef) the [pull request](https://github.com/FriendsOfCake/crud/pull/582) seems to be merged.
Is it still advised to use that custom commit/repo instead of the final 3.2.0?
I'm currently creating an 'Alpine Linux' package with php8 and wondering what's the best choice. I guess Crud 3.2.0 is the last version compatible to CakePHP 2.x.

**Comment by connortechnology** [comment]
Yeah I suspect you are right.  I will take a look at 3.2.0 for 1.34 and version 6 for 1.35

**Comment by knight-of-ni** [comment]
This request completed in 645dca6bc92262883a23dceacf1621e5b5350026

**Comment by knight-of-ni** [comment]
Please use official Crud 3.2.0 from here out
