### ISSUE TITLE
'PurgeWhenFull' filter doesn't work

### ISSUE THREAD

**Issue by BlueMax** [ZoneMinder/zoneminder#3081]
Is it possible that the 'PurgeWhenFull' filter is broken on `release-1.34` branch (13 commits ahead of 1.34.22)? Everything works fine here but this filter. I'm on a custom, handcrafted Alpine Linux setup i'm working on for some weeks to fix the downstream package.

There are no warnings, errors or similar. Sending the filters SQL command manually results just in an empty response. Something is wrong but i don't know what. 

~~Can someone confirm upstream (`release-1.34` branch) is working properly?~~

~~Storage just runs full and NULL files are created afterwards. The filter doesn't kick in.~~

~~Edit: I'm using the `release-1.34` branch as a temporary workaround as the stable branch submodules are broken (Crud) when doing a git pull recursive.~~

Edit2: Looks like it has something to do with setting a non-default path for 'default' storage. The 'PurgeWhenFull' filter seems to still search (only after reinstall?) in the default folder (/var/lib/zoneminder/events) for unknown reason. If i symlink that folder to my custom folder (that is still visible in options/storage) the 'PurgeWhenFull' filter works properly again. Other filter are not affected and pick up the path in the first place. Maybe zmlinkcontent.sh is involved or changing password. I re-install Zoneminder a lot at the moment (but keep the database). Maybe that's related as well.

I can handle the rest. I will keep the issue open in case its of any value for you. Feel free to close.

![diskspace](https://user-images.githubusercontent.com/1403092/100521530-4196e780-319c-11eb-86e1-d73d6c5fb0c3.png)

**Comment by connortechnology** [comment]
Yeah so what happens is that if you don't specify a storage area to check, it defaults to "df .".  
Perhaps we should be actually checking for a default storage area, using that as the path, or falling back to ZM_DIR_EVENTS.
