### ISSUE TITLE
Slow log, new lines have a time in past

### ISSUE THREAD

**Issue by Tony763** [ZoneMinder/zoneminder#3086]
**Describe Your Environment**
v1.35.14 -latest master - ffmpeg version N-100082-g81503ac58a-5 with cuda
from-source
Ubuntu 18.04 with updates from 20.10

**If the issue concerns a camera**
- Annker
- 12
- 3840x2160 
- ZoneMinder Source Type: ffmpeg

**Describe the bug**
Log is out of sync with time, new lines appear with time in past., Difference between times increases in time. 

**To Reproduce**

**Expected behavior**
When new line appear, it should have actual time.

**Debug Logs**

Check screen video: [log.zip](https://github.com/ZoneMinder/zoneminder/files/5618382/log.zip)

![image](https://user-images.githubusercontent.com/5598750/100655355-72694f00-334b-11eb-8694-b96b7f471000.png)
![image](https://user-images.githubusercontent.com/5598750/100655592-cbd17e00-334b-11eb-8597-d9cbe38dae77.png)

**Comment by vajonam** [comment]
Can you confirm that the time inside your container matched? also logs aren't written all the time in INFO/WARN levels, so a delay of a few minutes is normal. have look in the logs folder /var/log/zm (for me) for all the logs.

**Comment by solarpenguin1** [comment]
Note how the same error message repeats over and over?  I am having the same issue with version 1.34.23 and 1.34.25.

![ZMViewLogUI](https://user-images.githubusercontent.com/49759489/115257434-b213b600-a0f5-11eb-9777-36ac2e984a95.jpg)
![LinuxLogFile](https://user-images.githubusercontent.com/49759489/115257436-b2ac4c80-a0f5-11eb-9ac4-51d11d427caf.jpg)

**Comment by connortechnology** [comment]
Fixed in aaa130937764730147670cdbe29b4aec17e7c6dc released in 1.34.26
