### ISSUE TITLE
Can not edit group and error when delete group

### ISSUE THREAD

**Issue by footballstar1102** [ZoneMinder/zoneminder#3088]
Describe Your Environment
v1.35.13 - ffmpeg version 4.2.4
Ubuntu 20.04

Describe the bug:
1. I use API edit group to edit group 11 but it become add group 12
![image](https://user-images.githubusercontent.com/75405285/100960874-c34b9400-3553-11eb-99fc-8f0457d008ab.png)
![image](https://user-images.githubusercontent.com/75405285/100960728-723ba000-3553-11eb-9c51-8de5eb8b8dae.png)

2. When I use API delete group, can delete child group but when I delete group is parent group, it gets an error because database not delete
![image](https://user-images.githubusercontent.com/75405285/100961032-1faeb380-3554-11eb-90ee-9b756648c222.png)
![image](https://user-images.githubusercontent.com/75405285/100961059-2d643900-3554-11eb-9ef4-c0aa6fc42cae.png)
![image](https://user-images.githubusercontent.com/75405285/100961107-466cea00-3554-11eb-8ff7-174999bcd24c.png)

**Comment by connortechnology** [comment]
I wasn't able to reproduce your delete error.  I was able to delete All groups just fine.  However I have altered the database to add FOREIGN KEY constraints which the option to CASCADE delete child rows.  So I MAY have fixed it.  You will have to let us know and re-open if that is the case.
I was able to reproduce and fix the edit case.
