### ISSUE TITLE
ZMA not stopped when setting monitor mode via API

### ISSUE THREAD

**Issue by mjj4791** [ZoneMinder/zoneminder#3101]
**Describe Your Environment**
- ZoneMinder: 1.35.16 / (1.35.16~20201215093554-bionic)
- installed from PPA (http://ppa.launchpad.net/iconnor/zoneminder-master/ubuntu)
-  Ubuntu 18.04.5 LTS (4.15.0-128-generic (SMP) x86_64)

**Describe the bug**
With a recent update, introduced this month, updating the state of a monitor no longer works as it should.
When the state is switched from modect to monitor (it from motion detection to a state without motion detection), the zma process is not stopped and thus motion detection continues to be executed, even when the monitor is in 'monitor' state

**To Reproduce**
1. Go to Web console, set monitor 2 in Modect mode
2. verify in linux, zma and zmc running for monitor 2 (zma and zmc both running, as expected):
```
> ps -ef | grep zm
   www-data 23200  2213 10 17:33 ?        00:00:01 /usr/bin/zmc -m 2
   www-data 23208  2213  4 17:33 ?        00:00:00 /usr/bin/zma -m 2
```
3. Next, set monitor to 'monitor' mode in web ui & verify in linux (zma stopped, as expected):
```
> ps -ef | grep zm
www-data 23433  2213  8 17:33 ?        00:00:02 /usr/bin/zmc -m 2
```

4. Next, switch monitor to 'modect' mode via API (zma and zmc running as expected):
```
> curl -XPOST http://zmhost/zm/api/monitors/2.json  -d "Monitor[Function]=Modect"
> ps -ef | grep zm
  www-data 23639  2213 10 17:35 ?        00:00:01 /usr/bin/zmc -m 2
  www-data 23642  2213  3 17:35 ?        00:00:00 /usr/bin/zma -m 2
```

5. Next, switch monitor back to 'monitor' mode via API (zmc restarted, **but zma still running**!):
```
> curl -XPOST http://zmhost/zm/api/monitors/2.json  -d "Monitor[Function]=Monitor"
> ps -ef | grep zm
  www-data 23642  2213  2 17:35 ?        00:00:02 /usr/bin/zma -m 2
  www-data 23904  2213 24 17:37 ?        00:00:00 /usr/bin/zmc -m 2
```

**Expected behavior**
Expected would be that zma gets correctly stopped when a monitor is switched from 'modect' to 'monitor' mode via the API (as it is the case, when this is done via the webinterface)

**Debug Logs**
Once the zma is still running when it should have stopped, i see repeated messages like this in the log:
```
2020-12-23 17:37:36 | zma_m2 |   | 23642 | ERR | Got empty memory map file size 0, is the zmc process for this monitor running? | zm_monitor.cpp | 592
-- | -- | -- | -- | -- | -- | -- | --
```

**Comment by connortechnology** [comment]
Fixed via a362f2a
