### ISSUE TITLE
Option loglevel=debug 

### ISSUE THREAD

**Issue by PrplHaz4** [ZoneMinder/zoneminder#3109]
**Describe Your Environment**
- Version of ZoneMinder: 1.34.22
- How you installed ZoneMinder: Docker (dlandon/zoneminder)

**If the issue concerns a camera**
- ZoneMinder Source Type: ffmpeg

**Describe the bug**
The help text for ffmpeg options says to set `loglevel=debug`, but when set ffmpeg logs a "not recognized" warning.

**To Reproduce**
1. Go to Monitor
2. Click on Source
3. Scroll down to Options
4. Enter `loglevel=debug` and save

**Expected behavior**
ffmpeg debug messages are logged.  If this is no longer a valid ffmpeg option it should be removed from the online help (or changed to the correct value).

**Debug Logs**
```
2021-01-15 16:12:31 | zmc_m1 |   | 14040 | WAR | Option loglevel not recognized by ffmpeg | zm_ffmpeg_camera.cpp | 409
```

**Comment by connortechnology** [comment]
Control of ffmpeg logging moved to Options -> Logging
