### ISSUE TITLE
Can add a simple send mail function？

### ISSUE THREAD

**Issue by jtliaw** [ZoneMinder/ZoneMinder#311]
I have follow thise set postfix but can't send email! 

http://www.zoneminder.com/wiki/index.php/How_to_install_and_configure_Postfix_as_a_Gmail_SMTP_relay_for_ZoneMinder_email_filter_events.

**Comment by SteveGilvarry** [comment]
Close? Wiki page is blank, not sure setting up mail relay is ZM issue.
