### ISSUE TITLE
mail error without use of it

### ISSUE THREAD

**Issue by ycodryn** [ZoneMinder/zoneminder#3111]
**Describe Your Environment**
- Version of ZoneMinder:  v1.34.22
- How you installed ZoneMinder: ppa:iconnor/zoneminder
- Full name and version of OS: docker baseimage:focal-1.0.0alpha1-amd64

**Describe the bug**
I`m not using any mail for zoneminder, all settings regarding mail are disabled so why I have these logs ?

**Debug Logs**
```
2021-01-19 04:28:46 | stdout | jan 19 06:28:46 13a22e86bcfe CRON[10302]: (root) MAIL (mailed 733 bytes of output but got status 0x0001 from MTA
-- | -- | --
2021-01-19 04:28:46 | stderr | sendmail: Cannot open mail:25
-- | -- | --

```

**Comment by knight-of-ni** [comment]
From the provided data, a cronjob is trying to send mail. The ZoneMinder source code does not use cron, which makes this topic inappropriate for our github forum. Please take this conversation to our slack or user forum.
