### ISSUE TITLE
Log reveals authentication details

### ISSUE THREAD

**Issue by alabamatoy** [ZoneMinder/zoneminder#3118]
**Describe Your Environment**
- Version of ZoneMinder: 1.34.22
- How you installed ZoneMinder: PPA
- Full name and version of OS Ubuntu 16.04LTS
- Browser name and version: N/A

**If the issue concerns a camera**
N/A

**Describe the bug**
Certain errors are reported in the log in such a way that it reveals the authentication details to the camera.  Here is an example:
Feb  2 04:08:30 [zm_server_name] zmc_m17[30585]: ERR [zmc_m17] [Unable to open input rtsp://admin:adminPW@10.1.1.173:554/cam/realmonitor?channel=1&subtype=0 due to: Connection refused]

**To Reproduce**
Most any connection problem to a camera.  Simply unpower a camera, for example.

**Expected behavior**
Log entries should have the login and PW stripped from the text posted and replaced with "login:password".  This should be a relatively simple string manipulation to remove the text between "//" and "@" and replace with something like "[login:password]" before the error is actually written to log.

**Debug Logs**
```
N/A
```

**Comment by knight-of-ni** [comment]
You've posted a bug report with no content, which basically amounts to a feature request. This has been requested before. Try searching this forum to see our position on this matter. If you want this changed, posting empty bug reports is not the way to do it.

**Comment by alabamatoy** [comment]
Well, that's not what I did.  I posted exactly what the format required, with the bug details, example log entry, versions etc etc.  I dont know why/how all that got deleted.

I disagree that this is a feature request, its a cybersecurity requirement.  Posting the creds to the logs (which often get emailed unencrypted like with logcheck) is really bad practice.

**Comment by knight-of-ni** [comment]
The point of contention is you posted a bug report with no content. That by definition demands it be closed, regardless of the topic.

I edited the content of your message.  FYI, `<!--` and `-->` are HTML comments... anything you type in-between these gets interpreted as a comment and will not render.

**Comment by anon8675309** [comment]
I am also affected by this security issue of passwords appearing in the logs.  I can confirm that this is still an issue as of today (tested in HEAD).

This ticket is marked as a "duplicate" but there's no indication of what ticket it duplicates and I was not able to find any when searching through open issues.  Is there another ticket that I should be commenting on?

This ticket should also have the "Security issue" label, as is seen on other tickets related to security, such as #2466.  I'd add it, but it appears that adding a label is an administrative action in GitHub (either that or I just don't know how to add labels in GitHub, which is entirely possible).

**Comment by anon8675309** [comment]
Passwords are still being written out to the logs. If anyone would be willing to point me to where the code is that is writing this log message, I will take a stab at creating a patch and submitting a pull request.

This should still be tagged as a security issue as I mentioned in my previous comment. It is not a duplicate of any other open issue.
