### ISSUE TITLE
zmfilter should log moves and copies

### ISSUE THREAD

**Issue by dodexahedron** [ZoneMinder/zoneminder#3155]
**Describe Your Environment**
- Version of ZoneMinder 1.127.20210210gitg393e8b582.el8
- How you installed ZoneMinder rpmfusion
- Full name and version of OS CentOS 8.3 mainline kernel 5.10.13

**Describe the bug**
When moving or copying an event, it'd be nice to log it.

I'll have a pull request ready shortly if this is wanted.

**Comment by connortechnology** [comment]
It does if you have debugging enabled.

**Comment by dodexahedron** [comment]
Yep. It seemed like an appropriate thing to log at info level, anyway, being a normal operational thing that might want to be audited, or when running zmfilter manually.

Closing, since this has been merged already.
