### ISSUE TITLE
I noticed that if I delete all the events using the X buttons below the live view, after another event arrives I cannot delete events any more without going back to the console and selecting the monitor again. Is this a bug or a feature? I'm using v1.34.23 on Debian 10 "Buster," with Firefox 84.0.1 (64 bit).

### ISSUE THREAD

**Issue by vansnyder** [ZoneMinder/zoneminder#3168]
**Describe Your Environment**
- Version of ZoneMinder [release version, development version, or commit]
- How you installed ZoneMinder [e.g. PPA, RPMFusion, from-source, etc]
- Full name and version of OS
- Browser name and version (if this is an issue with the web interface)

**If the issue concerns a camera**
- Make and Model
- frame rate
- resolution
- ZoneMinder Source Type:

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Debug Logs**
```

<insert debug logs here, please make sure they are within the ``` quotes so they are formatted properly>

```

**Comment by connortechnology** [comment]
I am unable to reproduce this.  
Is there anything interesting logged in javascript console? Right click, inspect element, console tab.
