### ISSUE TITLE
Groups API 

### ISSUE THREAD

**Issue by AngioC** [ZoneMinder/zoneminder#3175]
Hello!
Is it possible through API to retrieve the associated monitors given the group ID?
And is it possible given the Monitor ID to retrieve the associated group?

**Comment by connortechnology** [comment]
http://servername/zm/api/monitors/index/GroupId:1.json
will fetch all monitors in Group 1. 

in 1.34.* you can only grab all groups, so you would have to parse them yourself.
In current master you can do:
http://servername/zm/api/groups/index/MonitorId:1.json will return the groups that monitor 1 is in.

Please note that github issues is for bug reports.  You expressly didn't read our instructions when posting your question. This is not a support group.  Go to http://forums.zoneminder.com for future assistance.
