### ISSUE TITLE
import_zm_zones = yes keeps old zones and does not get them updated as they change

### ISSUE THREAD

**Issue by dinaras** [ZoneMinder/zoneminder#3193]
Hello !
I am using dlandon docker on ubuntu 20.04. I am using mostly gpu for object detection and using the new updated format for ml.
- My zoneminder version is 1.34.23. I have updated ES to:
- app:6.1.14, pyzm:0.3.36, ES:6.1.14 , OpenCV:4.5.1

I had a camera and was using the substream in modect and had defined 3 zones. to it
In objectconfig.ini i am using 
import_zm_zones=yes
only_triggered_zm_zones=yes

So when something is detected i am getting an image with the object detected and the zone is in white color.
At some point i decided to use main stream of the camera for better clarity and in order to leverage alpr api.
In the meantime i was fiddling with the zones in order to fire at the correct spot and get the object where i want it for best detection. 
Problem is that although the zones show correct;y when i edit them in the web interface, the frame shown with the object detect shows a zone that does not exist. Detection works well.

**To Reproduce**
1. Add a camera with 2 zones
2. detect an object some how
2. Change camera stream size, play with the zones a bit move them around
3. Detect another object

**Expected behavior**
I would expect as zones change, image of zone  will be updated accordingly. It appears that zoneminder correctly imports the changed zones, and does detection as expected, but for some reason zone drawing is not up to date

![Screenshot from 2021-03-08 17-01-55](https://user-images.githubusercontent.com/1213097/110338973-4d623780-8030-11eb-80f3-f66e707abbc5.png)
![Screenshot from 2021-03-08 17-02-19](https://user-images.githubusercontent.com/1213097/110338988-50f5be80-8030-11eb-9f7e-202ad00ed526.png)

**Debug Logs**
```
DBG2 [zmesdetect_m10] [ignoring polygon: cam_model_sequence as only_triggered_zm_zones is true]
DBG4 [zmesdetect_m10] [[monitor-10] overrides key:wait with value:5]
DBG2 [zmesdetect_m10] [import_zm_zones: match_reason=False and reason=None]
DBG2 [zmesdetect_m10] [Getting ZM zones using https://zoneminder.xxxxxxxxxxxxx.xx8443/zm/api/zones/forMonitor/10.json?username=xxx&password=yyy&user=xxx&pass=yyy]
DBG2 [zmesdetect_m10] [importing zoneminder polygon: main_gate_in [0,234 253,231 461,716 0,719]]
DBG2 [zmesdetect_m10] [importing zoneminder polygon: main_road_out [572,168 909,166 1157,364 586,373]]
DBG2 [zmesdetect_m10] [importing zoneminder polygon: main_gate_out [263,227 560,175 610,686 485,716]]

```

**Comment by knight-of-ni** [comment]
While zmeventgnotification is a great project, this isn't the place the post issues against it. You probably want to open an issue here:
https://github.com/pliablepixels/zmeventnotification

Start there and if it turns out it does have something to do with ZoneMinmder then we can circle back.
