### ISSUE TITLE
zmrepo for master possibly not being updated?

### ISSUE THREAD

**Issue by dodexahedron** [ZoneMinder/zoneminder#3201]
Not sure if this is intentional or not, but, since the 20210310 build, no builds have been pushed to rpmfusion for the master branch.

Thought I'd mention in case something broke in the toolchain.

**Comment by knight-of-ni** [comment]
RPMFusion? Sorry we only push releases to that repo.

Perhaps you zmrepo

**Comment by dodexahedron** [comment]
Oops yes. zmrepo.

**Comment by knight-of-ni** [comment]
So this breakage was caused by the addition of a new submodule on march 10. The rpm specfile needs to be updated and tested to reflect the change. I've got other priorities at the moment, but it's on my task list.

**Comment by knight-of-ni** [comment]
This first step to fixing this has been made in  commit 3be21d0

**Comment by knight-of-ni** [comment]
Rpms are building now and beginning to show in zmrepo. Dnf should report new packages in ~24 hours or less.

**Comment by dodexahedron** [comment]
Confirmed they're showing up on a CentOS 8 Stream box now.
Will run an upgrade tonight and report results.

**Comment by dodexahedron** [comment]
Upgrade went smoothly and zoneminder seems to be functioning properly.
Thanks!
