### ISSUE TITLE
The Stats table is no longer being updated

### ISSUE THREAD

**Issue by neillbell** [ZoneMinder/zoneminder#3219]
**Describe Your Environment**
- Version of ZoneMinder: 1.35.26 (1.35.26~20210421084449-bionic)
- How you installed ZoneMinder: PPA zoneminder-master
- Full name and version of OS: Ubuntu 18.04.5

**Describe the bug**
The ZoneMinder Stats table is no longer being updated.

**Expected behavior**
The ZoneMinder Stats table should be updated with the motion detection stats for each analyzed frame.

When I examine the Stats table the last event for which stats were recorded was at: 2021-04-19 20:16:09. This corresponds to the time that I installed zoneminder 1.35.26~20210419170703-bionic.

Edit: It looks like this originally started with the installation of 1.35.26\~20210417125040-bionic. I briefly downgraded to 1.35.26\~20210413091429-bionic while motion detection was broken and then installed 1.35.26~20210419170703-bionic once @connortechnology had fixed motion detection.

**Comment by connortechnology** [comment]
So... I've done a partial fix on this. Needs more testing/work.  We are now writing some stats, even better we are queuing them and batch writing them, which should reduce db load.

**Comment by neillbell** [comment]
I'm not seeing any stats being written at all. Is there something I need to do to get them working?

**Comment by connortechnology** [comment]
A number of fixes have been made.  Please check latest.

**Comment by connortechnology** [comment]
I believe this is fixed. CLosing.
