### ISSUE TITLE
Don't install

### ISSUE THREAD

**Issue by Carambox** [ZoneMinder/zoneminder#3229]
**Describe Your Environment**
- Version of ZoneMinder [1.34.26]
- How you installed ZoneMinder [AUR]
- Full name and version of OS Arch Linux x86_64  Kernel: 5.12.1-arch1-1 
- Browser name and version (Fireox)

**If the issue concerns a camera**
- Make and Model
- frame rate
- resolution
- ZoneMinder Source Type:

**Describe the bug**
Don't install because don't detect Sys::Mmap . I think that the version perl 5.32 don't contain this lib.

![error 1](https://user-images.githubusercontent.com/65746729/117583850-1dd2b880-b0cf-11eb-8bc3-c3079028cfec.png)

CMakeError.log

![error_2](https://user-images.githubusercontent.com/65746729/117583957-b5380b80-b0cf-11eb-91a1-68d6bb671f30.png)

**To Reproduce**

**Expected behavior**

**Debug Logs**
```

<insert debug logs here, please make sure they are within the ``` quotes so they are formatted properly>

```

**Comment by Carbenium** [comment]
Please take a look at https://aur.archlinux.org/packages/zoneminder/ for the packages needed on Arch to compile/run ZoneMinder.
Since this is no bug, I'm closing the issue.

For further discussion/help regarding installing ZoneMinder, please use the [forum](https://forums.zoneminder.com/). Thanks!
