### ISSUE TITLE
Add the ability to force RTSP over TCP in ffmpeg cameras.

### ISSUE THREAD

**Issue by malazar** [ZoneMinder/zoneminder#323]
I was capturing 10 cameras at 720p encoded with x264 and I was getting a lot of artefacts.
While examining my system for network problems I noticed that the video stream was being sent over UDP. It seems like avformat_open_input (I'm using latest ffmpeg from git) defaults to RTSP over UDP. 

This is what I did in FfmpegCamera::PrimeCapture to fix my issue:
AVDictionary *opts = 0;
av_dict_set(&opts, "rtsp_transport", "tcp", 0);
avformat_open_input( &mFormatContext, mPath.c_str(), NULL, &opts )

It's a quick fix but it would be nice if it is added as an option in the web interface, as I belive there are situations where streaming over UDP is prefferable.

**Comment by Ph0t0nX** [comment]
Unfortunately, there is a bug in ffmpeg's udp.c that causes missed packets.  A long time ago (back in 20111 or so), ffmpeg worked perfectly fine, and then someone added a circular ring buffer with p-threads that had a bug that caused missed packets like crazy. Then someone added a patch that "mostly" fixed it... it ran a lot better, but still drops packets now and then when live555 does not.  Currently the only alternatives are to go into udp.c and try to fix whatever was broken, or use live555 or some other rtsp client library.  I found udp.c to be too cryptic for my tastes, so I'm opting for the latter.  ffmpeg advertises that it can read a rtsp/rtp stream, but in reality it's not reliable enough to be used with the millions of IP cameras or media servers that stream via rtsp.

**Comment by Ph0t0nX** [comment]
Also, the TCP mode is a hack... RTP was built for UDP and later adapted for TCP in order to punch through firewalls.  TCP mode just bypasses that bug in udp.c, but then latency and bandwidth increase.

**Comment by knnniggett** [comment]
...or build ffmpeg yourself without pthreads.

**Comment by cagnulein** [comment]
hi guys, i have an issue that it's not related to zoneminder, but i can't find other topics on internet talking about it.

I have a VSTARCAM that only accepts rtsp via udp. On android works fine with the app ONVIFER but with linux or macos and ffmpeg i've got always this problem:

<pre>
$ ffmpeg -v trace -rtsp_transport udp -i rtsp://admin:XXXXXX@192.168.0.37:10554/udp/av0_0 -vframes 1 -timeout 10 /tmp/ipcam-contatore-acqua.jpg

ffmpeg version 4.1.4-1~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Raspbian 8.3.0-6+rpi1)
  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --arch=arm --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Splitting the commandline.
Reading option '-v' ... matched as option 'v' (set logging level) with argument 'trace'.
Reading option '-rtsp_transport' ... matched as AVOption 'rtsp_transport' with argument 'udp'.
Reading option '-i' ... matched as input url with argument 'rtsp://admin:XXXXXX@192.168.0.37:10554/udp/av0_0'.
Reading option '-vframes' ... matched as option 'vframes' (set the number of video frames to output) with argument '1'.
Reading option '-timeout' ... matched as AVOption 'timeout' with argument '10'.
Reading option '/tmp/ipcam-contatore-acqua.jpg' ... matched as output url.
Finished splitting the commandline.
Parsing a group of options: global .
Applying option v (set logging level) with argument trace.
Successfully parsed a group of options.
Parsing a group of options: input url rtsp://admin:XXXXXX@192.168.0.37:10554/udp/av0_0.
Successfully parsed a group of options.
Opening an input file: rtsp://admin:XXXXXX@192.168.0.37:10554/udp/av0_0.
Probing rtsp score:100 size:0
[tcp @ 0x1a73600] No default whitelist set
[tcp @ 0x1a73600] Original list of addresses:
[tcp @ 0x1a73600] Address 192.168.0.37 port 10554
[tcp @ 0x1a73600] Interleaved list of addresses:
[tcp @ 0x1a73600] Address 192.168.0.37 port 10554
[tcp @ 0x1a73600] Starting connection attempt to 192.168.0.37 port 10554
[tcp @ 0x1a73600] Connection attempt to 192.168.0.37 port 10554 failed: Connection refused
[tcp @ 0x1a73600] Connection to tcp://192.168.0.37:10554?timeout=0 failed: Connection refused
rtsp://admin:XXXXX@192.168.0.37:10554/udp/av0_0: Connection refused
</pre>

Why ffmpeg tries always to run in tcp while i'm asking to use udp?

**Comment by cagnulein** [comment]
> ...or build ffmpeg yourself without pthreads.

i've tried without success
<pre>
./ffmpeg -i rtsp://admin:888888@192.168.0.37:10554/tcp/av0_0 -vframes 1 -timeout 10 /tmp/ipcam-contatore-acqua.jpg
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04)
  configuration: --disable-pthreads
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
[tcp @ 0x55e040a2aac0] Connection to tcp://192.168.0.37:10554?timeout=0 failed: Connection refused
rtsp://admin:888888@192.168.0.37:10554/tcp/av0_0: Connection refused</pre>

**Comment by connortechnology** [comment]
No idea, but this is not the appropriate place to discuss this.  I would expect you to get better results bringing it up with the developers of ffmpeg.

**Comment by cagnulein** [comment]
@connortechnology i know, i have already post to the ML of ffmpeg. But since this is one of few post on internet about this issue, i was hoping to find a solution here ;)
