### ISSUE TITLE
Video writer incorrectly encoding rotated monitor for h264/libx264

### ISSUE THREAD

**Issue by neillbell** [ZoneMinder/zoneminder#3233]
**Describe Your Environment**
- Version of ZoneMinder: 1.35.28~20210513142518-bionic
- How you installed ZoneMinder: PPA
- Full name and version of OS: Ubuntu 18.04.5 LTS

**If the issue concerns a camera**
- Make and Model: SV3C SV-B01POE-1080P-L
- frame rate: 10fps
- resolution: 1920x1080
- ZoneMinder Source Type: ffmpeg
- ZoneMinder orientation:  Rotate Right
- ZoneMinder Video Writer: Encode
- ZoneMinder OutputCodec: h264
- ZoneMinder Encoder: libx264

**Describe the bug**
When the camera/video writer combination is configured as described above, the encoded video is not properly rotated. If the orientation is set to "Normal", the video is encoded correctly. Using camera passthrough also works correctly.

**Debug Logs**
No errors are observed in the logs

**Example Encoded Video**

https://user-images.githubusercontent.com/19613739/118365823-e13a0d80-b563-11eb-9bfe-cd177722c3cc.mp4

**Comment by connortechnology** [comment]
I thought this was going to be an easy fix, but alas no.  I looked into it, and everything LOOKS correct but the output is definitely crap.

So I can reproduce it, don't have a fix yet.
