### ISSUE TITLE
AUTH_TYPE=remote not working in 1.26.4

### ISSUE THREAD

**Issue by timwhite** [ZoneMinder/zoneminder#324]
Not sure what changed, but AUTH_TYPE=remote no longer worked for me in 1.26.4 but did work in 1.25.0.

We rely on AUTH_TYPE=remote for LDAP logins. In 1.26.4 you end up in an almost login loop with AUTH_TYPE=remote. Local logins work.

**Comment by NibbleNinja** [comment]
I know this thread is a bit older, and this may be off-topic, but can someone explain how to use LDAP logins for zoneminder? I have not been able to find any tutorials on that subject at all... (I'm still pretty new at this kind of stuff)
