### ISSUE TITLE
Streaming not working on Chrome when authentication is ON

### ISSUE THREAD

**Issue by danielmsantana** [ZoneMinder/ZoneMinder#328]
System: Ubuntu 12.04.4 LTS
ZoneMinder: v1.26.5

I was trying to figure this out for a while and just found out a bug when streaming images on Google Chrome. I'm not using Camboloza, just mjpeg streaming. It works like a charm on Firefox, but when I turn the authentication ON, images stop streaming on Chrome and i got a lot of error relating to authentication on the log files.

This same issue is reported here:
http://ubuntuforums.org/showthread.php?t=2077027&p=12379486#post12379486

Just turned auth OFF, and streaming is back ON on Chrome. I dont know if this is a problem on Chrome, Ubuntu, or ZM, but I thought it worth a look.

**Comment by SteveGilvarry** [comment]
Close?
