### ISSUE TITLE
Storage 100%

### ISSUE THREAD

**Issue by roddone** [ZoneMinder/zoneminder#3288]
**Describe Your Environment**
- 1.36.x
- installed from PPA iconnor
- Ubuntu Server 20.04

**Describe the bug**
I have a strange behaviours since the upgrade from latest 1.34 to the 1.36.x versions. all the events from my cameras disappeared and my storage is always 98-100% full.
![image](https://user-images.githubusercontent.com/34140141/121563023-517c6780-ca1a-11eb-91c0-6d9b70175e6b.png)
![image](https://user-images.githubusercontent.com/34140141/121563110-6822be80-ca1a-11eb-841d-096738320271.png)

Normaly I use the "PurgeWhenFull" filter to delete oldest events when storage is greater than 75%, so I imagine that's why my events disappeared, but I don't know what occupies so much space.
![image](https://user-images.githubusercontent.com/34140141/121563528-c8196500-ca1a-11eb-8fd7-6f3693f951fb.png)

Logs page never shows up so I can't see if there are any problems 
![image](https://user-images.githubusercontent.com/34140141/121563671-f0a15f00-ca1a-11eb-8a39-c87d78d0ce86.png)

Can you please help me to figure out the problem ? is there something I can do to help debugging ?
To be honnest I don't even know where to start digging 😅

Thx !

**Comment by SteveGilvarry** [comment]
I think you need to Add StorageArea eq NewStorage to the filter, by default it is looking at the default storage area.

**Comment by roddone** [comment]
Hi, 

I already tried this with no success :( 
![image](https://user-images.githubusercontent.com/34140141/121652323-d196e180-ca9b-11eb-9cb4-1cd2d7137cc0.png)

**Comment by connortechnology** [comment]
perhaps it is something else filling it up?

Maybe try running sudo zmaudit.pl -i
Maybe you have Options->System->OPT_FAST_DELETE checked?

**Comment by roddone** [comment]
I found what was the problem, it seems there was too much logs (7 Millions) and it was filling all disk space.

I did a truncate on table Logs and my storage was back to 38% and after a few hours it seems everything is back to normal.

Thank your for your help ;)

**Comment by roddone** [comment]
In case you wanted to dig deeper on this, or if it can help someone ...  

The storage reached 100% again, it appears there was (once again) too much logs. On way or another, it seems having too much logs fills the storage and once the storage is full, the system can't write events anymore, which cause errors and writes more and more logs in database.
I don't know why, but it also prevents the system to remove events even if "PurgeWhenFull" is correctly configured.

In my case, the solution was to set 'LOG_DATABASE_LIMIT' to 50000 and temporary disable analysis on my cameras. After a few hours the logs were purged, the extra events were deleted and everything went back to normal.
