### ISSUE TITLE
Playback of event recorded with non-zero "Frame Skip" value does not work

### ISSUE THREAD

**Issue by peloy** [ZoneMinder/ZoneMinder#329]
I put a monitor in "record" mode. The monitor is configured with a non-zero "Frame Skip" (configured in the Misc tab of the monitor configuration dialog). Events recorded this way are not playable. The log contains the following messages after trying to play back such an event:

2014-02-16 15:10:55.100864 web_php[13407].ERR-/usr/share/zoneminder/includes/functions.php/2344 [Timed out waiting for msg ]
2014-02-16 15:10:55.440802 web_js[9647].ERR-?view=event [getCmdResponse stream error: Timed out waiting for msg  - checkStreamForErrors()]
2014-02-16 15:11:15.412760 zms[13634].ERR-zm_event.cpp/1114 [Can't sendto on sd 8: No such file or directory]

I re-configured the monitor to use a zero frame skip value and playback of events recorded this way does succeed.

This is with ZoneMinder version 1.26.5 although I was experiencing the same problem with 1.26.0 before upgrading yesterday to 1.26.5. I am using the unofficial Ubuntu packages referenced from the ZoneMinder download page.

As a side note, I configured a non-zero frame skip value because I was looking into creating a time-lapse video, and my cameras are running at 5 fps, so the non-zero frame skip value would allow me to create the time-lapse video at any speed independently from the speed the camera is running at.

**Comment by knnniggett** [comment]
We've added some fixes related to frame skip in the master branch.  
Since you are using Ubuntu you should be able to install a development snapshot available in @connortechnology  's Ubuntu PPA and test.  

If this does not fix this issue then feel free to reopen the issue.
