### ISSUE TITLE
What is SubPath, SourceSecondPath in table Monitor?

### ISSUE THREAD

**Issue by HaoLVb** [ZoneMinder/zoneminder#3305]
Describe Your Environment
Version of ZoneMinder : 1.36.1
How you installed ZoneMinder : from source
Full name and version of OS : Ubuntu 20.04

Describe the bug:
What is SubPath, SourceSecondPath in table Monitor?

When I use both SourcePath and SourceSecondPath in a monitor. Monitor can not monitor or record

![Screenshot from 2021-06-23 09-33-14](https://user-images.githubusercontent.com/16622245/123026589-a3ec5980-d406-11eb-92ea-80d1dd3de43b.png)

**Comment by connortechnology** [comment]
This is not a bug report.  Ignoring our rules is not cool.

SourceSecondPath is a second url to stream from, for example if the audio is not included in the main stream and you need to grab it from somewhere else.

**Comment by connortechnology** [comment]
If you want to ask me question, please do so on slack or by email.
