### ISSUE TITLE
Focus configuration error

### ISSUE THREAD

**Issue by alabamatoy** [ZoneMinder/zoneminder#3308]
Amcrest_HTTP.pm, ZM version 1.37

In view=controlcap, under Focus tab, selecting "can focus" and "can focus continuous", then SAVE, then restart ZM, I get:

``
ERR  No focus type selected. Please select Continuous, Relative, Absolute           /usr/share/zoneminder/www/includes/Control.php     Line 157
``

Everything seems to work, though.

**Comment by connortechnology** [comment]
Is this still an issue?

**Comment by alabamatoy** [comment]
This appears to be fixed in latest master.  I have created a simple focus functionality for the Amcrest HTTP script.  Do you want that?
