### ISSUE TITLE
Installs a file with bad shebang: bin/zmsystemctl.pl

### ISSUE THREAD

**Issue by yurivict** [ZoneMinder/zoneminder#3331]
The FreeBSD ports framework complains:
```
====> Running Q/A tests (stage-qa)
Error: '/usr/bin/pkexec' is an invalid shebang you need USES=shebangfix for 'bin/zmsystemctl.pl'
```

This is because the correct path is ```/usr/local/bin/pkexe```.

**Comment by knight-of-ni** [comment]
zmsystemctl.pl is a wrapper for systems using systemd.
Since FreeBSD doesn't use systemd, neither zmsystemctl.pl nor polkit are needed.

You should reach out to the manager of that port to help determine how best to handle this.

**Comment by yurivict** [comment]
Ok, thanks!
