### ISSUE TITLE
1.36.3 Failing to record linked zones

### ISSUE THREAD

**Issue by rmk92** [ZoneMinder/zoneminder#3339]
**Describe Your Environment**
- Version of ZoneMinder [release version, development version, or commit]
1.36.3
(Unable to update to 1.36.5 due to bug #3271)

- How you installed ZoneMinder [e.g. PPA, RPMFusion, from-source, etc]
Built from 1.36.3 source + Debian source files on http://zmrepo.zoneminder.com/debian/release-1.36/buster/

- Full name and version of OS
Linux 5.13 on aarch64

- Browser name and version (if this is an issue with the web interface)
Firefox 91.0.2

**Describe the bug**
With two linked streams, one low-res for motion analysis and the other high-res for capturing, the high-res stream does not always get recorded when the low-res stream is put in alarm state.

For example:
The low-res stream recorded events at: 09:01:50 09:02:13 09:10:36 09:11:41 09:38:41.
The high-res stream recorded events at: 09:01:50 09:11:42
Each event on both streams was 14 seconds long.

**To Reproduce**
1. Setup a camera with two streams:
    First stream: low-resolution, Modect, passthrough, recording of jpeg frames, setup motion areas
    Second stream: high-resolution, Nodect, passthrough, no recording of jpeg frames, default motion area, linked to first stream.
2. Leave to run for an hour or so
3. Check recordings
4. Notice that e.g. the low-resolution stream has recorded 5 events whereas the high resolution stream has recorded only two.

**Expected behavior**
High resolution stream should record when the low resolution stream is triggered.

**Debug Logs**
Log is too large to include in, so attached instead.
[zm-1.log](https://github.com/ZoneMinder/zoneminder/files/7056170/zm-1.log)

**Comment by rmk92** [comment]
Reviewing the recordings from last night, one camera stopped recording its high-res stream at just after 11pm, the other just after 9pm. Despite the low-res detecting motion multiple times after that point (20+) there are no high-res recordings. Apart from changing the log setting (Errors -> Fatal top stop the inline CSP errors being logged) nothing else has changed in the setup.

**Comment by rmk92** [comment]
It would appear that, if a triggering stream (low-res) is restarted (or presumably started) after the corresponding linked stream (high-res) then the high-res won't ever be triggered until the high-res stream is itself restarted.

**Comment by connortechnology** [comment]
I've just committed a one line fix that will likely fix this issue.  We were only setting shared mem valid flag when actually quitting the zmc process, however over the course of dev from 1.32 to now, I have been trying to handle situations more gracefully than just quit and restart.  The disconnect from shared mem function wasn't setting the valid flag to false.  So now it will and so the monitor linking should detect when the motion detecting process has reloaded.  You will have to update to a master dev version or wait for me to release 1.36.6 which should be soon but I have no fixed date set.

**Comment by rmk92** [comment]
Is it safe to backport https://github.com/ZoneMinder/zoneminder/commit/6de8c71d2ab583784db8ec757f54491785b16fd3 to 1.36.3 ? I've done so, and it seems to fail after about 50 seconds of run with "Shared data not valid for monitor X" where X is every monitor I have. This message comes from zmtrigger.pl.

**Comment by connortechnology** [comment]
The fix was not a good one. See the current code:
 if (purpose == CAPTURE) {
    if (unlink(mem_file.c_str()) < 0) {
      Warning("Can't unlink '%s': %s", mem_file.c_str(), strerror(errno));
    }
    Debug(1, "Setting shared_data->valid = false");
    shared_data->valid = false;
  }

The important part is that only when purpose==CAPTURE should we set shared_data->valid=false

**Comment by rmk92** [comment]
Thanks, I can confirm that this appears to have fixed the issue. Thanks!
