### ISSUE TITLE
zm_rtsp_server crash

### ISSUE THREAD

**Issue by HaoLVb** [ZoneMinder/zoneminder#3344]
Describe Your Environment
Version of ZoneMinder : 1.36.1
How you installed ZoneMinder : from source
Full name and version of OS : Ubuntu 20.04

Describe the bug:
I have a problem, zm_rtsp_server was crashed. After i checked it was caused by a cam causing this error. I don't know the reason but I think a cam can't crash the system
![image](https://user-images.githubusercontent.com/16622245/131259674-2a5d922e-5790-43d5-be68-91f12c4781bd.png)

**Comment by AndrewwHummer** [comment]
Did you verify the rtsp stream is readable by other applications like VLC Media Player?

The cam may very well crash the system if the stream is not in the correct format or an execption is not handled correctly by the code.
Garbage in Garbage out. Sometimes this crashes a system.

Check that your stream is really readable.

Cheers :)

**Comment by connortechnology** [comment]
I have seen this crash as well, but it is very intermittent and I havn't caught it with debug logs turned on yet.
