### ISSUE TITLE
zmu - unable to pass "index" from console results in a warning message

### ISSUE THREAD

**Issue by locutus13** [ZoneMinder/zoneminder#3354]
Version of ZoneMinder: 1.36.7-bionic1 (ppa:iconnor/zoneminder-1.36)
OS: ubuntu 18.04.6 LTS

https://github.com/ZoneMinder/zoneminder/blob/e6f4cdb584267bc46432f18eebfe3819b57c21ea/src/zm_monitor.cpp#L1154-L1167

The following happens always when calling ZMU from console:

```
# zmu -U zmuser -P zmpass -m 1 -i -t
zmu[10309].WAR-zm_monitor.cpp/1167 [Invalid index -1 passed. image_buffer_count = 3]

```
This is a behavior new to the 1.36 release.

I have tried my best but I cannot find a way to pass an "index" via cli.

As the image generation still works I would consider this to be only a minor issue.

**Comment by connortechnology** [comment]
In the next release we will bump this warning down to a debug level log. It is merely a warning, every should work as expected otherwise.

To pass an image index use something like: 
# zmu -U zmuser -P zmpass -m 1 -i=1 -t=1
