### ISSUE TITLE
Cannot add a camera

### ISSUE THREAD

**Issue by sflitman** [ZoneMinder/zoneminder#3385]
Browser goes to the configuration page for a new source, but nothing happens when you click anything and I see this in apache's error log:

[client 127.0.0.1:58236] PHP Fatal error:  Uncaught ValueError: min(): Argument #1 ($value) must contain at least one element in /usr/share/zoneminder/www/skins/classic/views/monitor.php:459\nStack trace:\n#0 /usr/share/zoneminder/www/skins/classic/views/monitor.php(459): min()\n#1 /usr/share/zoneminder/www/index.php(303): require_once('...')\n#2 {main}\n  thrown in /usr/share/zoneminder/www/skins/classic/views/monitor.php on line 459, referer: http://localhost/zm/index.php

**Comment by DanwithArduino** [comment]
what version are you on?
