### ISSUE TITLE
Last analyse time for 2 Backyard was zero.

### ISSUE THREAD

**Issue by junior466** [ZoneMinder/zoneminder#3389]
**Describe Your Environment**
- v1.37.3
- PPA
- Ubuntu 20.04

**If the issue concerns a camera**
- Amcrest IP8M-2496EW-V2
- frame rate ?
- resolution 4K
- ZoneMinder Source Type:

**Describe the bug**
Errors in the log

**To Reproduce**
1. See logs

**Debug Logs**
```
Last analyse time for 2 Backyard was zero.

```

These errors keep filling the logs and sometimes, this camera can't be viewed. It does work most of the time.

**Comment by moom0o** [comment]
Also happening for me. I get random "No Data" in montage review at times.
