### ISSUE TITLE
1.36.11 missing EMAIL_ADDRESS option

### ISSUE THREAD

**Issue by Vikkeseta** [ZoneMinder/zoneminder#3396]
- Version of ZoneMinder 1.36.11
- How you installed ZoneMinder: PPA (deb http://ppa.launchpad.net/iconnor/zoneminder-1.36/ubuntu xenial main)
- Full name and version of OS Ubuntu VERSION="16.04.7 LTS (Xenial Xerus)"

**Describe the bug**
In webpage: Options - Email: option EMAIL_ADDRESS is missing and no triggered events are mailed
in log: "zmfilter_1 |   | 1655 | ERR | No email address defined, not sending email | zmfilter.pl"

**To Reproduce**
1. Go to 'options'
2. Click on 'email'

**Expected behavior**
Place to set email address to whom send email notifications

**Comment by connortechnology** [comment]
Email address is now set in the filter.  Each filter can now go to a different recipient.
