### ISSUE TITLE
Gentoo Linux No Longer Offer Zoneminder

### ISSUE THREAD

**Issue by jlpoolen** [ZoneMinder/zoneminder#3402]
Zoneminder's downloads page at https://zoneminder.com/downloads/
![2021-12-26_18-39-10](https://user-images.githubusercontent.com/227313/147429202-d3991f2b-7074-47a6-8ee0-df70c68b4a24.png)
 states underneath a Gentoo logo:

     ZoneMinder is available just by typing emerge zoneminder. Thanks to the Gentoo web-apps team for making this available.

This is no longer true.  The Zoneminder  package was removed from Gentoo in 2020.  See  https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=c66a9574205fcefe13c0b13a778af774f2703a0b

The Zoneminder downloads page is therefore inaccurate and should be updated.

**Comment by connortechnology** [comment]
It has been removed.
