### ISSUE TITLE
Cause now includes zone info, without accounting for the database restrictions

### ISSUE THREAD

**Issue by libraryaddict** [ZoneMinder/zoneminder#3403]
**Describe Your Environment**
- https://launchpad.net/~iconnor/+archive/ubuntu/zoneminder-master - which should be https://github.com/ZoneMinder/zoneminder/commit/eef172379c11c60a68236d3768495e962bef398f

- Installed with apt-get update, and upgrade
-  Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-91-generic x86_64)

**Describe the bug**

Cause in SQL database previously inserted "Motion", now it's inserting the zone information as well. However, nothing was done to account for the increased string length.

```
 Can't  run query INSERT INTO `Events` ( `MonitorId`, `StorageId`, `Name`,  `StartDateTime`, `Width`, `Height`, `Cause`, `Notes`, `StateId`,  `Orientation`, `Videoed`, `DefaultVideo`, `SaveJPEGs`, `Scheme` ) VALUES  ( 1, 2, 'New Event', from_unixtime(1640688323), 1920, 1080, ' Inner  Driveway,Outer Driveway, Motion', 'Motion: Inner Driveway, Outer  Driveway', 1, 1, 0, 'incomplete.mp4', 3, 'Medium' ): Data too long for  column 'Cause' at row 1
```

Introduced in https://github.com/ZoneMinder/zoneminder/commit/eef172379c11c60a68236d3768495e962bef398f I believe

**To Reproduce**
1. Have zone names that are long
2.  Trigger event

**Expected behavior**
Either cause to be 'Motion', or 'Cause' in database to have the column size increased.

**Comment by connortechnology** [comment]
Thanks for report! An event can have multiple causes so even without the zone names it could overflow.
