### ISSUE TITLE
Images not being attached to emails in 1.37.10

### ISSUE THREAD

**Issue by jgoerzen** [ZoneMinder/zoneminder#3422]
**Describe Your Environment**
This is Zoneminder 1.37.10~20220201.107-buster from zmrepo on Debian buster.

**Describe the bug**

After upgrading to 1.37 (accidentally; whoops), emails no longer contain an attachment of my image.

My template includes:

`%EIM%` at the end.

However, no attachment is made.  The rest of the email is processed fine.

I tried this with both the old and new email modules and that setting made no difference either way.

**To Reproduce**
Set %EIM% in an email body.

**Expected behavior**
Should have an attachment.

**Comment by connortechnology** [comment]
Thanks for reporting!
