### ISSUE TITLE
frame URL generate HTTP 500

### ISSUE THREAD

**Issue by pavkamlc** [ZoneMinder/zoneminder#3433]
**Describe Your Environment**
- Version of ZoneMinder [v1.37.10 installed on Centos 8 by stable yum repository]
- apache http proxy
- Browser name and version [chrome-stable]
- ZoneMinder Source Type: modect from rtsp stream camera

**Describe the bug**
When I view records from camera https://.....:8444/zm/?view=events
I see correct preview images from url https://......:8444/zm/index.php?eid=4413&fid=snapshot&view=image
When I click for frames, I get correct list of frames on https://...:8444/zm/?view=frames&eid=4415
But when I click for full view of frame I get HTTP 500 on URL https://....:8444/zm/?view=frame&eid=4415&fid=1800
When I go manually to the same address with image instead frame, page display the correct frame https://....:8444/zm/?view=image&eid=4415&fid=1800

**Expected behavior**
It can be linked to frame page and display frame image. It seems to be bug in the skin

**Debug Logs**
I found maybe irrelevant records in php-fpm/www-error.log
```

[14-Feb-2022 14:17:31 Europe/Prague] PHP Warning:  Division by zero in /usr/share/zoneminder/www/skins/classic/includes/functions.php on line 476
[14-Feb-2022 14:18:28 Europe/Prague] PHP Parse error:  syntax error, unexpected ')' in /usr/share/zoneminder/www/skins/classic/views/frame.php on line 122

```

**Comment by connortechnology** [comment]
Fixed by b6d2d96d1
