### ISSUE TITLE
Gapless events play much too fast

### ISSUE THREAD

**Issue by jjakob** [ZoneMinder/zoneminder#3439]
**Describe Your Environment**
zoneminder 1.36.12-focal1
ppa.launchpad.net/iconnor/zoneminder-1.36
Ubuntu 20.04.3 LTS
mariadb-server 1:10.3.32-0ubuntu0.20.04.1
browser: vimb 3.6.0-57-g6dbde47
user-agent `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Safari/605.1.15 vimb/3.6.0-57-g6dbde47`
```
Version:         3.6.0-57-g6dbde47
WebKit compile:  2.34.3
WebKit run:      2.34.5
GTK compile:     3.24.29
GTK run:         3.24.30
libsoup compile: 2.72.0
libsoup run:     2.74.2
```

**Describe the bug**
Gapless playback causes events to play much too fast (as if the rate was set to much higher than actual). It's not the gap between events or events getting switched too fast, the actual event video is played at a too fast rate, the playback and event switching is smooth.
May be related to #3407.

**To Reproduce**
1. click "Audit Events Report"
2. click a number of events for a monitor to get a list of events
3. click on the oldest event in the list
4. select "Gapless events", scale "Actual", codec "Auto", rate "1x"
5. first event will play at a normal speed, the next events will play at a much higher speed

**Expected behavior**
all events play at the same 1x speed

**Debug Logs**
I don't get any errors in web_php.log, apache error.log or browser console. zms_e*.log for the events I'm testing with also don't have anything other than old errors in the rotated logs:
```
02/17/22 11:37:15.752938 zms_e463534[149392].WAR-zm_eventstream.cpp/1076 [Unable to send raw frame 27: Resource temporarily unavailable rc 49152]
02/17/22 11:37:20.766744 zms_e463534[149392].WAR-zm_eventstream.cpp/1076 [Unable to send raw frame 28: Resource temporarily unavailable rc 24576]
02/17/22 11:46:25.527420 zms_e463534[149392].WAR-zm_eventstream.cpp/1076 [Unable to send raw frame 179: Broken pipe rc -32]
02/17/22 11:46:25.532501 zms_e463534[149392].INF-zm_eventstream.cpp/1090 [Unable to send raw frame 179: Broken pipe]
02/17/22 11:46:25.532537 zms_e463534[149392].ERR-zm_eventstream.cpp/725 [Can't send /var/cache/zoneminder/events/1/2022-02-17/463550/00179-capture.jpg: Broken pipe]
```

**Comment by connortechnology** [comment]
Fixed in 1.36.15.
