### ISSUE TITLE
Error when deleting more than 200 events

### ISSUE THREAD

**Issue by DemoFreak** [ZoneMinder/zoneminder#3444]
**Describe Your Environment**
- Version 1.36.12
- installed by RPM package
- Opensuse 15.3

**Describe the bug**
If "ALL" is selected in the event list, the events are not deleted as long as there are more than 200 events in the list.

**To Reproduce**
1. Go to an event list with more than 200 entries
2. Select "ALL" in the bottom drop-down box
3. Select all events
4. Press the delete button and confirm the security prompt
5. No event will be deleted

**Expected behavior**
All events will be deleted

**Comment by connortechnology** [comment]
I havn;t been able to reproduce this. I may have already fixed it.. I am about to release 1.36.13.  I suggest we evaluate that and see if it still needs fixing.

**Comment by connortechnology** [comment]
Will be included in 1.36.20
