### ISSUE TITLE
shared memory ever show 0%

### ISSUE THREAD

**Issue by sagitt** [ZoneMinder/zoneminder#3473]
**Describe Your Environment**
- ZM 1.36.14
- Ubuntu Server 18.04.6 LTS in VM Proxmox
- From PPA
- Google Chrome Stable last version

**If the issue concerns a camera**
- 3 HikVision (RTSP\FFmpeg) + 1 MotionEyeOS (HTTP)
- 20 fps + 5 fps
- 1280x720p
- My server have 20gb of ram for this VM, cameras have lot of pre\post-alarm frames. Like 2,5 gb maximum used for single cam.

**Describe the bug**
After upgrade from 1.34.X, all works fine but my shared memory is ever showed as 0%. Before upgrade there is a right used %. I expanded from fstab to 80% (like described ZM official wiki)

![Schermata 2022-04-28 alle 14 41 38](https://user-images.githubusercontent.com/169086/165754338-8d720579-4b48-4915-bdee-0d21700e8b4e.png)

**Comment by connortechnology** [comment]
We don't use as much shm as before.  In 1.37 we even removed the display of it in favour of just ram use.  Check df /dev/shm.
