### ISSUE TITLE
Email issue ZM 1.36.XX

### ISSUE THREAD

**Issue by phuongpham** [ZoneMinder/zoneminder#3474]
Not sure if this is a bugs or a "feature"
But after upgrading to ZM1.36 I had to add email details in the Event filter section.
The problem I have is I'm using ZM togheter Event Server and the email is sending out to quickly.
It means ES is not finished to processing, before ZM already sent the email.
It's somewhere to change so the email is not sending after ES is finished.

I'm using ALPR, object recognition and Face Recognition in ES.
The ES work fine with this functionality. I'm can see the different object recognition inside the zmninja app.

@connortechnology  I tried to registred new profile in the Zoneminder forum but never got the "activation email". Have already looked inside the spam inbox etc. but nothing there.

**Comment by phuongpham** [comment]
> Add an EndTime is not null rule to the filter. This will make it wait until the event is over before sending the email.
> 
> Yes there is something weird going on with forum email.

Great! I will try this out now

**Comment by phuongpham** [comment]
@connortechnology 
I added the additional filter as you explain.
The problem now is ZM doesn't send email any longer

<img width="703" alt="msedge_df1OzQp0Vv" src="https://user-images.githubusercontent.com/2634344/166096032-ded01095-e82d-4854-9fa8-c6356934042c.png">

**Comment by connortechnology** [comment]
Sorry, my mistake, End StartDate/Time.

**Comment by phuongpham** [comment]
> Sorry, my mistake, End StartDate/Time.

I changed to uppercase and seems like it work. But still end time not equal to NULL

**Comment by connortechnology** [comment]
Please post another screen shot. Also... I guess I was a little scatter brained on the weekend... the field is End Date/Time.  So End Date/Time IS NOT NULL.  When you select IS NOT, the text field is supposed to only allow NULL but for some reason isn't. So I'll have to fix that.  Please type in uppercase NULL (it should be case insensitive, but just in case, make it upper case).

**Comment by phuongpham** [comment]
> Please post another screen shot. Also... I guess I was a little scatter brained on the weekend... the field is End Date/Time. So End Date/Time IS NOT NULL. When you select IS NOT, the text field is supposed to only allow NULL but for some reason isn't. So I'll have to fix that. Please type in uppercase NULL (it should be case insensitive, but just in case, make it upper case).

This is what I have today

<img width="661" alt="msedge_jXo9EWEqjH" src="https://user-images.githubusercontent.com/2634344/166293789-141d00cd-66eb-4172-ab25-978aae7795c7.png">

**Comment by connortechnology** [comment]
You still have End Time instead of End Date/Time.  End Time is just the time component, like 8:43.  We need the entire field. Which is End Date/Time
