### ISSUE TITLE
Restricted Monitors

### ISSUE THREAD

**Issue by alabamatoy** [ZoneMinder/zoneminder#3476]
Under USERS tab, when editing a user, it displays "restricted monitors" with a list of available monitors.  Logically, selecting a monitor will restrict access to that monitor, but in fact its exactly opposite effect - it will restrict ALL monitors, allowing access to only the one selected in "restrict monitors" field.  Recommend change the text to "Restrict access to following monitor(s), leave blank for access to all monitors" or somesuch.
```

**Comment by enkore** [comment]
> Allowed monitors (blank=all)

**Comment by connortechnology** [comment]
I drastically altered the UI here in master.  We now have a more complex system and this is no longer relevant.
