### ISSUE TITLE
Bug: no way to disable a timestamp. Add an option to disable timestamp and make timestamp as an opt-in option (not opt-out)

### ISSUE THREAD

**Issue by AIGeneratedUsername** [ZoneMinder/zoneminder#3488]
- [ ] Add an option to disable timestamp because there is no such option on the "Monitor config --> Timestamp" page.
- [ ] Make timestamp as an opt-in option (not opt-out). An ugly large default timestamp overlaps a bottom part of a video and prevents to view what it going on on the video. My proposal is to disable timestamp be default. Who wants it - s(he) will be able to enable it.

### Versions

Zoneminder 1.36

**Comment by connortechnology** [comment]
Just clear the format line, timestamp goes away.

**Comment by AIGeneratedUsername** [comment]
> Just clear the format line, timestamp goes away.

I have an empty "Timestamp Label Format" field. I even rebooted my system to make sure that changes are applied. Timestamp is still attached on videos in "Events".
![timestamp](https://user-images.githubusercontent.com/70140627/169660961-cc13cb51-46cf-4e42-a0c9-d82b7bd6f958.png)
![config](https://user-images.githubusercontent.com/70140627/169660962-358b8be9-d3f6-48f6-93ce-74e27d44c27f.png)

**Comment by connortechnology** [comment]
Ah... that's not actually in the video (if you downloaded the mp4 and played it in vlc or something it wouldn't be there).  It's just video.js overlaying it.  I agree it should be turn off-able.
