### ISSUE TITLE
Live view/preview not loading

### ISSUE THREAD

**Issue by AdBol05** [ZoneMinder/zoneminder#3493]
**Describe Your Environment**
- Version of ZoneMinder 1.36.12
- Installed on TrueNAS as plugin
- TrueNAS CORE 12.0-U8
- Tried with Crome and Internet Explorer

**Describe the bug**
Succesfully installed zoneminder on TrueNAS and connected my cameras to it. Everything was working fine.
After addind users and shutting the server down (so I could wire up the cameras) and starting zoneminder again the server still reciesves streams from camera, saves events and so on, but the live view and preview isn't working now. Only showing this icon:
![image](https://user-images.githubusercontent.com/98588523/170842221-dc264814-e3e3-44a2-80de-ccf664ffa54c.png)

So I am unable to set my detection zones because I only get this:
![image](https://user-images.githubusercontent.com/98588523/170842288-b732e453-052e-4605-b797-b33d79810de7.png)

When I disable user authentication the images load just fine.

**Comment by connortechnology** [comment]
Check that AUTH_HASH_LOGINS is also checked and that your timezone settings are correct.

**Comment by AdBol05** [comment]
Thanks that worked out.
