### ISSUE TITLE
1.36.18 Not available. 1.36.19 available in PPA eventhough its not released.

### ISSUE THREAD

**Issue by amimbitassu** [ZoneMinder/zoneminder#3503]
1.36.18 not available in the PPA. 1.36.19 available in PPA even though its not released.

Am I missing something?

https://launchpad.net/~iconnor/+archive/ubuntu/zoneminder-1.36

**Comment by SteveGilvarry** [comment]
Some issue with versioning for .18 so .19 was released, but is the same as
.18. That was in Slack discussion
