### ISSUE TITLE
PHP-Process required to prevent image redraw flicker

### ISSUE THREAD

**Issue by gcsprojects** [ZoneMinder/zoneminder#3515]
**Describe Your Environment**
- ZoneMinder 1.36.19
- RPM Fusion
- Rocky Linux 8.6 (but also seen in CentOS 7 / 8)

**Describe the bug**
As per forum thread [here](https://forums.zoneminder.com/viewtopic.php?t=31831&start=15)
After upgrading to v1.36.17 or newer, the image in Live or Montage "flickers" on each redraw

As per the above forum post, after installing the **php-process** package and restarting, the issue is resolved
Can we have this package installed as part of the ZoneMinder installation/update process? 

**To Reproduce**
1. Go to 'Montage'
2. Each time the image redraws the image will go blank and rdraw - creating a flicker effect

**Expected behavior**
The image should update cleanly with.

**Debug Logs**
```


ERR | Unable to get semaphore. | /usr/share/zoneminder/www/includes/functions.php | 1907

```

**Comment by connortechnology** [comment]
This was fixed in 1.36.20
