### ISSUE TITLE
Blank screen postinstall

### ISSUE THREAD

**Issue by fdfytr** [ZoneMinder/zoneminder#3542]
Linux 5.18.14-arch1-1 x86_64 as VM on Debian
Installed package as per arch wiki page
Nginx + Mariadb

**Describe the bug**
`[error] 104234#104234: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class "IntlDateFormatter" not found in /usr/share/webapps/zoneminder/www/includes/config.php:142`

**Comment by baudneo** [comment]
I believe you need the php-intl package

**Comment by fdfytr** [comment]
Ive seen that suggestion at forum. Tried all, and that did not help

**Comment by connortechnology** [comment]
It all comes down to arch packaging. Not much we here can do about it.
