### ISSUE TITLE
Duration time on a web table is increased, but duration of records right.

### ISSUE THREAD

**Issue by spanchy** [ZoneMinder/zoneminder#3555]
**Describe Your Environment**
- Version of ZoneMinder [1.36.21] - Latest on debian repo.
- How you installed ZoneMinder [repository]
- Debian 11.4
- Chrome latest.
- 
**Describe the bug**
The time of events increases by the previous one in each row. All records are 10 min, but duration in row below is increased on a previous durations.

![image](https://user-images.githubusercontent.com/562733/182089388-faac2852-44e5-47a9-b84b-7fc535859ae5.png)

**Comment by amimbitassu** [comment]
Same issue on a fresh install Ubuntu 20.04 Zoneminder 1.36.21

![image](https://user-images.githubusercontent.com/93249404/182822074-68124e89-9f21-4f19-9a0c-c2fe9d0b5889.png)

**Comment by connortechnology** [comment]
Fixed by 22331e02cdb4a0813f86a521d0c1b3fcb7e3d6f4.  Included in 1.36.22.
