### ISSUE TITLE
Quick question about a possible Perl module dependency

### ISSUE THREAD

**Issue by Nocifer** [ZoneMinder/zoneminder#3577]
**Describe Your Environment**
- Zoneminder 1.36.24
- Arch Linux

**Describe the bug**
I was recently informed that `zmonvif-probe.pl` on Arch Linux produces an error about a missing `IO::Interface` module. I verified that the following error is produced if `zmonvif-probe` is used with an interface name:

```
$ zmonvif-probe.pl probe 1.1,1.2 enp0s3
IO::Interface module not available; use IP addr for interface at /usr/share/perl5/vendor_perl/WSDiscovery/TransportUDP.pm line 78.
```

But if  `zmonvif-probe` is run with an IP instead (as the above error suggests) then everything works as expected.

So, seeing as IO::Interface is AFAICT not mentioned anywhere in Zoneminder's dependency lists, can I correctly assume that internally it is only ever used by Zoneminder with IPs/sockets and not with interface names (this is also suggested by reading the code around line 78 of TransportUDP.pm) and so IO::Interface is indeed not a required module? Or am I completely off the mark here and IO::Interface is a dependency I have missed?

Thanks.

**Comment by connortechnology** [comment]
Sounds like a real dependency to me. I think I'll add it to the ubuntu deps..
