### ISSUE TITLE
Alarm status numbering change impacts API backward compatibility

### ISSUE THREAD

**Issue by mhilbush** [ZoneMinder/zoneminder#3584]
- Version of ZoneMinder:  1.36.16 or later 
- How you installed ZoneMinder:   Not sure
- Full name and version of OS:   Debian (and probably others)
- Browser name and version :  API

Users of the ZoneMinder integration with the openHAB smarthome platform have reported that their alarm status is no longer working for them after upgrading to a ZoneMinder version later than 1.36.15. They report that the alarm status never returns to IDLE (0).

The openHAB integration makes use of the following API call to get the alarm status of each monitor.
```
http://zoneminder.mydomain/zm/api/monitors/alarm/id:2/command:status.json
```

Instead of the alarm status returning to 0 (IDLE), they are reporting that the alarm status returns to 1 (PREALERT).

I see there was a commit included in 1.36.16 that changed the `UNKNOWN` alarm status from -1 to 0, and as a result incremented all the other alarm status by 1. Would that change have caused this behavior?

https://github.com/ZoneMinder/zoneminder/commit/1af63e151bc1bcce08ecc3ebae12dd3be2d2f36b

Reference our openHAB forum discussion starting here as we try to figure out what changed.

https://community.openhab.org/t/new-zoneminder-binding-for-zoneminder-versions-1-34-0/95112/406

**Comment by bceylon** [comment]
Same happens with zmNinja, live monitor view previously showed "idle" status which has changed and now "pre-alarm" is shown.
