### ISSUE TITLE
Issue after install

### ISSUE THREAD

**Issue by proximus26usa** [ZoneMinder/zoneminder#3586]
Running linux mint and I was trying to install zm, however random issue keep starting and going away. i resolved few but can;t get few resolved. 
I have really try everything and yet, i cant figure out why I am getting this error:

Sep 07 01:58:45 thanatos-linux zmpkg[7222]: ERR [Error reconnecting to db: errstr:Can't connect to local MySQL s>
Sep 07 01:58:45 thanatos-linux systemd[1]: zoneminder.service: Control process exited, code=exited, status=255/E>

Sep 07 02:01:29 thanatos-linux systemd[1]: zoneminder.service: Control process exited, code=exited, status=255/EXCEPTION
Sep 07 02:01:29 thanatos-linux systemd[1]: zoneminder.service: Failed with result 'exit-code'.
Sep 07 02:01:29 thanatos-linux systemd[1]: Failed to start ZoneMinder CCTV recording and surveillance system.

It is clear that I can't connect to DB, MySQL, however I was able resolve this issue, and was okay, then I start getting other alarms and this was back... Frustrating ...

I check dependencies (ZM, mysql, apache) and all is okay...

**Comment by connortechnology** [comment]
This isn't a bug in ZM, it is simply a misconfiguration on your system. First, verify that mysql is running.  Then check your user credntials using the command line mysql client.  

Please take this to either the forums (https://forums.zoneminder.com) or slack. Or if you are interested in paid support, reach out to isaac@zoneminder.com.
