### ISSUE TITLE
zmc continues to stream cameras in Monitor mode when they're not opened

### ISSUE THREAD

**Issue by kylejohnson** [ZoneMinder/ZoneMinder#360]
As I see it, if a camera is in Monitor mode, zmc should only be open for cameras that being streamed to the webui via zms or something similar.  Would save a lot of resources, no?

Is this a bug or a feature?  
##

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
