### ISSUE TITLE
Unable to add new storage

### ISSUE THREAD

**Issue by Matt-M-3** [ZoneMinder/zoneminder#3605]
**Describe Your Environment**
- Version of ZoneMinder [release version, development version, or commit]
1.36.27
- How you installed ZoneMinder [e.g. PPA, RPMFusion, from-source, etc]
PPA
- Full name and version of OS
Ubuntu Server 22.04.1
- Browser name and version (if this is an issue with the web interface)
Chrome

**Describe the bug**
As of 1.36.27, I am unable to add any new storage. I have a version of 1.36.26 within a VM that I am still able to do so. Upon attempting to add a new location, I am sent to a blank white page. Refresh asks if I want to resubmit the form. 

**To Reproduce**
1. Goto Options, Storage, Add New Storage.
2. Enter any location.
3. Click Save

**Expected behavior**
The addition of a new storage location. 

**Debug Logs**
```

<insert debug logs here, please make sure they are within the ``` quotes so they are formatted properly>

```
Date/Time,Component,Server,PID,Level,Message,File,Line
"10/7/22, 2:28:17 PM CDT",zmdc,,1490,ERR,"'zmwatch.pl' exited abnormally, exit status 9",zmdc.pl,'-
"10/7/22, 2:28:17 PM CDT",zmdc,,2319,INF,"'zmwatch.pl' started at 22/10/07 14:28:17",zmdc.pl,'-
"10/7/22, 2:28:17 PM CDT",zmdc,,1490,INF,"'zmwatch.pl' starting at 22/10/07 14:28:17, pid = 2319",zmdc.pl,'-
"10/7/22, 2:28:17 PM CDT",zmdc,,1490,INF,"Starting pending process, zmwatch.pl",zmdc.pl,'-
"10/7/22, 2:28:15 PM CDT",zmc_m1,,1518,INF,"Living Room: 66300 - Capturing at 14.33 fps, capturing bandwidth 104003bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:28:08 PM CDT",zmc_m1,,1518,INF,"Living Room: 66200 - Capturing at 15.00 fps, capturing bandwidth 98731bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:28:01 PM CDT",zmc_m1,,1518,INF,"Living Room: 66100 - Capturing at 14.85 fps, capturing bandwidth 96862bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:27:54 PM CDT",zmc_m1,,1518,INF,"Living Room: 66000 - Capturing at 14.85 fps, capturing bandwidth 107807bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:27:47 PM CDT",zmc_m1,,1518,INF,"Living Room: 65900 - Capturing at 15.02 fps, capturing bandwidth 97032bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:27:47 PM CDT",zmdc,,1490,ERR,"'zmwatch.pl' exited abnormally, exit status 9",zmdc.pl,'-
"10/7/22, 2:27:46 PM CDT",zmdc,,1490,INF,"'zmwatch.pl' starting at 22/10/07 14:27:46, pid = 2316",zmdc.pl,'-
"10/7/22, 2:27:46 PM CDT",zmdc,,2316,INF,"'zmwatch.pl' started at 22/10/07 14:27:46",zmdc.pl,'-
"10/7/22, 2:27:46 PM CDT",zmdc,,1490,INF,"Starting pending process, zmwatch.pl",zmdc.pl,'-
"10/7/22, 2:27:41 PM CDT",zmc_m1,,1518,INF,"Living Room: 65800 - Capturing at 14.84 fps, capturing bandwidth 96790bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:27:34 PM CDT",zmc_m1,,1518,INF,"Living Room: 65700 - Capturing at 14.86 fps, capturing bandwidth 107510bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:27:27 PM CDT",zmc_m1,,1518,INF,"Living Room: 65600 - Capturing at 15.24 fps, capturing bandwidth 100722bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:27:21 PM CDT",zmc_m1,,1518,INF,"Living Room: 65500 - Capturing at 14.76 fps, capturing bandwidth 95395bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:27:16 PM CDT",zmdc,,1490,ERR,"'zmwatch.pl' exited abnormally, exit status 9",zmdc.pl,'-
"10/7/22, 2:27:16 PM CDT",zmdc,,2313,INF,"'zmwatch.pl' started at 22/10/07 14:27:16",zmdc.pl,'-
"10/7/22, 2:27:16 PM CDT",zmdc,,1490,INF,"'zmwatch.pl' starting at 22/10/07 14:27:16, pid = 2313",zmdc.pl,'-
"10/7/22, 2:27:16 PM CDT",zmdc,,1490,INF,"Starting pending process, zmwatch.pl",zmdc.pl,'-
"10/7/22, 2:27:14 PM CDT",zmc_m1,,1518,INF,"Living Room: 65400 - Capturing at 14.98 fps, capturing bandwidth 107183bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:27:07 PM CDT",zmc_m1,,1518,INF,"Living Room: 65300 - Capturing at 15.32 fps, capturing bandwidth 99654bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:27:01 PM CDT",zmc_m1,,1518,INF,"Living Room: 65200 - Capturing at 14.61 fps, capturing bandwidth 93876bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:26:54 PM CDT",zmc_m1,,1518,INF,"Living Room: 65100 - Capturing at 15.06 fps, capturing bandwidth 108007bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:26:47 PM CDT",zmc_m1,,1518,INF,"Living Room: 65000 - Capturing at 15.06 fps, capturing bandwidth 98537bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:26:46 PM CDT",zmdc,,1490,ERR,"'zmwatch.pl' exited abnormally, exit status 9",zmdc.pl,'-
"10/7/22, 2:26:46 PM CDT",zmdc,,2310,INF,"'zmwatch.pl' started at 22/10/07 14:26:46",zmdc.pl,'-
"10/7/22, 2:26:46 PM CDT",zmdc,,1490,INF,"'zmwatch.pl' starting at 22/10/07 14:26:46, pid = 2310",zmdc.pl,'-
"10/7/22, 2:26:46 PM CDT",zmdc,,1490,INF,"Starting pending process, zmwatch.pl",zmdc.pl,'-
"10/7/22, 2:26:41 PM CDT",zmc_m1,,1518,INF,"Living Room: 64900 - Capturing at 14.76 fps, capturing bandwidth 95753bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:26:34 PM CDT",zmc_m1,,1518,INF,"Living Room: 64800 - Capturing at 14.77 fps, capturing bandwidth 106793bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:26:27 PM CDT",zmc_m1,,1518,INF,"Living Room: 64700 - Capturing at 14.95 fps, capturing bandwidth 96280bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:26:20 PM CDT",zmc_m1,,1518,INF,"Living Room: 64600 - Capturing at 15.10 fps, capturing bandwidth 97235bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:26:16 PM CDT",zmdc,,1490,ERR,"'zmwatch.pl' exited abnormally, exit status 9",zmdc.pl,'-
"10/7/22, 2:26:16 PM CDT",zmdc,,2308,INF,"'zmwatch.pl' started at 22/10/07 14:26:16",zmdc.pl,'-
"10/7/22, 2:26:16 PM CDT",zmdc,,1490,INF,"'zmwatch.pl' starting at 22/10/07 14:26:16, pid = 2308",zmdc.pl,'-
"10/7/22, 2:26:16 PM CDT",zmdc,,1490,INF,"Starting pending process, zmwatch.pl",zmdc.pl,'-
"10/7/22, 2:26:14 PM CDT",zmc_m1,,1518,INF,"Living Room: 64500 - Capturing at 14.43 fps, capturing bandwidth 104766bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:26:07 PM CDT",zmc_m1,,1518,INF,"Living Room: 64400 - Capturing at 14.98 fps, capturing bandwidth 98013bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:26:00 PM CDT",zmc_m1,,1518,INF,"Living Room: 64300 - Capturing at 14.70 fps, capturing bandwidth 105781bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:25:53 PM CDT",zmc_m1,,1518,INF,"Living Room: 64200 - Capturing at 15.01 fps, capturing bandwidth 98030bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:25:47 PM CDT",zmc_m1,,1518,INF,"Living Room: 64100 - Capturing at 14.83 fps, capturing bandwidth 95908bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:25:46 PM CDT",zmdc,,1490,ERR,"'zmwatch.pl' exited abnormally, exit status 9",zmdc.pl,'-
"10/7/22, 2:25:46 PM CDT",zmdc,,1490,INF,"'zmwatch.pl' starting at 22/10/07 14:25:46, pid = 2305",zmdc.pl,'-
"10/7/22, 2:25:46 PM CDT",zmdc,,2305,INF,"'zmwatch.pl' started at 22/10/07 14:25:46",zmdc.pl,'-
"10/7/22, 2:25:46 PM CDT",zmdc,,1490,INF,"Starting pending process, zmwatch.pl",zmdc.pl,'-
"10/7/22, 2:25:40 PM CDT",zmc_m1,,1518,INF,"Living Room: 64000 - Capturing at 14.84 fps, capturing bandwidth 105666bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:25:33 PM CDT",zmc_m1,,1518,INF,"Living Room: 63900 - Capturing at 14.76 fps, capturing bandwidth 96290bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:25:26 PM CDT",zmc_m1,,1518,INF,"Living Room: 63800 - Capturing at 14.93 fps, capturing bandwidth 96375bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:25:20 PM CDT",zmc_m1,,1518,INF,"Living Room: 63700 - Capturing at 14.57 fps, capturing bandwidth 105705bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:25:16 PM CDT",zmdc,,1490,ERR,"'zmwatch.pl' exited abnormally, exit status 9",zmdc.pl,'-
"10/7/22, 2:25:16 PM CDT",zmdc,,2302,INF,"'zmwatch.pl' started at 22/10/07 14:25:16",zmdc.pl,'-
"10/7/22, 2:25:16 PM CDT",zmdc,,1490,INF,"'zmwatch.pl' starting at 22/10/07 14:25:16, pid = 2302",zmdc.pl,'-
"10/7/22, 2:25:16 PM CDT",zmdc,,1490,INF,"Starting pending process, zmwatch.pl",zmdc.pl,'-
"10/7/22, 2:25:13 PM CDT",zmc_m1,,1518,INF,"Living Room: 63600 - Capturing at 14.85 fps, capturing bandwidth 96433bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:25:06 PM CDT",zmc_m1,,1518,INF,"Living Room: 63500 - Capturing at 15.48 fps, capturing bandwidth 100843bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:25:00 PM CDT",zmc_m1,,1518,INF,"Living Room: 63400 - Capturing at 14.43 fps, capturing bandwidth 103969bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:24:53 PM CDT",zmc_m1,,1518,INF,"Living Room: 63300 - Capturing at 14.87 fps, capturing bandwidth 95389bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:24:46 PM CDT",zmc_m1,,1518,INF,"Living Room: 63200 - Capturing at 14.88 fps, capturing bandwidth 107571bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:24:46 PM CDT",zmdc,,1490,ERR,"'zmwatch.pl' exited abnormally, exit status 9",zmdc.pl,'-
"10/7/22, 2:24:46 PM CDT",zmdc,,2299,INF,"'zmwatch.pl' started at 22/10/07 14:24:46",zmdc.pl,'-
"10/7/22, 2:24:46 PM CDT",zmdc,,1490,INF,"'zmwatch.pl' starting at 22/10/07 14:24:46, pid = 2299",zmdc.pl,'-
"10/7/22, 2:24:46 PM CDT",zmdc,,1490,INF,"Starting pending process, zmwatch.pl",zmdc.pl,'-
"10/7/22, 2:24:39 PM CDT",zmc_m1,,1518,INF,"Living Room: 63100 - Capturing at 15.13 fps, capturing bandwidth 97567bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:24:33 PM CDT",zmc_m1,,1518,INF,"Living Room: 63000 - Capturing at 14.96 fps, capturing bandwidth 97560bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:24:26 PM CDT",zmc_m1,,1518,INF,"Living Room: 62900 - Capturing at 14.89 fps, capturing bandwidth 107067bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:24:19 PM CDT",zmc_m1,,1518,INF,"Living Room: 62800 - Capturing at 15.25 fps, capturing bandwidth 98755bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:24:16 PM CDT",zmdc,,1490,ERR,"'zmwatch.pl' exited abnormally, exit status 9",zmdc.pl,'-
"10/7/22, 2:24:16 PM CDT",zmdc,,2295,INF,"'zmwatch.pl' started at 22/10/07 14:24:16",zmdc.pl,'-
"10/7/22, 2:24:16 PM CDT",zmdc,,1490,INF,"'zmwatch.pl' starting at 22/10/07 14:24:16, pid = 2295",zmdc.pl,'-
"10/7/22, 2:24:16 PM CDT",zmdc,,1490,INF,"Starting pending process, zmwatch.pl",zmdc.pl,'-
"10/7/22, 2:24:13 PM CDT",zmc_m1,,1518,INF,"Living Room: 62700 - Capturing at 14.59 fps, capturing bandwidth 95659bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:24:06 PM CDT",zmc_m1,,1518,INF,"Living Room: 62600 - Capturing at 14.85 fps, capturing bandwidth 106055bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:23:59 PM CDT",zmc_m1,,1518,INF,"Living Room: 62500 - Capturing at 14.70 fps, capturing bandwidth 96638bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:23:52 PM CDT",zmc_m1,,1518,INF,"Living Room: 62400 - Capturing at 15.01 fps, capturing bandwidth 97083bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:23:46 PM CDT",zmc_m1,,1518,INF,"Living Room: 62300 - Capturing at 14.99 fps, capturing bandwidth 108122bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:23:46 PM CDT",zmdc,,1490,ERR,"'zmwatch.pl' exited abnormally, exit status 9",zmdc.pl,'-
"10/7/22, 2:23:45 PM CDT",zmdc,,2292,INF,"'zmwatch.pl' started at 22/10/07 14:23:45",zmdc.pl,'-
"10/7/22, 2:23:45 PM CDT",zmdc,,1490,INF,"'zmwatch.pl' starting at 22/10/07 14:23:45, pid = 2292",zmdc.pl,'-
"10/7/22, 2:23:45 PM CDT",zmdc,,1490,INF,"Starting pending process, zmwatch.pl",zmdc.pl,'-
"10/7/22, 2:23:39 PM CDT",zmc_m1,,1518,INF,"Living Room: 62200 - Capturing at 14.86 fps, capturing bandwidth 95345bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:23:32 PM CDT",zmc_m1,,1518,INF,"Living Room: 62100 - Capturing at 14.87 fps, capturing bandwidth 96957bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:23:26 PM CDT",zmc_m1,,1518,INF,"Living Room: 62000 - Capturing at 14.99 fps, capturing bandwidth 107030bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:23:19 PM CDT",zmc_m1,,1518,INF,"Living Room: 61900 - Capturing at 14.98 fps, capturing bandwidth 97912bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:23:15 PM CDT",zmdc,,1490,ERR,"'zmwatch.pl' exited abnormally, exit status 9",zmdc.pl,'-
"10/7/22, 2:23:15 PM CDT",zmdc,,2290,INF,"'zmwatch.pl' started at 22/10/07 14:23:15",zmdc.pl,'-
"10/7/22, 2:23:15 PM CDT",zmdc,,1490,INF,"'zmwatch.pl' starting at 22/10/07 14:23:15, pid = 2290",zmdc.pl,'-
"10/7/22, 2:23:15 PM CDT",zmdc,,1490,INF,"Starting pending process, zmwatch.pl",zmdc.pl,'-
"10/7/22, 2:23:12 PM CDT",zmc_m1,,1518,INF,"Living Room: 61800 - Capturing at 15.03 fps, capturing bandwidth 96636bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:23:06 PM CDT",zmc_m1,,1518,INF,"Living Room: 61700 - Capturing at 14.98 fps, capturing bandwidth 107316bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:22:59 PM CDT",zmc_m1,,1518,INF,"Living Room: 61600 - Capturing at 15.00 fps, capturing bandwidth 97986bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:22:52 PM CDT",zmc_m1,,1518,INF,"Living Room: 61500 - Capturing at 14.84 fps, capturing bandwidth 94887bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:22:46 PM CDT",zmc_m1,,1518,INF,"Living Room: 61400 - Capturing at 15.00 fps, capturing bandwidth 107872bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:22:45 PM CDT",zmdc,,1490,ERR,"'zmwatch.pl' exited abnormally, exit status 9",zmdc.pl,'-
"10/7/22, 2:22:45 PM CDT",zmdc,,2287,INF,"'zmwatch.pl' started at 22/10/07 14:22:45",zmdc.pl,'-
"10/7/22, 2:22:45 PM CDT",zmdc,,1490,INF,"'zmwatch.pl' starting at 22/10/07 14:22:45, pid = 2287",zmdc.pl,'-
"10/7/22, 2:22:45 PM CDT",zmdc,,1490,INF,"Starting pending process, zmwatch.pl",zmdc.pl,'-
"10/7/22, 2:22:39 PM CDT",zmc_m1,,1518,INF,"Living Room: 61300 - Capturing at 15.02 fps, capturing bandwidth 97324bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
"10/7/22, 2:22:32 PM CDT",zmc_m1,,1518,INF,"Living Room: 61200 - Capturing at 14.82 fps, capturing bandwidth 96055bytes/sec Analysing at 0.00 fps",zm_monitor.cpp,1680
```

**Comment by connortechnology** [comment]
Thanks for the report.  Fixes are incoming and will be released tonight as 1.36.28.

**Comment by Matt-M-3** [comment]
Awesome! Question for anyone else, what's the turn around time for it to hit Ubuntu's PPA?

**Comment by connortechnology** [comment]
Packages should be building now.  Can take 15 minutes to a day though. Depending on how busy they are.
