### ISSUE TITLE
ZM doesn't create symlinks in events directory such as monitor name.

### ISSUE THREAD

**Issue by spanchy** [ZoneMinder/zoneminder#3613]
- latest from repo. version is 1.36.31
- repository debian 11
- Debian 11

Earlier in the ZM version, that soft created a symbolic link with the monitor name for my ID-monitor, now there is no such thing. Has a bug?
<img width="116" alt="no problem here" src="https://user-images.githubusercontent.com/562733/198072302-e6a625a5-e314-4d9e-8db0-9be272c7ce68.png">
<img width="107" alt="that's problem" src="https://user-images.githubusercontent.com/562733/198072335-a72152de-42c9-4be5-a4ef-628a5b8e9c93.png">

How I can setup my configuration for create symlink?

**Comment by connortechnology** [comment]
The symlink is created when saving the monitor.  It is used NOWHERE else in ZoneMinder. It is there purely for user convenience.  Some filesystems don't support symlinks, in which case it will not be created.  Which is why we don't use it anywhere else, because we can't count on it.

**Comment by spanchy** [comment]
> The symlink is created when saving the monitor.  It is used NOWHERE else in ZoneMinder. It is there purely for user convenience.  Some filesystems don't support symlinks, in which case it will not be created.  Which is why we don't use it anywhere else, because we can't count on it.

Hello, I'm have the installed zm (4 different server) and have setting archive drive on ext2, ext4, xfs filesystems - symlink not creating after saving monitor. I know that zm not used this symlinks, but I need them.

**Comment by connortechnology** [comment]
So I took a look at the code and found I could make some improvements.  So you can try out the version in my proposed ppa (ppa:iconnor/zoneminder-proposed), to get a pre-release of 1.36.32.  See if it solves your problems.

**Comment by spanchy** [comment]
> With the release of 1.36/32, those fixes should be generally available to debian using packages at zmrepo.
> 
> 
> 
> Can you update and report?

Hello, yes, of course. I add reply later.

**Comment by spanchy** [comment]
@connortechnology works fine. Thank you! Close it.
