### ISSUE TITLE
GUI version 1.37.25 vs released 1.36.31

### ISSUE THREAD

**Issue by radoslavv** [ZoneMinder/zoneminder#3617]
**Describe Your Environment**
- Version of ZoneMinder: **1.37.25** vs [1.36.31](https://github.com/ZoneMinder/zoneminder/releases/tag/1.36.31)
- How you installed ZoneMinder: **git + compile from source**
- Full name and version of OS: **Ubuntu 22.04**
- Browser name and version: **irrelevant**

**If the issue concerns a camera**
irrelevant

**Describe the bug**
different version in release notes [1.36.31](https://github.com/ZoneMinder/zoneminder/releases/tag/1.36.31)
![image](https://user-images.githubusercontent.com/5048591/198900803-60be72e4-38b9-4a11-81a4-453f67e06fea.png)
different version shown in GUI 1.37.25
![image](https://user-images.githubusercontent.com/5048591/198900870-62b84667-8962-4de0-87f1-81521d71811f.png)
+ Log 1.37.25
![image](https://user-images.githubusercontent.com/5048591/198900812-4844bcfc-122c-4980-961d-eb06d8e5df47.png)
Unclear which one is valid

**To Reproduce**
compile from sources 

**Expected behavior**
identical version in GUI and release notes

**Debug Logs**
not applicable

**Comment by connortechnology** [comment]
1.36.31 is the stable release.
1.37.25 is the latest development version, which has NOT been released.  

If you want to follow stable, follow the tags, or the release-1.36 branch.

**Comment by radoslavv** [comment]
OK, thx, clear now
