### ISSUE TITLE
ZM_PATH_ZMS=/cgi-bin/nph-zms instead of ZM_PATH_ZMS=/zm/cgi-bin/nph-zms

### ISSUE THREAD

**Issue by radoslavv** [ZoneMinder/zoneminder#3619]
**Describe Your Environment**
- Version of ZoneMinder: **1.37.25** (shown in web GUI)
- How you installed ZoneMinder: git + sources compile
- Full name and version of OS: **Ubuntu 22.04**
- Browser name and version: irrelevant

**If the issue concerns a camera**
irrelevant

**Describe the bug**
incorrect path in 01-system-paths.conf, missing /zm prefix in path

**To Reproduce**
compile from sources
1. cmake .
2. make
3. make install

check 01-system-paths.conf for ZM_PATH_ZMS
```
root@ubuntu_22:/etc/conf.d# cat 01-system-paths.conf | grep -B1 ZM_PATH_ZMS
# ZoneMinder url path to the zms streaming server
ZM_PATH_ZMS=/cgi-bin/nph-zms
```
**Expected behavior**
prefix /zm to be part of ZM_PATH_ZMS
```
# ZoneMinder url path to the zms streaming server
ZM_PATH_ZMS=/zm/cgi-bin/nph-zms
```

**Debug Logs**
not applicable

**Comment by connortechnology** [comment]
Kindly stop spamming our issues with your lack of configuration.

**Comment by radoslavv** [comment]
Apologies if you are considering this as spamming, in default configuration binary is in right place, but incorrect in config file.
I would say it is a bug.

**Comment by connortechnology** [comment]
No.  You need to tell it where you want things.  Every distro has different thoughts on the matter.
