### ISSUE TITLE
JSON generation of web backend fails in case of non-UTF8 characters

### ISSUE THREAD

**Issue by mispdev** [ZoneMinder/zoneminder#3631]
**Describe Your Environment**
- Ubuntu 22.04 (Jammy)
- ZoneMinder installed via the [`iconnor` PPA](http://ppa.launchpad.net/iconnor/zoneminder-1.36/ubuntu/dists/jammy/) for Jammy.

**Describe the bug**

PHP web backend is encoding data fetched from the DB to JSON using function `json_encode` in multiple locations. When data contains non-UTF8 characters, the conversion fails (with `json_last_error()` = `JSON_ERROR_UTF8` = `5`), and `json_encode` will return an empty string instead of valid JSON. This leads to a lot of errors in JSON delivered to the UI, which even renders UIs to be unusable.

Example: [Lines 107 to 108 in `web/skins/classic/views/js/montagereview.js.php`](https://github.com/ZoneMinder/zoneminder/blob/bfaf8c8b5399b4d9485bbcc5a9d2a637c4c2c782/web/skins/classic/views/js/montagereview.js.php#L107-L108)

```
    $event_json = json_encode($event, JSON_PRETTY_PRINT|JSON_NUMERIC_CHECK);
    echo " $event_id : $event_json,\n";
```

The code there is generating an element of a JSON array. If conversion with `json_encode` fails, an empty string is returned in `$event_json`. This leads to a generated JSON with syntax errors that is delivered to the UI, and causes the UI to fail (neither rendering properly, nor providing any sensible functionality to the user).

**To Reproduce**

 - Insert non-UTF8 characters into DB that will be fetched by PHP web backend to be converted to JSON, e.g. in description of manually triggered events.
 - Open a UI that will try to fetch all these events from DB and get it as proper JSON (e.g. montage review with an according time frame to include such events).
 - UI will break.

**Expected behavior**

UI renders correctly and provides sensible functionality to the user, even if non-UTF8 characters are stored within the DB.

**Debug Logs**

Just one example:

```
	web_php[781]. ERR [192.168.x.x] [Unable to decode JSON string 'array (
	[...PHP Array...]
	', unexpected error 5] at /usr/share/zoneminder/www/includes/functions.php line 1791
```

**Suggested Fix**

I proposed a fix in this [Pull Request](https://github.com/ZoneMinder/zoneminder/pull/3630). According to the ["Contribution Model and Development" section](https://github.com/ZoneMinder/zoneminder#contribution-model-and-development) of the README.md, I hereby open an issue to document this.

Excerpt of the Pull Request description:

Suggested Fix
=============

The issue can easily be avoided by setting the charater encoding of the DB connection to UTF8. After that, all data returned from DB queries will be proper UTF8, and all the JSON encodings with `json_encode` will work without problems.

All it takes to set the proper character encoding, is adding the desired character encoding to the connection string when opening the DB connection. This can easily be done by adding `;charset=utf8` at the end of the connection string.

Suggested fix is to do this in function `dbConnect` [line 49 of `web/includes/database.php`](https://github.com/ZoneMinder/zoneminder/blob/bfaf8c8b5399b4d9485bbcc5a9d2a637c4c2c782/web/includes/database.php#L49) by changing the line from

	`$dsn .= 'dbname='.ZM_DB_NAME;`

to

	`$dsn .= 'dbname='.ZM_DB_NAME.';charset=utf8';`

That's it. After that, all `json_encode` operations will succeed and the UI doesn't break anymore (even if non-UTF8 characters find their way somehow into the DB, e.g. by externally triggered events and their custom descriptions).

Tested
======

Using Ubuntu 22.04 (Jammy), installed ZoneMinder via the [`iconnor` PPA](http://ppa.launchpad.net/iconnor/zoneminder-1.36/ubuntu/dists/jammy/) for Jammy. Issue existed after installation. By changing the single line in the code (as suggested above), all issues were gone.

**Comment by connortechnology** [comment]
Fixed by #3630?
