### ISSUE TITLE
Options->Servers POST is broken

### ISSUE THREAD

**Issue by jonnio** [ZoneMinder/zoneminder#3649]
**Describe Your Environment**
- Version of ZoneMinder 1.36.32
- apt PPA
- Ubuntu 22.04 LTS
- Chrome

**Describe the bug**
Adding or editing **Servers** from the Servers tab on the **Options** menu is broken.

**To Reproduce**
1. Go to '.Options'
2. Click on 'Servers'
3. Scroll down to 'Add New Server'
4. See error in Log

**Expected behavior**
The Server could get created

**Debug Logs**
```
12/22/22, 12:45:19 PM EST | web_php |   | 10425 | FAT | View 'server' does not exist | /usr/share/zoneminder/www/index.php | 281
-- | -- | -- | -- | -- | -- | -- | --
12/22/22, 12:45:19 PM EST | web_php |   | 10425 | ERR | actions can no longer be performed without POST. Requested: save for server | /usr/share/zoneminder/www/index.php | 200

```

Simple fix to add action to the modal form.

**Comment by connortechnology** [comment]
Should be fixed by  f96c90ffa790c4516ade9ef5ee7be4cdf7087a75.  Will be included in 1.36.33.  You can test it by using the proposed ppa.

ppa:iconnor/zoneminder-proposed
