### ISSUE TITLE
'\' character deleted in FTP password

### ISSUE THREAD

**Issue by Tiller** [ZoneMinder/zoneminder#3655]
**Describe Your Environment**
- Version of ZoneMinder : 1.34.23
- How you installed ZoneMinder : debian repository
- Full name and version of OS : debian 11
- Browser name and version : lastest firefox

**Describe the bug**
My FTP password contains the character `\`. In configuration > upload, if I enter my password as-is, it fails to upload any files. And when I come back to the page, the `\` disappeared.
The solution is to put `\\` instead of `\`, however the next time you load the page, a single `\` will be displayed and saving the page will lead to an incorrect password.

**To Reproduce**
1. Go to options >upload
2. Set a FTP password with `\`
3. Save and reload the page
4. The `\` got deleted and the actual password used for upload won't contain the character

**Comment by connortechnology** [comment]
Please note that 1.34 has long been unsupported.  It is unlikely that this fix will make it into official debian packages.  You may want to either apply the patch manually yourself or update to a newer version of zoneminder.  We provide packages at https://zmrepo.zoneminder.com
