### ISSUE TITLE
filling 100% of RAM when using DecoderHWAccelName = VAAPI 

### ISSUE THREAD

**Issue by Habraten** [ZoneMinder/zoneminder#3672]
ZoneMinder [v1.36.32]
installed ZoneMinder from RPMFusion
CentOS 7.9 (kernel 3.10.0-1160.83.1.el7.x86_64)
Xeon® E3-1270 v3
24 Gb Ram
AMD RX 550 2Gb (Radeon™ Software for Linux® version 21.10 for RHEL 7.9)

7 cameras. 1080p H.264. 25 fps
Save JPEG Disabled 
- 2 cameras in Record passthrough 
- 5 cameras in Modect
-  DecoderHWAccelName = VAAPI
- also tried set DecoderHWAccelDevice: /dev/dri/renderD128 (But I guess it didn't make sense because [If not specified, it will attempt to open the default X11 display ($DISPLAY) and then the first DRM render node (/dev/dri/renderD128](https://ffmpeg.org/ffmpeg.html) )

System at startup shows consumption of about 7 GB RAM and after slowly by 100-200mb grows until it takes up of all RAM and the swap file. When I turn off VAAPI on all monitors then memory consumption stabilized.
any ideas about this?

**Comment by SteveGilvarry** [comment]
Closing as possible 1.36 issue, please test with current development version 1.37.xx and reopen if still seeing this.
