### ISSUE TITLE
New monitor insert fails, possibly because there were no other monitors before.

### ISSUE THREAD

**Issue by myankele** [ZoneMinder/zoneminder#3691]
**Environment**
Version: zoneminder/jammy,now 1.37.37~20230421175235-jammy amd64 [installed]
Installed using standard apt method using master tip

**Code**
https://github.com/ZoneMinder/zoneminder/blob/a256056d0a3a8bccabb57ae8328bfd6498e3d6c9/web/includes/actions/monitor.php#L244

I had to add:
$changes['Deleted'] = 0;
below line 244.

Also, tried around line 90:
 // Define a field type for anything that's not simple text equivalent
  $types = array(
      'Deleted' => 0,
      'Triggers' => array(),
But, it didn't work, although this seems like the right place.

**To Reproduce**
Start from fresh ZM install and add a monitor.  I didn't have a ZM DB previously on this machine.

**Log**
<html><body>

4/22/23, 2:03:17 AM MDT | web_php | 29390 | ERR | SQL-ERR  'SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for  column 'Deleted' at row 1', statement was 'INSERT INTO `Monitors` (`Id`,  `Name`, `Deleted`, `Notes`, `ServerId`, `StorageId`, `ManufacturerId`,  `ModelId`, `Type`, `Capturing`, `Analysing`, `Recording`,  `RecordingSource`, `AnalysisSource`, `AnalysisImage`, `Enabled`,  `Decoding`, `JanusEnabled`, `JanusAudioEnabled`,  `Janus_Profile_Override`, `Janus_Use_RTSP_Restream`, `Janus_RTSP_User`,  `Janus_RTSP_Session_Timeout`, `LinkedMonitors`, `Triggers`,  `EventStartCommand`, `EventEndCommand`, `ONVIF_URL`, `ONVIF_Username`,  `ONVIF_Password`, `ONVIF_Options`, `ONVIF_Alarm_Text`,  `ONVIF_Event_Listener`, `use_Amcrest_API`, `Device`, `Channel`,  `Format`, `V4LMultiBuffer`, `V4LCapturesPerFrame`, `Protocol`, `Method`,  `Host`, `Port`, `SubPath`, `Path`, `SecondPath`, `Options`, `User`,  `Pass`, `Width`, `Height`, `Colours`, `Palette`, `Orientation`,  `Deinterlacing`, `Decoder`, `DecoderHWAccelName`,  `DecoderHWAccelDevice`, `SaveJPEGs`, `VideoWriter`, `OutputCodec`,  `Encoder`, `OutputContainer`, `EncoderParameters`, `RecordAudio`,  `RTSPDescribe`, `Brightness`, `Contrast`, `Hue`, `Colour`,  `EventPrefix`, `LabelFormat`, `LabelX`, `LabelY`, `LabelSize`,  `ImageBufferCount`, `MaxImageBufferCount`, `WarmupCount`,  `PreEventCount`, `PostEventCount`, `StreamReplayBuffer`,  `AlarmFrameCount`, `SectionLength`, `SectionLengthWarn`,  `MinSectionLength`, `FrameSkip`, `MotionFrameSkip`, `AnalysisFPSLimit`,  `AnalysisUpdateDelay`, `MaxFPS`, `AlarmMaxFPS`, `FPSReportInterval`,  `RefBlendPerc`, `AlarmRefBlendPerc`, `Controllable`, `ControlId`,  `ControlDevice`, `ControlAddress`, `AutoStopTimeout`, `TrackMotion`,  `TrackDelay`, `ReturnLocation`, `ReturnDelay`, `ModectDuringPTZ`,  `DefaultRate`, `DefaultScale`, `SignalCheckPoints`, `SignalCheckColour`,  `WebColour`, `Exif`, `Sequence`, `ZoneCount`, `Refresh`,  `DefaultCodec`, `Latitude`, `Longitude`, `RTSPServer`, `RTSPStreamName`,  `Importance`, `MQTT_Enabled`, `MQTT_Subscriptions`) VALUES (?, ?, ?, ?,  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'  params:,East  Side,,,0,2,4,,Remote,Always,Always,OnMotion,Primary,Primary,FullColour,0,Always,0,0,,0,,0,,,,,,,,,,0,0,,0,0,,1,http,simple,192.168.2.5,80,,mjpeg,,,,,1600,1200,4,0,ROTATE_0,0,,,,2,0,0,auto,,#  Lines beginning with # are a comment # For changing quality, use the  crf option# 1 is best, 51 is worst  qualitycrf=23,0,0,-1,-1,-1,-1,Event-,%N - %d/%m/%y  %H:%M:%S,0,0,2,3,0,0,5,5,0,1,600,0,10,0,0,5,0,,,100,6,6,0,,,,,0,,-1,,0,100,0,0,#0000be,#2e9cd0,0,1,0,,auto,,,0,,Normal,0,
-- | -- | -- | -- | --

</body>
</html>

<html><body>

4/22/23, 2:03:17 AM MDT | web_php | 29390 | ERR | Error saving new Monitor. | /usr/share/zoneminder/www/includes/actions/monitor.php | 268
-- | -- | -- | -- | -- | -- | --

</body>
</html>

**Notes**
The Deleted field is blank, and I guess it needs to be an Int ? 0 or 1?  
params:,East  Side,(Needs to be 0 ?),,0,2
After adding above hack, it works, but I suspect I won't be able to delete a monitor now, so not a good solution.

**Comment by connortechnology** [comment]
I may have already fixed this one... I had to change the default for Deleted to 0 instead of false.
