### ISSUE TITLE
Redhat install instructions should mention that ARMv7 is unsupported in >F36, which is EOL this June

### ISSUE THREAD

**Issue by ruzko** [ZoneMinder/zoneminder#3697]
Zoneminder doc:
https://zoneminder.readthedocs.io/en/latest/installationguide/redhat.html#background-fedora

Relevant Fedora doc:
https://fedoraproject.org/wiki/Changes/RetireARMv7

**Comment by SteveGilvarry** [comment]
Fixed via #3698
