### ISSUE TITLE
Empty email body 

### ISSUE THREAD

**Issue by mfaroukg** [ZoneMinder/zoneminder#3708]
**Describe Your Environment**
- Version of ZoneMinder 1.37.40
- How you installed ZoneMinder : PPA
- Full name and version of OS: Ubuntu 22.10
- Browser name and version : Chrome, Firefox, ... etc

**Describe the bug**
The email received using OPT_EMAIL body is empty 

**To Reproduce**
1. Go to Options.
2. Tick OPT_EMAIL option to enable
3. Go to Filters
4. Create a proper filter that works in the background and send the following:
subject: ZoneMinder: Alarm from *** - %MN%-%EI% %EC%
body: ZM alarm detected :
	Name of the monitor : %MN%
	Number of events for the monitor in the last hour : %MEH%
	Cause of the event : %EC% 
	Time of the event : %ET%
	Attach first alarmed event image: %EI1%
	Attach (first) event image with the highest score : %EIM%
        Path to the event stream: %EPS%
6. Setup the ssmtp application 
7.  Alarm generated 
8. receive email with correct subject but no email body 

**Expected behavior**
Expected to see the text and photos attached as per version 1.36.xx

**Debug Logs**
"5/15/23, 9:32:12 AM GMT+1",zmfilter_3,326749,INF,"Notification email sent to [info@example].com",zmfilter.pl,'-
"5/15/23, 9:32:12 AM GMT+1",zmfilter_3,326749,INF,"Attaching '/var/cache/zoneminder/events/1/2023-05-15/25675/00006-capture.jpg' which is 23858 bytes",zmfilter.pl,'-
"5/15/23, 9:32:12 AM GMT+1",zmfilter_3,326749,INF,"Attaching '/var/cache/zoneminder/events/1/2023-05-15/25675/00005-capture.jpg' which is 23867 bytes",zmfilter.pl,'-

**Comment by connortechnology** [comment]
Latest should fix this. You might want to consider switching to html body so that inline images work...
