### ISSUE TITLE
ZM (2:1.32.3) in D10 repo brakes zm installation from zm repos (1:136:33) when updateting system

### ISSUE THREAD

**Issue by speefak** [ZoneMinder/zoneminder#3716]
zoneminder package in debian repos updated to version 2:1.32.3. This is allready ZM v1.32 and downgrades / brakes the zm 1.36.33 installation when updated OS

echo deb https://zmrepo.zoneminder.com/debian/release-1.36 buster/ | sudo tee -a /etc/apt/sources.list
wget -O - https://zmrepo.zoneminder.com/debian/archive-keyring.gpg | sudo apt-key add -
sudo apt update
 
# install selected version ( 1.36.33 )
sudo apt install zoneminder=1.36.33-buster2
 
# prevent zoneminder from update for Debian 10 
sudo apt-mark hold zoneminder
 
# configure system services
sudo systemctl enable zoneminder.service
sudo systemctl start zoneminder 
sudo a2enconf zoneminder
sudo a2enmod rewrite
sudo systemctl reload apache2

=> https://speefak.spdns.de/oss_lifestyle/zoneminder-leistungsstarke-opensource-videoueberwachung/#Software-Installation

**Comment by connortechnology** [comment]
So I think it is unlikely that we can do anything about this, other than add it to the documentation.  I don't know why their version would start with a 2.  

I wonder if 1.37 packages are similarly affected.
