### ISSUE TITLE
Monitors.Triggers Column: MySQL SET Datatype?

### ISSUE THREAD

**Issue by jlpoolen** [ZoneMinder/ZoneMinder#372]
I've created a set of tables for PostgreSQL.

The only question I have concerns the columns Monitors.Triggers.  A dump of the table from MySQL has that column defined as:
  `Triggers` set('X10') NOT NULL DEFAULT '',

Is there a specific reason why the MySQL "SET" datatype was used?  Any suggestions on an equivalent 1 byte substitute for PostgreSQL?

http://ftp.nchu.edu.tw/MySQL/tech-resources/articles/mysql-set-datatype.html

**Comment by knnniggett** [comment]
I'm going to close this out due to inactivity.
Feel free to reopen it if there are any new developments.
