### ISSUE TITLE
1.36.33 - Can`t change storge directoriees 

### ISSUE THREAD

**Issue by speefak** [ZoneMinder/zoneminder#3721]
zm on Debian 10 / php 7.3 

storage directory change were not accepted, i create storage dir to an usb disk, the new storage dir is listet in the zm interface but it is not used. I disabled and later delete the default storage dir ( var(cahce/zoneminder ) but the error still persists. Sometimes in the past i got this problem, so i create a symlink in /var/cache/zoneminder to /storage/dir.

This works great but some routines overwrite the symlink with a directory, so zoneminder delete all records using the "disk full " filter if the default storage is used.

The sollution is now to remount the target storage dir into the zm default dir ( mount --bind </storage/dir> /var/cache/zoneminder ) 

Should work but a working configuration in the zm interface is better.

regards speefak

**Comment by speefak** [comment]
i wrote a little check script : 

 (https://speefak.spdns.de/oss_lifestyle/zoneminder-leistungsstarke-opensource-videoueberwachung/#Tipps-und-Tricks)

(Storage Pfade ändern)

**Comment by ovargasp** [comment]
speefak, when you create a storage area for Zoneminder, in order for zm to use it, you have to configure it in the monitor(s) you want stored there, else is going to show as configured but is not going to record in that location...

![zmstorage](https://github.com/ZoneMinder/zoneminder/assets/59069596/48cde9c0-cec7-4c8c-ad3d-1053c8c797b2)
