### ISSUE TITLE
Debian Bookworm - can't update/install ZoneMinder v1.37.x via zmrepo

### ISSUE THREAD

**Issue by jzahraoui** [ZoneMinder/zoneminder#3730]
Hello :)
this not a bug but simply a kind of feature request.
want to be able to get the benefit of the 1.37 version on my installation.
I based on the previous ticket : https://github.com/ZoneMinder/zoneminder/issues/3665

**Describe Your Environment**- 
- Full name and version of OS : debian bookworm stock

**Describe the bug**
I can see that no builds are presents on the repo : https://zmrepo.zoneminder.com/debian/master/bookworm/

tried to install unbutu releases with this apt configuration :
deb https://ppa.launchpadcontent.net/iconnor/zoneminder-master/ubuntu kinetic main

but dependency do not resolve.

It si possible to install it from sources ? and what will be the procedure ?

**Comment by connortechnology** [comment]
You should be able to now. We have packages available for amd64

**Comment by jzahraoui** [comment]
thank you it work like a charm.

**Comment by mtk11** [comment]
@connortechnology How about packages for armhf ?
