### ISSUE TITLE
If zm:monitors:type is set to libvlc in web GUI then the Source link vanishes

### ISSUE THREAD

**Issue by barjac** [ZoneMinder/ZoneMinder#376]
Clicking the Soucre link for a camera in the ZM console and changing the Source Type to libvlc causes the source link to that monitor setup UI to vanish, leaving no way to access the setup.
This happens with only analog cameras on the system, so the setting would be invalid, but this should not break the GUI.

**Comment by knnniggett** [comment]
This was addressed in commit 2b00ebd02cbb7f0d0f18ff2faf2d31e08f022a80
Closing.
