### ISSUE TITLE
Potential memory leak in FfmpegCamera OpenFfmpeg()

### ISSUE THREAD

**Issue by d-bum** [ZoneMinder/zoneminder#3764]
**Describe Your Environment**
- ZoneMinder master branch commit b44216d3da88f84a9150ae9dde1e970b4d1ba09d
- compiled from source
- own custom OS

**Describe the bug**
in FfmpegCamera class, in OpenFfmpeg() function, the second_input pointer gets initialized with FFmpeg_Input class that allocates ressources for the AVCodecContext and AVFormatContext. The second_input object life time is only for a small scope and never gets deleted that leads to a potentiel memory leak.

**Expected behavior**
Use unique_ptr for second_input so all ressources get freed correctly on end of FfmpegCamera object life time.
Use already initialized context from FFmpeg_Input instead initializing the audio context again.

**Comment by connortechnology** [comment]
confirmed... the second input stuff is totally unfinished.  

Where I'd like to go is using FFmpeg_Input for both first and second and abstract a lot of that code into FFmpeg_Input....
