### ISSUE TITLE
5% Space on a new disk lost?

### ISSUE THREAD

**Issue by amimbitassu** [ZoneMinder/zoneminder#3770]
**Describe Your Environment**
- 1.36.33
- PPA
- Ubuntu 20.04
- Edge

**Describe the bug**
I'm building a new server. 17.5TB & 3,5TB 2 drives are mounted and tested according to Zoneminder Tutorials on youtube. Everything works as intended. But both drives report 5% space already used. Thats a little over 1TB of storage. Is this allocated to something I can adjust? Because ubuntu reports that there is no space used.

![msedge_oSzRytdgMr](https://github.com/ZoneMinder/zoneminder/assets/93249404/b944a9b4-3219-448b-a86d-cda0d8c8e939)

![putty_L6dJJ1xknk](https://github.com/ZoneMinder/zoneminder/assets/93249404/0a9ddadc-f09a-49ff-8911-c1229b1a2912)

**Comment by connortechnology** [comment]
When you create an ext4 filesystem in linux it reserves 5% for root.  Sinc zm doesn't run as root, it sees the available storage as 95%.  You can tell mkfs to use a different value when you create the fs, and you can change it using tune2fs.

Usage: tune2fs [-c max_mounts_count] [-e errors_behavior] [-f] [-g group]
        [-i interval[d|m|w]] [-j] [-J journal_options] [-l]
        [-m reserved_blocks_percent] [-o [^]mount_options[,...]]
        [-r reserved_blocks_count] [-u user] [-C mount_count]
        [-L volume_label] [-M last_mounted_dir]
        [-O [^]feature[,...]] [-Q quota_options]
        [-E extended-option[,...]] [-T last_check_time] [-U UUID]
        [-I new_inode_size] [-z undo_file] device
