### ISSUE TITLE
Build failure for Ubuntu: `version.txt: No such file or directory` 

### ISSUE THREAD

**Issue by LukeSavefrogs** [ZoneMinder/zoneminder#3798]
- OS: `Linux user-aspiree1522 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

## Problem
Following [this guide](https://zoneminder.readthedocs.io/en/stable/installationguide/ubuntu.html#harder-way-build-package-from-source) I tried building the deb package from source using the `stable` branch, but it fails at line 183:

https://github.com/ZoneMinder/zoneminder/blob/df72726eedde68a30c970d67696a086091efc105/utils/do_debian_package.sh#L182-L183

This is because the `master` branch has the `version.txt` file, while the latest tag (currently `1.36.33`) only has `version` (no `.txt` extension).

## Solution

I worked around this issue by searching both files:
```shell
VERSION=$(cat "$(find . -name 'version' -o -name 'version.txt')")
```

**Comment by connortechnology** [comment]
You need to use do_debian_package from the stable branch in order to build the stable branch.

**Comment by LukeSavefrogs** [comment]
> You need to use do_debian_package from the stable branch in order to build the stable branch.

As i told in the issue i already did that. The stable release gets the latest STABLE tag and compiles from there, which leads to the bug explained up here

**Comment by LukeSavefrogs** [comment]
Ty @connortechnology for pushing the fix
