### ISSUE TITLE
High Load when recording

### ISSUE THREAD

**Issue by newburns** [ZoneMinder/ZoneMinder#386]
This is in reference to no response of issue #326 
I am using CentOS 6.5 with Zoneminder 1.27
All camera streams are ffmpeg

This is still running 20+ monitors at 704x480@30fps
I have 0 Zones set for each monitor.
Initial loads are low until something crashes out. Monitors go red and then load begins to sky rocket. CPU usage stays about the same, but LOAD average will hit 30+

![image](https://cloud.githubusercontent.com/assets/5234107/2706996/cd4586b2-c49b-11e3-8067-eabe264e8c30.png)

**Comment by knnniggett** [comment]
This is an installation question, which should be be discussed in our user forum or IRC channel. 
Closing.
