### ISSUE TITLE
Scale Button on Console window does not  work on Zoneminder 1.37.55

### ISSUE THREAD

**Issue by ppnacho69** [ZoneMinder/zoneminder#3861]
Ubuntu 20.04.6 LTS, 5.15.0-100-generic #110~20.04.1-Ubuntu

Installed/Updated from http://ppa.launchpad.net/iconnor/zoneminder-master/ubuntu focal InRelease

Browser version: Mozilla Firefox 123.0.1

**Description of bug**
After more than 3 updates back (or more, I don't remember), Scale option on console screen, stopped working. Whatever option I select, the image doesn't change

**To Reproduce**

1. Login as administrator
2. Click on Console
3. Click on camera name
4. Go to Scale option, click on Auto button, click on any option and nothing happens.

**Expected behavior**
Camera Image should resize depending on option selected. This worked fine before.

**Debug Logs**
```

```

**Comment by connortechnology** [comment]
@IgorA100 Looks like you broke this.... I don't have the energy to dig into it tonight.
