### ISSUE TITLE
Docker Install Needs Testing

### ISSUE THREAD

**Issue by hamiltont** [ZoneMinder/ZoneMinder#394]
I'm not sure of the proper testing procedure--are there docs somewhere, or standard monitors to use? I'm currently experiencing issues trying to get docker working with a remote HTTP monitor. ATM I have searched for a list of open IP cameras, and entered one. Here is a selection of the errors I see in the logs -- any guidance or help is appreciated. 

ZMS: ![alt text](http://i.imgur.com/Uf2WrHK.png)

ZMU: ![alt text](http://i.imgur.com/lEyEsEM.png)

ZMWatch: ![alt text](http://i.imgur.com/0OOHXuc.png)

This is all off a clean build, setup with

```
./configure --with-libarch=lib/$DEB_HOST_GNU_TYPE --disable-debug --host=$DEB_HOST_GNU_TYPE --build=$DEB_BUILD_GNU_TYPE --with-mysql=/usr  --with-webdir=/var/www/zm --with-ffmpeg=/usr --with-cgidir=/usr/lib/cgi-bin --with-webuser=www-data --with-webgroup=www-data --enable-mmap=yes ZM_SSL_LIB=openssl ZM_DB_USER=zm ZM_DB_PASS=zm
```
##

**Comment by knnniggett** [comment]
@DanTheColoradan I noticed that you had some changes related to Docker documented in a past issue.  Can you generate a PR that contains just the Docker stuff?

**Comment by DanTheColoradan** [comment]
@hamiltont, for my own setup, I use [aptalca's](https://hub.docker.com/r/aptalca/docker-zoneminder/) image. Here is the [repo](https://github.com/aptalca/docker-zoneminder).

I need to look at @aptalca's build and see how it compares to my old build script. Originally, I just pulled everything out and then added pieces back in until it ran. However, once I found aptalca's repo, I stopped testing my own script any further.

**Comment by aptalca** [comment]
I tried to follow the install instructions in the wiki as closely as possible in my docker build. The main difference is that, I move all the config and mysql folders out of the container (so they persist through updates and re-installs) and add symlinks in during first run.

**Comment by ibizaman** [comment]
Another example is the first step in the [wiki](https://github.com/ZoneMinder/ZoneMinder/wiki/Docker). For we I first needed to clone the repo, then run `sudo docker build -t='kylejohnson/release-1.27' .`.

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
