### ISSUE TITLE
Filter does not correctly calculate the available space in the storage

### ISSUE THREAD

**Issue by IgorA100** [ZoneMinder/zoneminder#3974]
**Describe Your Environment**
ZoneMinder 1.37.58

Storage is connected as a shared share in Ubuntu

![Correctly](https://github.com/ZoneMinder/zoneminder/assets/5006170/a7ed0eda-6268-42f4-8989-381db58d56a5)
![Filter](https://github.com/ZoneMinder/zoneminder/assets/5006170/eb1dac1e-674c-4f53-b8e5-49c0e4de9706)
![NoCorrectly](https://github.com/ZoneMinder/zoneminder/assets/5006170/a144a506-7fbc-48c0-9aa3-60feaf17c7f0)

Filter selection includes all events from the storage.

**Comment by connortechnology** [comment]
So... NAS is at 80% and your filter is set to list events when it is above 77%.  And it does.  What am I missing?

**Comment by IgorA100** [comment]
> What am I missing?

The filter selected ALL events available on the NAS. This can be seen by date (sorting column) and quantity (bottom left)

**Comment by connortechnology** [comment]
So the point is that it isn't honouring the 100 limit. Nothing to do with disk percent.

**Comment by IgorA100** [comment]
Oh dear Isaac, I've overworked, I'll go and rest.
I'm sorry.
