### ISSUE TITLE
Trying to install the program “ZoneMinder”, problems with dependencies and package breakage

### ISSUE THREAD

**Issue by Username23453** [ZoneMinder/zoneminder#3978]
I'm using ZorinOS, trying to install zoneminder_1.36.33-jammy1_amd64.deb.

It requires "libavcodec58_4.4.2", so I try to install that, with this link:
http://archive.ubuntu.com/ubuntu/pool/universe/f/ffmpeg/libavcodec58_4.4.2-0ubuntu0.22.04.1_amd64.deb

but then that breaks "ffmpeg". See screenshot, I dont know what to do:
![image](https://github.com/ZoneMinder/zoneminder/assets/105397593/235f4c0c-4cd8-4a16-9b21-3b8a81ca0b7c)

**Comment by connortechnology** [comment]
I would try our version from our ppa.  If that fails, you can always build from source.
