### ISSUE TITLE
When viewing a recorded event, the stream stops when viewing ends and does not resume when you click "Play"

### ISSUE THREAD

**Issue by IgorA100** [ZoneMinder/zoneminder#4005]
**Describe Your Environment**
- Version of ZoneMinder 1.37

**To Reproduce**
1. Enable viewing of a recorded event lasting 1 minute
2. Go have a coffee, come back in 5-10 minutes
3. Press the "Play" button to watch again.
4. Viewing is not available, there is an error in the browser console

> js_logger-base-1712621798.js:91 getCmdResponse stream error: socket_sendto( /run/zm/zms-002076s.sock ) failed: Connection refused

**Expected behavior**
After pressing the "Play" button, playback should begin.

**Comment by connortechnology** [comment]
the error message means that zms exited.  Maybe check in zms logs for why. Because it should hang around on pause.  However I can simulate the situation by manually killing zms.

**Comment by IgorA100** [comment]
Pause works - OK
zms exited after the event has finished playing - OK
But after clicking on the "Play" button, you need to restart the zms process.
