### ISSUE TITLE
Jiggling montage layout

### ISSUE THREAD

**Issue by connortechnology** [ZoneMinder/zoneminder#4028]
On my system, I have 12 cameras, a mix of 1080p, 720p, some webrtc some playing by zms.  If I select a 4wide layout, and hide the filter bar, they almost exactly fill the space.  However it clearly overflows by like 1 pixel and then the scroll bar appears, but then the layout code does it's thing and the scroll bar disappears and then the layout code does it's thing and the scroll bar reappears, etc.  Causing them all to bounce around by a pixel or two.

**Comment by IgorA100** [comment]
> If I select a 4wide layout

What is the behavior of monitors on other layouts (2wide, 6wide)?

**Comment by connortechnology** [comment]
Perfect behaviour because there either is or isn't scrolling.  I think there is a 1 pixel height difference on some of the streams because they don't always layout perfectly.

![badlayout](https://github.com/ZoneMinder/zoneminder/assets/925519/a3257aba-7c6b-4b5e-b820-9496d1e8dc29)

**Comment by connortechnology** [comment]
When I inspect them though they appear to all have the correct height.

**Comment by IgorA100** [comment]
> because they don't always layout perfectly.

Yes, I also discovered this problem. This is probably due to the <video> tag

> then the scroll bar appears

Is the scroll bar on the entire page or on some camera?

Does the scrollbar appear when Ratio=Real?

**Comment by connortechnology** [comment]
scroll bar is on the #content div.  When ratio = real the layout is all over the place due to the presence of 1280x800 and 640x480 monitors so the scroll bar is on and stays on.

**Comment by IgorA100** [comment]
> because they don't always layout perfectly.

It seems that I have found the reason, I will think about how best to solve it. But this most likely has nothing to do with the appearance of the scrollbar.

> scroll bar is on the #content div.

Understood,
Based on the location of the monitors, should the scroll bar be displayed or do they all fit on the screen?
As far as I understand, the height of the monitors **almost** fits into the visible area of the browser. If you expand the browser in height or, on the contrary, shrink it, what happens to the scroll bar?

**Comment by IgorA100** [comment]
> because they don't always layout perfectly.

Try using PR #4029
It should be better.
And maybe this will affect the scrollbar, although I'm not sure.
If the monitor layout improves, I will work on improving the code.

**Comment by IgorA100** [comment]
Please check: #4030

**Comment by connortechnology** [comment]
#4029 doesn't fix the jiggling either. I had changed the ratio to Auto from 16:9 and so the video was a little larger and hence the scrollbar was staying on.

**Comment by connortechnology** [comment]
The issue is that the showing of the scroll bar shrinks the width of the video frames, which shrinks the height, which makes us not need the scroll bar. 
I wonder if there is a way to tell if the scrollbar is visible and if so add a fix pixels to the content div so it stays. This might be difficult to solve

**Comment by IgorA100** [comment]
> #4029 doesn't fix the jiggling either.

Those.:
1. #4029 & #4030 fixes the layout problem
2. #4029 & #4030 not fixes the jiggling
Right ?

**Comment by connortechnology** [comment]
Correct.

**Comment by IgorA100** [comment]
> and if so add a fix pixels to the content div so it stays.

This job should be done by GridStack.

Indeed, when there are 1-5 pixels left from the bottom edge of the lower monitor to the bottom edge of the browser window, then there is a problem with the scroll bar. As a temporary solution, change the browser height a little.
At first glance, this is a difficult task to solve.

**Comment by IgorA100** [comment]
I had an idea, but I didn’t implement it quickly...

**Comment by IgorA100** [comment]
Try #4031

**Comment by connortechnology** [comment]
No luck still does it.

**Comment by IgorA100** [comment]
Must work!
Maybe cached?

**Comment by IgorA100** [comment]
Yes, there is a problem.
I continue to work.

**Comment by IgorA100** [comment]
I made a change to #4031
Try again.
