### ISSUE TITLE
The placement of monitors on the Montage page is broken again

### ISSUE THREAD

**Issue by IgorA100** [ZoneMinder/zoneminder#4037]
**Describe Your Environment**
- Version of ZoneMinder 1.37

Someone somewhere broke something...... #4032

**Comment by connortechnology** [comment]
What is happening is that my 1080p cameras end up with a width of 433px. My 640x480 cameras end up with a width of 430.  So the ratio calculation results in a different height value. 

It is not clear to me how the width could be different. Perhaps that points you in the right direction.

**Comment by IgorA100** [comment]
Are the heights of these cameras the same or different?

**Comment by IgorA100** [comment]
Check it like this:
1. layout = "4Wide" then refresh the page (Ctrl+F5)
2. Switch Layout="3Wide"
3. Refresh page (Ctrl+F5) (The previous selection 3Wide should remain)
4. Switch Layout="4Wide"

How will the cameras be positioned after each of the 4 actions?

**Comment by connortechnology** [comment]
THe source heights are different 1920x1080 vs 640x480.  The resulting heights after scaling are different because the widths somehow end up different. 275px vs 279px.

**Comment by connortechnology** [comment]
They are also a mix of img and video tags. May be related.

**Comment by connortechnology** [comment]
3 Wide lays out correct immediately and after refresh.  4 out lays out correctly after change to 4 wide but incorrectly on refresh.  Again, it may be an interaction with the video tag.
