### ISSUE TITLE
Rate=1 on Watch page does not work

### ISSUE THREAD

**Issue by IgorA100** [ZoneMinder/zoneminder#4043]
**Describe Your Environment**
- Version of ZoneMinder 1.37
It works, but it’s somehow strange... The image disappears and appears.
The other Rate options work.

**Comment by IgorA100** [comment]
> Works for me although I have seen some weird behaviour with the stream sometimes, not dependent on fps

Hm. Additional analysis is probably required.

> What doesn't work is Stills mode.

I didn’t even know what kind of regime this was, but now I understand. Perhaps it should be removed from the selection?

> Seems to me we may need rate options less than 1. Like update every 10 seconds or every minute.

Maybe. 
Just tried it. When the FPS value is less than 1 (as with =1), a black screen with the words "Waiting for capture" appears, and then a picture appears, then again a black screen and again a picture. Not pretty at all.

**Comment by connortechnology** [comment]
Yeah I have seen that behaviour but cannot at this moment reproduce it.  Log analysis will be required.  Waiting for capture means that zmc isn't decoding.

**Comment by IgorA100** [comment]
If "decode = All" - the black screen appears less frequently, if "decode = On demand + key" - the black screen appears more often. And it’s like this on all my cameras...
There are no errors in the logs, I did not enable debugging.
