### ISSUE TITLE
UI Improvement on watch view

### ISSUE THREAD

**Issue by connortechnology** [ZoneMinder/zoneminder#4059]
Initial video load makes the UI jump around too much.  We should just figure out the scaling and start the stream all in javascript.

The UI jumps again on cycle change.  It seems to jump stopping the existing stream, then do a full page reload. Ideally we would just change the stream without a full reload.

**Comment by IgorA100** [comment]
Agree.

**Comment by IgorA100** [comment]
I was able to switch to the next monitor without reloading the page (there are some nuances, but this can all be fixed), but what about the event table that is under the monitor? It remains unchanged and misleading.

**Comment by connortechnology** [comment]
table.bootstrapTable('refresh'); should handle reloading that data.
