### ISSUE TITLE
"Path must be set to a valid value" returned when setting an ONVIF camera

### ISSUE THREAD

**Issue by flixman** [ZoneMinder/zoneminder#4086]
**Describe Your Environment**
- Version of ZoneMinder: 1.36.33
- How you installed ZoneMinder: Distribution package
- Full name and version of OS: Debian 12.6
- Browser name and version: Firefox 127.0.2

**If the issue concerns a camera**
- Make and Model: Tapo C200
- frame rate
- resolution
- ZoneMinder Source Type: ONVIF

**Describe the bug**
On the Monitors page I want to add the camera as ONVIF source. After setting the URL (http://<ip>:2020/onvif/device_service), username and password, I click save and I get the error:

```
Path must be set to a valid value
Width must be set to a valid value
Height must be set to a valid value
```

**Expected behavior**
The camera gets added and I can PTZ it.

**Debug Logs**
I have not found any, all happens in the browser and there is no message in the console. The error gets triggered in line 78 of /usr/share/zoneminder/www/skins/classic/views/js/monitor.js.php, as the camera type is ffmpeg.

**Comment by connortechnology** [comment]
You havn't set the stream path.  This is different from the onvif path. Check the Source tab.
