### ISSUE TITLE
"Monitors" Table Missing "WallClockTimestamps" Column

### ISSUE THREAD

**Issue by jalitriver** [ZoneMinder/zoneminder#4087]
**Environment**
- ZoneMinder v1.37.62
- Installed from ppa:iconnor/zoneminder-master
- Ubuntu-24.04

**Describe the bug**
The "Monitors" table appears to be missing the new "WallClockTimestamps" column.

**To Reproduce**
The problem occurs when adding a new camera which fails with the error message shown in the log below.

**Expected behavior**
I expected to be able to add the new camera.  After looking through recent commits, it looks like the WallClockTimestamps column should hold booleans so I manually added the a WallClockTimestamps column to my "zm" database, and it appears to have fixed the problem.

I also expected to find "WallClockTimestamps" in the files in /usr/share/zoneminder/db, but it is not there.

**Debug Logs**
```
SQL-ERR 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'WallClockTimestamps' in 'field list'', statement was 'INSERT INTO `Monitors` (...)
```

**Comment by connortechnology** [comment]
Fixed by 7d685e96df1be6fa1355d22e080edeb6445502cb
