### ISSUE TITLE
FreeBSD image missing in CI

### ISSUE THREAD

**Issue by trysten** [ZoneMinder/zoneminder#4088]
The commit yesterday failed checks because of google cloud: https://github.com/ZoneMinder/zoneminder/runs/27216986715

maybe updating to freebsd-13-3 would fix it, but maybe there's a way to make it more dynamic if google is going to remove their images like that.

**Comment by connortechnology** [comment]
Have bumped it.  I have no time to look into making it dynamic. Feel free to take that on.
