### ISSUE TITLE
Cameras showing offline when they are still recording

### ISSUE THREAD

**Issue by daniel-hodgson** [ZoneMinder/zoneminder#4109]
**Describe Your Environment**
- 1.37.63
- PPA
- Ubuntu 24.04
- Firefox 128.0.3

**If the issue concerns a camera**
- Camera Make/Model Varies
- 11fps
- Resolution Varies (720p mostly)
- Source Type:  FFMPEG

**Describe the bug**
May be related to old bug #3766 

All cameras in the system report offline, even though they are actively recording footage. FPS Report Interval is set to default (100). Reducing the interval to 50 or even 22 does not fix the issue. 

 `Monitors` table in the DB also showed `Function` column was set to `Monitor` instead of `Record` for all cams. Updating this manually in the DB to `Record` did not resolve this issue.

This seems to have started after a recent power outage, and ZM is running inside of a virtual machine (RHEL 7, QEMU-KVM).

**Expected behavior**
All cameras should show online.

**Comment by connortechnology** [comment]
The Function column is no longer used.  Monitor status is contained in the Monitor_Status table.

A failed db update could be causing the problem in which case there will be errors logged.  Check your logs.

**Comment by dghodgson** [comment]
False alarm! It was a Timezone mismatch. Relevant error was in the web_php log.
