### ISSUE TITLE
MariaDB Support?

### ISSUE THREAD

**Issue by robertsilen** [ZoneMinder/zoneminder#4115]
Hello, I happend to notice that [MySQL](https://zoneminder.readthedocs.io/en/stable/search.html?q=mysql&check_keywords=yes&area=default) is mentioned more than [MariaDB](https://zoneminder.readthedocs.io/en/stable/search.html?q=mariadb&check_keywords=yes&area=default#) in your documentation - any particular reason for that? Can I make a PR to add more MariaDB? Where are the corresponding files in github in that case?

**Comment by connortechnology** [comment]
Because mysql predates mariadb?

files are in the docs directory.

**Comment by robertsilen** [comment]
Thanks, I made a suggestion: https://github.com/ZoneMinder/zoneminder/pull/4117
