### ISSUE TITLE
Compile error zm_monitor_onvif.cpp:287:7: error: ‘alarms’ was not declared in this scope

### ISSUE THREAD

**Issue by loganavalari** [ZoneMinder/zoneminder#4169]
**Describe Your Environment**
I got the following Compile error on 
Suse Linux Ent 15.4  
ZoneMinder 1.37.64 (current git release)
Source Compile
make 4.2.1
gcc 7.5.1
ffmpeg 4.4 and also tried with ffmpeg 7.1

**Describe the bug**
[ 41%] Building CXX object src/CMakeFiles/zm.dir/zm_monitor_rtsp2web.cpp.o
[ 42%] Building CXX object src/CMakeFiles/zm.dir/zm_monitor_janus.cpp.o
[ 42%] Building CXX object src/CMakeFiles/zm.dir/zm_monitor_amcrest.cpp.o
[ 43%] Building CXX object src/CMakeFiles/zm.dir/zm_monitor_onvif.cpp.o
/server/ZoneMinder-1.37.64/src/zm_monitor_onvif.cpp: In member function ‘void Monitor::ONVIF::SetNoteSet(Event::StringSet&)’:
/server/ZoneMinder-1.37.64/src/zm_monitor_onvif.cpp:287:7: error: ‘alarms’ was not declared in this scope
   if (alarms.empty()) return;
       ^~~~~~
/server/ZoneMinder-1.37.64/src/zm_monitor_onvif.cpp:287:7: note: suggested alternative: ‘alarm’
   if (alarms.empty()) return;
       ^~~~~~
       alarm
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
make[2]: *** [src/CMakeFiles/zm.dir/build.make:538: src/CMakeFiles/zm.dir/zm_monitor_onvif.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:503: src/CMakeFiles/zm.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**To Reproduce**
on make this compiel error occur
cmake also tried with -DWITH_GHOSTRIDER=OFF, same

Which packages resides on this onvif module compile?

**Comment by connortechnology** [comment]
This is due to the lack of installed libgsoap-dev.  I believe the fix is already applied.
