### ISSUE TITLE
You have set the max video packets in the queue to ......

### ISSUE THREAD

**Issue by IgorA100** [ZoneMinder/zoneminder#4182]
H264B, 2688*1520, FPS=20, Keyframe = 40

Buffers:
Image Buffer Size (frames) - 3
Maximum Image Buffer Size (frames) - 421
Warmup Frames - 0
Pre Event Image Count - 10
Post Event Image Count - 10
Stream Replay Image Buffer - 0
Alarm Frame Count - 1

Motion Detection - None

In this case, the image becomes distorted.

```
10/28/24, 10:48:35 AM GMT+3	zmc_m38		96815	WAR	Found locked packet when trying to free up video packets. This means that decoding is not keeping up.	zm_packetqueue.cpp	174
10/28/24, 10:48:30 AM GMT+3	zmc_m38		96815	INF	Pod lestnicey 1etazh: 1000 - Capturing at 20.87 fps, capturing bandwidth 874221bytes/sec Analysing at 0.00 fps	zm_monitor.cpp	1840
10/28/24, 10:48:30 AM GMT+3	zmc_m38		96815	WAR	You have set the max video packets in the queue to 421. The queue is full. Either Analysis is not keeping up or your camera's keyframe interval 41 is larger than this setting.	zm_packetqueue.cpp	154
10/28/24, 10:48:28 AM GMT+3	zmc_m38		96815	WAR	You have set the max video packets in the queue to 421. The queue is full. Either Analysis is not keeping up or your camera's keyframe interval 41 is larger than this setting.	zm_packetqueue.cpp	154

```

[_debug.zip](https://github.com/user-attachments/files/17539187/_debug.zip)

**Comment by IgorA100** [comment]
This problem usually occurs during live viewing. In the settings, the image is rotated by 90 degrees.

**Comment by connortechnology** [comment]
Are you rotating in ZM? Don't do that it is way too CPU intensive.  Do it in the camera.

**Comment by IgorA100** [comment]
> Are you rotating in ZM?

Yes.
I use "Orientation = Rotate Left"


> Don't do that it is way too CPU intensive.

HTOP shows 105-115% for the ZMC process, I have a similar load indicator when viewing 4K cameras without image rotation. There are no problems with the display.
The overall CPU load on the server does not exceed 50%


> Do it in the camera.

I would love to rotate the image on the camera, but the camera doesn't allow it. :(

**Comment by connortechnology** [comment]
You don't have enough cpu to do the rotation + everything else.  I am working on a change that will remove 1 copy (conversion to rgba).  But on a high res image, rotation is going to be slow.  Perhaps we can implement an AVX or SSE3 improved rotation, or use ffmpeg's version assuming that that is likely optimised.  How about physically remounting the camera?

**Comment by IgorA100** [comment]
> You don't have enough cpu to do the rotation + everything else.

So one zmc process cannot use multiple CPU threads?

> How about physically remounting the camera?

My camera is turned to portrait mode, which is the best way to view the corridor. The camera itself does not allow you to turn the image. That's why I decided to rotate the image in ZM, so that it would be more convenient to watch.
I will have to rotate the monitor itself connected to the computer :)))))))))))))))))))))))))))))

**Comment by connortechnology** [comment]
The rotate code is not multi-threaded.  The h264/5 decoding code likely is and zmc itself is 5 threads.  One for capture, one for decoding, one for motion detection, one for writing out events and one for writing to db.

**Comment by IgorA100** [comment]
Now I get it.
