### ISSUE TITLE
Event playback skips some events

### ISSUE THREAD

**Issue by j-marz** [ZoneMinder/zoneminder#4186]
**Describe Your Environment**
- v1.37.50 installed from PPA
- Ubuntu 20.04.6 LTS
- Firefox v130.0.1

**Describe the bug**
Playback of filtered events misses some events if the the next sequential event ID has a timestamp that is earlier than the next event ID. Changing the event list sorting doesn't resolve the issue.

**To Reproduce**
1. cause a zmtrigger event across multiple monitors
2. configure different pre-event buffers per monitor (this changes the event start time - ie. larger pre-event buffer will have earlier start time even though it was trigger later in the zmtrigger list)
3. list matching events using a filter
4. sort events by ID, name or start time (issue occurs in all scenarios)
5. playback in ascending order
6. notice some events are skipped and never playback

**Expected behavior**
event playback honors the filter sorting and doesn't skip events

**Debug Logs**
NA

**Comment by j-marz** [comment]
Looks like playback uses the filter query and doesn't update the query when the event list sorting changes (e.g. change table sorting in event list view after running filter and before playback). Updating the event filter to sort by ID instead of start time seems to work (ie. doesn't skip events), but the side effect is the events don't technically play in chronological order.

**Comment by connortechnology** [comment]
in zms when it goes to get the next event, it uses the following SQL:
SELECT `Id` FROM `Events` WHERE `MonitorId` = %d AND `Id` > last_event_id ORDER BY `Id` ASC LIMIT 1
So yeah, if the Ids are out of sync, it will mess up. It ignores the filter sort.  In fact the filter is never passed to zms.  

Which view is this? event view, or montage review?

**Comment by j-marz** [comment]
`view=events`
The filter is definitely used for the event view playback - changing `Sort by` in the filter results in `sort_field` changing in the event playback URL and therefore `skip_next`.

**Comment by connortechnology** [comment]
What have you got for Options->Web->WEB_EVENT_SORT_FIELD ? I bet it's Id.  Should be changed to StartDateTime.

**Comment by j-marz** [comment]
It's already `StartDateTime`, maybe i need to change that to `Id`?
![image](https://github.com/user-attachments/assets/49317527-3e2e-4f96-bee2-212cab586e3d)

Sorting IS being applied via the filter. What isn't happening is after running a filter (to find events of interest) and then resorting the the events table, the re-sorted event table view is ignored in playback and the original filter query (used to produce the events list) is passed to the playback. I had to change the sort field in the event filter to `Id` to avoid missing events.
![image](https://github.com/user-attachments/assets/a384f5c3-0fd8-46c6-99e3-f3d50efd069b)

**Comment by connortechnology** [comment]
Nah there was some code in there that made it always use E.Id.  Should be fixed now.  You'll have to update.

**Comment by j-marz** [comment]
@connortechnology thanks for looking into this. I upgraded to v1.37.65 and still running into missed events during playback.

For example event ID 6056855 is skipped during playback. I assume because 6056855 has the same start time as 6056854
![image](https://github.com/user-attachments/assets/0903ce02-6037-4e07-9889-fa792924ca8a)

Before upgrading, i was able to get all events to play if i sorted the event filter by ID. The only issue was some events wouldn't play in chronological order, but it was a technicality and not a blocker because in my case it was <1 min out for some events.

After, upgrade, it doesn't matter if i change the sort field in the filter or and events table, 6056855 is always skipped during playback of events. 

Can you please take another look or revert the changes in https://github.com/ZoneMinder/zoneminder/commit/359330b3840676ff2f5e032d4f0889f5db06360c ?

**Comment by j-marz** [comment]
Changing Options->Web->WEB_EVENT_SORT_FIELD also doesn't help.

**Comment by connortechnology** [comment]
Try latest.  We were using a > but your skipped event has the same starttime.. so I've changed it to >=

**Comment by connortechnology** [comment]
Sweet!
