### ISSUE TITLE
Add support for saving Events and Frames to Elasticsearch instead of MySQL [$250]

### ISSUE THREAD

**Issue by kylejohnson** [ZoneMinder/ZoneMinder#422]
After talking over and discussing #400, I realized that this approach is actually what I am looking for.  As such I am closing out #400 and moving the bounty over to here.

I am looking for support for saving of events, and their associated frames, to Elasticsearch.  This would then disable saving of events, and their associated frames, to MySQL.

This feature does _not_ cover any UI aspects - only the backend code to make this happen.

Requirements:
1. A compile-time option to enable Elasticsearch.
2. A compile-time option to disable MySQL - for Events and Frames.
3. Determine where to save Events and Frames to, if using Elasticsearch, from zm.conf, with the following fields: ZM_ES_HOST, ZM_ES_DOCUMENT, ZM_ES_PORT, ZM_ES_PROTOCOL
4. Elasticsearch should be treated and function as, but in place of, MySQL.  To me, this means that wherever one would save an Event or Frame to MySQL, they'd save it to ES (or both) instead.
5. Event.StartTime, Event.EndTime and Frame.TimeStamp should be converted to unix epochs if saving to Elasticsearch.

This way, one could support both ES and MySQL concurrently, or the one of their choice (MySQL can stay as the default).

Provided that ZM_ES_PROTOCOL = https, ZM_ES_HOST = es01, ZM_ES_PORT = 1234 and ZM_ES_DOCUMENT = zoneminder, an event could be saved by POSTing or PUTing JSON-encoded data to https://es01:1234/zoneminder/event/$event_id, and a frame could be saved by doing the same to https://es01:1234/zoneminder/frame/$frame_id

Please also consider this a request for discussion.  
##

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.

**Comment by sivom** [comment]
@kylejohnson 
Discussion is very interesting. I work in elastic search implementations. Would like to contribute. In fact I am thinking of using elastic search with zone minder events.


_Sent from my Asus ASUS_Z00AD using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
