### ISSUE TITLE
FreeBSD pbi update [$70]

### ISSUE THREAD

**Issue by petrklus** [ZoneMinder/ZoneMinder#429]
Hi,

I was looking into getting ZM installed on my BSD machine but the latest version I could get was 1.25:

http://ftp.pcbsd.org/pub/pbioutgoing/amd64/9/multimedia/zoneminder/

Are there any plans on updating to latest 1.27?
##

**Comment by NCommander** [comment]
I'm going to take a stab at updating the PBI to 1.28.1, I'll keep you apprised of my status.

**Comment by josh4trunks** [comment]
@NCommander you mind hosting your endevors to update the freebsd port on github. I want to be able to follow and possibly contribute if I find time.

I worked on this a bit before. I had a port that compiled, but I think running zms or some of the other binaries had some issues.

**Comment by NCommander** [comment]
I got horridly sidetracked on this and haven't had time to resume it. I
didn't get very far; I don't believe I even had the tree compiling let
alone test >.<;
Michael

**Comment by connortechnology** [comment]
I had it compiling once... and recently took another look and found that it doesn't anymore.

Mostly the issues are just including the right include file.

I also had it compiling on kfreebsd for debian..

**Comment by connortechnology** [comment]
I have fixed the basic autoconf/cmake build issues.

**Comment by Sauraus** [comment]
@connortechnology I am about to give this a go all in my self interest of running ZoneMinder in a FreeBSD jail ;) where can I find your changes?

**Comment by connortechnology** [comment]
They have all been merged

**Comment by abishai** [comment]
It is done
https://www.freshports.org/multimedia/zoneminder/

**Comment by josh4trunks** [comment]
As far as I understand PBIs are no longer used, though I could build one if really necessary, lol.
I haven't played with Docker at all, but that might be a way we could have a standalone (including dependencies) package of Zoneminder distributed.

Either way, this issue can be closed. Zoneminder v1.30 is straight forward to install on FreeBSD.
Not sure how the bounty works, or if it is still available, but @abishai did the bulk of the FreeBSD port work/debugging.

**Comment by connortechnology** [comment]
I am happy to give @abishai my share of the bounty, I do want to say that it was not all him.  He has been the latest player and has put a lot of work in and has been instrumental in bringing the final bits into place. 

However, I would say that I have done at least 25% of the work, and I know @kylejohnson put a significant effort, and there have been others.  I just want to make sure that everyone gets thanked.  

Also, I might like to see the freebsd native local camera code get merged in....

**Comment by knnniggett** [comment]
@abishai There is still a $70 open bounty on this. I would encourage you to claim it:
https://www.bountysource.com/issues/2056027-freebsd-pbi-update

**Comment by abishai** [comment]
@knnniggett better to redirect this to zmdc issue. It drives me mad

**Comment by connortechnology** [comment]
We don't have the power to redirect it.  Please accept it, and then send it where you want.
