### ISSUE TITLE
libvlc ip camera status does not recover automatically [$35]

### ISSUE THREAD

**Issue by vlad2005** [ZoneMinder/ZoneMinder#476]
I would like to point out the following functional issue. If an IP camera is unavailable for a period, when gets back online, ZoneMinder no longer follows.
The expected behavior is that camera to be continuously monitored and when back online ,returns to normal functionality.
##

**Comment by SteveGilvarry** [comment]
Our libvlc monitor not getting much love these days. Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
