### ISSUE TITLE
Basic ONVIF support [$45]

### ISSUE THREAD

**Issue by altaroca** [ZoneMinder/ZoneMinder#478]
I added basic ONVIF support to my local zm installation. <a href="http://altaroca.wordpress.com/2014/07/14/onvif-probing-for-zoneminder/">See here</a>. I intend to upload it to the repository.

**Comment by SteveGilvarry** [comment]
Merge with #208 they both have bounty attached?

**Comment by knnniggett** [comment]
ONVIF support was officially merged in #479 as an optional feature.

If I understand Bountysource correctly, I need to close the issue in order for the bounty to be claimed.
@altaroca feel free to claim the bounty.
