### ISSUE TITLE
Nordmark IP camera

### ISSUE THREAD

**Issue by wadimm** [ZoneMinder/zoneminder#483]
Error while decoding frame 0.

256: 00 00 00 00 01 ff f0 87 00 00 00 80 28 1c 1e 23 1e 19 28 23 21 23 2d 2b 28 30 3c 64 41 3c 37 37 3c 7b 58 5d 49 64 91 80 99 96 8f 80 8c 8a a0 b4 e6 c3 a0 aa da ad 8a 8c c8 ff cb da ee f5 ff ff ff 9b c1 ff ff ff fa ff e6 fd ff f8 2b 2d 2d 3c 35 3c 76 41 41 76 f8 a5 8c a5 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 86 de 03 71 2e c0 70 31 92 7d 28 9e 1f 28 a1 56 dc 8e bb 95 b1 8c ff 00 9e 3f 3a 58 a5 f2 e1 9a 3d b9 f3 17 6e 73 d3 af f8 d4 b3 7f c8 36 0f fa e8 7f f6 6a 60 54 ab 71 d9 86 11 6f 97 6b c8 09 55 db 9e 2a ad 5d bb ff 00 90 a4 3f 45 ff 00 d0 8d 00 51 20 82 43 0c 10 70 47 a1 a7 46 8d 23 84 41 96 3d 05 49 7b ff 00 1f b3 7d 47 fe 82 29 b6 ff 00 f1 f1

Network Digital Video
MODEL HIPC-1080P-S22
IPCamera

ONVIF camera, but  STREAM 1920x1080 MJPEG,

VLC ok  
rtsp://323.sytes.net:554/VideoInput/1/mpeg4/1
or rtsp://323.sytes.net:554/av0_0

**Comment by ziotibia81** [comment]
I have the same problem with ZM 1.30.4
See [ZM Forum](https://forums.zoneminder.com/viewtopic.php?f=36&t=26660) for reference.
