### ISSUE TITLE
MESSAGE_BODY not remembering saved value

### ISSUE THREAD

**Issue by Germs2004** [ZoneMinder/ZoneMinder#486]
Version 1.27.1
When I go to the Options page and Email tab, the MESSAGE_BODY option is either blank or  shows the default value.  However, the emails I actually receive show my custom body content.  It looks like this page doesn't retrieve the MESSAGE_BODY value from the database to display it on the page, which makes it hard to make small changes because I have to retype the entire thing every time.

Sorry I can't help much.  I'm a noob at Linux and Zoneminder.
##

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
