### ISSUE TITLE
Show Point Numbers on the Zone overlay

### ISSUE THREAD

**Issue by Germs2004** [ZoneMinder/ZoneMinder#489]
Minor suggestion:
In the "zone" view where you drag and drop points to create zones on an overlay of the camera image, it would be helpful if the little round points actually showed the Point Number next to them.  That would make it easier to know which "+" button to click below to add a point.  I know you can hold your mouse over the point to see it, but this is just a little faster because the numbers will show without holding the mouse over the points.

**Comment by knnniggett** [comment]
Closing due to lack of support for this feature request.  A pull request, which addresses this, is still welcome.
