### ISSUE TITLE
Add NewPoint feature to Zone edit page

### ISSUE THREAD

**Issue by Germs2004** [ZoneMinder/ZoneMinder#490]
Currently, to add a point to a Zone polygon, you have to click the correct "+" button at the bottom of the page.  Here's the new idea: add a different colored point between every two points that the user can click to automatically add a point there.

For example, say I have a square polygon zone.  There will be 4 real points at each corner and 4 dimmed points in the middle of each line.  If the user clicks and drags one of those dimmed points, it becomes a real point automatically.

This way, you don't have to figure out which "+" button to click.  OpenLayers has this feature and it works very well.

**Comment by knnniggett** [comment]
Closing due to lack of support for this feature request. A pull request, which addresses this, is still welcome.
