### ISSUE TITLE
VBV buffer size not set, muxing may fail; [mpeg1video @ 0x7a5e320] MPEG1/2 does not support 14/1 fps

### ISSUE THREAD

**Issue by steryoshkin** [ZoneMinder/ZoneMinder#499]
When requesting a stream other than jpeg, such as mpeg or mp4, it appears in the log:
[Thu Aug 07 10:19:36 2014] [error] [client 192.168.6.12] VBV buffer size not set, muxing may fail
[Thu Aug 07 10:19:36 2014] [error] [client 192.168.6.12] [mpeg1video @ 0x7a5e320] MPEG1/2 does not support 14/1 fps

http://server/cgi-bin/nph-zms?mode=jpeg&monitor=2&scale=100&maxfps=10&buffer=1000&auth=da0b2f4b779c7afba5e78a16ef4d1a2c&connkey=555215&rand=1407396294 - work

http://server/cgi-bin/nph-zms?mode=mpeg&monitor=2&scale=100&maxfps=10&buffer=1000&auth=da0b2f4b779c7afba5e78a16ef4d1a2c&connkey=555215&rand=1407396294 - not work and error.

#uname -a
Linux pto 3.2.0-29-generic 46-Ubuntu SMP Fri Jul 27 17:03:23 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
#ffmpeg
ffmpeg version N-65367-g5b12b4f Copyright (c) 2000-2014 the FFmpeg developers
  built on Aug  7 2014 09:56:09 with gcc 4.6 (Ubuntu/Linaro 4.6.3-1ubuntu5)
  configuration: --enable-gpl --enable-shared --enable-pthreads
  libavutil      52. 98.100 / 52. 98.100
  libavcodec     55. 73.100 / 55. 73.100
  libavformat    55. 52.100 / 55. 52.100
  libavdevice    55. 13.102 / 55. 13.102
  libavfilter     4. 11.102 /  4. 11.102
  libswscale      2.  6.100 /  2.  6.100
  libswresample   0. 19.100 /  0. 19.100
  libpostproc    52.  3.100 / 52.  3.100

ZoneMinder v1.27.99.0 (at last on github)

a similar problem I have not found...

**Comment by knnniggett** [comment]
```
[Thu Aug 07 10:19:36 2014] [error] [client 192.168.6.12] [mpeg1video @ 0x7a5e320] MPEG1/2 does not support 14/1 fps
```

The mpeg standard does not support the frame rate your camera is using.  Change your frame rate to one that is compatible.
