### ISSUE TITLE
Automatically exporting events to video for backup purposes

### ISSUE THREAD

**Issue by kylejohnson** [ZoneMinder/ZoneMinder#5]
22:23 < rveach> something like what u would see in a professional security system, convert to video after maybe 1 day, and store it in a seperate directory for X days and delete
                afterwards
22:24 < rveach> i know its not hard to do, but i just havent gotten around to doing it :P
##

**Comment by SteveGilvarry** [comment]
Closing out not as complete yet, but video storage branches replace this.
