### ISSUE TITLE
Pick a DB versioning strategy

### ISSUE THREAD

**Issue by kylejohnson** [ZoneMinder/ZoneMinder#505]
## Overview
@knnniggett, @connortechnology and I talked about this at length last week as a part of #350.  The actual branching strategy is discussed in #350.  Regarding DB versioning, let us settle that here.

## As I understand it, here is the problem:
Upgrading from an older master to a newer master will be unsuccessful if a new DB schema file has been added, as the 'version' has not changed.

## Solution

My proposed solution is to have `zmupdate.pl` install /all/ schema files that are newer than `$lastVersion`.

Say the actual release version is 1.27 and we're on 1.26.  We checkout master and upgrade to it. We run `zmupgrade.pl`, it finds all files > 1.26 and installs them.

### Caveats
 * I do not know what exactly to name the files.  1.27+1.sql could work, as could 1.27.99.
 * Please discuss!

**Comment by knnniggett** [comment]
I'm going to close this out as we have settled on using the third octect in the zoneminder revision to indicate a bump in the dB schema.  Feel free to reopen this if more discussion is required.
