### ISSUE TITLE
hi all, i'm under Linux Gentoo with systemd - ZM v1.27.99.0

### ISSUE THREAD

**Issue by christophey2k** [ZoneMinder/ZoneMinder#511]
hi all, i'm under linux gentoo with systemd, 
i can't start zm with web interface ... since latest merge
now i can use systemd but i don't know the name of the service 
//# systemctl enable zoneminder.service (not exist)
for enable before start in my system
//# systemctl start zoneminder

Thanks

**Comment by SteveGilvarry** [comment]
@christophey2k Sounds like you have resolved this issue?  Based on #841 you having issues with cameras now, so I am going to close this call.
