### ISSUE TITLE
Get the script on alarm feature working

### ISSUE THREAD

**Issue by ghost** [ZoneMinder/zoneminder#515]
Hi,

I have Zoneminder running for a couple of days now and want to have a script to execute when there is an alarm.
I have a script but are clueless on how to get it running. I found this: http://www.zoneminder.com/wiki/index.php/FAQ#How_can_I_use_ZoneMinder_to_trigger_something_else_when_there_is_an_alarm.3F
Which should do what I need but I have no idea on how to get it working.
Can anyone point me in the right direction?

**Comment by fedegovoni** [comment]
Hi guys, i've got the same problem, but I can't unterstand how to make the script.pl executable by the system when an alarm is generated. Which file have I to modify and how?
Thank you a lot

**Comment by cecchisandrone** [comment]
Is there a way to pass some parameters to the script?
