### ISSUE TITLE
Want built-in support for BCM970012 Crystal HD cards.

### ISSUE THREAD

**Issue by connortechnology** [ZoneMinder/ZoneMinder#517]
Like this one.

http://www.amazon.com/gp/product/B003TU07GU/ref=oh_aui_detailpage_o03_s00?ie=UTF8&psc=1

Apparently ffmpeg supports it.  The idea is to use this to do the decompression of HD encoded streams instead of CPU.  Would be nice to have it built in.
##

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
