### ISSUE TITLE
ZoneMinder Console - Stopped despite zmdc.pl startup running [$15]

### ISSUE THREAD

**Issue by troywill** [ZoneMinder/ZoneMinder#518]
I've written an Arch Linux build package ([in GitHub](https://github.com/troywill/zoneminder-aur/tree/master/zoneminder-git)) for ZoneMinder Git.

However, the status remains "Stopped."  I looked through the PHP functions to see how the running state of zoneminder is determined but I was unsuccessful.  Since I can't see any error messages it's hard for me to see what's going wrong. It appears to me that zoneminder is running
```
USER  PID
http 12645 /usr/bin/perl -wT /usr/bin/zmdc.pl startup
http 12670  \_ /usr/bin/perl -wT /usr/bin/zmfilter.pl
http 12676  \_ /usr/bin/perl -wT /usr/bin/zmaudit.pl -c
http 12686  \_ /usr/bin/perl -wT /usr/bin/zmwatch.pl
http 12695  \_ /usr/bin/perl -w /usr/bin/zmupdate.pl -c
```
I use the same zoneminder.service file that's in the zoneminder misc directory:
```
# ZoneMinder systemd unit file
# This file is intended to work with all Linux distributions

[Unit]
Description=ZoneMinder CCTV recording and security system
After=network.target mysqld.service httpd.service
Requires=mysqld.service httpd.service

[Service]
User=http
Type=forking
ExecStart=/usr/bin/zmpkg.pl start
ExecReload=/usr/bin/zmpkg.pl restart
ExecStop=/bin/bash -c '[[ "$(/usr/bin/pgrep zmdc.pl)" > 0 ]] && /usr/bin/zmpkg.pl stop'
PIDFile="/var/run/zm/zm.pid"

[Install]
WantedBy=multi-user.target
```

**Comment by knnniggett** [comment]
PR #524 changes some of the default values in zoneminder to avoid the issue of private tmp folders.  Consequently, I consider this issue to be resolved. Please let me know if I am mistaken, and I can reopen it for further investigation.

@PX03AFK makes a good point concerning stale values remaining in the database.  
However, I consider that to fall under the context of these issues:
#790 
#12
