### ISSUE TITLE
ZM doesn't build with latest ffmpeg.

### ISSUE THREAD

**Issue by connortechnology** [ZoneMinder/ZoneMinder#522]
Just putting this here, so that it can be a bounty target.

ZM doesn't build with latest ffmpeg.  This also means it doesn't build on the next ubuntu (14.10).

**Comment by SteveGilvarry** [comment]
Assigning to me to test this

**Comment by knnniggett** [comment]
Since Ubuntu 14.10 is out and ZoneMinder packages for this distro have been built, I'm going to assume this issue has been resolved.  If I am mistaken, please reopen it.
