### ISSUE TITLE
Attempt to assign buffer from a NULL pointer

### ISSUE THREAD

**Issue by zsx** [ZoneMinder/zoneminder#523]
I installed zoneminder from master (1.27.0 didn't work either), and it didn't work with my webcam (HD Webcam C525 (046d:0826)). The log is given below. I tried ffmpeg to record a video on this system, and it worked fine. Please let me know if you need more information. Thanks!

Oct 04 19:24:00 odroid systemd[1]: [/usr/lib/systemd/system/zoneminder.service:15] Not an absolute path, ignoring: "/var/run/zm/zm.pid"
Oct 04 19:24:01 odroid systemd[1]: Starting ZoneMinder CCTV recording and security system...
Oct 04 19:24:03 odroid zmpkg[1720]: INF [Command: start]
Oct 04 19:24:05 odroid zmdc[1733]: INF [Server starting at 14/10/04 19:24:05]
Oct 04 19:24:14 odroid zmdc[1733]: INF ['zmc -d /dev/video0' starting at 14/10/04 19:24:14, pid = 1759]
Oct 04 19:24:14 odroid zmdc[1759]: INF ['zmc -d /dev/video0' started at 14/10/04 19:24:14]
Oct 04 19:24:19 odroid zmdc[1733]: ERR ['zmc -d /dev/video0' exited abnormally, exit status 255]
Oct 04 19:24:25 odroid zmdc[1733]: INF [Starting pending process, zmc -d /dev/video0]
Oct 04 19:24:25 odroid zmdc[1733]: INF ['zmc -d /dev/video0' starting at 14/10/04 19:24:25, pid = 1766]
Oct 04 19:24:25 odroid zmdc[1766]: INF ['zmc -d /dev/video0' started at 14/10/04 19:24:25]
Oct 04 19:24:25 odroid zmdc[1733]: INF ['zmfilter.pl' starting at 14/10/04 19:24:25, pid = 1769]
Oct 04 19:24:25 odroid zmdc[1769]: INF ['zmfilter.pl' started at 14/10/04 19:24:25]
Oct 04 19:24:25 odroid zmc_dvideo0[1766]: INF [Starting Capture]
Oct 04 19:24:26 odroid zmc_dvideo0[1766]: ERR [Attempt to assign buffer from a NULL pointer]
Oct 04 19:24:26 odroid zmc_dvideo0[1766]: ERR [Attempt to assign buffer from a NULL pointer]
Oct 04 19:24:26 odroid zmc_dvideo0[1766]: ERR [Attempt to assign buffer from a NULL pointer]
Oct 04 19:24:26 odroid zmc_dvideo0[1766]: ERR [Attempt to assign buffer from a NULL pointer]

and this message repeated hundreds of times ....

Another thing I did see from "dmesg" is that:
[ 1640.703753] usb 1-3.3: reset high-speed USB device number 5 using exynos-ehci

Not sure if this is something suspicious, but this message shows up even with ffmpeg, which works fine. 
##

**Comment by mastertheknife** [comment]
I am pretty sure this is not relevant anymore, its over 2 years old
But if it does, something about the error doesn't make sense. That error comes from Assign(), which only runs when there is no format conversion to perform, however the logs show that there is format conversion.
Unfortunately, the logging level was too low and the format conversion debugging is at level 9. These level 9 messages seem to be missing from the bottom part of the log, after the "snipped".

**Comment by connortechnology** [comment]
I'd like to think it isn't relevant.. .but nothing has been done to fix it.  So something is amiss, but until we can reproduce it... we might as well close it.
