### ISSUE TITLE
no streaming with libvlc

### ISSUE THREAD

**Issue by connortechnology** [ZoneMinder/ZoneMinder#525]
Using libvlc to grab an rtsp stream.  When I open the monitor, I get a current image, but it doesn't stream (the timestamp doesn't change).  Reloading the page gets a different (up to date) image, but no stream.
##

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
