### ISSUE TITLE
Maximum FPS ignored

### ISSUE THREAD

**Issue by vlad2005** [ZoneMinder/ZoneMinder#528]
Hi!
I running latest zoneminder 1.27.99+1-trusty-SNAPSHOT2014092601.
Normally, i don't set any value for MaxFPS and AlarmMaxFPS.
When i try to set MaxFPS to 1fps (as example), nothing change.  All cameras still working (in idle mode) at maximum fps allowed by capture card, in my case about 1,35fps.
##

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
