### ISSUE TITLE
Regular user cannot create or access groups

### ISSUE THREAD

**Issue by barjac** [ZoneMinder/ZoneMinder#541]
I'm under the impression that this feature (groups) is intended to be accessible to all web users, however testing in 1.28.0 it seems that the groups feature is only visible in the UI to admins with system edit rights.

Can this be changed so that any user can set his/her own groups for monitoring?

**Comment by knnniggett** [comment]
Didn't @connortechnology previously fix this, or do I mis-remember?

**Comment by connortechnology** [comment]
I did do something, but I can't find it now.  Must have just committed it instead of doing a PR.  I think barjac wanted more.

**Comment by barjac** [comment]
IIRC you made it so that normal users could access groups previously set by an admin, but not set them up. I thought that regular users should be able to set up their own groups.

**Comment by knnniggett** [comment]
@barjac what say ye? Can we close this or is there more work to be done?

**Comment by barjac** [comment]
I have not rebuilt recently so no idea how it is at present. Mageia 5 was in freeze for months :\ I still think as above. If a user just wants to group a few monitors together for a montage they should be able to do that.
