### ISSUE TITLE
Create a Video Download Wizard [$105]

### ISSUE THREAD

**Issue by butlerm1977** [ZoneMinder/zoneminder#542]
Pulling video from Zoneminder through the filter interface is always a bit clunky.  I am suggesting a more user friendly approach to the task of downloading a video.  This request focuses on two major changes.  
1.  Rather than using the filter interface, I am suggesting a new button be added to the frontend called “Download Wizard”.  This button would launch a single window with the following:
    a.  Name: (Dropdown Box containing all “Enabled” camera feeds
    b.  Start Date/Time: Can use the standard date/time picker along with a text box.
    c.  End Date/Time: same as above

Example of a similar window:

![vid](https://cloud.githubusercontent.com/assets/5910607/4817181/5edc02a6-5ee6-11e4-8341-42f09203f9d8.PNG)
1.  Improving the precision of the video request.  Currently the video export, through ffmpeg, is limited to the length of the section/event.  If more than one event is found in the filter, each event will need to be exported to video individually.  Also in the current implementation, it is impossible to export video that is smaller or larger than the length of a single event.  

I am requesting a new approach to exporting video.  I would like to be able to export a video based on start time and end time.  In doing so, the result would not be a listing of events, but a single video download.

Based on the source settings of the video (FPS) and system settings (DIR_EVENTS & ZM_USE_DEEP_STORAGE) the full inventory of jpegs residing in storage would be passed through to FFMPEG for video creation.  Since the storage method of jpegs changes when using deep storage, this would have to be taken into account when deriving the inventory of frames involved between a start time and an end time.  The FFMPEG command would be executed on all calculated frames and follow the syntax set forth in FFMPEG_OUTPUT_OPTIONS.
##

**Comment by lbdc** [comment]
Hello

A while ago I wrote a single file PHP script that looks and probably does similar to what you ask. Works great for me to create videos between start/end dates from stills

The script has 2 modes:
All = movies generated from all frames between time period
Alarm = alarm frames only (with time buffer before and after). The intent of this is to be used with mocord.

Tested in ubuntu 14.04 using mysql DB, apache, mencoder

How can I upload you the script?

**Comment by butlerm1977** [comment]
This solution used to work great!  But it's no longer working on Zoneminder 1.30. I'm testing this on CentOS 7.3  x64 installation with PHP 7 and FFMPEG 2.8.7.

**Comment by lbdc** [comment]
On Ubuntu PHP 7 "parse_ini_file" function replaced "#" with ";" as comment lines (zm.conf uses "#") and broke the script

I assume that's the problem. Which script do you use? zm-movie or zm_movie_bootstrap

I wish this functionality could be included in zm. For now the script works great for me also. I will update shortly.

**Comment by connortechnology** [comment]
Perhaps we should take it over and integrate it. What we would really like to do is integrate the developer. We are so sorry if developer resources.

**Comment by butlerm1977** [comment]
@lbdc I'm currently using the zm_movie_bootstrap script.  @connortechnology I think this would be fantastic to integrate into zoneminder build.  This method is by far the easiest way to pull and encode videos.

**Comment by lbdc** [comment]
I can look into integrating in zm but would need a bit of support. Putting a link in zm to my script is probably not what you had in mind. Can we take this offline?
