### ISSUE TITLE
zmtrigger barf

### ISSUE THREAD

**Issue by pashdown** [ZoneMinder/ZoneMinder#545]
1.27.99

zmtrigger eventually dies with this error:

Use of uninitialized value $nbytes in concatenation (.) or string at /usr/share/perl/5.18.2/ZoneMinder/Trigger/Channel/Handle.pm line 90.
Use of uninitialized value $nbytes in concatenation (.) or string at /usr/share/perl/5.18.2/ZoneMinder/Trigger/Channel/Handle.pm line 90.
variable is not a string at /usr/share/perl/5.18.2/ZoneMinder/Memory/Mapped.pm line 125.

**Comment by CalebMuhia** [comment]
Hi, 

am also getting variable is not a string at /usr/share/perl5/ZoneMinder/Memory/Mapped.pm line 125.
i have zoneminder 1.28 build from source

zmtrigger.pl dies and does not work again till the next restart
would like to sort out the issue

Thanks

**Comment by pashdown** [comment]
I had to resort to starting zmtrigger with a bash loop, so it gets restarted every time it dies.  And yes, I'm using 1.28.0.

**Comment by connortechnology** [comment]
I've been tracking this on zoneminder.com too.  it is weird... something to do with the monitors being reloaded and the mmap variable getting corrupted. doesn't happen for me either, but it definitely is an ongoing problem.

**Comment by CalebMuhia** [comment]
we are using video card for the capture. does it help when using ip cameras?

**Comment by XenonofArcticus** [comment]
Currently happening for me with HD IP cameras.

**Comment by cryo** [comment]
My speculation is this is due to a socket timeout from the IP camera (or a telnet connection to the zmtrigger port.  It still seems to want to use it until it is corrupted and crashes.  Implemented bash loop as mentioned to keep it going.

**Comment by XenonofArcticus** [comment]
However, when it crashes, it does lose the event in progress, which is an undesired behavior so fixing this would be important.

**Comment by knnniggett** [comment]
Putting this here, because I believe it will resolve this issue.

The following sample code from @pliablepixels is intended to fix a suspected problem with zmtrigger when a monitor is saved or modified. Zmtrigger does not update its memory handle and consequently crashes or fails when it attempts to read from the old, invalid handle.

```Perl
#!/usr/bin/perl
use ZoneMinder;
use DBI;

my @monitors = ();
my $dbh = zmDbConnect();

loadMonitors();

my $iter=1;

for (;;)
{
        foreach $mon (@monitors)
        {
               
                my $mr = zmMemRead($mon, "shared_data:valid");
                print ("Iteration:$iter Checking Monitor ".$mon->{Id}." MemReadResult:$mr Name:".$mon->{Name}." MMap address:".$mon->{MMapAddr}."\n");
                if ($mr!="1")
                {
                        zmMemInvalidate($mon);
                        my $mv =zmMemVerify($mon);
                        print ("Reloading memory for ".$mon->{Id}.", status of verify is:$mv\n");
                }
        }
        print ("==================================\n");
        sleep(1);
        $iter++;
}

sub loadMonitors()
{
        @monitors =();
        my $sql = "SELECT * FROM Monitors
               WHERE find_in_set( Function, 'Modect,Mocord,Nodect' )" ;
        my $sth = $dbh->prepare_cached( $sql )
        or Fatal( "Can't prepare '$sql': ".$dbh->errstr() );
        my $res = $sth->execute()
            or Fatal( "Can't execute: ".$sth->errstr() );
         while( my $monitor = $sth->fetchrow_hashref() )
        {
                push @monitors, $monitor;
        }
}
```

We could use someone willing to incorporate this into the zmtrigger script on their system and then run it for an extended period to check for failures.  If no one else does, I will eventually get to this, but it is not on my immediate task list.

**Comment by knnniggett** [comment]
I'm putting @connortechnology 's comment here:
> I have put a package up on my ppa. Anyone subscribed to it who is on 14.04 should get the updated Sys::MMap and the variable is not a string problem should be resolved.

The cause of Issue #545 has been identified to be a bug in the Perl Sys:MMap module. To resolve this, go the PPA and install the latest libsys-mmap-perl package @connortechnology has placed there. This affects Ubuntu LTS users or anyone else with a perl mmap module older than version 17.
