### ISSUE TITLE
Create new bootstrap-based skin

### ISSUE THREAD

**Issue by kylejohnson** [ZoneMinder/ZoneMinder#547]
This is linked to #546 

My goal is to create a new skin with the best of classic and flat, but is more maintainable by taking some best practices, such as using `include`s for various files, using a modern CSS framework (bootstrap), and perhaps eventuallly removing mootools in place of jquery - but that isn't fully required.

The real goal of this skin is to hold us over until a complete rewrite of the UI can take place.
##

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
