### ISSUE TITLE
Create new zoneminder.com website

### ISSUE THREAD

**Issue by kylejohnson** [ZoneMinder/ZoneMinder#548]
This should be part of the 1.29 release.  We need a website that is tracked in source control along with the rest of our code.

 * Website is currently accessible at http://zoneminder.gnulnx.net/
 * Code for the website is in the gh-pages branch
 * Website uses jekyll for templating, etc.

**Comment by knnniggett** [comment]
Closing this as we have previously deployed our new website.

@scottgrobinson We have a mailing list now. Let us know if you are not already on it.

@kylejohnson should we delete the gh-pages branch??
