### ISSUE TITLE
Zoneminder Foscam libvlc

### ISSUE THREAD

**Issue by pge** [ZoneMinder/ZoneMinder#552]
Hey! I'm running Zoneminder 1.28.0 on Ubuntu 14.04.1 LTS.

I have 2 Foscam Cameras in Place.

- FI9804W
- FI9831W

Both have been working with ffmpeg until now but produced garbage frames too often.
I was told to switch to VLC which i gladly wanted to try.

I installed Zoneminder from the iconnor PPA and have the following vlc libraries installed on my system: 

ii  libvlc5                             2.1.4-0ubuntu14.04.1                 amd64        multimedia player and streamer library
ii  libvlccore7                         2.1.4-0ubuntu14.04.1                 amd64        base library for VLC and its modules
ii  vlc-data                            2.1.4-0ubuntu14.04.1                 all          Common data for VLC

Up until now i used the standard rtsp URL with ffmpeg in format: 

rtsp://user:password@10.1.56.11:88/videoMain

I have switched TO libvlc with the following settings in place:

Source Type: libvlc
Source Path: rtsp://user:password@10.1.56.11:88/videoMain
Remote Method: RTP/Unicast (as suggested on freenode/#zoneminder)

Unfortuantely i get no picture and this error on the log:

2014-11-05 00:54:49.504890	zmdc	19262	ERR	'zmc -m 2' exited abnormally, exit status 255	zmdc.pl	
2014-11-05 00:54:49.464636	zmc_m2	19587	FAT	Unable to create libvlc instance due to: (null)	zm_libvlc_camera.cpp	170

Maybe someone has an idea on how to debug/fix this?

Thanks in advance,
Patrick

**Comment by knnniggett** [comment]
Please try the latest zoneminder 1.28.1 package or the latest development package as they contain RTSP changes. For example, I can successfully use my Foscam 9821 using a source type of Remote and Remote Protocol of RTSP.

**Comment by pge** [comment]
Well, I have already been running 1.28.1-trusty-1 for the entire time and there doesnt seem to be an update on ppa.launchpad.net/iconnor/zoneminder/

@connortechnology ?

**Comment by knnniggett** [comment]
Well no, you weren't running 1.28.1 the entire time.  Refer to your very first statement. We only know what you tell us in writing. 

In any case, you need to try the remote/RTSP method.  There is currently no information stated in this issue that indicates this is any kind of a bug that we don't already know about.
