### ISSUE TITLE
Mobile Application

### ISSUE THREAD

**Issue by scottgrobinson** [ZoneMinder/ZoneMinder#559]
With EyeZM not having been updated in a while and using the mobile skin specificall, would it be worth developing a mobile application similar to ZM?

Happy to take a lead on it if there's intrest..

Main changes being:
- Free
- Github code again so we're not locked down and stuck if things need updating in it
- Using API/Not reliant on the skin!

Thoughts?

**Comment by arjunroychowdhury** [comment]
scott, is this under development? open source by any chance?

**Comment by knnniggett** [comment]
Development of a mobile application, zmninja, is being done by @pliablepixels and is currently in alpha stages, which obsoletes this particular issue.  

If anyone wishes to participate in testing, feel free to contact him.

**Comment by pliablepixels** [comment]
Yup, almost 5 months since I posted this message. Decided to make my own. Its in stable state now for both iOS and Android

https://github.com/pliablepixels/zmNinja for source
https://www.youtube.com/watch?v=sSIMic2V6Jo&feature=youtu.be for a video (of the iOS client)
App Store/Play Store status: In beta testing - will make it live when ZM folks release 1.29

**Comment by PaulHam211** [comment]
Pilablepixels,
Is there any chance to get access to the IOS beta test? I assume it would go through something like 'testflight'?

I have just bought a house and have set up zoneminder, but have noticed that the eyeZM app that i bought from the appstore a few years ago now seems to have disappeared! Very disappointing.

**Comment by pliablepixels** [comment]
@PaulHam211 please refer to http://www.zoneminder.com/forums/viewtopic.php?f=32&t=23073 for the criteria and then please send me an email when done so we can take the rest of the conversation offline
