### ISSUE TITLE
Live view wrong socket name

### ISSUE THREAD

**Issue by milefork** [ZoneMinder/zoneminder#563]
Hi,

if i want to Live view the Camera I recently added I get an error like this:

`socket_sendto( /var/run/zm/zms-152934s.sock ) failed: No such file or directory`

while looking at this directory there exists a `zms-152934w.sock` .
Have I configured something wrong?

**Comment by slippers** [comment]
had this issue:  the PATH_ZMS path and the apache path for the cgi did not match.  was missing /zm/cgi...

also added +FollowSymLinks to the zonminder.conf for cgi

**Comment by grndamgt4** [comment]
slippers, thank you. Adding "/zm" in front of "/cgi-bin/nph-zms" to make it "/zm/cgi-bin/nph-zms" under options->path tab->PATH_ZMS fixed this for me.

**Comment by knnniggett** [comment]
Guys, properly configuring PATH_ZMS is part of the installation documentation of every distro we support.
Please make sure and read the documentation for your distro after every installation and upgrade.
