### ISSUE TITLE
Implement version check for ffmpeg and libav

### ISSUE THREAD

**Issue by SteveGilvarry** [ZoneMinder/ZoneMinder#580]
@knnniggett Reminded me of some information I found on handling ffmpeg and libav versions. Putting this in here as a reminder to me to come back and look at implementing it.

Looking for av_frame_alloc here (thanks @SteveGilvarry ) : https://github.com/FFmpeg/FFmpeg/blob/master/doc/APIchanges

I found the relevant text:

2013-12-11 - 29c83d2 / b9fb59d,409a143 / 9431356,44967ab / d7b3ee9 - lavc 55.45.101 / 55.28.1 - avcodec.h
av_frame_alloc(), av_frame_unref() and av_frame_free() now can and should be
used instead of avcodec_alloc_frame(), avcodec_get_frame_defaults() and
avcodec_free_frame() respectively. The latter three functions are deprecated.
This tells us that libav implemented av_frame_alloc() in version 55.45.101
while ffmpeg implemented the same function in version 55.28.1

(if the third octect in the version number is >100 then we know it applies to libav)

So this puts us in a bit of a pickle due to the differences in versions. Technically, the best "correct" way to do this is to implement what @SteveGilvarry found for us in the libvlc library:
https://github.com/videolan/vlc/blob/d36bc0a71a7a69afd085c8b2754ecfbc5876fd2b/modules/codec/avcodec/avcommon_compat.h

But that will require more time than either of us want to spend our weekend working on.

However, the following might work if we just check the larger version number:
# if LIBAVCODEC_VERSION_INT >= AV_VERSION_INT(55, 45, 101)

```
  av_frame_alloc()
```
# else

```
avcodec_alloc_frame()
```
# endif

It's not as efficient for ffmpeg since we won't be using the newer function call for all versions of ffmpeg that support it.

Yeah, I know. This sure is a lot of work for such a small change, and it is probably why we don't get many volunteers to help our with this kind of work. I learn a little but more each time we get a new pull request that deals with the c++ side of zoneminder.
##

**Comment by connortechnology** [comment]
I think we should only support back to the last ubuntu lts release, which is 12.04.  Or debian wheezy.

**Comment by knnniggett** [comment]
Relevant quote from @onlyjob in #762 

~~~~
Compilation on Debian Jessie revealed multiple deprecations:

src/zm_ffmpeg.cpp:79:18: warning: ‘AVFrame* avcodec_alloc_frame()’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3195)
src/zm_ffmpeg.cpp:79:38: warning: ‘AVFrame* avcodec_alloc_frame()’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3195)
src/zm_ffmpeg.cpp:85:19: warning: ‘AVFrame* avcodec_alloc_frame()’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3195)
src/zm_ffmpeg.cpp:85:39: warning: ‘AVFrame* avcodec_alloc_frame()’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3195)

src/zm_local_camera.cpp:614:16: warning: ‘AVFrame* avcodec_alloc_frame()’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3195)
src/zm_local_camera.cpp:614:36: warning: ‘AVFrame* avcodec_alloc_frame()’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3195)
src/zm_local_camera.cpp:844:24: warning: ‘AVFrame* avcodec_alloc_frame()’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3195)
src/zm_local_camera.cpp:844:44: warning: ‘AVFrame* avcodec_alloc_frame()’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3195)

src/zm_mpeg.cpp:326:14: warning: ‘AVFrame* avcodec_alloc_frame()’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3195)
src/zm_mpeg.cpp:326:35: warning: ‘AVFrame* avcodec_alloc_frame()’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3195)
src/zm_mpeg.cpp:347:19: warning: ‘AVFrame* avcodec_alloc_frame()’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3195)
src/zm_mpeg.cpp:347:40: warning: ‘AVFrame* avcodec_alloc_frame()’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3195)

src/zm_remote_camera_rtsp.cpp:194:17: warning: ‘AVFrame* avcodec_alloc_frame()’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3195)
src/zm_remote_camera_rtsp.cpp:194:37: warning: ‘AVFrame* avcodec_alloc_frame()’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3195)
src/zm_remote_camera_rtsp.cpp:197:14: warning: ‘AVFrame* avcodec_alloc_frame()’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3195)
src/zm_remote_camera_rtsp.cpp:197:34: warning: ‘AVFrame* avcodec_alloc_frame()’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3195)

src/zm_sdp.cpp:407:45: warning: ‘AVCodecContext::codec_name’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:1065)
src/zm_sdp.cpp:407:45: warning: ‘AVCodecContext::codec_name’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:1065)
src/zm_sdp.cpp:407:112: warning: ‘AVCodecContext::codec_name’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:1065)
src/zm_sdp.cpp:407:112: warning: ‘AVCodecContext::codec_name’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:1065)
src/zm_sdp.cpp:423:45: warning: ‘AVCodecContext::codec_name’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:1065)
src/zm_sdp.cpp:423:45: warning: ‘AVCodecContext::codec_name’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:1065)
src/zm_sdp.cpp:423:113: warning: ‘AVCodecContext::codec_name’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:1065)
src/zm_sdp.cpp:423:113: warning: ‘AVCodecContext::codec_name’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:1065)
src/zm_sdp.cpp:431:30: warning: ‘AVCodecContext::codec_name’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:1065)
src/zm_sdp.cpp:431:30: warning: ‘AVCodecContext::codec_name’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:1065)
~~~

**Comment by SteveGilvarry** [comment]
We keeping this open for the latter part of the discussion around supported versions of ffmpeg/libav? Not sure much point breaking stuff that is working, but if we are changing something we should be able to say  no more hacks for versions < x.x.

**Comment by onlyjob** [comment]
By the way Debian is switching to ffmpeg: https://lists.debian.org/debian-devel-announce/2015/07/msg00001.html

**Comment by knnniggett** [comment]
Hey, I'm not crazy after all.  This is issue is still open.  Thought I was losing it the other day when I missed @manupap1 's fix for this.

This is as good a spot as any to talk about supported versions of ffmpeg.
Perhaps we can get an answer to that by answering the question, "What versions of ffmpeg do our most actively support Linux distros ship with?"

Of course, this question is more convoluted than it sounds due to libav in the Debian distros and redhat distros for example don't (won't ever?) even ship with ffmpeg.

For Redhat, I've been relying on RPMFusion for fffmpeg.
They've got ffmpeg 0.10 for RHEL 6 and ffmpeg 2.6 for Fedora.  This unfortunately means supporting a lot of versions inbetween.

What versions are shipped with and/or most used in Debian and Ubuntu?

**Comment by onlyjob** [comment]
Debian "testing" have 2.7.2 at the moment, see https://packages.qa.debian.org/f/ffmpeg.html

**Comment by knnniggett** [comment]
If it looks like like CentOS 6 is the only distro requiring an old version of ffmpeg, I would be willing to rebuild a newer 2.x ffpmeg package for centos 6 and place it into zmprepo, if it makes it easier for the goals of the zoneminder project. 

Since redhat does not host ffmpeg packages, building ffmpeg for zmrepo does not violate the golden rule of replacing core packages in the base repo.

**Comment by knnniggett** [comment]
@barjac what version of ffmpeg does Mageia currently use?

**Comment by barjac** [comment]
Mageia 5 (current stable) uses ffmpeg version 2.4.9
Mageia 6 development has ffmpeg version 2.7.1
