### ISSUE TITLE
Wrong encoding for some lang files

### ISSUE THREAD

**Issue by manupap1** [ZoneMinder/zoneminder#583]
Some lang files are encoded to non UTF8 encoding and this results in a bad translation for special characters. For example (french lang file fr_fr.php encoded to ISO-8859):
![zm_encoding_issue](https://cloud.githubusercontent.com/assets/7723405/5091552/cfde810e-6f49-11e4-8eb6-d99611e5b1bd.png)

All lang files should be encoded to UTF-8.
##

**Comment by cpasqualini** [comment]
Workaround, at least in Debian official packages for my language:
cp /usr/share/zoneminder/www/lang/es_ar.php .
iconv -f iso8859-1 -t utf8 es_ar.php >/usr/share/zoneminder/www/lang/es_ar.php

best regards

**Comment by cpasqualini** [comment]
Workaround, at least in Debian official packages for my language:
cp /usr/share/zoneminder/www/lang/es_ar.php .
iconv -f iso8859-1 -t utf8 es_ar.php >/usr/share/zoneminder/www/lang/es_ar.php

best regards

**Comment by cpasqualini** [comment]
Hi all
Any progress on this issue?

**Comment by knight-of-ni** [comment]
Fixed in #2131. Closing.

**Comment by cpasqualini** [comment]
Thanks for merging this!!
