### ISSUE TITLE
ZMS crashes after "Attempt to directly assign buffer from an undersized buffer of size" error

### ISSUE THREAD

**Issue by warner83** [ZoneMinder/ZoneMinder#586]
ZMS process crashes after "Attempt to directly assign buffer from an undersized buffer of size" error.
The bug appears only with RTSP stream. 
My system is Ubuntu 14.10 64-bit. 

Here is the log:
zms[5521].ERR-zm_image.cpp/344 [Attempt to directly assign buffer from an undersized buffer of size: 1993728]
zms[5521].ERR-zm_image.cpp/344 [Attempt to directly assign buffer from an undersized buffer of size: 1993728]
zms[5521].ERR-zm_image.cpp/344 [Attempt to directly assign buffer from an undersized buffer of size: 1993728]
zms[5521].ERR-zm_image.cpp/344 [Attempt to directly assign buffer from an undersized buffer of size: 1993728]
zmwatch[5468].ERR-zmwatch.pl [Shared data size conflict in shared_data for monitor Monitor-3, expected 336, got 4281274139]
zmwatch[5468].ERR-zmwatch.pl [Shared data size conflict in shared_data for monitor Monitor-3, expected 336, got 4281274139]
zmc_m2[5402].INF-zm_monitor.cpp/2899 [Monitor-2: 1000 - Capturing at 13.70 fps]
zma_m2[5404].INF-zm_monitor.cpp/1150 [Monitor-2: 1000 - Processing at 13.51 fps]
zms[5521].ERR-zm_monitor.cpp/4147 [Terminating, last frame sent time 10.014127 secs more than maximum of 10.000000]
zms[5500].ERR-zm_monitor.cpp/4147 [Terminating, last frame sent time 10.022925 secs more than maximum of 10.000000]
zms[5521].ERR-zm_signal.cpp/54 [Got signal 6 (Aborted), crashing]
zms[5521].ERR-zm_signal.cpp/77 [Signal address is 0x2100001591, from 0x7fbaadfb2d27]
zms[5521].ERR-zm_signal.cpp/98 [Backtrace 0: /usr/lib/cgi-bin/zms() [0x47bed5]]
zms[5521].ERR-zm_signal.cpp/98 [Backtrace 1: /lib/x86_64-linux-gnu/libpthread.so.0(+0xfc90) [0x7fbaaf30dc90]]
zms[5521].ERR-zm_signal.cpp/98 [Backtrace 2: /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37) [0x7fbaadfb2d27]]
zms[5521].ERR-zm_signal.cpp/98 [Backtrace 3: /lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x7fbaadfb4418]]
zms[5521].ERR-zm_signal.cpp/98 [Backtrace 4: /lib/x86_64-linux-gnu/libc.so.6(+0x789f4) [0x7fbaadff49f4]]
zms[5521].ERR-zm_signal.cpp/98 [Backtrace 5: /lib/x86_64-linux-gnu/libc.so.6(+0x7ea77) [0x7fbaadffaa77]]
zms[5521].ERR-zm_signal.cpp/98 [Backtrace 6: /usr/lib/cgi-bin/zms() [0x43add8]]
zms[5521].ERR-zm_signal.cpp/98 [Backtrace 7: /usr/lib/cgi-bin/zms() [0x42983b]]
zms[5521].ERR-zm_signal.cpp/98 [Backtrace 8: /usr/lib/cgi-bin/zms() [0x43ae9e]]
zms[5521].ERR-zm_signal.cpp/98 [Backtrace 9: /usr/lib/cgi-bin/zms() [0x429c0e]]
zms[5521].ERR-zm_signal.cpp/98 [Backtrace 10: /lib/x86_64-linux-gnu/libc.so.6(+0x3a599) [0x7fbaadfb6599]]
zms[5521].ERR-zm_signal.cpp/98 [Backtrace 11: /lib/x86_64-linux-gnu/libc.so.6(+0x3a5e5) [0x7fbaadfb65e5]]
zms[5521].ERR-zm_signal.cpp/98 [Backtrace 12: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfc) [0x7fbaadf9decc]]
zms[5521].ERR-zm_signal.cpp/98 [Backtrace 13: /usr/lib/cgi-bin/zms() [0x407529]]

**Comment by Konstigt** [comment]
Wonder if I have the same problem.  I get this if I try to access my web ui with skin=flat.. but if I access with skin=mobile it works.

zms[2801]: WAR [Shared data not initialised by capture daemon, some query functions may not be available or produce invalid results for monitor Monitor-1]
zms[2801]: ERR [Attempt to directly assign buffer from an undersized buffer of size: 136305, needed 234x196*3 colours = 3213035440]
zms[2801]: message repeated 9 times: [ ERR [Attempt to directly assign buffer from an undersized buffer of size: 136305, needed 234x196*3 colours = 3213035440]]
zms[2801]: INF [Got signal 15 (Terminated), exiting]
zms[2801]: ERR [Unable to send stream frame: Broken pipe]
zms[2801]: INF [Terminating Logger]

$ apt-cache policy zoneminder
zoneminder:
  Installed: 1.28.0+1-trusty-SNAPSHOT2014121201
  Candidate: 1.28.0+1-trusty-SNAPSHOT2014121201
  Version table:
 *** 1.28.0+1-trusty-SNAPSHOT2014121201 0
        500 http://ppa.launchpad.net/iconnor/zoneminder-master/ubuntu/ trusty/main i386 Packages
        100 /var/lib/dpkg/status
     1.26.5-1ubuntu3 0
        500 http://se.archive.ubuntu.com/ubuntu/ trusty/universe i386 Packages

ipcs -l

------ Shared Memory Limits --------
max number of segments = 4096
max seg size (kbytes) = 3222656
max total shared memory (kbytes) = 4267483648
min seg size (bytes) = 1

------ Semaphore Limits --------
max number of arrays = 128
max semaphores per array = 250
max semaphores system wide = 32000
max ops per semop call = 32
semaphore max value = 32767

------ Messages Limits --------
max queues system wide = 1652
max size of message (bytes) = 8192
default max size of queue (bytes) = 16384
