### ISSUE TITLE
Editing control settings on a monitor should probably try to kill any running zmcontrol

### ISSUE THREAD

**Issue by connortechnology** [ZoneMinder/ZoneMinder#590]
A running zmcontrol.pl will not pick up new settings.  

Maybe the fix is to make zmcontrol constantly reload the monitor, because in a distributed setup, zmcontrol.pl might be running on another machine.

**Comment by thebostik** [comment]
This was a huge pain to figure out. Plenty of great messages to the user about how some settings changes require a zoneminder service restart, by contrast, didn't see anything about this. A good fix would be to just indicate to the user on saving any control tab settings that they must manually kill the zmcontrol process or else it won't pick up their changes.
