### ISSUE TITLE
RECORD_EVENT_STATS and ZM_RECORD_DIAG_IMAGES should be per monitor

### ISSUE THREAD

**Issue by connortechnology** [ZoneMinder/ZoneMinder#597]
These should be configured on a per-monitor basis as well.  The performance hit it huge, and I tend to only analyze one monitor at a time.
##

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
