### ISSUE TITLE
mjpg streamer installations on fedora 20

### ISSUE THREAD

**Issue by 1989canyontechnologies** [ZoneMinder/ZoneMinder#600]
I have installed zone minder on fedora 20 am not try to connect web camera in zoneminder,But am unable to installed package name mjpg_streamer on same. i have downloaded .rpm of mjpg_streamer but its failed at the end of installations  i have also tried to install through command but its says invalid db format.. i have installed gstreamer. Kindly help Email me on phulambrikarvasudev9@gmail.com

**Comment by connortechnology** [comment]
I don't see what this has to do with ZoneMinder.
