### ISSUE TITLE
ffmpeg not working with second identical ipcam - zoneminder 1.28.0

### ISSUE THREAD

**Issue by vlad2005** [ZoneMinder/ZoneMinder#604]
Hi!
I have two identical ipcam with same settings in same network.
One work very well with ffmpeg but second give me blue screen.
If i change source for second ipcam to libvlc then work ok, but libvlc give me another problems. After some period image freeze and server stop receive any image.
I'm very happy with ffmpeg, work well, but why second cam give me blue screen? Any suggestion?

**Comment by knnniggett** [comment]
Closing this out as there is nothing here that indicates this is a bug in ZoneMinder.

If you have upgraded to the latest version of zoneminder and still experience this issue, you should take this to the user forum. Information required to troubleshoot this is: make & model of camera, your complete monitor config, your distro, how you installed zoneminder (from source or package), and the version of ffmpeg on your system.
