### ISSUE TITLE
Several crashes on Fedora 20

### ISSUE THREAD

**Issue by astafyev** [ZoneMinder/ZoneMinder#637]
Hi, I've installed zoneminder-1.28.0-3.fc20.x86_64.rpm from official ZM repo and it seems very unstable. I got lots of crashes of zma, zmc and zmu:

Dec 14 23:05:38 srv zmdc[8756]: WAR [Can't find process with command of 'zmtrack.pl -m 1']
Dec 14 23:05:39 srv zmdc[8756]: WAR [Can't find process with command of 'zma -m 1']
Dec 14 23:05:39 srv zmdc[8756]: INF ['zmc -d /dev/video0' stopping at 14/12/14 23:05:39]
Dec 14 23:05:39 srv zmc_dvideo0[8795]: INF [Got signal 15 (Terminated), exiting]
Dec 14 23:05:39 srv zmc_dvideo0[8795]: ERR [Got signal 11 (Segmentation fault), crashing]
Dec 14 23:05:45 srv zmdc[8756]: INF ['zmc -d /dev/video0' crashed, signal 8]
Dec 14 23:05:45 srv zmdc[8756]: INF ['zmc -d /dev/video0' starting at 14/12/14 23:05:45, pid = 9572]
Dec 14 23:05:45 srv zmdc[9572]: INF ['zmc -d /dev/video0' started at 14/12/14 23:05:45]
Dec 14 23:05:45 srv zmdc[8756]: INF ['zma -m 1' starting at 14/12/14 23:05:45, pid = 9581]
Dec 14 23:05:45 srv zmdc[9581]: INF ['zma -m 1' started at 14/12/14 23:05:45]
Dec 14 23:05:46 srv kernel: [1995673.051141] zma[9581]: segfault at 18 ip 00007f7a40204fe0 sp 00007fff6db91e38 error 4 in libpthread-2.18.so[7f7a401fb000+18000]
Dec 14 23:05:46 srv zmc_dvideo0[9572]: INF [No direct match for the selected palette and target colorspace. Format conversion is required, performance penalty expected]
Dec 14 23:05:46 srv zma_m1[9581]: ERR [Shared data not initialised by capture daemon]
Dec 14 23:05:46 srv zmdc[8756]: INF ['zma -m 1' crashed, signal 10]
Dec 14 23:05:46 srv zmdc[8756]: INF [Starting pending process, zma -m 1]
Dec 14 23:05:46 srv zmc_dvideo0[9572]: INF [Starting Capture]
Dec 14 23:05:46 srv zmdc[8756]: INF ['zma -m 1' starting at 14/12/14 23:05:46, pid = 9603]

Dec 14 23:09:01 srv zmu[9631]: WAR [Shared data not initialised by capture daemon, some query functions may not be available or produce invalid results]
Dec 14 23:09:01 srv zmu[9631]: ERR [Got signal 11 (Segmentation fault), crashing]

Crashes usually happen when I try to see live stream or make some changes in Monitor configuration. After that web interface stucks and I have to restart httpd to get it back to live. I use only one USB camera:
Bus 006 Device 002: ID 046d:08da Logitech, Inc. QuickCam Messanger

**Comment by knnniggett** [comment]
This issue appears to be resolved.  If I am mistaken please reopen and let us know the current status.
