### ISSUE TITLE
Horrible error message when pressing probe

### ISSUE THREAD

**Issue by wwat** [ZoneMinder/ZoneMinder#658]
When I press probe, I get the following message:
```
Unable determine arp path, status is '1'
```
1) it's not correct English
2) arp is spelt ARP (if that's what it's about)
3) 'status' (???) 
4) '1'(???) (does this mean on or off)

tl;dr WTF?!

**Comment by kylejohnson** [comment]
Please feel welcome to submit a PR - seems like an easy fix.  I am assuming 1 is the exit code when attempting to run the arp command.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SteveGilvarry** [comment]
Means it couldn't find the file path for the arp command, as opposed to the protocol ARP. Try running 'type -p arp' on your system and you will probably get a 1 returning.

**Comment by SteveGilvarry** [comment]
PR done and merged, hopefully my new message is better.
