### ISSUE TITLE
Modify Frames table to not have a composity key [$150]

### ISSUE THREAD

**Issue by kylejohnson** [ZoneMinder/ZoneMinder#663]
Hey everyone.  Looking for feedback on modifying the ZM DB schema to NOT use a composite (multi-column) primary key on the Frames table.  The reason being a limitation with CakePHP - it does not support composite keys.  And as I am /heavily/ invested in CakePHP for the API, it makes more sense to modify the schema than it does to ditch the tool.

```
mysql> describe Frames;
+-----------+-------------------------------+------+-----+-------------------+-----------------------------+
| Field     | Type                          | Null | Key | Default           | Extra                       |
+-----------+-------------------------------+------+-----+-------------------+-----------------------------+
| EventId   | int(10) unsigned              | NO   | PRI | 0                 |                             |
| FrameId   | int(10) unsigned              | NO   | PRI | 0                 |                             |
| Type      | enum('Normal','Bulk','Alarm') | NO   | MUL | Normal            |                             |
| TimeStamp | timestamp                     | NO   | MUL | CURRENT_TIMESTAMP | on update CURRENT_TIMESTAMP |
| Delta     | decimal(8,2)                  | NO   |     | 0.00              |                             |
| Score     | smallint(5) unsigned          | NO   |     | 0                 |                             |
+-----------+-------------------------------+------+-----+-------------------+-----------------------------+
6 rows in set (0.00 sec)
```

What I propose is removing all of the current PRI and MUL key's, adding an 'Id' field and making that the PRI key, and then modifying the indexes appropriately (which I could use help with).

Thoughts?
I'd like to do this ASAP as it is blocking progress on the new frontend.

**Comment by knnniggett** [comment]
I don't see a problem with this.  Would like to test with the legacy UI.

**Comment by connortechnology** [comment]
also need to make sure we have indexes, but I'm fine with the idea

**Comment by kylejohnson** [comment]
Sounds good - I will do some more testing with the legacy UI.

Could one of you help me with how to get the change in?  It has been a while since I messed with the DB upgrade stuff.

**Comment by connortechnology** [comment]
Sure.  One thing, if we are going to do this, we go all the way and make it perfect. :)  So get rid of frame_id.... I'll start, make a branch for it all...  I can handle the legacy UI changes... you worry about the new UI changes...

**Comment by kylejohnson** [comment]
oh boy.  My concerns were in c++ and perl code, which I'm not as involved in.

**Comment by connortechnology** [comment]
Oh, and I think we need to change the type of Score to a bigger int.

**Comment by kylejohnson** [comment]
65535 isn't high enough?

**Comment by connortechnology** [comment]
Oh, I'm thinking of a different column TotScore of Events, never mind.

**Comment by newburns** [comment]
No one has issues with a remote MySQL 5.6? Does anyone have one setup where
they can easily test my MySQL settings?
I can't seem to understand why MySQL remote is giving me a hard time, but
local MySQL 5.1 is not

**Comment by connortechnology** [comment]
@newburns this could be so many things, all of which are mysql problems, not ZoneMinder.

What error messages does it give?
Have you configured mysql to accept remote connections?
Have you setup the users to be available to remote connections?

You aren't giving us any info, and it's unrelated to this issue.

**Comment by kylejohnson** [comment]
I have confirmed that after executing the above SQL, the app is not affected.  Saving, Viewing and Deleting Events (and their associated frames) still works as expected.
