### ISSUE TITLE
Unable to probe local cameras, status is '127'

### ISSUE THREAD

**Issue by 1989canyontechnologies** [ZoneMinder/ZoneMinder#673]
Hello conern person,
Greetings!!!
 We are using linux fedora 20 and on that we have install zoneminder 1.28.0 web camera is working fine on cheese but not on zonminder we are unable to probe camera and unable to see camera in ZM. we are able to see camera in browser http://localhost/?action=stream

Kindly help us out its too late....

My email id is vasudevp@custom-soft.com,phulambrikavasudev9@gmail.com

Kindly let me know if anything am missing our skype id is customsoftba1

**Comment by knnniggett** [comment]
The probe command was not designed for local cameras.  It only works for a select few IP cameras. 

If you are still interested in getting the probe command to work then you need to verify you have the "arp" command installed on your machine.
