### ISSUE TITLE
Make Monitor Probe useful

### ISSUE THREAD

**Issue by connortechnology** [ZoneMinder/ZoneMinder#674]
For a local camera, it should scan /dev/video*.  If there is already a monitor setup for /dev/video0 but not for /dev/video1 then it should setup /dev/video1.  It should detect optimal palette, colorspace, maximum size, etc.

For remote cameras I guess we just need to add more camera support.
##

**Comment by knnniggett** [comment]
Note that the ONVIF feature will supersede the current probe method for ip cameras.

**Comment by connortechnology** [comment]
Note that ONVIF isn't supported on older cameras...

**Comment by knnniggett** [comment]
Yes, of course. I was merely pointing out that we don't need to add support for ONVIF cameras using this method.  I could probably have said that more clearly.

**Comment by connortechnology** [comment]
but maybe this should run the onvif code...

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
