### ISSUE TITLE
PDO_MYSQL the only PHP driver needed?

### ISSUE THREAD

**Issue by troywill** [ZoneMinder/ZoneMinder#679]
The previous maintainers of the Arch Linux zoneminder build were loading MYSQL and MYSQLI extensions for PHP (mysql.so and mysqli.so in /etc/php/php.ini.) I am trying to confirm that they are not needed by zoneminder >= 1.8.0 and PDO_MYSQL is the only one.

Thanks.

**Comment by connortechnology** [comment]
I believe so yes.

**Comment by troywill** [comment]
Thanks.
