### ISSUE TITLE
 short PHP open tags paragraph on zoneminder.com Troubleshooting page

### ISSUE THREAD

**Issue by troywill** [ZoneMinder/ZoneMinder#684]
Could the paragraph on the short PHP open tags on the Troubleshooting page be removed? (http://www.zoneminder.com/wiki/index.php/Troubleshooting.) (Since zoneminder no longer uses short open tags.)

**Comment by troywill** [comment]
Thanks for the update. I applied it.

**Comment by knnniggett** [comment]
We have not yet released a version of zoneminder that no longer requires short tags.
Note that anyone can update the WiKi.  Typically other users in the forum have been managing it.

**Comment by troywill** [comment]
Sorry. I read https://github.com/ZoneMinder/ZoneMinder/pull/620 and presumed (incorrectly) that applied to current version.

**Comment by knnniggett** [comment]
Closing.  Feel free to reopen this if you notice any short php tags in the next release.
