### ISSUE TITLE
When editing a monitor, using RTSP, host cannot contain random punctuation

### ISSUE THREAD

**Issue by connortechnology** [ZoneMinder/zoneminder#695]
However the password might have punctuation in it.

We need to be consistent on all the various methods, including the control tab.  

I think username/password should be separate fields, that way we can actually do useful input validation.
##

**Comment by SteveGilvarry** [comment]
Use Username and Password fields already in the db and just do this.

**Comment by connortechnology** [comment]
I hate you stale bot.

**Comment by GlenCooper** [comment]
Just commenting because I've reached this point, but need sleep (sorry).  Hopefully this comment will keep the stale-bot at bay for a little longer.

**Comment by parvit** [comment]
Hi all,
i'm working on this and i've just got the system working from source.
I'll let you know as i have a change ready.

**Comment by parvit** [comment]
@connortechnology I've added the PR responding to your request.

**Comment by parvit** [comment]
Hello, is there any feedback on this?

**Comment by parvit** [comment]
@connortechnology 
Thanks for merging the PR, if we may close this ticket it would allow me to claim the bounty.

As a side note: I would like to work also on #355, but it's locked so i don't know if i can proceed, can we unlock that one? thanks.

**Comment by connortechnology** [comment]
I don't see anything locked about #355.  You might want to discuss your approach on it before digging in too far.  Would be great to have it done though.

I've modified your code a bit.  in php8 passing null to a lot of functions generates errors.  Also I'm not sure strlen is the most efficient way to determine if a string is empty or not.  I also took out the setting of auth_type in ffmpeg.  It shouldn't be necessary and is just generating errors in the logs.

**Comment by parvit** [comment]
This is what i see from my side on #355
![image](https://user-images.githubusercontent.com/93098480/186004199-745178f5-6478-4e17-aad9-4743e612a1aa.png)

**Comment by connortechnology** [comment]
Okay it is unlocked.

**Comment by parvit** [comment]
It worked, thanks.
