### ISSUE TITLE
Ability to backup, restore zoneminder configuration [$90]

### ISSUE THREAD

**Issue by kylejohnson** [ZoneMinder/zoneminder#7]
##

**Comment by federico-digito** [comment]
Is there a plugin for zoneminder 1:30 to save the configuration of the cameras
thanks

**Comment by jjanderson** [comment]
are there any updates on this? I need to rebuild my system and really don't feel like having to setup all my cameras again..

**Comment by knnniggett** [comment]
@jjanderson The feature request described here is only for convenience. It would merely provide the ability to backup and restore the database, specifically the Config table, which does not contain camera information, directly from the web console. It would not provide any new functionality you can't already do easily from the command line.

If you are not doing so already, you should be performing regular mysql backups of your database on any production system. To preserve all your settings after a rebuild, simply restore your most recent backup.
