### ISSUE TITLE
Disabling cambozola in options doesn't actually disable?

### ISSUE THREAD

**Issue by frankc420** [ZoneMinder/ZoneMinder#735]
In Options under Images, if OPT_CAMBOZOLA is unchecked, IE still tries to load cambozola.jar -- How would I go about having IE use MJPEG in the same manner as Chrome and FF?  I'm trying to eliminate the java requirement.

**Comment by knnniggett** [comment]
The only way to not have a Java requirement that is to not use IE.  IE has never supported multiplart jpeg streaming.  Ever. That's why Cambozola exists.

**Comment by frankc420** [comment]
Thank you for your prompt response!
