### ISSUE TITLE
zms show test pattern + error message on error.

### ISSUE THREAD

**Issue by connortechnology** [ZoneMinder/ZoneMinder#742]
Basically,  the idea is that zms should return something useful on error.  So, for example a test pattern  image with some error text overlaid.  Something like that, instead of returning nothing or silently crashing, or requiring people to check the logs to find out what's going on.
##

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
