### ISSUE TITLE
zmupdate.pl: ignores ZM_SERVER_HOST in zm.conf

### ISSUE THREAD

**Issue by onlyjob** [ZoneMinder/ZoneMinder#765]
`zmupdate.pl` always tries to connect to databse at `localhost` disregarding of ZM_SERVER_HOST in `zm.conf`.
Also there is no option to provide database host name through command line...

**Comment by knnniggett** [comment]
That is because zmupdate.pl uses ZM_DB_HOST not ZM_SERVER_HOST

**Comment by onlyjob** [comment]
I see, thanks... Sorry, my mistake. Closing...
