### ISSUE TITLE
Security issue:Please remove login:password from camera URL path

### ISSUE THREAD

**Issue by pliablepixels** [ZoneMinder/zoneminder#767]
This causes various security issues:
a) The username and password are always exposed in logs for anyone to see (not necessary)
b) If someone is using your current APIs, it does not tie into OPT_AUTH, so anyone who has exposed their zone minder via a public IP and has password protected the login but has enabled APIs has just enabled everyone to get access to all their camera feeds, because the monitor.json request returns all passwords in plain text without needing any auth.

I'd recommend moving auth to another field and not exposing it via any API and masking out the logs to not have them too
##

**Comment by connortechnology** [comment]
Also, see #695

**Comment by kylejohnson** [comment]
I have started work on moving the user and pass fields out of the camera path, but I don't have an ETA for this right now.  We all agree that it is sorely needed.
