### ISSUE TITLE
fflushing log file output

### ISSUE THREAD

**Issue by connortechnology** [ZoneMinder/ZoneMinder#768]
I often look at the zmc log files to check status... and see that nothing is happening because we are never fflushing the log file output.  So I have to kill zmc and then it fflush's..

I really wonder what the performance impact of fflushing every line is.  

Currently you can set an ENV var to turn it on, but I think it should be a proper config option. 

Thoughts?
##

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
