### ISSUE TITLE
FTBFS on GNU Hurd

### ISSUE THREAD

**Issue by onlyjob** [ZoneMinder/ZoneMinder#779]
There are at least three problems with building Zoneminder on GNU Hurd:

First is the same as #771 (i.e. `SYS_gettid` not declared).

Second is addressed by #778.

Third is this:

```
ZoneMinder-1.28.1/src/zm_ffmpeg_camera.cpp:123:56: error: ‘pthread_tryjoin_np’ was not declared in this scope
```

Looks like `pthread_tryjoin_np` is not always available so some even test for it like this:
- http://sources.debian.net/src/npth/1.0-1/configure.ac/?hl=256#L256
- http://sources.debian.net/src/npth/1.0-1/config.h.in/?hl=54#L54
##

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
