### ISSUE TITLE
live feed freezes if source settings change

### ISSUE THREAD

**Issue by dvsingletary** [ZoneMinder/ZoneMinder#808]
1) Open a live feed for a given source
2) open source settings
3) click "save"
--> live feed freezes and will not recover because the socket file used to transfer images from the capture process to the stream process is gone.

capture process should re-create the socket file if a live feed is active (?) or the feed should detect a missing socket-file and attempt to re-open the live stream.
##

**Comment by connortechnology** [comment]
Yeah.

So what happens is that zmc is killed.  zms gets it's stream from the shared mmap memory... 
I bet zmc deletes the mmap file and creates a new one and zms never notices, still mmapd to the old memory.

Now zms _should_ notice after ten seconds that it isn't getting any new data and die, but I've noticed that it doesn't.  Not for several days.  

So I'll be taking a look in zms... but saving the monitor should probably outright kill any zms processes that are streaming that monitor... or maybe when zmc dies it should set a kill flag in the mmap'd mem before unmapping. Something like that.

**Comment by SteveGilvarry** [comment]
Closing as part of 2017 cleanup, not saying not valid, just no one is working on this and don't believe anyone is planning on doing so.
