### ISSUE TITLE
Upgrade bundled CakePHP

### ISSUE THREAD

**Issue by onlyjob** [ZoneMinder/ZoneMinder#814]
Recently CakePHP released new stable version _3.0.1_ while our bundled CakePHP is _2.5.0-RC1_. Let's upgrade please? See https://github.com/cakephp/cakephp/releases
##

**Comment by kylejohnson** [comment]
Nope.  3.x is not backwards compatible.  We won't be upgrading for a loooooong time, at least until the new ui + api is finished.

On April 15, 2015 8:44:38 PM EDT, Dmitry Smirnov <notifications@github.com> wrote:
>Recently CakePHP released new stable version _3.0.1_ while our bundled
>CakePHP is _2.5.0-RC1_. Let's upgrade please? See
>https://github.com/cakephp/cakephp/releases
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ZoneMinder/ZoneMinder/issues/814

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kylejohnson** [comment]
That said, we may be able to upgrade to a later 2.x release.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by onlyjob** [comment]
Fair enough. Then perhaps 2.6.3 would be the good version to upgrade to and it is already in Debian. ;)

**Comment by SteveGilvarry** [comment]
Don't want to say it but hoping this is the last version of CakePHP we have.
