### ISSUE TITLE
Global symbol requires explicit package name...

### ISSUE THREAD

**Issue by hans109h** [ZoneMinder/ZoneMinder#846]
After build of master today I am unable to run zmupdate

$ zmupdate.pl 
Global symbol "%Config" requires explicit package name at /usr/local/bin/zmupdate.pl line 81.
Global symbol "%Config" requires explicit package name at /usr/local/bin/zmupdate.pl line 81.
Global symbol "%Config" requires explicit package name at /usr/local/bin/zmupdate.pl line 81.
Global symbol "%Config" requires explicit package name at /usr/local/bin/zmupdate.pl line 81.
BEGIN not safe after errors--compilation aborted at /usr/local/bin/zmupdate.pl line 81.

**Comment by connortechnology** [comment]
I think you are mixing ilbraries from an old zm with programs from a new zm.

**Comment by hans109h** [comment]
So true.  I wonder how long that has been the case....yikes.  Thanks for pointing that out.
