### ISSUE TITLE
On ubuntu 14.04 zoneminder 1.28.1 alarm never terminate!!

### ISSUE THREAD

**Issue by far5893** [ZoneMinder/ZoneMinder#852]
Hi,
i use last zoneminder 1.28.1 , and configure motion detect as done for years with precedents versions , but once alarm trigger it stay ON for hours without stopping , sensitivity is correct because allarm start only when needed , but stop only hours from start(and have only long events ).
I make this test:
In idle mode for a long time in daylight i switch on electric illumination  of the room under monitoring, alarm start, 
i wait 10 minute, (no other changes in room), and alarm not stop,
i switch off light , and alarm stop.
Seems that zoneminder wait scene to return in the situation before alarm condition to stop alarm,
but sometimes it will not return in the same conditions for hours!!!

**Comment by far5893** [comment]
OK i answer my self , it's called image blending , and is a cam based option,
but not so clear explained.

**Comment by knnniggett** [comment]
@far5893 The zoneminder github forum is not a discussion forum. This is a bug reporting and feature request forum.  Please take this and any future "how do I use zoneminder" type of question to the zoneminder forum at zoneminder.com. Thank you.

**Comment by far5893** [comment]
Sorry but i think was a bug before discover that it's a feature (Cit.)

**Comment by knnniggett** [comment]
Your right.  One thing we can always use is better documentation.  We've got a very large userbase, but we there are just a handful of people willing to give back to this project in the form of writing code, testing, and documentation.  You can help by updating the documentation found in the WiKi.
