### ISSUE TITLE
Popup window sizes don't take into account that WEB_LIST_THUMBS is set

### ISSUE THREAD

**Issue by lingfish** [ZoneMinder/ZoneMinder#863]
The eventual popup drawn has the thumbs (and select boxes) off to the side, only reachable via horizontal scrolling.

(I run `WEB_LIST_THUMB_WIDTH = 150`, not that that should matter.)

I could just cheat and adjust `popupSizes`, but it really should be calculated dynamically based on `WEB_LIST_THUMB_WIDTH`.  That of course isn't available to JS, so I assume `js/skin.js.php` would have to feed it to JS, and more magic happen in `createPopup`.

**Comment by knnniggett** [comment]
Out of curiosity, I went ahead and set my WEB_LIST_THUMB_WIDTH to 150, but I did not get horizontal scroll bars when viewing the event list. In both Firefox and Chromium, the thumbnails appeared appropriately bigger without any negative apparent side effects.

In any case, this is similar to your other request, which fits into the category of visual preference.  My advice is to either follow the help text, which states to keep this value small, or you can submit a pull request to help make ZoneMinder more flexible to meet your needs.
