### ISSUE TITLE
Odd window size differences when viewing frame alarm image between Chrome & FF

### ISSUE THREAD

**Issue by lingfish** [ZoneMinder/ZoneMinder#865]
Chrome sizes perfectly, Firefox doesn't.  Everything gets nudged down, and a scrollbar is required.

Best way to show this is with an image:

![image](https://cloud.githubusercontent.com/assets/1295960/7956336/9a9c3490-0a22-11e5-912b-6761662c6068.png)

**Comment by connortechnology** [comment]
I just pushed a fix to master for this.  

The popup it was loading was using the dimensions for an image, but this is the frame page, which has another 20px in height for the prev/next buttons.

**Comment by lingfish** [comment]
Nice one, thanks.  A bit painful for me to test (Debian, using testing, silly libturbo hacks etc).

**Comment by connortechnology** [comment]
I do have a ppa for debian... needs updating.  I'll see about that today.

**Comment by SteveGilvarry** [comment]
@lingfish If you want to manually apply the fix it is in referenced commit. Closing the issue, please feel free to re-open if fix described doesn't work.
https://github.com/ZoneMinder/ZoneMinder/commit/f99c5f36278d2b98bddd42959f1f0663accea2ff
