### ISSUE TITLE
[CRITICAL] zms crashes with hashed authentication

### ISSUE THREAD

**Issue by knnniggett** [ZoneMinder/ZoneMinder#88]
Reproducible: always

Observed on CentOS 6.4 and Ubuntu 12.04 server w/ puppet module

Steps to reproduce:
1) Build & install zoneminder in the normal manner
2) Create an empty database and add a monitor.  Open the monitor and observe all is well.
3) Enable OPT_USE_AUTH and verify AUTH_RELAY is set to "hashed"
4) save and restart zoneminder
5) Open a monitor and observe there is no longer a live stream.  Observe log entries such as:
`08/25/13 15:33:54.908546 zms[23317].INF-zm_signal.cpp/65 [Got signal 6 (Aborted), exiting and forcing backtrace]`

NOTE: This issue occurs even though date.timezone in php.ini has a valid entry (if you happen to remember that previous issue).

Workaround:
For CentOS 6.4, setting ZM_SSL_LIB=gnutls at compile time resolves the issue. However, this workaround did not work on Ubuntu 12.04. Note that it has a newer version of gnutls than CentOS.

Further Discussion:
I have observed this issue as far back as svn3827. RPMs built on svn3639 with ZM_SSL_LIB=openssl worked fine. Until today, I had assumed it had something to do with the likely-outdated version of openssl on the CentOS platform, so I didn't initially report it.

Here is a sample of my http access log of the event that triggered the crash:
`127.0.1.1:80 192.168.1.156 - - [25/Aug/2013:15:58:13 -0500] "GET /cgi-bin/nph-zms?mode=jpeg&monitor=1&scale=100&maxfps=15&buffer=1000&auth=30f76e63e2849871d683eab5e0d7f073&connkey=64310&rand=1377464293 HTTP/1.1" 200 0 "http://192.168.1.180/index.php?view=watch&mid=1" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:23.0) Gecko/20100101 Firefox/23.0"`

It is definitely generating a hash, but how to tell what is wrong with it?

**Comment by george-viaud** [comment]
I'm still able to replicate these conditions / failure mode in Debian variant Raspbian running 1.29.0 fresh install - I'm not sure if the cause is the same but the workaround is.

**Comment by connortechnology** [comment]
@george-viaud Can you be clearer which workaround? The change to md5len?

**Comment by george-viaud** [comment]
Sorry about the ambiguity.

I disabled the hash options in the configuration and the problem ceased - (I think this has the end effect of going around the hashing code all-together).

**Comment by connortechnology** [comment]
I am re-opening, because I have been seeing this on my pi as well. There is some difference in the hashing algorithms.

**Comment by george-viaud** [comment]
Playing with this again today.  Observation:

Browsing to /zm/cgi-bin/zms while hash is enabled results in a Internal Server Error and the following in the apache2 error.log file:

[cgi:error] [pid 1722] [client x.x.x.x:xxxxxx] End of script output before headers: zms

**Comment by knnniggett** [comment]
I'm closing this again as this thread has gone stale.
I haven't seen this on my pi's, but if someone still has this issue and has new, relevant data then please create a new issue.

**Comment by jeroenst** [comment]
> Playing with this again today. Observation:
> 
> Browsing to /zm/cgi-bin/zms while hash is enabled results in a Internal Server Error and the following in the apache2 error.log file:
> 
> [cgi:error] [pid 1722] [client x.x.x.x:xxxxxx] End of script output before headers: zms

I also experience this error when hash is enabled in zoneminder 1.34.16, when AUTH_RELAY is none, zms works fine.

**Comment by connortechnology** [comment]
Probably your timezones are incorrectly set (this is the #1 reason why this fails.) Go actually look in your logs.  Turn on debug.  Look again.
