### ISSUE TITLE
Video Smear - Vertical Striping

### ISSUE THREAD

**Issue by clmarshall** [ZoneMinder/ZoneMinder#888]
Video Smear using 3MP Dahua 4300S over rtsp.

Smearing reduces when lowering resolution and framerate, but is not eliminated and triggers false positive motion making ZM unuseable. 

Similar smearing also appeared (not pictured) on GW Security 5MP IP 2300 Series cam, also RTSP.

![zm1](https://cloud.githubusercontent.com/assets/3595063/8211645/a79044ac-14e5-11e5-9d11-51012ce69c56.png)

**Comment by knnniggett** [comment]
This issue does not describe a bug or feature request within the zoneminder software.
There are different causes for smearing and multiple workarounds.  Topics that discuss these issues are found in the zoneminder user fourm.
