### ISSUE TITLE
Allow use of UNIX File Sockets for MySQL Connection

### ISSUE THREAD

**Issue by josh4trunks** [ZoneMinder/ZoneMinder#901]
Documentation for PDO is here.
http://php.net/manual/en/ref.pdo-mysql.connection.php

The $dbConn line needs to modified to allow inclusion of "unix_socket", and probably needs a bit of logic added to know when to include it.
ZoneMinder/web/includes/database.php

I'm not sure what else needs is crucial that needs modification for this to work. Most of the other instances of the database parameters being used seemed like distro specific stuff.

**Comment by knnniggett** [comment]
Why?

It's working fine the way it is.  From the documentation you referenced:
```
 unix_socket

    The MySQL Unix socket (shouldn't be used with host or port).
```
We are specifying the host, so unix socket shouldn't be used:
https://github.com/ZoneMinder/ZoneMinder/blob/master/web/includes/database.php#L34

**Comment by josh4trunks** [comment]
Im asking that the option be added, not that force admins to use either method. file sockets have higher performance because that aren't going through the network stack (being chunked, TCP reliability which is irrelevant on a local system)

It shouldn't be too hard to implement. I helped did this for owncloud and it when I have more time can try making a PR for zoneminder.

**Comment by josh4trunks** [comment]
It should only take a line of logic to see if ZM_DB_SOCK ( or whatever ) is defined an to know what parameters to pass to PDO.

**Comment by knnniggett** [comment]
Feel free to submit a pr.  Naturally, we want to make sure it doesn't break installations with a remote dB.

**Comment by josh4trunks** [comment]
OK, will look into it sometime in the future.

**Comment by knnniggett** [comment]
I'm closing this out due to inactivity.  The idea is sound.  If you choose to implement this, feel free to reopen this issue and generate a pull request.

**Comment by josh4trunks** [comment]
I might try tackling this, this weekend.

It looks like zoneminder doesn't even take into account port numbers? so if someone tried connecting to a mysql running on a different port it wouldn't work?

**Comment by josh4trunks** [comment]
@knnniggett I don't see a way to reopen this issue, can you do that?

Can someone please help me a little?
https://github.com/josh4trunks/ZoneMinder/tree/mysql_socket

I got the PHP done, but am having trouble with the Perl connection, at least I get an error when trying to start the zoneminder daemon.
It looks like `lib/ZoneMinder/Config.pm`, also has a db connection. Is there any possibilty to have this use `Database.pm` instead of having to have the database connection logic in 2 places for perl?
https://github.com/ZoneMinder/ZoneMinder/blob/master/scripts/ZoneMinder/lib/ZoneMinder/Config.pm.in#L86-90

Thanks

**Comment by josh4trunks** [comment]
I looks like Perl has connections made in multiple scripts, I got another error with `Logger.pm`.
I'll just put the needed logic everywhere, and let someone else decide if they want to made these more maintainable by just using `Database.pm`.
