### ISSUE TITLE
TimeStamp timezone [$15]

### ISSUE THREAD

**Issue by jamesmbowler** [ZoneMinder/zoneminder#908]
I have a field called timezone in the Monitors table, let's say it contains a timezone in any format, could be 'America/Los_Angeles', or even just a GMT differential, like -07, and I different monitors have different timezones. How can I get the timestamp in the upper left of my images to be in that timezone? 
##

**Comment by knnniggett** [comment]
What timezone did you put in your php.ini?

**Comment by jamesmbowler** [comment]
Actually, I added a timezone field to the Monitors table, so that each Monitor can have it's own timezone.

**Comment by connortechnology** [comment]
The code that does the timestamping is in zm_image.cpp around line 1853.

grep for Timestamp to find where it is used.

**Comment by SteveGilvarry** [comment]
Add to my other one to move to UTC and then put time zone on user and monitors
