### ISSUE TITLE
make error AVFormatContext

### ISSUE THREAD

**Issue by debelan** [ZoneMinder/ZoneMinder#917]
zm_event.cpp: In member function ‘virtual void EventStream::processCommand(const StreamBase::CmdMsg*)’:
zm_event.cpp:888:51: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
      if ( (mode == MODE_SINGLE) && (curr_frame_id == event_data->frame_count) )
                                                   ^
x86_64-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I..  -I/usr/include -I/usr/include -I/usr/include -D__STDC_CONSTANT_MACROS -Wall -finline-functions -fomit-frame-pointer -I/usr/include -D__STDC_CONSTANT_MACROS -D__STDC_CONSTANT_MACROS -D__STDC_CONSTANT_MACROS -DHAVE_LIBCRYPTO -c -o zm_exception.o zm_exception.cpp
x86_64-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I..  -I/usr/include -I/usr/include -I/usr/include -D__STDC_CONSTANT_MACROS -Wall -finline-functions -fomit-frame-pointer -I/usr/include -D__STDC_CONSTANT_MACROS -D__STDC_CONSTANT_MACROS -D__STDC_CONSTANT_MACROS -DHAVE_LIBCRYPTO -c -o zm_file_camera.o zm_file_camera.cpp
x86_64-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I..  -I/usr/include -I/usr/include -I/usr/include -D__STDC_CONSTANT_MACROS -Wall -finline-functions -fomit-frame-pointer -I/usr/include -D__STDC_CONSTANT_MACROS -D__STDC_CONSTANT_MACROS -D__STDC_CONSTANT_MACROS -DHAVE_LIBCRYPTO -c -o zm_ffmpeg_camera.o zm_ffmpeg_camera.cpp
zm_ffmpeg_camera.cpp: In member function ‘int FfmpegCamera::OpenFfmpeg()’:
zm_ffmpeg_camera.cpp:263:21: error: ‘AVFormatContext’ has no member named ‘interrupt_callback’
     mFormatContext->interrupt_callback.callback = FfmpegInterruptCallback;
                     ^
zm_ffmpeg_camera.cpp:264:21: error: ‘AVFormatContext’ has no member named ‘interrupt_callback’
     mFormatContext->interrupt_callback.opaque = this;
                     ^
Makefile:629: recipe for target 'zm_ffmpeg_camera.o' failed
make[3]: *** [zm_ffmpeg_camera.o] Error 1
make[3]: Leaving directory '/usr/src/zoneminder/src'
Makefile:513: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/usr/src/zoneminder'
Makefile:420: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/zoneminder'
dh_auto_build: make -j1 returned exit code 2
debian/rules:28: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by knnniggett** [comment]
That means make cannot find your ffmpeg (or libav) header files on your system.  This a common problem that has already been mentioned several times.  I'm closing this because it does not describe a bug.  For support with this, search up past issues with similar make errors or post into the user forum.
