### ISSUE TITLE
minor Sphinx error

### ISSUE THREAD

**Issue by onlyjob** [ZoneMinder/ZoneMinder#946]
During re-build of documentation Sphinx reported the following error:

    docs/api.rst:31: ERROR: Unexpected indentation.

Probably because it expects empty line (or double spaces followed by end-of-line on the previous line), as it seems from looking at the other paragraphs of the same file.
Affects "master".

**Comment by pliablepixels** [comment]
Thanks -  I wasn't aware this needed to be tested with sphinx. I'll have a setup ready tomorrow and will make the changes.

**Comment by pliablepixels** [comment]
this can be closed - was addressed (I can't close this as I am not the author)
