### ISSUE TITLE
PHP warnings

### ISSUE THREAD

**Issue by onlyjob** [ZoneMinder/ZoneMinder#948]
"master" exhibit the following warning

1) on top of `index.php`:

    Warning: implode(): Argument must be an array in /usr/share/zoneminder/www/skins/classic/views/console.php on line 74

2) on top of `index.php?view=monitor&mid=1`:

    Notice: Use of undefined constant ZM_SERVER_ID - assumed 'ZM_SERVER_ID' in /usr/share/zoneminder/www/skins/classic/views/monitor.php on line 43

In "options" there are no servers under "Servers" tab, but "AddNewServer" button show empty page with error "View 'server' does not exist".

**Comment by connortechnology** [comment]
I believe I fixed this... can you confirm with latest master and close if so?

**Comment by onlyjob** [comment]
1) is still there.

2) is gone. (Thank you).

**Comment by onlyjob** [comment]
Just noticed another warning: `Notice: Undefined index: Id in /usr/share/zoneminder/www/skins/classic/views/monitor.php on line 116` in "Add New Monitor" dialog...
