### ISSUE TITLE
Annoying error message if localized string Monitor contains non ASCII characters

### ISSUE THREAD

**Issue by manupap1** [ZoneMinder/zoneminder#957]
Depending on local translations, the string `$LANG['Monitor']` can contains valid unicode characters which are not in ASCII table.
This string is used as default setting for the monitor `Name` field. However, user entry for this field is tested only against ASCII table (use of regex `\w` in `web/skins/classic/views/js/monitor.js.php` at line 62).
All localized strings containing such characters (like `é` in french) lead to an error message and the user is forced to replace them before submitting.

I tried to check if the regex could be fixed to include all alphanumeric characters, hyphen and underscore contained in unicode but it seems there is no easy way to do this or I have not found it. 
Regex `\p` is not officially supported in JavaScript, this may work but not in all cases (didn't work when I tested it).
Unicode support in JavaScript regexes would request to match specific code points with \uFFFF but unicode has multiple code charts (http://www.unicode.org/charts/) and some contain unwanted characters. Skipping these characters requires to check each chart and include only sub ranges. This would take time and would lead to a very long regular expression, not very maintainable.
This javascript issue is discussed here http://stackoverflow.com/questions/280712/javascript-unicode-regexes. Someone has posted a posted a hack that could be tested (http://stackoverflow.com/a/8933546).
##

**Comment by SteveGilvarry** [comment]
Review this and action.
