### ISSUE TITLE
669781 - Transition towards Apache 2.4

### ISSUE THREAD

**Issue by kylejohnson** [ZoneMinder/ZoneMinder#96]
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=669781

**Comment by knnniggett** [comment]
This almost certainly has to have been fixed now that we have an active Debian package maintainer and new packages exist in the Debian repositories.
@onlyjob If I am mistaken, let me know and we can re-open this issue.

**Comment by onlyjob** [comment]
Just to confirm, transition to Apache-2.4 was done in 1.28.1-1 and 1.28.1-5 introduced `dh_apache2`. I had no idea that there is a corresponding upstream bug as Debian bug 669781 have no `Forwarded` field...

However [apache.conf](https://anonscm.debian.org/cgit/collab-maint/zoneminder.git/tree/debian/conf/apache2/zoneminder.conf) may benefit from review and potential updates for better compatibility with Apache-2.4. I mostly use ZoneMinder with `nginx/php5-fpm`...
