### ISSUE TITLE
Default scale other than actual skews image

### ISSUE THREAD

**Issue by hans109h** [ZoneMinder/ZoneMinder#963]
With latest build if the default scale (in monitor settings) is an enlargement (ie. 2x 3x) the image is skewed at an angle when viewing.

If the default scale is set to actual, and the scale is changed in the viewer the image is not skewed.

If the default scale is set to a reduction, the image is not skewed either.

**Comment by connortechnology** [comment]
confirmed.

**Comment by connortechnology** [comment]
I have applied a fix.

**Comment by connortechnology** [comment]
fix tested, fix works.

**Comment by hans109h** [comment]
Issue resolved.
