### ISSUE TITLE
Zoneminder Signal Loss event

### ISSUE THREAD

**Issue by Munk0** [ZoneMinder/ZoneMinder#964]
I know this is a "feature" but according to the help in and on the wiki it's only supposed to fire on "local" camera's.  I have two "remote" camera's that I know are near the edge of my wifi range and constantly drop signal for a brief moment.  My log and events list is full of mostly the "Signal" loss event.  How do I turn this event off on these REMOTE camera's?

I'll address the range issue eventually but don't want to be forced to do it now.  My event list is almost unusable due to trying to weed out events I care about over this "Signal" event. I'm talking 100's per day.

**Comment by knnniggett** [comment]
@Munk0 This issue does not describe a bug, nor is it a feature request.  This is a question concerning how to use the filtering capabilities in the log viewer.  The place to ask this question is in the user forum.
